### ISSUE TITLE
C2382 happening without -Za

### ISSUE THREAD

**Issue by tiagomacarios** [MicrosoftDocs/cpp-docs#1035]
The help page for 2382 mentions that the error will only happen under -Za, but it seems like -Za is not necessary to trigger the error. The below triggers the error without Za.
https://godbolt.org/z/0BQ0w2
struct S
{
    void f() noexcept;
};
void S::f(){}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 27ac393f-e411-95d2-3725-761159630929
* Version Independent ID: c41fba83-aa6c-9cd7-13c7-e84409f313e7
* Content: [Compiler Error C2382](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-errors-1/compiler-error-c2382?view=vs-2019)
* Content Source: [docs/error-messages/compiler-errors-1/compiler-error-c2382.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/error-messages/compiler-errors-1/compiler-error-c2382.md)
* Product: **visual-cpp**
* Technology: **cpp-diagnostics**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@tiagomacarios 

Maybe that's what it means, or maybe it means the error can occur other ways, but the error *also* happens under /Za on an attempt to overload a function based on the *specific* exception specification. 

I say that because it looks like some things are *only* an error under /Za. For example, this code fails to compile under /Za, but compiles if /Za isn't specified:

```
struct S
{
    void f() throw(char);
};
void S::f() throw(long) {}
```

It looks like, by default, the compiler considers `noexcept` and `throw(any_or_no_type)` as synonymous as far as exception specifications are concerned, and only considers their presence or absence when detecting this error. Under /Za, the error check goes further and complains about a mismatch in the specification types, something the compiler doesn't even implement.

**Comment by Shobhitp2018** [comment]
Hi
I am getting error while running my code in visual studio 2019 although I have dune the coding of the program in visual studio 2012 .The error is related to longjump redefinition. Please tell what to do?
**Severity	Code	Description	Project	File	Line	Suppression State
Error	C2382	'longjmp': redefinition; different exception specifications	TestCPLEX_Jan27_2014	C:\Program Files\IBM\ILOG\CPLEX_Studio_Community129\concert\include\ilconcert\ilosys.h	705**

**Comment by corob-msft** [comment]
Addressing some old issues. Fix should appear in next published update Monday.
