### ISSUE TITLE
Stuck with Error C1010 "unexpected end of line looking for precompiled..." even when asking to NOT use precompiled error. 

### ISSUE THREAD

**Issue by ebqc** [MicrosoftDocs/cpp-docs#1036]
There is a bug in VisualStudio 2019. V16.1.1. It is a C++ MFC project. Cannot convince Visual Studio to stop looking for those precompiled files. I set the option at 'off' and 'on' several times, closed the projects, closed VC, re-started, it just does not want to compile without those 'pre-compiled' headers.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7710ea05-1307-eaaf-3ba0-86175eeaf184
* Version Independent ID: 30568a08-383b-1676-dfb3-e1dc6f28f38c
* Content: [Fatal Error C1010](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-errors-1/fatal-error-c1010?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(C1010)%26rd%3Dtrue&view=vs-2019#feedback)
* Content Source: [docs/error-messages/compiler-errors-1/fatal-error-c1010.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/error-messages/compiler-errors-1/fatal-error-c1010.md)
* Product: **visual-cpp**
* Technology: **cpp-diagnostics**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@ebqc 

This is unlikely to be a product bug, though the documentation does need to be updated for the new project default precompiled header file name, *pch.h*. On the assumption that you know what you're asking for (precompiled headers are a *huge* win for MFC compilation times, which is why they're generated by default):

Look at the properties page for your source file named pch.cpp, or possibly stdafx.cpp if the project was generated by an older copy of VS. (Don't look at the Project properties page, as I assume you've already turned off the PCH option there). In the **Configuration Properties > C/C++ > Precompiled Headers** page, set the **Precompiled Header** property from **Create (/Yc)** to **Not Using Precompiled Headers**. Also, delete any file with a .pch suffix in your output directory. If you don't have a pch.cpp or stdafx.cpp file in your project, it's possible if unlikely that another file has the **/Yc** option set - you'll have to look through them all. If you do that, you may as well check all your source files for the **/Yu** option, and turn that off, too. See if that makes a difference.
