### ISSUE TITLE
No code for French-French fr-FR

### ISSUE THREAD

**Issue by Abracadacook** [MicrosoftDocs/cpp-docs#1066]
No code for French-French .
"fr-FR" is not working on windows plateform.
Thank for your help

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a25b2062-1d8a-a709-dcaa-638f7a1ebc01
* Version Independent ID: d734a773-6beb-305b-96f7-dff303a99567
* Content: [Language Strings](https://docs.microsoft.com/en-us/cpp/c-runtime-library/language-strings?view=vs-2019#feedback)
* Content Source: [docs/c-runtime-library/language-strings.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/c-runtime-library/language-strings.md)
* Product: **visual-cpp**
* Technology: **cpp-ucrt**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@Abracadacook 

Generally speaking, we don't do programming support here. Have you tried using "French-France" or the 0x040C language ID?

If you're wondering why "French-France" isn't listed In the article, it's because the official list of language and location names is found in [Appendix A: Product Behavior](https://docs.microsoft.com/openspecs/windows_protocols/ms-lcid/a9eac961-e77d-41a6-90a5-ce1a8b0cdb9c) of [\[MS-LCID]: Windows Language Code Identifier (LCID) Reference](https://docs.microsoft.com/openspecs/windows_protocols/ms-lcid/70feba9f-294e-491e-b6eb-56532684c37f), which includes "French-France", and "fr-FR". The table in this article only lists the *extra* locale aliases that are supported by the C runtime library, but are not part of the official Windows list. 

I'm closing this issue, because it doesn't seem like a documentation problem. If your code does not produce the results you expect, I recommend you try our [Developer Community](https://developercommunity.visualstudio.com/spaces/62/index.html) for answers, or ask a question on [Stack Overflow](https://stackoverflow.com/questions/tagged/c%2b%2b). Good luck!
