### ISSUE TITLE
doesn't specify the command interpreter

### ISSUE THREAD

**Issue by aardvarkkrill** [MicrosoftDocs/cpp-docs#1071]
"Command Line:  The command to be executed by the custom build step."
is not at all helpful.  Is this Windoze command interpreter?  Some VS thing?  Bash?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f34e186-20d4-e937-8b4a-036b4708aad8
* Version Independent ID: 0d911d7c-1338-c554-bb55-7de0c33e846a
* Content: [Custom Build Step Property Page: General](https://docs.microsoft.com/en-us/cpp/build/reference/custom-build-step-property-page-general?view=vs-2019#feedback)
* Content Source: [docs/build/reference/custom-build-step-property-page-general.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/reference/custom-build-step-property-page-general.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@aardvarkkrill 

The interpreter is essentially the Windows command interpreter in a custom environment, with a Visual Studio macro interpreter at the front end. The environment is the same one the IDE provides to its own command-line tools, the compiler and linker and so on. For example, the PATH and INCLUDE and LIBRARY environment variables reflect the properties set in your solution, or possibly set as parameters to the DEVENV command. See [Understanding Custom Build Steps and Build Events](https://docs.microsoft.com/cpp/build/understanding-custom-build-steps-and-build-events) for an overview, and [Specifying build events](https://docs.microsoft.com/en-us/cpp/build/specifying-build-events) for information on using the command line with macros. The Visual Studio IDE documentation has additional information in [Specify custom build events in Visual Studio](https://docs.microsoft.com/visualstudio/ide/specifying-custom-build-events-in-visual-studio).

Since the answer is available in the relevant documentation you'd look at when you create a custom build step, I don't think it needs to be specified in detail here.

**Comment by aardvarkkrill** [comment]
Thanks corob-msft, that's helpful.  However, this was the page that VS directed me to when I asked for help on that object, isn't that, therefore, the "relevant documentation"?  At least there should be a link on this page to "Understanding Custom Build..." which as far as I can see there isn't.  Thanks again.
