### ISSUE TITLE
Page content does not change when switching between VS2015/VS2017/VS2019 on menu (upper left corner)

### ISSUE THREAD

**Issue by fpl9000** [MicrosoftDocs/cpp-docs#1072]
When I use the menu on the upper left corner of the page to switch between various Visual Studio versions, the list of compiler options on this page does not change. This makes it hard to compare the compiler options for different VS versions.

Same problem happens with the linker options shown at https://docs.microsoft.com/en-us/cpp/build/reference/linker-options?view=vs-2019

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2353367-e490-5dc3-fc39-3bcba30bf365
* Version Independent ID: 4300089e-7ea0-68bf-eb1f-c9c31cdb8d41
* Content: [Compiler Options Listed Alphabetically](https://docs.microsoft.com/en-us/cpp/build/reference/compiler-options-listed-alphabetically?view=vs-2017)
* Content Source: [docs/build/reference/compiler-options-listed-alphabetically.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/reference/compiler-options-listed-alphabetically.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@fpl9000 

The best way to see what's supported by each compiler is to use the **/?** option at the command line. You'll see the results are slightly different by version, by host, and by target architecture. For simplicity, the [Compiler options listed alphabetically](https://docs.microsoft.com/cpp/build/reference/compiler-options-listed-alphabetically) article lists everything, and doesn't call out these differences.

I agree that it would be nice to be able to see what's different by version in these tables. There are some technical details about how we support different versions of an article from a single source document that make it difficult to solve this problem. Basically, we can't switch versions of content by row within a table. (Yes, I tried it, and I've asked for such support, but it's not available yet.) That means that to have versioned content, we'd have to have three copies of the table that are about 98% identical, and worry about keeping them in sync. Rather than do that, we rely on statements in the individual articles that say the option is available starting in a particular version of the product, or that it's obsolete as of a particular version. We use similar statements for options that only apply to a particular target architecture. It's not as convenient when you'd like to see several differences at once, I suppose.

This is a long-winded way of saying we don't intend to fix this issue, because the choices available to us aren't good. Sorry.

**Comment by fpl9000** [comment]
Then what does that menu do? It looks like it's supposed to change the content based on the selected VS version.

**Comment by corob-msft** [comment]
The version selector tool is a relatively recent addition to our interface on docs.microsoft.com. Before it was available, we tried to make the content as universally applicable as possible. When something specific to a version of the product was described, we'd call it out in the text. There was only one set of C++ documentation for VS2015 and VS2017. Now we have the ability to add tags to our content at the paragraph level that specify which versions the paragraph should be visible in. We've started using them to mark the version-specific content in things we write or update for VS 2019, and we occasionally go back and split out VS2017- and VS2015-specific content. The vast majority of our content predates this ability, and has no tags. Generally, that's okay, since most content doesn't change much between versions, if at all. Going forward, we'll be using the tags in new and edited content, and that's where the version selector will make a visible difference.
