### ISSUE TITLE
Please use code blocks for operators

### ISSUE THREAD

**Issue by mqudsi** [MicrosoftDocs/cpp-docs#1295]
In the list of operator precedence, you have runs of text like `<<>>` which makes it hard to distinguish if it's the greater than symbol or the shift operator (especially depending on the font it's rendered in). If it were written as `<<` `>>`, it would make it much clearer to visually parse.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ddc4f59b-159f-5038-fc24-4e78c7dff783
* Version Independent ID: f0015080-14af-58f1-15bb-c2691ea4186f
* Content: [Precedence and Order of Evaluation](https://docs.microsoft.com/en-us/cpp/c-language/precedence-and-order-of-evaluation?view=vs-2019#feedback)
* Content Source: [docs/c-language/precedence-and-order-of-evaluation.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/c-language/precedence-and-order-of-evaluation.md)
* Product: **visual-cpp**
* Technology: **cpp-c-language**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by mikeblome** [comment]
@mqudsi agreed the formatting isn't great. I am reluctant to use code block formatting for operators because that's not in accordance with our markdown style guide. I tried adding some extra spaces between the operators. Changes should be visible by Monday July 15. If in your opinion that doesn't fix the problem feel free to reopen this.
