### ISSUE TITLE
C# Web Developer Speculative Execution Side Channels

### ISSUE THREAD

**Issue by anandash** [MicrosoftDocs/cpp-docs#1349]
Hi We have developed our application in ASP.NET using C# which has been deployed on IIS. Please suggest do we also need to run Speculative Execution Side Channels if yes how we can do Speculative Execution Side Channels test on our server.  Here I want to mention that we can't use internet on our server.

Please suggest.

Thanks,
Ashish Anand

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 44335d36-ff41-976a-5488-e1a877156040
* Version Independent ID: 42cf8d00-f65e-78c5-17e4-92580aefc996
* Content: [C++ Developer Guidance for Speculative Execution Side Channels](https://docs.microsoft.com/en-us/cpp/security/developer-guidance-speculative-execution?view=vs-2019#feedback)
* Content Source: [docs/security/developer-guidance-speculative-execution.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/security/developer-guidance-speculative-execution.md)
* Product: **visual-cpp**
* Technology: **cpp-windows**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by corob-msft** [comment]
@anandash 
Spectre mitigations are done by the C++ compiler. This is not something you need to worry about when you use C# and ASP.NET. The mitigations should be done for you by the server-side code that supports ASP.NET. To get those mitigations, make sure your server is up-to-date with patches.

**Comment by anandash** [comment]
Hi Colin,

May I know is there specific patch we need update regularly or it's comes under routine patches released by Microsoft.

Thanks & Regards
Ashish Anand

________________________________

**Comment by corob-msft** [comment]
As far as I know, every software update since about February 2018 has checked for and installed patches required for Spectre mitigation. For more information by platform, see [Windows client guidance for IT Pros to protect against speculative execution side-channel vulnerabilities](https://support.microsoft.com/help/4073119/protect-against-speculative-execution-side-channel-vulnerabilities-in), [Windows Server guidance to protect against speculative execution side-channel vulnerabilities](https://support.microsoft.com/help/4072698/windows-server-speculative-execution-side-channel-vulnerabilities-prot), and [Guidance for mitigating speculative execution side-channel vulnerabilities in Azure](https://docs.microsoft.com/azure/virtual-machines/windows/mitigate-se).
