### ISSUE TITLE
What is the "non-Microsoft specific" method of using dllexport and dllimport in C++ classes?

### ISSUE THREAD

**Issue by tommai78101** [MicrosoftDocs/cpp-docs#1456]
In this section, it mentioned there is a Microsoft specific method of using `dllexport` and `dllimport` in C++ classes:

https://docs.microsoft.com/en-us/cpp/cpp/using-dllimport-and-dllexport-in-cpp-classes?view=vs-2019#microsoft-specific

So, what is the "non-Microsoft specific" method? I think it warrants a section to explain what's the difference between a "Microsoft-specific" and "non-Microsoft-specific" `dllexport` and `dllimport` approaches in C++ classes.

Otherwise, this is just too vague on why there's this "specific Microsoft method" here... I have no clue what's the opposite of this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54007cc2-08f5-05ca-355f-4ddafc7a083f
* Version Independent ID: d31e6e36-27a3-e59a-0268-71ab603e0ddd
* Content: [Using dllimport and dllexport in C++ Classes](https://docs.microsoft.com/en-us/cpp/cpp/using-dllimport-and-dllexport-in-cpp-classes?view=vs-2019)
* Content Source: [docs/cpp/using-dllimport-and-dllexport-in-cpp-classes.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/cpp/using-dllimport-and-dllexport-in-cpp-classes.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by corob-msft** [comment]
@tommai78101 
We use **Microsoft specific** to mark features and behaviors that are not part of the language standard, or that are particular to the Microsoft implementation of the compiler toolset and runtime library environment. It means you may not find this feature in other compilers or on other platforms. It's basically a warning that code using the feature or relying on the behavior is not portable.

In this case, the use of `dllexport` and `dllimport` attributes is a compiler extension specific to Microsoft Windows platforms, where they indicate symbols that can be loaded and shared via DLLs. There's no way to describe a non-Microsoft-specific use, because these attributes are essentially meaningless on other platforms. 

Being Microsoft-specific doesn't mean no other compilers implement the extension, though. These are non-standard attributes implemented by the Microsoft toolset, and hence we call them Microsoft-specific. However, they are also implemented by some other compilers that build for Windows, such as GCC and Clang, to perform the same function the same way when targeting Windows platforms. They are not supported by those compilers when, say, targeting Linux. 

The upshot is, we have **Microsoft specific** sections to describe things our tools do, that other tools might not. If (as in this case) there's no other description, then it's safe to say there *is* no standard non-Microsoft behavior.

**Comment by tommai78101** [comment]
Ohhh, I just saw the "End Microsoft Specific" text near the bottom of the article.

It's very easy to miss this text.

@corob-msft  May I request for both the "Microsoft Specific" amd "End Microsoft Specific" text titles be colored coded, can have a different color, can have a light/faint rectangle box, or have a subtle styling, so it's easier to see where it begins and where it ends, and also marks out which sections in the articles are Microsoft specific?

I really didn't see the "End Microsoft Specific" text near the bottom, and this is why I made this issue. Otherwise, I wouldn't make this issue in the first place.
