### ISSUE TITLE
cvtres.exe tool isn't documented

### ISSUE THREAD

**Issue by LegalizeAdulthood** [MicrosoftDocs/cpp-docs#1465]
This tool is what the linker uses to convert .res files into .obj files, but the cvtres tool itself isn't documented.  It should probably be added to this list of additional MSVC build tools.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 380e8af0-aa0f-d882-d764-ddc02991d537
* Version Independent ID: ac27a8d9-280d-89b6-ed33-8c8fbb80c146
* Content: [Additional MSVC Build Tools](https://docs.microsoft.com/en-us/cpp/build/reference/c-cpp-build-tools?view=vs-2019#feedback)
* Content Source: [docs/build/reference/c-cpp-build-tools.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/reference/c-cpp-build-tools.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@LegalizeAdulthood 
Thanks for taking the time to make this proposal. As far as I can tell, cvtres.exe has been undocumented all the way back to VC 2.0 (currently the oldest doc set I have access to). That's because ever since then, you don't need to invoke it yourself. The linker is smart enough to do it on your behalf, with all the right options set, if you include a .res file in your list of files to be linked. Basically, it's just a helper for the linker now. As long as the linker can find cvtres.exe, it just works. And that should never be a problem, since it's installed automatically with every version of the toolset. 
I can see a purist's argument for including it in the documentation, but [it's mentioned where you might need to know about it](https://docs.microsoft.com/en-us/cpp/build/reference/dot-res-files-as-linker-input?view=vs-2019). I think that's good enough.
