### ISSUE TITLE
You should add $(PublishDir)

### ISSUE THREAD

**Issue by ms-jasondel** [MicrosoftDocs/cpp-docs#1467]
$(PublishDir) is missing from this documentation.  I spent hours trying to figure out how to get the Output Directory from a Publish task, after many forums I finally stumbled upon what seems to be undocumented here, the answer I was looking for was the PublishDir variable.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b46cf831-faea-6357-0e06-3284f114c879
* Version Independent ID: 0345affe-ce33-c438-d3e4-d134f905d084
* Content: [Common macros for MSBuild commands and properties](https://docs.microsoft.com/en-us/cpp/build/reference/common-macros-for-build-commands-and-properties?view=vs-2019#feedback)
* Content Source: [docs/build/reference/common-macros-for-build-commands-and-properties.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/reference/common-macros-for-build-commands-and-properties.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@ms-jasondel 
That sounds like a bad experience. To jump-start my search for the right property macro, I usually scan the list of available macros in VS for something with a value that matches what I expect. In this case, I'd look for a value that looks like the output directory, with `app.publish\` appended to it, since I know that's where the output for publishing is found. (If I didn't know that, it would be harder.)
I'll look into adding an entry.

**Comment by corob-msft** [comment]
Fix is live.
