### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by Naryoril** [MicrosoftDocs/cpp-docs#1478]
The link to the OPENFILENAME struct in the description of the dwFlags of the constructor leads to a 404 page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b86e2a5b-600c-6514-da7e-dd3c690fee0e
* Version Independent ID: d014df1a-8e49-85ae-589e-f4ec84f714bd
* Content: [CFileDialog Class](https://docs.microsoft.com/en-us/cpp/mfc/reference/cfiledialog-class?view=vs-2019#feedback)
* Content Source: [docs/mfc/reference/cfiledialog-class.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/mfc/reference/cfiledialog-class.md)
* Product: **visual-cpp**
* Technology: **cpp-mfc**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by corob-msft** [comment]
A fix is in progress.

**Comment by corob-msft** [comment]
@Naryoril 
Thanks for spotting this. I've updated all the links to point at OPENFILENAMEW, since there are no landing pages for the OPENFILENAME macro; you have to pick either OPENFILENAMEA or OPENFILENAMEW, and I figure most MFC is compiled for Unicode these days.
The fix is merged and should show up tomorrow.
