### ISSUE TITLE
Rediculous

### ISSUE THREAD

**Issue by humanmattias** [MicrosoftDocs/cpp-docs#1479]
I don't know if there was an absolutely huge oversight on whoever is working on the new versions of C++ but the if/else statements DO NOT WORK. The syntax always leaves my IDE asking for ; before the expressions after the 'else' statement, and removing the else statement just to try to make my program run makes the debug window crash. 

So? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b385eb6a-6880-d24d-99de-4618f11db864
* Version Independent ID: f74e6e06-29b0-8ead-c9a6-e0ffc7070f24
* Content: [if-else Statement (C++)](https://docs.microsoft.com/en-us/cpp/cpp/if-else-statement-cpp?view=vs-2019#feedback)
* Content Source: [docs/cpp/if-else-statement-cpp.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/cpp/if-else-statement-cpp.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by corob-msft** [comment]
@humanmattias 
Sorry you're having trouble with the syntax, here. It's a safe bet the language isn't broken, but the compiler doesn't understand something you've done. Start at the top of your function and verify your syntax first. Some things to check are that all parens, brackets, and braces match in your code, and that every statement has a semicolon at the end. It's good practice to use braces around the statements in **if** and **else** clauses, even if they only have one statement inside. The compiler isn't always good at understanding that a semicolon is missing, and may give strange error messages two or three lines later. If it suggests that you're missing a semicolon, that might not be the real problem, but the real problem is almost certainly broken syntax somewhere in your code. Good luck!
