### ISSUE TITLE
The link failed.

### ISSUE THREAD

**Issue by songxia233** [MicrosoftDocs/cpp-docs#1484]
The link here  in this page failed.
![121213](https://user-images.githubusercontent.com/32254161/62592013-226bab00-b904-11e9-88b3-c0f3f3cd74d5.JPG)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc5f434a-c825-8829-4a1f-942024217d78
* Version Independent ID: 83e224e4-e334-266e-98a9-a5a87d992feb
* Content: [CMFCToolBar Class](https://docs.microsoft.com/en-us/cpp/mfc/reference/cmfctoolbar-class?view=vs-2019)
* Content Source: [docs/mfc/reference/cmfctoolbar-class.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/mfc/reference/cmfctoolbar-class.md)
* Product: **visual-cpp**
* Technology: **cpp-mfc**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by corob-msft** [comment]
@songxia233 
The lack of a link is probably intentional. Most members of the inheritance hierarchy are found in different articles, but the last one represents the class described in the current article. If that element had a link, it would just go to the current article, making it redundant. The equivalent elements in many MFC articles I checked don't link to their own articles, but some do. It doesn't seem worthwhile to fix up this minor consistency issue.
