### ISSUE TITLE
Samples include how but not why

### ISSUE THREAD

**Issue by BillMedland** [MicrosoftDocs/cpp-docs#1495]
For C4530 (in this case) I would appreciate an example that indicated some code that would work incorrectly and an indication of what would be the impact at runtime. This would help me during code reviews to indicate why it is not enough to disable the warning, or to know under what circumstances I can safely disable the warning. The description is quite clear but the example would help.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a00ea2b-8677-83de-875f-b01637d76fe0
* Version Independent ID: 03938a2e-6e17-596d-eec1-96f89b103d89
* Content: [Compiler Warning (level 1) C4530](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-1-c4530?view=vs-2019#feedback)
* Content Source: [docs/error-messages/compiler-warnings/compiler-warning-level-1-c4530.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/error-messages/compiler-warnings/compiler-warning-level-1-c4530.md)
* Product: **visual-cpp**
* Technology: **cpp-diagnostics**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@BillMedland 

I get what you're saying about examples in general. It's nice to know the real-world consequences of ignoring a particular warning. In this particular case, it's hard to enumerate all the ways things could go wrong. If your code attempts to use C++ exception handling without enabling compiler support for it, resource leaks, indeterminate state, and undefined behavior are just the start. C++ exception handling that follows the language standard behavior for try/catch blocks requires /EHsc. I'm having trouble thinking of a reason to disable this warning.

That's not to say there are no good reasons to write code that doesn't use /EHsc everywhere. If you don't call any code that can throw an exception, then you don't need to have try/catch blocks, and can safely skip /EHsc. You have to use a different /EH switch in code that interfaces with other exception models, such as SEH or .NET interop, and you can't mix exception models in the same source file. Pure C code doesn't need any /EH switch at all.

I don't think this belongs in the topic, but since you asked:

```cpp
// C4530_leak.cpp
// To show leak without /EHsc, compile with: cl C4530_leak.cpp
// For correct behavior, compile with: cl /EHsc C4530_leak.cpp
#include <iostream>
#include <exception>

char resource[9] { "uninited" };

struct Leakage
{
    Leakage() { strcpy_s(resource, "leaked!"); }
    ~Leakage() { strcpy_s(resource, "unleaked"); }
};

void Leaker()
{
    Leakage leaky;   // resource is leaked without /EHsc
    throw std::exception();
    return;
}   // With /EHsc, resource is cleaned up when stack is unwound.

int main()
{
    try { Leaker(); }
    catch (const std::exception&) {}
    std::cout << "resource is " << resource << std::endl;
}
```

**Comment by TylerMSFT** [comment]
Closing per discussion above.
