### ISSUE TITLE
_udiv128 does not accept dividend bigger than 0x308FFFFFFFFFFFFFFFF

### ISSUE THREAD

**Issue by falcon111** [MicrosoftDocs/cpp-docs#1515]
```
#include <stdio.h>
#include <immintrin.h>

typedef struct _u128 {
  unsigned __int64 Low;
  unsigned __int64 High;
} u128;

int main(int argc, char **argv) {
  u128 x;
  unsigned __int64 Remainder, Result;

//  x.High=0x308;
//  x.Low=0xFFFFFFFFFFFFFFFF;
  x.High=0x309;
  x.Low=0;
  Result=_udiv128(x.High, x.Low, 777, &Remainder);
  printf("%I64u %I64u\n", Result, Remainder);
  return 0;
}

```
0x308FFFFFFFFFFFFFFFF and compiled binary works ok:
T:\C>vs2019.exe
18446744073709551615 776

0x3090000000000000000 and compiled binary crashes.

Similar problem exists with _udiv64
Trying new intrinsics on i7-8550U CPU.
Is it me, or is it vs2019 ?

PS: Obviously, result is overflowing, but I do not need a result, I only need a Remainder. Something like this: _udiv128(x.High, x.Low, 777, &Remainder);
Is is possible to get a division reminder ignoring overflowing int64 result?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b4942d1-d3ba-6ac9-b99a-06023ee6697d
* Version Independent ID: d2b669e9-622d-b7e7-57e8-bda054e6478f
* Content: [_udiv128](https://docs.microsoft.com/en-us/cpp/intrinsics/udiv128?view=vs-2019)
* Content Source: [docs/intrinsics/udiv128.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/intrinsics/udiv128.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@falcon111 
When I look at the x64 disassembly, I see the `_udiv128` intrinsic just turns into a `DIV` instruction, after loading the appropriate registers (RDX:RAX). In your sample, the instruction then raises the DE overflow exception, since the maximum quotient of 2^64 - 1 is exceeded. The VC runtime doesn't handle that exception, since it can't distinguish it from a divide-by-zero error on the Intel hardware (per the standard, integer overflow such as divide-by-zero is explicitly specified as undefined behavior), so the program terminates. As for getting a valid result, all bets are off. Normally, the remainder is returned in RDX, but examining it in the debugger doesn't show any change when the exception is raised, for the small range of values I checked, so it's probably not available, even if you do trap and ignore the exception.

To solve your math problem, you could try a library specifically build to handle large numbers, such as [Boost.Multiprecision](https://github.com/boostorg/multiprecision). The [SafeInt library](https://github.com/dcleblanc/SafeInt) might work for certain use cases, too.

I don't see a specific documentation issue to address, so I'm closing the issue.
