### ISSUE TITLE
Missing Store App guidance

### ISSUE THREAD

**Issue by admachina** [MicrosoftDocs/cpp-docs#1551]
Going through these instructions yield a file not found error for store app builds. Forcing the /spectre/onecore libraries to be used cause a WACK test failure.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ad87698-8cd7-aaf9-87b1-eaf8c290017f
* Version Independent ID: be796703-261a-ec99-11e6-d023aa7ee849
* Content: [/Qspectre](https://docs.microsoft.com/en-us/cpp/build/reference/qspectre?view=vs-2019#feedback)
* Content Source: [docs/build/reference/qspectre.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/reference/qspectre.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@admachina

There are no instructions for store app builds because there are no Spectre-mitigated libraries that ship with VS for UWP apps or components. At present, there's no way to deploy such libraries. In other words, the lack of Spectre-mitigated UWP support in MSVC is by design. I've added a note to that effect to the document, and it should appear Monday.

The dev teams for both C++ and WinRT are aware of the issue, and apparently it's been in discussion internally since at least last November. Here's a Developer Community issue that's related: [Turning on spectre mitigations for UWP project results in build errors](https://developercommunity.visualstudio.com/content/problem/589733/turning-on-spectre-mitigations-for-uwp-project-res.html).

About all I can tell you is, when or if support is announced, we'll add such instructions to the docs.
