### ISSUE TITLE
_localtime64_s maximum supported date

### ISSUE THREAD

**Issue by skissane** [MicrosoftDocs/cpp-docs#1556]
This page says that "_localtime64_s, which uses the __time64_t structure, allows dates to be expressed up through 23:59:59, January 18, 3001, coordinated universal time (UTC)".

This is saying the maximum supported date – that corresponding to _MAX__TIME64_T – is 3001-01-18T23:59:59Z. I don't believe that's correct. _MAX__TIME64_T is actually defined as 0x793406fff which corresponds to 3001-01-01T07:59:59Z. 

(Also, the docs for _gmtime64_s give a different date of 3000-12-31T23:59:59Z – shouldn't that be 3001-01-01T07:59:59Z as well?)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 684adba0-62cb-59d7-d58c-69c7181b9903
* Version Independent ID: ef0c00f2-d75b-42f2-7918-208dd9c96560
* Content: [localtime_s, _localtime32_s, _localtime64_s](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/localtime-s-localtime32-s-localtime64-s?view=vs-2019)
* Content Source: [docs/c-runtime-library/reference/localtime-s-localtime32-s-localtime64-s.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/c-runtime-library/reference/localtime-s-localtime32-s-localtime64-s.md)
* Product: **visual-cpp**
* Technology: **cpp-ucrt**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by skissane** [comment]
I just noticed the PR #6. Maybe the actual maximum depends on DLL versions, etc? Does _localtime64_s give a success result if you pass it _MAX__TIME64_T+1? What is the maximum argument for which it returns success?

**Comment by corob-msft** [comment]
@skissane 

There's no defined value for `_MAX__TIME64_T` in the headers now. Instead, the maximum value is defined in a time traits structure used internally, and according to the UCRT sources in the Windows SDK, for 64-bit time types, the maximum value is 0x793582affLL. The immediately preceding comment claims this represents "Number of seconds from 00:00:00, 01/01/1970 UTC to 23:59:59, 01/18/3001 UTC". That matches the current documentation. If you're using an older version of the CRT (older than the last update of VS 2015), then the value is going to be different. In any case, I'd avoid a dependency on the highest possible value for a `__time64_t`, because it's not portable, and as we've seen, it's been changed at least once in the CRT. Instead, pay attention to the success or failure of the functions that use time values. That will keep your code future-proof, in case the value changes again.
