### ISSUE TITLE
2 typos in constructors-cpp.md

### ISSUE THREAD

**Issue by panikgit** [MicrosoftDocs/cpp-docs#1596]
In Move constructors section: "The variable _box_ returned by get_Box() is an xvalue (eXpiring value) which is about to go out of scope." Typos:
1. get_Box() declares and returns variable _b_;
2. return result of get_Box() is value, hence the expression get_Box() is prvalue, not xvalue.

**Comment by mikeblome** [comment]
@panikgit thanks for the feedback. The explanation in the topic was unclear and is now fixed. Should be public in 1-2 days. 

Within the constructor, the value returned by get_Box() is in fact an expiring value. It is a "[temporary](https://en.cppreference.com/w/cpp/language/implicit_conversion#Temporary_materialization)" because the constructor does not assign that return value to any variable, and it will go out of scope as soon as the constructor returns. Therefore it is safe for the constructor to move the contents of the original vector without having to copy it.
