### ISSUE TITLE
VS2019 Debugger hanging when interrupted when remote debugging on gdb

### ISSUE THREAD

**Issue by gzorlee** [MicrosoftDocs/cpp-docs#1616]
Hello,

I have raised what I think could be an issue on the previous MSDN website. We are currently migrating a massive project running on Linux to Visual Studio 2019.

We have already migrated quite a lot of it to remote Linux debugging using CMake 3.14.x for the build and gdb 7.10 for debugging. Now we are at a point where the binary is properly built on Linux and can be run under the debugger from VS. We can put breakpoints (if the breakpoints are set from the beginning. Wink! Wink! Spoiler altert.) and VS properly stops and show all the information. We can see the stacks, the threads. We can step in a function, go to next step, F10, F11 all those guys work. Awesome!

BUT anything we do while the program is running, by running I mean not halted after for instance having hit a breakpoint or pressing break all, results in VS freezing forever. This include adding breakpoints, doing a break all…

We have witnessed few things:

1 - When the break all button is pressed then gdb properly sees the program being halted.

This mean the kill -2 properly reached the Linux host. As you can see:

~"\nProgram received signal "
~"SIGINT, Interrupt.\n"
~"0x000000365d812d34 in dl_open_worker () from /lib64/ld-linux-x86-64.so.2\n"
*stopped,reason="signal-received",signal-name="SIGINT",signal-meaning="Interrupt",frame={addr="0x000000365d812d34",func="dl_open_worker",args=[],from="/lib64/ld-linux-x86-64.so.2"},thread-id="1",stopped-threads="all",core="3"

2 - There is another shellexec.exe spawn by VS:

This is VS while in step by step mode. You see. Only one shellexec.exe.

 
![image001](https://user-images.githubusercontent.com/54445165/66485979-c0e8c980-ea77-11e9-8222-38c533f53a5b.png)

Then we press F5 let’s say and then we try to do a break all. At that time a second shellexec.exe appears in the list:

![image002](https://user-images.githubusercontent.com/54445165/66486013-d4943000-ea77-11e9-9391-42b44d04aa2b.png)

Now if you kill the one which just appeared then, voilaaaa, VS works again and is properly halted at the right place.

If by mistake you killed the first one then nothing happens. But then if you kill the seconds one when VS comes back to life again it tells you the connection with the debugger is lost and you have to restart debugging. Not a big deal, at least VS is alive!

3 - If you do a kill -2 on the process pid directly from Linux then it works!

VS will not freeze and properly halt at the right place.

4 - If you create a task which pretty much does the kill -2 directly from VS it works too!

For instance if you create such a task in the tasks.vs.json:

{
  "version": "0.2.1",
  "tasks": [
    {
      "taskLabel": "Interrupt GT",
      "taskName": "InterruptGT",
      "appliesTo": "*",
      "type": "remote",
      "command": "kill -2 `ps aux | grep gtorrent | grep myProgram | grep -v grep | grep -v gdb | awk '{print $2}'`",
      "remoteMachineName": "mymachinename-123.blabla.com"
    }
  ]
}

Then it works too! You are going to say “Indeed because it is just the kill -2”. I agree. I just wanted to mention it :)

5 - Nothing crazy in the logs of VS

There are a lot of machine names and program names in the log but there is really nothing bad. If you think I should look for something please let me know.

This is pretty much all what we know about the problem so far. Any help would be greatly appreciated.

GT.

**Comment by corob-msft** [comment]
@gzorlee 

Sorry it's giving you trouble. We've alerted the product team to your issue. One thing they'd prefer is that product issues get reported in the [Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html) forum, which they look at regularly, rather than here in the documentation issues board. There's an easy way to do that, built right into Visual Studio. Go to the **Help** menu, select **Send Feedback** > **Report a Problem**, and fill out a new problem report. Your report will be seen by the product developers who can do something about it. We've got [more complete directions here](https://docs.microsoft.com/cpp/overview/how-to-report-a-problem-with-the-visual-cpp-toolset), but the gist is basically the same as what you reported here, with a description of what you're trying to do, all the steps you took, and what didn't work the way you expected. You can expect follow-up on the Visual Studio [Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html) web site.

Normally we close product support issues like this unless they have a clear documentation aspect, but I'll leave this open temporarily to report anything we hear back from the developers in the near term.

**Comment by gzorlee** [comment]
@corob-msft

Thank you very much for the prompt answer. We tried the VS report first but it is blocked by our admins hence the post on the MSDN and then on this github. I don't mind at all posting on the Dev Community page but I don't want to create another duplicate. Shall I though? You think it can help?

Have a good day.

GT.

**Comment by gzorlee** [comment]
Also we are updating to 16.3.3 and we will see if it changes anything :)

**Comment by corob-msft** [comment]
@gzorlee 

If your IT staff have blocked Visual Studio reports with a firewall, it's still possible to enter issues directly in the Developer Community website, if you have access to it: [Here's the web form for entering C++ issues.](https://developercommunity.visualstudio.com/content/problem/post.html?space=62)
An engineering issue doesn't really count as a duplicate with documentation issues, so I'd say go ahead and enter it.

I can also copy your report into an issue on your behalf, but then the notifications and questions would go to me instead of to you. That's not quite as useful, but I think it's possible for anyone to follow issues there, so if you'd prefer that, I can do it and post a link to the issue here.

**Comment by gzorlee** [comment]
Just reported it under https://developercommunity.visualstudio.com/content/problem/770160/vs2019-debugger-hanging-when-interrupted-when-remo.html

Thank you for all the advices!

**Comment by corob-msft** [comment]
That looks great. The engineering team will let us know if any documentation needs to be updated.
