### ISSUE TITLE
No mention of /analyze:projectdirectory parameter

### ISSUE THREAD

**Issue by adamgoon** [MicrosoftDocs/cpp-docs#1624]
There is no description of the /analyze:projectdirectory that can be observed in the VS build output along side the other /analyze commands. It is also not mentioned in cl.exe help (cl /?)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 09296a0d-dea6-bcf6-7370-5ec2cf061835
* Version Independent ID: b6de3061-2d20-4508-6a76-663a2d61d098
* Content: [/analyze (Code Analysis)](https://docs.microsoft.com/en-us/cpp/build/reference/analyze-code-analysis?view=vs-2019#feedback)
* Content Source: [docs/build/reference/analyze-code-analysis.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/reference/analyze-code-analysis.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@adamgoon 

**/analyze:projectdirectory** is an internal option invoked by MSBuild. It effectively prepends a project directory to the ruleset directories search path. That means your project's custom ruleset, if you have one, is found first, before the compiler looks in the common ruleset directories. It's shorthand, because you can achieve the same effect by using the **/analyze:ruleset** option with a relative or absolute path one or more times at the command line.
