### ISSUE TITLE
Missing content on error C1049

### ISSUE THREAD

**Issue by bhupeshpant19jan** [MicrosoftDocs/cpp-docs#1639]
Please add more information on error type: C1049 : invalid numerical argument 'value'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dcda27f2-fc5a-65d9-663c-3d40f5e5e7db
* Version Independent ID: c2d44f5c-f391-b1ae-605f-1d02e164ce0f
* Content: [Compiler fatal errors C999 through C1999](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-errors-1/compiler-fatal-errors-c999-through-c1999?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(C1049)%26rd%3Dtrue&view=vs-2019#feedback)
* Content Source: [docs/error-messages/compiler-errors-1/compiler-fatal-errors-c999-through-c1999.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/error-messages/compiler-errors-1/compiler-fatal-errors-c999-through-c1999.md)
* Product: **visual-cpp**
* Technology: **cpp-diagnostics**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by bhupeshpant19jan** [comment]
I am getting this error while building my projects but could not find any information around.

```
Error	C1049	invalid numerical argument 'specanalysismode:v1_0'	SysLockCommonTest	LINK         Line:1
```

**Comment by corob-msft** [comment]
@bhupeshpant19jan 

This is a command-line parsing error message. The command-line parser encountered the string `specanalysismode:v1_0` somewhere it expected to find a numerical argument instead. It's obviously not a number, so the parser complained.

I'd look at what appears before this on the command line to make sure it's well-formed. It could also be caused by a makefile or other build tool configuration error. There's no way to tell from the information provided.

**Comment by bhupeshpant19jan** [comment]
Please let me know what all information you are looking for?

**Comment by corob-msft** [comment]
@bhupeshpant19jan 

The universe of ways to cause C1049 is large. It can happen when tools are invoked by Visual Studio, in makefiles or by CMake, or if you're just entering commands on the command line. To fix this error, you need to know what the complete command line is. I can't tell you exactly where to look, since that depends on your project and how you build it.

If you're building inside Visual Studio, you can open your project's **Property Pages** dialog. On the **Configuration Properties** > **C/C++** > **General** page, change the **Suppress Startup Banner** property to **No**. Choose **OK** to save your changes. The **Output** window now shows the command line when you build. It's near the top, and starts with "cl", right after the copyright line.

Somewhere in your compiler command line, there's an option that requires a numerical argument, and you don't supply one. You should be able to find it easily, because it's the one immediately before 'specanalysismode:v1_0' appears on the command line. That's what the command tried to parse as a number.

**Comment by cnrshantanu** [comment]
Not sure why its not working, I tried your suggested changes but I donot see specanalysismode anywhere


`1>------ Build started: Project: ConsoleApplication2, Configuration: Debug x64 ------
1>Microsoft (R) C/C++ Optimizing Compiler Version 19.16.27031.1 for x64
1>Copyright (C) Microsoft Corporation.  All rights reserved.
1>
1>cl /c /IC:\Users\shadas\Source\Repos\ConsoleApplication2\ConsoleApplication2\aik /ZI /JMC /W3 /WX- /diagnostics:classic /sdl- /Od /D _DEBUG /D _CONSOLE /D _UNICODE /D UNICODE /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /permissive- /Zc:wchar_t /Zc:forScope /Zc:inline /std:c++latest /Yc"pch.h" /Fp"x64\Debug\ConsoleApplication2.pch" /Fo"x64\Debug\\" /Fd"x64\Debug\vc141.pdb" /Gd /TP /FC /errorReport:prompt pch.cpp
1>
1>pch.cpp
1>Microsoft (R) C/C++ Optimizing Compiler Version 19.16.27031.1 for x64
1>Copyright (C) Microsoft Corporation.  All rights reserved.
1>
1>cl /c /IC:\Users\shadas\Source\Repos\ConsoleApplication2\ConsoleApplication2\aik /ZI /JMC /W3 /WX- /diagnostics:classic /sdl- /Od /D _DEBUG /D _CONSOLE /D _UNICODE /D UNICODE /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /permissive- /Zc:wchar_t /Zc:forScope /Zc:inline /std:c++latest /Yu"pch.h" /Fp"x64\Debug\ConsoleApplication2.pch" /Fo"x64\Debug\\" /Fd"x64\Debug\vc141.pdb" /Gd /TP /FC /errorReport:prompt ConsoleApplication2.cpp
1>
1>ConsoleApplication2.cpp
1>Microsoft (R) Incremental Linker Version 14.16.27031.1
1>Copyright (C) Microsoft Corporation.  All rights reserved.
1>
1>"/OUT:C:\Users\shadas\Source\Repos\ConsoleApplication2\x64\Debug\ConsoleApplication2.exe" /INCREMENTAL:NO /LIBPATH:C:\Users\shadas\Source\Repos\ConsoleApplication2\ConsoleApplication2\aik TpmEngFWInit.lib kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST "/MANIFESTUAC:level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG:FASTLINK "/PDB:C:\Users\shadas\Source\Repos\ConsoleApplication2\x64\Debug\ConsoleApplication2.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT "/IMPLIB:C:\Users\shadas\Source\Repos\ConsoleApplication2\x64\Debug\ConsoleApplication2.lib" /MACHINE:X64 x64\Debug\ConsoleApplication2.obj
1>x64\Debug\pch.obj
1>ConsoleApplication2.obj : warning LNK4075: ignoring '/EDITANDCONTINUE' due to '/INCREMENTAL:NO' specification
1>TpmEngFWInit.lib(fwinit.obj) : MSIL .netmodule or module compiled with /GL found; restarting link with /LTCG; add /LTCG to the link command line to improve linker performance
1>Microsoft (R) Incremental Linker Version 14.16.27031.1
1>Copyright (C) Microsoft Corporation.  All rights reserved.
1>
1>"/OUT:C:\Users\shadas\Source\Repos\ConsoleApplication2\x64\Debug\ConsoleApplication2.exe" /INCREMENTAL:NO /LIBPATH:C:\Users\shadas\Source\Repos\ConsoleApplication2\ConsoleApplication2\aik TpmEngFWInit.lib kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST "/MANIFESTUAC:level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG:FASTLINK "/PDB:C:\Users\shadas\Source\Repos\ConsoleApplication2\x64\Debug\ConsoleApplication2.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT "/IMPLIB:C:\Users\shadas\Source\Repos\ConsoleApplication2\x64\Debug\ConsoleApplication2.lib" /MACHINE:X64 x64\Debug\ConsoleApplication2.obj
1>x64\Debug\pch.obj
1>ConsoleApplication2.obj : warning LNK4075: ignoring '/EDITANDCONTINUE' due to '/INCREMENTAL:NO' specification
1>LINK : fatal error C1049: invalid numerical argument 'specanalysismode:v1_0'
1>LINK : fatal error LNK1257: code generation failed
1>Done building project "ConsoleApplication2.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
`

**Comment by corob-msft** [comment]
@cnrshantanu @bhupeshpant19jan 

You're right, it's not in those command lines. The more I look at this, the more I suspect a bug in the compiler. There's an internal flag for pass 2 named "guardspecanalysismode:v1_0", which I think is related to Spectre mitigations. It looks like this flag is being used and partially clobbered by something during your compile, and then the remainder is reported out as a parsing error. Perhaps a buffer gets reused and isn't null-terminated appropriately. I don't know.

The trick is to create a minimal repro to track it down, and then post it on [Developer Community](https://docs.microsoft.com/en-us/cpp/overview/how-to-report-a-problem-with-the-visual-cpp-toolset?view=vs-2019) for proper attention. Even teams internal to Microsoft are encouraged to use this forum for reporting compiler and linker issues. I think this issue fits the bill. It's a bit of work, but I recommend it. 

@manbearian for compiler back end contacts who might know more.

**Comment by bhupeshpant19jan** [comment]
We were able to get around this problem by consuming the dlls instead of libs. We were not able to root cause it.

**Comment by corob-msft** [comment]
@GreatKeeper for reference.

**Comment by manbearian** [comment]
If you suspect a compiler bug, then opening an issue Developer Community is the right thing to do. The documentation at https://aka.ms/compilerbug can be helpful when creating a compiler repro.
