### ISSUE TITLE
Close method and dtor

### ISSUE THREAD

**Issue by travnick** [MicrosoftDocs/cpp-docs#1648]
Is it really required to always call `Close()` event if object goes out of scope?
In other words: Does the dtor clean up resources, or it does not fulfill the RAII, ans just leaves the dangling resources?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71164027-2c34-9866-08c8-8ceef252b0a8
* Version Independent ID: 9a2b95ed-065d-cb52-29e5-669d232230c0
* Content: [CRecordset Class](https://docs.microsoft.com/en-us/cpp/mfc/reference/crecordset-class?view=vs-2019#remarks)
* Content Source: [docs/mfc/reference/crecordset-class.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/mfc/reference/crecordset-class.md)
* Product: **visual-cpp**
* Technology: **cpp-mfc**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by corob-msft** [comment]
@travnick 

The MFC design predates widespread adoption of RAII, so it's not perfect. You can read the source code for CRecordset yourself, in the VS install directory, in VC\Tools\MSVC\\*version*\atlmfc\src\mfc\dbcore.cpp. It does call `close()` in the destructor, but with a caveat that it can leak resources if called implicitly under some circumstances. It's best to stick with the documentation in this case.

**Comment by travnick** [comment]
So examples like that are quite misleading:
https://docs.microsoft.com/en-us/sql/ado/guide/appendixes/visual-c-ado-programming?view=sql-server-ver15#casting-ado-object-pointers-with-idispatch-

There is no cleanup code in `catch` (and only _com_error is "handled"), so depending on place where exception is thrown, then resource leakage appears.
So how should we follow the documentation, since it's not clearly stated how the classes behaves in case of going out of scope?

**Comment by corob-msft** [comment]
The documentation does say how the class behaves. For CRecordset, it says if you have code paths that can destroy a CRecordset object with an open recordset before `close` is called, you have a potential resource leak. Whether it happens because of an exception, or just falling off the end of the scope, doesn't really matter. How you resolve the potential leak is up to you. I'd consider using a wrapper or helper class that implements a complete RAII model on the open recordset, so resources can't escape the block they're created in if an exception is thrown. Other solutions are possible. Most of the example code predates the stack-based object lifetime model. Owning pointers and resource flags were declared in outer scopes, for objects created by using `new`. The resources had to be released and the objects deleted explicitly on every code path. It was complicated and error-prone, and that's why we recommend you don't write code that way anymore. Unfortunately, not all of our code samples follow good engineering practice, especially older ones. You've linked to one example.
