### ISSUE TITLE
Why is dumpbin documentation appearing in the NMAKE reference?

### ISSUE THREAD

**Issue by dunhor** [MicrosoftDocs/cpp-docs#1657]
E.g. this page appears in https://docs.microsoft.com/en-us/cpp/build/reference/dependents?view=vs-2019 which doesn't seem correct

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d9eebf2c-e39f-ba28-d37c-24481caba46c
* Version Independent ID: c9bcfe46-7f88-7004-b18f-feac77bb7fbf
* Content: [/DEPENDENTS](https://docs.microsoft.com/en-us/cpp/build/reference/dependents?view=vs-2019#feedback)
* Content Source: [docs/build/reference/dependents.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/reference/dependents.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@dunhor 

You are right. This mistake happened when two documents with the same name were merged into the same location. For now, you can find the documentation in [Dependents](https://docs.microsoft.com/en-us/previous-versions/visualstudio/visual-studio-2013/w9a45wd6%28v%3dvs.120%29) while I get around to reviving it. Since this issue is a dup of #1530 I'm closing it. You can watch that issue for information on when the doc gets fixed.
