### ISSUE TITLE
Error Loading Template for Tutuorial

### ISSUE THREAD

**Issue by Ownpaku** [MicrosoftDocs/cpp-docs#1670]
[Enter feedback here]

Hello, I just downloaded Visual Studio to try it out and go through this tutorial, and immediately I'm hit with this error about templates, which of course makes it difficult to go through the tutorial.

![image](https://user-images.githubusercontent.com/33004051/67725191-79d36180-f9af-11e9-91ab-890fa94e9d3f.png)
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f51e5807-3f78-ff63-ef41-4629b7ae84d5
* Version Independent ID: c1dbef6c-f895-a6d7-9d83-e2ac8f864327
* Content: [Create a C++ console app project](https://docs.microsoft.com/en-us/cpp/get-started/tutorial-console-cpp?view=vs-2019#feedback)
* Content Source: [docs/get-started/tutorial-console-cpp.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/get-started/tutorial-console-cpp.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@Ownpaku 

Sorry you're having trouble. This looks like a product issue with your installation of Visual Studio. It's possible that it's [already fixed](https://developercommunity.visualstudio.com/content/problem/572125/visual-studio-2019-doesnt-handle-14000-assembly-re.html) in an update, so make sure you've applied the latest updates to your copy of Visual Studio. (For Visual Studio 2017, that's version 15.9.17, and for Visual Studio 2019, it's currently 16.3.5.) If that doesn't solve the problem, it's possible that removing then reinstalling the **Desktop development with C++** workload might help.

If an updated version of Visual Studio and an up-to-date install of the C++ workload doesn't fix this problem, then I'd use the [built-in feedback system to report the issue](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2019). That sends the issue to the development team, which has the resources to investigate and make any product fixes required.

Unfortunately, this problem is not something the documentation team can fix with updates to the docs, so I'm closing this issue.
