### ISSUE TITLE
What does it mean when filename_1.obj is EMPTY?

### ISSUE THREAD

**Issue by nurbles** [MicrosoftDocs/cpp-docs#1682]
I just received this warning:
13&gt;LINK : warning LNK4286: symbol 'uLWM_Notify' defined in '' is imported by 'main.obj'
The info here is not helping me to figure out what I am being told.  As best I can figure out, the symbols is never defined elsewhere, but the linker believe it may have been (but cannot say where) so it is complaining.  Maybe this condition could be mentioned in the documentation?  Please?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 82e663e7-83de-68f1-1f0a-29e7db4f2783
* Version Independent ID: 53efb74d-9f84-63d7-8206-2bb6ca836d27
* Content: [Linker Tools Warning LNK4286](https://docs.microsoft.com/en-us/cpp/error-messages/tool-errors/linker-tools-warning-lnk4286?view=vs-2019)
* Content Source: [docs/error-messages/tool-errors/linker-tools-warning-lnk4286.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/error-messages/tool-errors/linker-tools-warning-lnk4286.md)
* Product: **visual-cpp**
* Technology: **cpp-diagnostics**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@nurbles 

It's not documented because it hadn't been considered a possibility. It could represent a linker bug.

Before reporting it, I'd do a couple of things: If any linker errors appear before that one, I'd fix those first and see if it goes away. If not, I'd generate the preprocessed output for main.cpp (use the [/P](https://docs.microsoft.com/cpp/build/reference/p-preprocess-to-a-file) option, which will create main.i) and search it for the symbol, then look at the context to see where it's coming from. `uLWM_Notify` may be the product of some macro gone wrong in a header file. Perhaps after seeing that, a solution will suggest itself.

If this doesn't solve your problem, then [reporting it on Developer Community](https://docs.microsoft.com/cpp/overview/how-to-report-a-problem-with-the-visual-cpp-toolset) is your best option. If for some reason this is a feature and not a bug, the engineering team will let us know, and we'll see about documenting it.
