### ISSUE TITLE
Unicode is... what?

### ISSUE THREAD

**Issue by larvacea** [MicrosoftDocs/cpp-docs#169]
https://github.com/MicrosoftDocs/cpp-docs/blob/master/docs/cpp/char-wchar-t-char16-t-char32-t.md

The sentence fragment "Unicode is" has been frustrating readers since 2016; I would be happy to supply a pull request with my thoughts on the joys of wchar_t, char16_t, and char32_t as character types if you like.
  --Martin Harriman (Microsoft Office Telemetry)

**Comment by corob-msft** [comment]
Yes, that dangling sentence fragment isn't very informative. I'm not sure what the original author had in mind, so I just gave the topic a quick refresh and left it out.

I didn't bother with a table, since I'm not sure what it would add. The UCRT doesn't support char16_t or char32_t at all, but the C++ Standard Library does just fine.
