### ISSUE TITLE
compiler toolset

### ISSUE THREAD

**Issue by cmoisei** [MicrosoftDocs/cpp-docs#1708]
At the top of the article you can read "compiler toolset is also downloadable as a standalone package from the Visual Studio downloads page. " I don't see any options to download that standalone package. Can you please be more specific about its location?

Much appreciated!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45e8226e-799c-2e3b-01c6-d7603141d5ca
* Version Independent ID: 4f7cd478-ffcc-bec5-b61a-e17085ccd6f5
* Content: [Use the Microsoft C++ toolset from the command line](https://docs.microsoft.com/en-us/cpp/build/building-on-the-command-line?view=vs-2019#feedback)
* Content Source: [docs/build/building-on-the-command-line.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/building-on-the-command-line.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@cmoisei 
The compiler toolset download has become slightly harder to find on the Downloads page since the article was written. On the [Visual Studio Downloads](https://visualstudio.microsoft.com/downloads/) page, scroll down to the **All downloads** section. Expand the **Tools for Visual Studio 2019** node. The download you want is named **Build Tools for Visual Studio 2019**. It's not C++-specific; you'll also get the .NET compilers and other tools. You can safely ignore those if you don't need them. It would be nice to have a simpler and smaller download of just the C++ tools, but that's not available.

**Comment by cmoisei** [comment]
Excellent. I found it. Thank you!
