### ISSUE TITLE
C++ indirection

### ISSUE THREAD

**Issue by larvacea** [MicrosoftDocs/cpp-docs#172]
cpp-docs / docs / c-language / indirection-and-address-of-operators.md 

The C++ standard has a very limited definition of "invalid pointer values" (see sections 6.7 and 6.9.2) and the semantics of operations on those values (specifically, indirection is "undefined" and other operations are "implementation-defined").

This is a really minor issue, but pedantically, the standard would not call most of the categories called out on this page"invalid pointer values," and the standard includes a few issues that you have not included, e.g., pointers to other objects whose storage has been freed (not just local, automatic objects).

If you care about extreme pedantry, you might use a different term than "invalid" to avoid confusion with the standard's "invalid pointer value."

An even more minor problem: the indentation after the bullet list (the description of the address-of operator) is one indent too deep.

**Comment by corob-msft** [comment]
Thanks. This is actually the C language reference, not the C++ reference, and I'm pretty sure this topic hasn't been updated since it was created to describe C89. The equivalent in the C99 Standard documentation, which is nominally our C target language, is section 6.5.3.2. Our description of invalid pointer values is a bit of a superset of the standard language from footnote 87: "Among the invalid values for dereferencing a pointer by the unary * operator are a null pointer, an address inappropriately aligned for the type of object pointed to, and the address of an object after the end of its lifetime." We include addresses outside the valid range for the executing program, which seems like an implementation detail. 

Feel free to propose an edit to fix this; I may get around to it, but probably not immediately.

**Comment by corob-msft** [comment]
Fixes are live.
