### ISSUE TITLE
Some steps missing

### ISSUE THREAD

**Issue by asfarley** [MicrosoftDocs/cpp-docs#1748]
For future readers, I found that a few key steps were missing from the steps given above for implementing a drop-target.

1) InitInstance() for your top-level application should call AfxOleInit(), otherwise the Register() function will fail.

2) I can't see how directly using the base COleDropTarget would ever do anything useful. I found that the only way to implement drop functionality was to inherit from COleDropTarget and override OnDragEnter/OnDragLeave/OnDragOver/OnDrop. I can't see how it would be possible to implement drag'n'drop functionality without overriding these functions.

This page in particular was helpful:
https://jeffpar.github.io/kbarchive/kb/135/Q135299/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d7e1a35-f31b-83b8-7fcb-d16e4a2aec59
* Version Independent ID: c81d11be-5c95-839a-3450-8c727c18728e
* Content: [Drag and Drop: Implementing a Drop Target](https://docs.microsoft.com/en-us/cpp/mfc/drag-and-drop-implementing-a-drop-target?view=vs-2019#feedback)
* Content Source: [docs/mfc/drag-and-drop-implementing-a-drop-target.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/mfc/drag-and-drop-implementing-a-drop-target.md)
* Product: **visual-cpp**
* Technology: **cpp-mfc**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by corob-msft** [comment]
@asfarley 
There's more than one way to implement drag and drop in MFC. The method described is demonstrated in the [OCLIENT sample in the VCSamples archive](https://github.com/microsoft/VCSamples/tree/master/VC2010Samples/MFC/ole/oclient). And yes, it does have a call to `AfxOleInit` in it, but otherwise it's as described in the article. There doesn't seem to be a compelling argument for change.

**Comment by asfarley** [comment]
@corob-msft  So 1 critical line is missing, and the demo won't work without it. This isn't compelling?

This website is the **primary documentation** for the scroll feature. Referring me to an example that happens to do it one particular way, and saying that the documentation doesn't need clarification because the example exists, does not eliminate the problem. 

Anyone developing scroll-features on MFC will probably start with the online documentation, not by reviewing every code sample. 

The core of my complaint is that Microsoft's documentation around scrolling is distributed among too many pages, making it impossible to identify a source of truth.

**Comment by corob-msft** [comment]
@asfarley 
I'm confused by your complaint about scroll features, since the article is about implementing a drag-and-drop target, using either OLE or non-OLE methods. I could be wrong about your initial complaint: I understood you'd found some different way to implement the feature and thought this article was misleading, partly because it doesn't mention that you have to initialize OLE to use OLE features. That's true, though any MFC app created by the new project template gets OLE initialized by default. Is that what you'd like to see mentioned, for people building MFC apps from scratch?

**Comment by asfarley** [comment]
Sorry, I've been working on a scrolling-related issue recently; that was a typo in my previous message. I meant to say drag'n'drop.

Also, I apologize for my rude tone; I appreciate that you're helping me out. 

> Is that what you'd like to see mentioned, for people building MFC apps from scratch?

I'm not building from scratch exactly (I do use wizards and MFC generators whenever possible), but the short answer is: **yes**, I do want documentation that assumes the reader is starting from scratch (or is at least organized in a recursive manner so I can dive deeper if necessary). 

My scenario is that I'm supporting a complex legacy MFC application. Development began about 10 years ago on VS2008. 

I'm finding that relying on wizards and generators is simply not sufficient to resolve issues in our code-base, or to develop new features. Often, I try the wizard, but some field is e.g. greyed-out or missing compared to the tutorial I'm following, so I need to know what's happening underneath.

It might seem obvious to you that Ole applications need to initialize Ole, but it wasn't obvious to me as a new MFC developer. There are so many layers that even if I know "Ole should be initialized", I don't necessary know what that means; is the init function called by MFC? What function do I use to initialize it? Is there more than one way to initialize it? Etc etc. 

Consider the difference between these two documents:

[https://docs.microsoft.com/en-us/cpp/mfc/drag-and-drop-ole?view=vs-2019#implement-a-drop-target](https://docs.microsoft.com/en-us/cpp/mfc/drag-and-drop-ole?view=vs-2019#implement-a-drop-target)

[https://github.com/MicrosoftDocs/cpp-docs/blob/master/docs/mfc/drag-and-drop-implementing-a-drop-target.md](https://github.com/MicrosoftDocs/cpp-docs/blob/master/docs/mfc/drag-and-drop-implementing-a-drop-target.md)

If Ole initialization is assumed, why does the page about Drag'n'Drop OLE specifically mention the Ole initialization, while the other page does not? 

In general, I've run into this problem many times: there are 2-3 Microsoft documentation pages covering a particular topic, all from a slightly different angle, none of them being totally comprehensive. So then I try to use a Wizard to get a complete working example, and even the Wizard doesn't work, so I'm stuck inspecting the generated code and trying to pull together several documentation pages. 

I understand if you want to close this issue since it isn't very specific; I'm not overly concerned about Ole initialization, but I wanted someone to hear what I'm running into with the documentation. It feels like the documentation hasn't been tested, in the sense that a person new to MFC can't really use it to learn topics that they don't already know.

**Comment by corob-msft** [comment]
In this particular instance, it's because I just rewrote the OLE drag and drop page to incorporate the content of the Implement a drop target page and a couple others, and added an initialization step, while removing the bits about non-OLE targets, since they were confusing and not called out specifically. Non-OLE drag and drop is basically file-centric and works a little differently anyway. The other page is about to get deleted. 

So, your specific issue is fixed. The general issue isn't, and probably never will be. The MFC content is not quite archived yet, but it only gets bug fixes. We'll never have the resources to reorganize or rewrite it, because it's a legacy product with, similarly, only bug-fix levels of ongoing development. When we do touch it, we try to consolidate it and fix what we can. Your best resources for MFC overviews are likely to be decade-old blog posts, and old books like Jeff Prosise's Programming Windows with MFC (which is really good, BTW). Feel free to continue to raise issues in the MFC content, though. That's the only way anything will be fixed.

**Comment by asfarley** [comment]
Thank you - I've been doing as you suggest, pulling together old blog posts and the Prosise book. I do appreciate the ongoing bug-fixes and documentation cleanup, even if it's minor.
