### ISSUE TITLE
Very large tuple

### ISSUE THREAD

**Issue by sergegers** [MicrosoftDocs/cpp-docs#1760]
[Enter feedback here]

Is where a way to increase compiler stack depth in case of the very large tuple?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee2d101e-aa75-3dc3-6c62-ef0474ede931
* Version Independent ID: 75162c73-c5e4-cd1c-f971-616d26a6158c
* Content: [Fatal Error C1202](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-errors-1/fatal-error-c1202?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev16.query%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(C1202)%26rd%3Dtrue&view=vs-2019)
* Content Source: [docs/error-messages/compiler-errors-1/fatal-error-c1202.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/error-messages/compiler-errors-1/fatal-error-c1202.md)
* Product: **visual-cpp**
* Technology: **cpp-diagnostics**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@sergegers 

I don't know of a compiler option to do that. I put in a question to the dev team, and I'll post their response if I hear back. I believe there's a hard limit on the number of template expansions of around 500, but it's not one of our [documented compiler limits](https://docs.microsoft.com/en-us/cpp/cpp/compiler-limits?view=vs-2019).

That said, I'm closing the issue, since it doesn't seem like a documentation issue. It's a question that's more appropriate for the C++ section of the Visual Studio [Developer Community](https://developercommunity.visualstudio.com/spaces/62/index.html) site.
