### ISSUE TITLE
Please provide some examples of reference 

### ISSUE THREAD

**Issue by NerkarVijay** [MicrosoftDocs/cpp-docs#1765]
Documentation is very good. Very clear picture after reading all examples.
But please provide examples of if type-id is a reference type 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 50d85be2-8651-4283-1781-2fb38dcf6024
* Version Independent ID: 9108c324-b273-959b-12b3-b0995c44d59a
* Content: [dynamic_cast Operator](https://docs.microsoft.com/en-us/cpp/cpp/dynamic-cast-operator?view=vs-2019&source=docs#feedback)
* Content Source: [docs/cpp/dynamic-cast-operator.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/cpp/dynamic-cast-operator.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by corob-msft** [comment]
@NerkarVijay 

The code you seek is in the function called `Globaltest` in the Example code section. Other than requiring an exception trap instead of a null check, reference and pointer `dynamic_cast` behavior is similar enough that we haven't thought it worth cluttering the article with double the examples.
