### ISSUE TITLE
What folders are included in the rsync transfer to the remote Linux machine?

### ISSUE THREAD

**Issue by DavidA2014** [MicrosoftDocs/cpp-docs#1781]
My project folder has this structure:

    --|--CMake
      |    |-- CMakeLists.txt
      |    |-- CMakeSettings.json
      |    |-- <build folders for Windows>
      |
      |-- Source_files
      |
      |-- Data_files

When I select the Linux-Debug configuration, Visual Studio 2019 correctly copies, using rsync, all files and folders in the tree shown above (except those explicitly excluded).

However, with Visual Studio 2017, only files and folders beneath the CMake folder are copied.   Source_files and  Data_files are not copied.

Is this a bug in Visual Studio 2017?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 296f6914-b366-1ab8-4c08-6d51fc7212fa
* Version Independent ID: 04aec2e0-f39a-2e52-6a09-354222d47146
* Content: [Create and configure a Linux CMake project in Visual Studio](https://docs.microsoft.com/en-us/cpp/linux/cmake-linux-project?view=vs-2019#feedback)
* Content Source: [docs/linux/cmake-linux-project.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/linux/cmake-linux-project.md)
* Product: **visual-cpp**
* Technology: **cpp-linux**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by corob-msft** [comment]
@DavidA2014 
Sorry about the delayed response. I know that 2017 has more limited support for CMake projects than 2019, but I don't know if this falls under that heading. When you have a product question of this sort (that is, "Is this a bug?"), it's better to ask about it on [Developer Community](https://developercommunity.visualstudio.com/spaces/62/index.html) than to create a doc issue. If it turns out it really is a doc issue, the dev team members that respond will tell us what needs to be updated, which might be different behavior, or just a caveat about a particular version.
Closing for now, as it's not known to be a doc issue. Yet.
