### ISSUE TITLE
not running stdlib.h 

### ISSUE THREAD

**Issue by muhammadfawad1** [MicrosoftDocs/cpp-docs#1784]
[a.TXT](https://github.com/MicrosoftDocs/cpp-docs/files/3961615/a.TXT)
THE FILE RENAMED TO a.TXT

a.c(1): fatal error C1083: Cannot open include file: 'stdlib.h': No such file or
 directory
i want to run system calls linux (learning OS course BSCS )
but it isn't compiling

from:
https://docs.microsoft.com/en-us/cpp/build/walkthrough-compile-a-c-program-on-the-command-line?view=vs-2019

what are suggestions so that i can run code on linux but debug on visual studio

**Comment by corob-msft** [comment]
@muhammadfawad1 

It looks like you're on a page with an example meant for Windows. For Linux, I'd start with [Download, install, and set up the Linux workload](https://docs.microsoft.com/cpp/linux/download-install-and-setup-the-linux-development-workload) to make sure you've got everything set up correctly. The Windows Subsystem for Linux (WSL) is a convenient way to try things out, although you can also target another Linux computer.

Once that's set up, you need to [Connect to your target Linux system in Visual Studio](https://docs.microsoft.com/cpp/linux/connect-to-your-remote-linux-computer). There are separate instructions for a remote box or for WSL connections.

Next, follow the steps in [Create a new Linux project](https://docs.microsoft.com/cpp/linux/create-a-new-linux-project), and choose the **Console Application (Linux)** template. It starts with a "Hello, World" app that you should be able to edit into what you really want to build. At the bottom of the article, follow the **Next steps** links to move on to articles about configuring, deploying, and debugging your programs.

I'm closing your issue, since it doesn't seem to show a problem with this particular article. Good luck with your schoolwork.
