### ISSUE TITLE
DEP description link is dead

### ISSUE THREAD

**Issue by Holo-Krzysztof** [MicrosoftDocs/cpp-docs#1792]
The first link on this page leads to a 404 and I've been unable to locate the original article (Google cache says 404 as well).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 15af21c2-96ba-a549-3d56-afac64abeb19
* Version Independent ID: e657c6a5-873a-8ad5-ecef-8d60166d4838
* Content: [/NXCOMPAT (Compatible with Data Execution Prevention)](https://docs.microsoft.com/en-us/cpp/build/reference/nxcompat-compatible-with-data-execution-prevention?view=vs-2019#feedback)
* Content Source: [docs/build/reference/nxcompat-compatible-with-data-execution-prevention.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/reference/nxcompat-compatible-with-data-execution-prevention.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@Holo-Krzysztof 
It looks like the article has been deleted. Probably because it was part of the Windows XP support documentation, and Windows XP isn't supported anymore. I found [a copy on the Internet Archive](https://web.archive.org/web/20191018064507/https://support.microsoft.com/en-us/help/875352/a-detailed-description-of-the-data-execution-prevention-dep-feature-in). Since there's no current version available, my only option is to delete the link. I've made a PR to do that; it should be visible tomorrow.
