### ISSUE TITLE
Parallel Patterns Library (PPL) build for linux

### ISSUE THREAD

**Issue by antgr** [MicrosoftDocs/cpp-docs#1801]
Hi, can I do that? I want to build a cross platform app, and I want to use the library for both windows and linux. Can I rely on this library, or should I use different implementations for the two platforms?
Here is the documentation : https://github.com/MicrosoftDocs/cpp-docs/blob/master/docs/parallel/concrt/parallel-patterns-library-ppl.md

**Comment by corob-msft** [comment]
@antgr 

As far as I know, it's possible to use the PPL on both Windows and Linux. There are several things to consider, though:

- The PPL is not under active development. It's no longer used as part of the implementation of the VC runtime, and hasn't been since the VS 2015 release.

- Intel supports a mostly-PPL-compatible library called [Threading Building Blocks](https://github.com/intel/tbb) that works cross-platform. They've extended the parallel APIs significantly, but use a different task model.

- Microsoft made the asynchronous task patterns available in the open source [C++ REST SDK](https://github.com/Microsoft/cpprestsdk). This library is actively maintained and is truly cross-platform. It includes some of the PPL library as a PPLX subset, so if that's what you want the PPL for, then it's a reasonable choice.

- As of C++17, the C++ standard library itself supports parallel algorithms. They're selectable by a policy parameter. You may find these form a more portable API across compilers than the PPL. The programming model just extends the standard algorithms and functional model into parallelism, so it's pretty easy to use if you're already into algorithms.

- If you want to live on the edge, C++20 now includes async programming support. It allows for coroutines as well as promise/future async task modeling. 

Good luck!
