### ISSUE TITLE
Can we add general command description to cl /?

### ISSUE THREAD

**Issue by ortymd** [MicrosoftDocs/cpp-docs#1811]
When I want to recall syntax of certain command, I anticipate that this syntax is at the very top of help/man for this command. Example:
$ man gcc
NAME
       gcc - GNU project C and C++ compiler

SYNOPSIS
       gcc [-c|-S|-E] [-std=standard]
           [-g] [-pg] [-Olevel]
           [-Wwarn...] [-Wpedantic]
           [-Idir...] [-Ldir...]
           [-Dmacro[=defn]...] [-Umacro]
           [-foption...] [-mmachine-option...]
           [-o outfile] [@file] infile...

When I want to check how to call cl.exe I do "cl /?" and here is what at the top:
Microsoft (R) C/C++ Optimizing Compiler Version 19.24.28314 for x86
Copyright (C) Microsoft Corporation.  All rights reserved.

                         C/C++ COMPILER OPTIONS

                              -OPTIMIZATION-

What is needed to improve this and give user command syntax somewhere(best at the top as Linux does it) ? Like wiht 'link.exe'

 usage: LINK [options] [files] [@commandfile]

   options:

      /ALIGN:#

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c858436-2aa3-92b0-0044-1000ce770d78
* Version Independent ID: fa816e98-49f1-1647-5ca9-d62dd9247c92
* Content: [MSVC Compiler Command-Line Syntax](https://docs.microsoft.com/en-us/cpp/build/reference/compiler-command-line-syntax?view=vs-2019)
* Content Source: [docs/build/reference/compiler-command-line-syntax.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/reference/compiler-command-line-syntax.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@ortymd 
It's not a bad idea, but it sounds like a product behavior suggestion, not something we'd change in the documentation. You can make suggestions for the product right from inside Visual Studio. There's a command right on the Help menu, under **Help** > **Send feedback** > **Make a suggestion** that will let you propose your idea to the product team on the [Developer Community](https://developercommunity.visualstudio.com/spaces/62/index.html) website. Go for it!

Since this doesn't seem like a documentation issue (yet), I'm closing this.
