### ISSUE TITLE
/Qspectre is on by default for every new project

### ISSUE THREAD

**Issue by JanCharler** [MicrosoftDocs/cpp-docs#1833]
Hi, I was wondering how the default for spectre mitigation could be changed to be OFF by default? My projects always start with it on (/Qspectre)!

**Comment by corob-msft** [comment]
@JanCharler 

Generally speaking, the default project options are set to improve the security of your code, and make it a cooperative player in the Windows ecosystem. I don't think every template sets the /Qspectre option, but several do. If there's a template that you use consistently, and you're tired of changing settings in every new project, you can make your own copy of the template with the settings you prefer pretty easily. Follow the instructions in [How to: Update existing templates](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-update-existing-templates?view=vs-2019) to use the Export Template Wizard to make a new project template from an existing one, with any changes you like. I'd recommend you use it to make a copy of the template with your changes, rather than edit the original template. Good luck!
