### ISSUE TITLE
Samples should always be as simple as possible

### ISSUE THREAD

**Issue by dtobias** [MicrosoftDocs/cpp-docs#1839]
The reason I am here is that I do not understand the purpose of the *next_tokenx variable.  It only complicates matters that the example deals with two strings instead of just one.  Nothing is gained by it, no new insight is provided.  That make it superfluous and thus effectively noise.  When the message is hard to hear, it is not prudent to add noise.  Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba4b0c0f-c781-903c-9c46-f562546a3c2c
* Version Independent ID: 17285c50-16d2-cafb-c976-29983f66f822
* Content: [strtok_s, _strtok_s_l, wcstok_s, _wcstok_s_l, _mbstok_s, _mbstok_s_l](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/strtok-s-strtok-s-l-wcstok-s-wcstok-s-l-mbstok-s-mbstok-s-l?view=vs-2019#feedback)
* Content Source: [docs/c-runtime-library/reference/strtok-s-strtok-s-l-wcstok-s-wcstok-s-l-mbstok-s-mbstok-s-l.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/c-runtime-library/reference/strtok-s-strtok-s-l-wcstok-s-wcstok-s-l-mbstok-s-mbstok-s-l.md)
* Product: **visual-cpp**
* Technology: **cpp-ucrt**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@dtobias 
Sorry you didn't find the example enlightening. The `next_token` variables maintain token scanning state for different strings between calls to the `strtok_s` functions. There are two of them, along with two strings and two sets of calls, to demonstrate that you can scan any number of separate strings simultaneously with the `strtok_s` functions. That isn't possible with `strtok`, because `strtok` uses a static state buffer owned by the runtime, which would be overwritten by starting a scan on a second string.

There doesn't seem to be an issue to fix here, so I'm closing this.
