### ISSUE TITLE
The sample code is not following the conventions! 

### ISSUE THREAD

**Issue by fffelix-jan** [MicrosoftDocs/cpp-docs#1850]
You should use int main(void) and not void main() ! Also, you should type return 0; at the end of int main(void) .

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6b25c8d-63c4-e903-69cc-a90b88f7b13d
* Version Independent ID: 113c6b83-1457-d4ac-93d0-4177abb3b993
* Content: [Walkthrough: Compiling a Native C++ Program on the Command Line](https://docs.microsoft.com/en-us/cpp/build/walkthrough-compiling-a-native-cpp-program-on-the-command-line?view=vs-2019#feedback)
* Content Source: [docs/build/walkthrough-compiling-a-native-cpp-program-on-the-command-line.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/walkthrough-compiling-a-native-cpp-program-on-the-command-line.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@fffelix-jan 

We get this comment once in a while, mostly from people who read [Stroustrup's opinionated FAQ](http://www.stroustrup.com/bs_faq2.html#void-main). From that same FAQ entry you'll see that `return` statements are optional in `main` and always have been. Also, `void` parameter lists are required in C to specify that a function takes no parameters, because a function with an empty parameter list can take any number of parameters - but in C++ both `void` and an empty parameter list means the function takes no parameters. So, the use of parameter `void` is considered a C idiom, and an empty parameter list is the common C++ idiom, as also seen in Stroustrup's examples.

Microsoft extensions to the C and C++ languages have long allowed a signature of `void main( /* optional argc, argv, and even more optional argp here */);` for instances of `main` without a `return` statement, mostly out of an offended sense of symmetry. Also, just to disagree a little with the master, [it's not strictly true](https://en.cppreference.com/w/c/language/main_function) that the return type of `main` must be an `int`. It's up to the implementation, in versions of the C language standards since C99, at least. (See for example the last clause in C11 section 5.1.2.2.1 paragraph 1.)  

However, `main` having an `int` return type has been made explicit in more recent C++ standards, clarified in both C++14 and C++17. If you use the `/permissive-` flag, a `void` signature return type will produce `warning C4326: return type of 'main' should be 'int' instead of 'void'`. So, the signature returning `void` is legal C, and a non-standard extension in C++. 

The upshot - the `main` return type should change. The rest is good.

**Comment by corob-msft** [comment]
A fix should appear later today.
