### ISSUE TITLE
Incorrect .h file

### ISSUE THREAD

**Issue by herb-amd** [MicrosoftDocs/cpp-docs#1861]
#include &lt;wrl.h&gt;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c769cdb9-ab7c-77bd-16b7-8bb686169eff
* Version Independent ID: ff913b70-328c-9d9e-c7ec-ba942db726b1
* Content: [ComPtr Class](https://docs.microsoft.com/en-us/cpp/cppcx/wrl/comptr-class?view=vs-2019#feedback)
* Content Source: [docs/cppcx/wrl/comptr-class.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/cppcx/wrl/comptr-class.md)
* Product: **visual-cpp**
* Technology: **cpp-cx**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@herb-amd 

`class ComPtr` is declared in *wrl\\client.h* [as described](https://docs.microsoft.com/en-us/cpp/cppcx/wrl/comptr-class?view=vs-2019#requirements). The *wrl.h* header just includes *client.h* and a few other headers. You might need those headers for other parts of your code, such as a type used as a template parameter to `ComPtr`, but they shouldn't be required for `ComPtr` by itself. 

I'm closing this as not a doc issue, though if you have evidence that *client.h* is not sufficient to use `ComPtr`, I'm willing to reopen it.

**Comment by herb-amd** [comment]
Your page is WRONG.

"Requirements
Header: client.h"

NOWHERE does it mention: #include <wrl.h>

**Comment by corob-msft** [comment]
@herb-amd 

Unless you've fiddled with your include paths, you do need to add a relative qualification to the *client.h* include, and any other includes from the *wrl* subfolder. We're assuming that as a given in the documentation. Maybe it's not a good assumption.

I'm unconvinced by your assertion the page is wrong. As long as your code includes either *client.h* or something that in turn includes *client.h*, then you've met the `ComPtr` requirements. While *wrl.h* does include *client.h* and will therefore provide your code with the required declaration to use `ComPtr`, I don't see any evidence that the other headers included by *wrl.h* are required in addition to *client.h*. In fact, all the other headers included by *wrl.h* - *implements.h*, *module.h*, and *event.h* - also include *client.h*. The [Requirements](https://docs.microsoft.com/en-us/cpp/cppcx/wrl/comptr-class?view=vs-2019#requirements) section documents only what is *necessary* to use the class, and not what else may be required for *your* particular code, since we don't know what else your code might need. Maybe your code does need *implements.h*, *module.h*, and *event.h*. What the documentation is saying is only that all code that uses `ComPtr` must have *client.h* somewhere in the include hierarchy.

**Comment by herb-amd** [comment]
My point is that the code on the page doesn't work as documented. It should at least be:

"Requirements
Header: wrl/client.h"

Your docs. You do you.  I'm out.
