### ISSUE TITLE
VS 2019 hangs with "initializing debugger" for "Linux-Debug" and "Linux-Release"

### ISSUE THREAD

**Issue by oviupstack** [MicrosoftDocs/cpp-docs#1863]
I have Microsoft Visual Studio Professional 2019 Version 16.4.2
I want to build and debug a c++ project for Linux.  My whole setup used to work great, I was able to build my project (c++) and debug it as well. 
One day it stopped working (I am not 100% sure if it was before or after I installed latest VS update). 

Problem: When I start debugging the VS builds the project and __hangs forever__ with the dialog showing the message __"Initializing debugger"__.

I have my bash setup correctly, ssh server started and tested (VS has a connection opened and tested to it), the MS cmake 3.16.3311152-MSVC_2,  build-essential, gdb, zip, rsync, gcc.

The "Debug->Linux Console" window is empty, not showing anything.
On the output window there's no error or warning printed/shown and no other popup either.

How can I investigate, understand what is going on? I can provide any detail needed to move on with this matter which is blocking my progress.

Thank you!

**Comment by corob-msft** [comment]
@oviupstack 
That doesn't sound like a good experience. I'm also sorry to say, you've entered your question in the board for documentation issues, rather than somewhere that can support you with product issues. And since I don't see a documentation problem I can address here, I'm closing it. This is not to say it's not a real product issue, though. You should report it in Visual Studio C++ [Developer Community](https://developercommunity.visualstudio.com/spaces/62/index.html), instead. When you report issues there, they get the attention of the product developers, as well as other members of the community who might have work-arounds or other things for you to try. Best of luck in finding a solution!

**Comment by oviupstack** [comment]
thank you, I filed it [here](https://developercommunity.visualstudio.com/content/problem/892158/vs-2019-hangs-with-initializing-debugger-for-linux.html).
I hope someone would be able to help.
