### ISSUE TITLE
C2382 error happening

### ISSUE THREAD

**Issue by Shobhitp2018** [MicrosoftDocs/cpp-docs#1869]
Hi
I am getting error while running my code in visual studio 2019 although I have done the coding of the program in visual studio 2012 ,and it was running in that version without any error.But in VS19  I am getting error C2382
The error is related to longjump redefinition. Please tell what to do?
Severity Code Description Project File Line Suppression State
Error C2382 'longjmp': redefinition; different exception specifications TestCPLEX_Jan27_2014 C:\Program Files\IBM\ILOG\CPLEX_Studio_Community129\concert\include\ilconcert\ilosys.h 705

**Comment by corob-msft** [comment]
@Shobhitp2018 

I'm sorry you're having difficulty. Versions of the compiler and libraries before Visual Studio 2015 are incompatible with anything that came afterward. You can read about how to update projects to build in newer versions of Visual Studio here in [Upgrade C++ projects from earlier versions of Visual Studio](https://docs.microsoft.com/cpp/porting/upgrading-projects-from-earlier-versions-of-visual-cpp?view=vs-2019). There's also lots of useful guidance in [Overview of potential upgrade issues](https://docs.microsoft.com/cpp/porting/overview-of-potential-upgrade-issues-visual-cpp?view=vs-2019). Your exact problem isn't listed, but it's the kind of thing I'd expect to happen if you mix your own definitions of C runtime functions with the official headers. Those are described in the [Errors involving CRT functions](https://docs.microsoft.com/cpp/porting/overview-of-potential-upgrade-issues-visual-cpp?view=vs-2019#errors-involving-crt-functions) section. The error message conveniently tells you both the file and line to look at for the definition that's causing a problem. It's probably safe to remove the definition of `longjmp` from your ilosys.h header, and anything else defined by the CRT.

That said, this is not a support forum. This section of the C++ Docs repo is for reporting issues (bugs) in the documentation. For product issues, you should check out the [Visual Studio C++ Developer Community](https://developercommunity.visualstudio.com/spaces/62/index.html). Since this appears to be a support request, I'm closing the issue.
