### ISSUE TITLE
A question

### ISSUE THREAD

**Issue by X-mcfirer** [MicrosoftDocs/cpp-docs#1890]
Visual Studio uses .ixx as the extension name of module files, while clang uses .cppm instead. Is there an extension name that can be recognized by not only Visual Studio but also other compilers? If not, can I force the IDE and the compiler to accept extension names like .mpp?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad1fef9a-9c55-a8ab-faf4-8b9ceb9ff688
* Version Independent ID: 0eadb3ed-bb38-58bc-b335-687b10f0fd31
* Content: [Overview of modules in C++](https://docs.microsoft.com/en-us/cpp/cpp/modules-cpp?view=vs-2019#feedback)
* Content Source: [docs/cpp/modules-cpp.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/cpp/modules-cpp.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@X-mcfirer 

Making other extensions work here doesn't seem like an unreasonable thing to do. At present, I'm not aware of a way to change the extension used, but that doesn't mean there can't be. This is a product question/request best directed at the development team. I recommend using [Developer Community](https://developercommunity.visualstudio.com/spaces/62/index.html) to make your request as a suggestion, where it can pick up votes from fellow developers facing a similar prospect, and possibly turn into a work item for the implementers.

I'm closing the issue, as the documentation isn't wrong, yet. If you're successful, that may change in the future. Good luck!

**Comment by X-mcfirer** [comment]
Thank you very much and sorry for my late reply.



At 2020-02-03 17:47:59, "Colin Robertson" <notifications@github.com> wrote:

@X-mcfirer

Making other extensions work here doesn't seem like an unreasonable thing to do. At present, I'm not aware of a way to change the extension used, but that doesn't mean there can't be. This is a product question/request best directed at the development team. I recommend using Developer Community to make your request as a suggestion, where it can pick up votes from fellow developers facing a similar prospect, and possibly turn into a work item for the implementers.

I'm closing the issue, as the documentation isn't wrong, yet. If you're successful, that may change in the future. Good luck!

**Comment by BrennenSprimont** [comment]
I'm not sure why a new file extension is needed in any compiler. It would be nice if folks kept it simple and just supported ".cpp", they are still just files conforming to the c++ spec after all. https://developercommunity.visualstudio.com/idea/978893/c-modules-consider-supporting-custom-extensions-ot.html

**Comment by DarranRowe** [comment]
@BrennenSpirmont
Well, you could also argue that .h/.hpp extensions are not needed because they are just files conforming to the C++ spec after all.
The reason why we use these different extensions is for convenience, simple as that. We could give every single C++ file a .cpp extension, but why would you when it differentiates the intended use?

**Comment by DarranRowe** [comment]
@X-mcfirer
If you know the command line options there is a way to use an extension other than .ixx as a module interface file.
The very first module blog post (the one introducing modules in Visual Studio 2015 Update 1 all the way back in 2015) states:
"If you want to use another extension on your interface file you also have to supply the switch /module:interface."
So if you put module generation stuff in a .cpp/.cxx/.cc file (the extension that cl.exe recognises as C++ source files) then it will produce a module interface. However, if you use an extension like .ipp with this switch then the compiler doesn't like it.
Since this works with files recognised as C++ source files then the other step you need to do is tell the compiler to recognise this file as a C++ source file. You can tell the compiler to recognise an arbitrary extension as a C++ source file by using /Tp (for a single file) or /TP (for all files passed in on the command line). So as an example:
cl /c /std:c++latest /experimental:module /module:interface /Tptest.ipp
or
cl /c /std:c++latest /TP /experimental:module /module:interface test.ipp
This works with any extension.

**Comment by BrennenSprimont** [comment]
@DarranRowe I guess my issue is that each compiler chose a different extension (.cppm) and if nobody changes then it's going to be a pita to write multi-platform c++ modules. Also, "ixx" is the most bizarre of the choices in my opinion.

As for a dedicated module extension vs just using cpp. As I understand it, modules could completely replace the current header (interface)/source (implementation) file dynamic. With c++20, you could write a library/application that is entirely c++ modules and has no header files at all. This would bring c++ to a similar (simple/better) feature parity that every other modern language has (java/c#/python/etc). I'm probably being too optimistic, but heck, in 10 years, maybe new c++ developers won't even know what a ".h" file is.

Why not keep it simple and use ".cpp" for this file type? Or at least keep the extension intuitive and use what clang's using with ".cppm". Opening a folder and seeing a ".ixx" file without knowing about modules would be very confusing, at least with "cppm" you have a shot of intuiting "cpp module" and having some search terms.

All that being said, I didn't know about the flags to change the extension. Thanks for sharing them, this works for me.

**Comment by DarranRowe** [comment]
@BrennenSprimont
One major thing to note, it is still protected by the /experimental option, this means that the implementation details are still not finalised yet.
Also I don't think that the .ixx extension is that weird if you remember one of the C++ file extensions is .cxx. Also, if you also remember that this file is for the module interface then it should also be just as easy to intuit "interface++".
Well anyway, you should expect the compiler team to add more extensions when it no longer requires the /experimental option to activate modules. Until then you should seriously consider the extension a placeholder.
