### ISSUE TITLE
The Startup Item dropdown menu does not show all available executables

### ISSUE THREAD

**Issue by mcleary** [MicrosoftDocs/cpp-docs#1894]
As [discussed here](https://developercommunity.visualstudio.com/content/problem/433982/cmake-build-only-cannot-display-more-than-186-item.html) the dropdown menu can only display up to 186 items, which means the opening sentence of this page is not technically correct.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a7a4e8b-d422-93b1-e042-55c2acbf8ef3
* Version Independent ID: 0d55f5d8-846e-3282-b580-9b7770053958
* Content: [Configure CMake debugging sessions in Visual Studio](https://docs.microsoft.com/en-us/cpp/build/configure-cmake-debugging-sessions?view=vs-2019&source=docs#feedback)
* Content Source: [docs/build/configure-cmake-debugging-sessions.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/configure-cmake-debugging-sessions.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@mcleary 
As Visual Studio UI implementation technical limits are rarely if ever communicated to the docs team, we're inclined to leave such qualifications and possible workarounds to the responses like the ones you got on the Developer Community forum. If that info is of sufficient general interest that it needs to be added to the documentation, the developers let us know. For now, I'm closing this as something we're unlikely to change. If I hear otherwise, I'll update this note.
