### ISSUE TITLE
Where is the Scribble sample?

### ISSUE THREAD

**Issue by JSilverst** [MicrosoftDocs/cpp-docs#1896]
I cannot find the scribble sample.  When I click on the link in the documentation for CScrollView,   I end up on a "Permanently redirected page" which cannot seem to find the sample.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6703184d-efb9-65e6-b9ef-31882e7e1e2b
* Version Independent ID: 27d915fa-1a40-947e-05f0-fc9413c42ad4
* Content: [Visual C++ Samples](https://docs.microsoft.com/en-us/cpp/overview/visual-cpp-samples?view=vs-2019#feedback)
* Content Source: [docs/overview/visual-cpp-samples.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/overview/visual-cpp-samples.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@JSilverst 
We have a background task bubbling away at gradually fixing our samples links. Most C++ samples are now in GitHub. You'll find the Scribble sample here: 
https://github.com/microsoft/VCSamples/tree/master/VC2015Samples/scribble/
Confusingly, our repo is under the first link of the Visual C++ samples page, to [Visual C++ Samples](https://github.com/Microsoft/vcsamples), rather than what you probably considered the obvious one linking to MFC samples. The latter link got broken by a recent move of the main docs samples page, which only transferred the highest traffic samples.

**Comment by JSilverst** [comment]
Thanks for the link.  I seem to have had to download the entire list of 
VCsamples, but I managed to extract the scribble sample.
-- 
/Joan/
