### ISSUE TITLE
If there is a single copy of a DLL in memory, how can it be loaded into an application's memory space?

### ISSUE THREAD

**Issue by AlexanderMace** [MicrosoftDocs/cpp-docs#1906]
The second paragraph on this page says the following:

> A DLL isn't a stand-alone executable. DLLs run in the context of the applications that call them. **The operating system loads the DLL into an application's memory space**. It's done either when the application is loaded (implicit linking), or on demand at runtime (explicit linking). DLLs also make it easy to share functions and resources across executables. Multiple applications can access the contents of a single copy of a DLL in memory at the same time.

I believe the highlighted sentence above is incorrect. How does one reconcile this statement with the first bullet in [Advantages of Dynamic Linking](https://docs.microsoft.com/en-us/windows/win32/dlls/advantages-of-dynamic-linking) which I reproduce below:

> - Multiple processes that load the same DLL at the same base address share a single copy of the DLL in physical memory. Doing this saves system memory and reduces swapping.

In summary, if there is a single copy of a DLL in memory, how can it be loaded into an application's memory space?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dfc6a520-6880-1dee-6c80-30a54fd90169
* Version Independent ID: bb521f2c-9784-9432-f098-8e488cea7b2d
* Content: [Create C/C++ DLLs in Visual Studio](https://docs.microsoft.com/en-us/cpp/build/dlls-in-visual-cpp?view=vs-2019)
* Content Source: [docs/build/dlls-in-visual-cpp.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/dlls-in-visual-cpp.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@AlexanderMace 

"Load" as used in both documents means "what the OS loader does." It may mean copying from storage, if it's the first time some image is loaded into memory. And, it may mean virtual memory mapping, if the image is already in memory somewhere. After copying or mapping, as required, the loader then fixes up the relative virtual addresses for symbols to match the virtual pages loaded for all the various images in the process. The bit about matching base addresses is no longer true. Addresses get translated from the virtual addresses used by a process to physical memory addresses by way of some processor-based look-up table managed by the OS. That's how different apps can make use of the same DLL image, at a virtual base address that may be different for every app, while there's only one copy of the DLL image itself at some particular physical location in memory. Basically, you get a form of ASLR whether you ask for it or not. And all that old Windows documentation about carefully setting the base addresses of your images to speed loading and avoid collisions is long obsolete. Unless you're writing real mode code, image addresses don't matter at all.

I'm closing this because I don't see an issue with the doc as written. If you think that's wrong, feel free to argue your case. I've been known to come around.
