### ISSUE TITLE
C/C++ options only appear for main project

### ISSUE THREAD

**Issue by hwynn** [MicrosoftDocs/cpp-docs#1916]
The C/C++ node does not appear under Configuration Properties for additional projects. It only appears in the Configuration Properties of the main project of a solution. 

What if an additional project needs to specify Additional Include Directories or Additional #using Directories?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d320011e-7558-c4fc-04d8-31cbc2fda834
* Version Independent ID: 7b598fab-e8c1-d3a0-0fbf-730a7b2511a5
* Content: [Set C++ compiler and build properties in Visual Studio](https://docs.microsoft.com/en-us/cpp/build/working-with-project-properties?view=vs-2019#c-compiler-and-linker-options)
* Content Source: [docs/build/working-with-project-properties.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/working-with-project-properties.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@hwynn 

Every Visual Studio-native C++ project should have a C/C++ node in its Property Pages dialog. Here's how to check if you have a native C++ project:

Select the project in Solution Explorer. You should see a summary of some of its properties in the Properties window, which is directly below the Solution Explorer window in the default VS layout. One of the listed properties should be Project File. Put the cursor in the file name and scroll to the end. A native C/C++ project will have an extension of .vcxproj. If your additional project doesn't have this extension, it's not a native C/C++ project, and the properties listed in the Project Properties dialog will be different. What you'll see depends on the actual project type. 

Other project types can include CMake projects, Linux cross-platform projects, or even Android or iOS projects. These aren't considered native C++ projects, even if they build C++ code. They have their own set of Property Pages, and the ones in this documentation for native C++ projects don't apply.

If your project is supposed to be a native C++ project, but it doesn't have a .vcxproj file, you may need to recreate your project as a C++ project.

If your additional project is a .vcxproj file, and if when you right-click on it in Solution Explorer then choose Properties, you get a Property Pages dialog that doesn't include the usual C++ nodes in the Configuration Properties tree, then it's possible but unlikely that your project or solution files have a problem. That's a little outside my expertise, so I'd refer you to Visual Studio's C++ [Developer Community](https://developercommunity.visualstudio.com/spaces/62/index.html) to follow up.

For now, I'm calling this a product support issue rather than a documentation issue. If you get back to me with information that's in need of updating on this page, I'll be happy to reopen this issue and do that.

**Comment by hwynn** [comment]
I [figured it out](https://developercommunity.visualstudio.com/content/problem/87843/property-pages-cc-category-missing.html). The C/C++ does not appear unless the project has a cpp file in it. Mine had the files in it, but they were not included in the project because I copy/pasted the files into a folder. The files had a little red circle with a dash through them, but I wasn't sure what that meant.

**Comment by corob-msft** [comment]
Good to know. I had guessed you'd created the project by the "Open a folder" method, and wasn't aware of the behavior of a project with no .cpp files in it.
