### ISSUE TITLE
canonical bug

### ISSUE THREAD

**Issue by mheyman** [MicrosoftDocs/cpp-docs#1925]
Under the hood, canonical calls GetFinalPathNameByHandleW which, in the remarks (https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-getfinalpathnamebyhandlew#remarks), states "when you call this function passing the handle of a file opened using SMB, and with the FILE_NAME_NORMALIZED flag, the function splits the path into its components and tries to query for the normalized name of each of those components in turn. If the user lacks access permission to any one of those components, then the function call fails with ERROR_ACCESS_DENIED."

The canonical() call should not fail with "access denied" for a valid file path. One mitigation for this failure should be to retry GetFinalPathNameByHandleW with the FILE_NAME_OPENED flag to at least get something close. Better might be to implement some of the logic behind weakly_canonical(). Even better would be to follow/expand DFS records when building the canonical path.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a4e66b74-13dd-eab7-a68b-b76e266adbe7
* Version Independent ID: 35b6cc52-be26-e9d0-2c27-56c6a5adcba8
* Content: [&lt;filesystem&gt; functions](https://docs.microsoft.com/en-us/cpp/standard-library/filesystem-functions?view=vs-2019#canonical)
* Content Source: [docs/standard-library/filesystem-functions.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/standard-library/filesystem-functions.md)
* Product: **visual-cpp**
* Technology: **cpp-standard-libraries**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by corob-msft** [comment]
@mheyman 
Feel free to correct me if I'm wrong, but this sounds like a product suggestion, rather than a documentation issue. The way to bring this idea to the library engineers is to make the suggestion on Visual Studio's C++ [Developer Community](https://developercommunity.visualstudio.com/spaces/62/index.html) board. You can even make a suggestion from the IDE, by using **Help** > **Send feedback** > **Suggest a feature**. 
I'm closing the issue, unless there's also a Docs defect to resolve.

**Comment by mheyman** [comment]
Thanks, just pushed the "feedback" button without noticing it was documentation feedback vs implementation feedback. I have now submitted to Developer Community.
