### ISSUE TITLE
`remoteCopyAdditionalIncludeDirectories` is not working in Visual Studio.

### ISSUE THREAD

**Issue by grasmanek94** [MicrosoftDocs/cpp-docs#1943]
The documentation mentions `remoteCopyAdditionalIncludeDirectories`.  
Yet when using it in `CMakeSettings.json` in Visual Studio 16.4.5 (Professional 2019), the editor says this property is not allowed by the schema.  
Including it anyway and proceeding to build doesn't copy the additional include directories.  

The Visual Studio installer tells me that VS is "Up to date".

Is this planned?

**Comment by corob-msft** [comment]
@grasmanek94 

I'm sorry it's giving you trouble. I can't tell yet if it's a documentation error or a product error. In either case, I recommend you also report this as an issue on [Developer Community](https://developercommunity.visualstudio.com/spaces/62/index.html). If it's a product issue, that's the fastest way to bring it to the attention of the development team. And if it's a documentation issue, they'll tell me what to fix. It's win-win!

@esweet431 Is this expected behavior? Is there a typo in the property name?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* Version Independent ID: cb5427c7-ee24-c972-bc44-ff890621cbf9
* Content: [CMakeSettings.json schema reference](https://docs.microsoft.com/en-us/cpp/build/cmakesettings-reference?view=vs-2019#feedback)
* Content Source: [docs/build/cmakesettings-reference.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/cmakesettings-reference.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by grasmanek94** [comment]
Reported: https://developercommunity.visualstudio.com/content/problem/933768/remotecopyadditionalincludedirectories-is-not-work.html

**Comment by corob-msft** [comment]
@grasmanek94 Thanks, that's perfect.

**Comment by grasmanek94** [comment]
Got an answer:

> Hi, the “remoteCopyAdditionalIncludeDirectories” is supported in 16.5 preview 3.
