### ISSUE TITLE
open does not call fopen

### ISSUE THREAD

**Issue by yecril71pl** [MicrosoftDocs/cpp-docs#1950]
It may as well call wfopen.  Also, the overloads without protection seem spurious.

---
#### Szczegóły dokumentu

⚠ *Nie edytuj tej sekcji. Jest ona wymagana dla docs.microsoft.com ➟ Dołączanie problemu w usłudze GitHub.*

* ID: 988d0f9c-053a-5af7-67af-5adaa4dac2c4
* Version Independent ID: 2660e94d-c65f-cf03-4962-d8ba29338567
* Content: [basic_filebuf Class](https://docs.microsoft.com/pl-pl/cpp/standard-library/basic-filebuf-class?view=vs-2019#open)
* Content Source: [docs/standard-library/basic-filebuf-class.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/standard-library/basic-filebuf-class.md)
* Product: **visual-cpp**
* Technology: **cpp-standard-libraries**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
@yecril71pl , Hi. I'm looking at this issue but am not sure what you would like to see fixed. Can you elaborate?

**Comment by yecril71pl** [comment]
It then stores the value returned by `fopen`/`wfopen` in the file pointer fp.

**Comment by TylerMSFT** [comment]
@yecril71pl , After looking carefully at this, I think you may be asking for this:
I think you are referring to two statements in the Remarks section for basic_filebuf::open.  They are:

- The member function opens the file with name filename, by calling fopen(filename, strmode).
   I think you want this to say that it is opened by calling fopen/wfopen(), rather than fopen(). Is that right?

-  It then stores the value returned by fopen in the file pointer fp
   I think you want this to say what it is returned by fopen/wfopen in the file pointer fp. Is that right?

This topic is over 17 pages long and documents over a dozen functions. Have I been able to pin down the particular fix you are looking for?

**Comment by TylerMSFT** [comment]
I've simplified the description in the remarks section, and indicated that it is fopen/wfopen that is called underneath.
The doc update should be live by Monday afternoon, 6/29
