### ISSUE TITLE
Is this still relevant?

### ISSUE THREAD

**Issue by congkun-ck** [MicrosoftDocs/cpp-docs#2029]
With VS2019 16.5, the generated call instructions have no difference with or without __declspec(dllimport).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45a7f37b-1563-7dbd-7fd2-58648c4d2260
* Version Independent ID: 0e2fc14d-4646-661a-8e9e-289411081d6e
* Content: [Importing Function Calls Using __declspec(dllimport)](https://docs.microsoft.com/en-us/cpp/build/importing-function-calls-using-declspec-dllimport?view=vs-2019)
* Content Source: [docs/build/importing-function-calls-using-declspec-dllimport.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/importing-function-calls-using-declspec-dllimport.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@congkun-ck 
Are you reporting an observed behavior change? It's possible the compiler might generate a direct call instead of an indirect one when you put `__declspec(dllimport)` modifier on a function if it's seen the definition already in your translation unit. Normally it tells the compiler to use an indirect call for that function. If you leave the modifier off, the compiler generates a direct call, and if the function is in a DLL, then the linker creates a thunk to redirect that call through. This can be slightly less efficient than letting the linker fixup the indirect call. Only profiling will tell you for sure. Effectively, the modifier is optional on function calls. However, `__declspec(dllimport)` is definitely still required for data imports.

**Comment by congkun-ck** [comment]
@corob-msft 
What I observed is ta behavior change WITHOUT `__declspec(dllimport)` modifier. I found even I don't specified the modifier in the code of the consumer of DLL, the generated assembly is still invoking the import function _imp_XXXX directly, which is not what is described in the document.
In another word, the assembly looks the same with or without `__declspec(dllimport)` modifier for function.

**Comment by offensivelearning** [comment]
I think the observed behavior (that is an indirect call is generated, with or without `__declspec(dllimport)` ) is some optimization done by the compiler. You can disable this optimization from the Configuration Properties of the Project, `C/C++ -> Optimation`. Then, set the value of `Whole Program Optimization` to `No`.

**Comment by offensivelearning** [comment]
With `Whole program optimization` enabled, the call to the stub gets converted to a call to the import table. I read this [here](https://repnz.github.io/posts/reversing-windows-libraries/#what-does-declspec-dllimport-do).

**Comment by corob-msft** [comment]
A doc update that should close this issue is coming in the next day or so.
