### ISSUE TITLE
How does the /DEBUG influence the executable's performance?

### ISSUE THREAD

**Issue by ZjhHopesHakuna** [MicrosoftDocs/cpp-docs#2066]
For some history reasons, our release build software is set as "Generate Debug Info: No", so when we build it, no pdb file will be generated.  But now I find that if I want to debug the minidump of our software, we need the pdb.  So I try use "Generate Debug Info: Generate Debug Information (/DEBUG)", after built, I find the executable gets bigger than before(maybe it is normal because this page says that "An executable (.exe file or DLL) created for debugging contains the name and path of the corresponding PDB").  But I wonder whether this change will bring in any bad influences or not, such as lower run speed and so on.
Very appreciate for your time~

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed59e5e2-fd9a-167a-2db0-f088cb24233c
* Version Independent ID: fb205f89-37fb-4323-316f-8841a6315b2e
* Content: [/DEBUG (Generate Debug Info)](https://docs.microsoft.com/en-us/cpp/build/reference/debug-generate-debug-info?view=vs-2017#feedback)
* Content Source: [docs/build/reference/debug-generate-debug-info.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/reference/debug-generate-debug-info.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@ZjhHopesHakuna 
When you use the [/DEBUG](https://docs.microsoft.com/en-us/cpp/build/reference/debug-generate-debug-info) option on a release build, it expands your executable a little bit to store links to the PDB file paths. However, the biggest size change is because by default, **`/DEBUG`** also enables the [/INCREMENTAL](https://docs.microsoft.com/en-us/cpp/build/reference/incremental-link-incrementally) linker option. **`/INCREMENTAL`** adds padding space around code and data, so individual objects can be recompiled and, if the changes aren't too large, inserted in the executable without requiring a full re-link. The larger image can take slightly longer to load, but the compiled object code itself is the same, and shouldn't behave any differently. If you just want to use debugging symbols and don't care about incremental linking, then you can specify **`/INCREMENTAL:NO`** to the linker. Then the change to the executable size should be trivial.

**Comment by ZjhHopesHakuna** [comment]
Thanks for your help.  I checked my projects, /INCREMENTAL keeps NO.  My release executable is 266KB when Generate Debug Information (/DEBUG), and is 236KB when "Generate Debug Information (/DEBUG)" is No.  I guess the 30KB difference for "a little bit to store links to the PDB file paths" is reasonable, and if I use the 266KB one, it may works as fast or as good as the 236KB one.  Am I right?  Sorry for my poor English.

**Comment by ZjhHopesHakuna** [comment]
> @ZjhHopesHakuna
> When you use the /DEBUG option on a release build, it expands your executable a little bit to store links to the PDB file paths. However, the biggest size change is because by default, /DEBUG also enables the /INCREMENTAL linker option. /INCREMENTAL adds padding space around code and data, so individual objects can be recompiled and, if the changes aren't too large, inserted in the executable without requiring a full re-link. The larger image can take slightly longer to load, but the compiled object code itself is the same, and shouldn't behave any differently. If you just want to use debugging symbols and don't care about incremental linking, then you can specify /INCREMENTAL:NO to the linker. Then the change to the executable size should be trivial.

Thanks for your help.  I checked my projects, /INCREMENTAL keeps NO.  My release executable is 266KB when Generate Debug Information (/DEBUG), and is 236KB when "Generate Debug Information (/DEBUG)" is No.  I guess the 30KB difference for "a little bit to store links to the PDB file paths" is reasonable, and if I use the 266KB one, it may works as fast or as good as the 236KB one.  Am I right?  Sorry for my poor English.

**Comment by corob-msft** [comment]
@ZjhHopesHakuna 
I don't know what the expected size difference should be. Maybe it's always around 30KB. The code that runs should be the same in both versions of your executable, so I don't expect a performance difference.

**Comment by ZjhHopesHakuna** [comment]
> executable

Thank you~

**Comment by ZjhHopesHakuna** [comment]
> @ZjhHopesHakuna
> I don't know what the expected size difference should be. Maybe it's always around 30KB. The code that runs should be the same in both versions of your executable, so I don't expect a performance difference.

Thank you~
