### ISSUE TITLE
x86 Software Conventions?

### ISSUE THREAD

**Issue by daviddetweiler** [MicrosoftDocs/cpp-docs#2068]
Is there any documentation for x86-specific handling of exceptions, etc.?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7052f5eb-e592-2920-e58a-30a6d4bbc3b8
* Version Independent ID: dfe35b76-1b05-7914-70a8-e35e17ef6624
* Content: [x64 software conventions](https://docs.microsoft.com/en-us/cpp/build/x64-software-conventions?view=vs-2019)
* Content Source: [docs/build/x64-software-conventions.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/x64-software-conventions.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@daviddetweiler 
The short answer is no, not distilled into one place like there is for x64, ARM, and ARM64. Notes about x86-specific behavior are scattered in many topics. x86 code uses a frame pointer and stack-based parameters and automatics, since the defaults for code generation are usually __cdecl or __thiscall, rather than __vectorcall. That makes it slightly simpler to unwind than the x64 mechanisms described in these documents, and in the [PE Format](https://docs.microsoft.com/en-us/windows/win32/Debug/pe-format) document. For in-depth descriptions, your best bet might be old MSDN/MSJ articles. The odds of us getting around to creating a one-stop document for x86 conventions are effectively zero, so I'm not going to leave this open. My apologies.
