### ISSUE TITLE
Provide more information on CImage::Save() return value

### ISSUE THREAD

**Issue by Sachelis** [MicrosoftDocs/cpp-docs#2071]
Saying CImage::Save() returns "A standard HRESULT" is vague. What is standard, what values can it return, how can you determine if there was an error, etc? Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fa78f56-aed9-e282-4a30-6e0656f48074
* Version Independent ID: f428718a-ad6b-908b-5967-a6361ee977d8
* Content: [CImage Class](https://docs.microsoft.com/en-us/cpp/atl-mfc-shared/reference/cimage-class?view=vs-2019#save)
* Content Source: [docs/atl-mfc-shared/reference/cimage-class.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/atl-mfc-shared/reference/cimage-class.md)
* Product: **visual-cpp**
* Technology: **cpp-mfc**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by corob-msft** [comment]
@Sachelis 

I'm sorry the documentation isn't telling you what you want to know. A standard [HRESULT](https://docs.microsoft.com/en-us/windows/win32/com/structure-of-com-error-codes) return value is `S_OK` on success, and some error HRESULT such as `E_FAIL` on failure. The way to handle standard HRESULT values is described in [Error Handling in COM](https://docs.microsoft.com/en-us/windows/win32/com/error-handling-in-com). Generally, you'll want to [use a macro](https://docs.microsoft.com/en-us/windows/win32/com/using-macros-for-error-handling) such as `SUCCEEDED` to test for a returned success value. Your `else` case can test for specific failure HRESULTs if they matter, but often you'll only have a single handler. You'll probably want to log the failure and report it to the user, then try to recover if you can. Most MFC/ATL functions return a limited set of error results. Your error handling options tend to be limited, too.

You can look at the source code for the function you're interested in to see the specific values that might be returned, in some cases. For example, `CImage::Save`, found in *atlimage.h*, can return `E_FAIL` and `E_OUTOFMEMORY`. For many functions, the only non-success value returned is `E_FAIL`, though sometimes you might see `E_OUTOFMEMORY`, `E_INVALIDARG`, `E_POINTER`, `E_ACCESSDENIED`, `E_UNEXPECTED`, `E_NOINTERFACE`, `E_NOTIMPL`, and a few domain-specific failure codes. Sometimes the return value is an `HRESULT` created from a system error code using the macro `HRESULT_FROM_WIN32`. It's not always possible to tell the specific value you might get in that case. 

As you read the ATL and MFC documentation, you'll find that this is about as specific as we usually get. That's why I'm closing this issue, too.

**Comment by Sachelis** [comment]
Wow! I didn’t expect a long, detailed explanation. Thanks.

 

I do think, regardless of the platform (e.g., MFC, native API, etc), all mentions of the return value should link to a page that shows the possible results. 

 

#define NOERROR             0

#define E_UNEXPECTED                     _HRESULT_TYPEDEF_(0x8000FFFFL)

#define E_NOTIMPL                        _HRESULT_TYPEDEF_(0x80004001L)

#define E_OUTOFMEMORY                    _HRESULT_TYPEDEF_(0x8007000EL)

#define E_INVALIDARG                     _HRESULT_TYPEDEF_(0x80070057L)

#define E_NOINTERFACE                    _HRESULT_TYPEDEF_(0x80004002L)

#define E_POINTER                        _HRESULT_TYPEDEF_(0x80004003L)

 

Etc…

 

It doesn’t even mention S_OK.

 

Also seems like the linked page would mention:

_com_error error(h);

                error.ErrorMessage();

 

One guy’s option, although I **REALLY** appreciated your prompt reply.

 

Thanks,

 

Steve
