### ISSUE TITLE
The compiler's default behavior (if invoked without /EH) is poorly and incorrectly documented

### ISSUE THREAD

**Issue by TheJCAB** [MicrosoftDocs/cpp-docs#2073]
Note that this applies to this and other pages in this section, as well as the documentation of /EH itself.

This page explicitly states that "C++ exception handling is the default". However, the compiler seems to default to no exception handling (if no /EH option is specified).

This is easy to verify, just try to compile this with "cl &lt;file.cpp&gt;": "int main() try { } catch (int code) { }". You'll get "warning C4530: C++ exception handler used, but unwind semantics are not enabled. Specify /EHsc"

There are two issues here: when the documentation says that exception handling is the default, it is misleading. But also, it doesn't clearly specify what the default of /EH is (when not specified). This should be corrected.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5811ff85-117b-379d-711a-3983244282bf
* Version Independent ID: 0eeacf8b-984a-087e-9b95-c6ae6b128946
* Content: [Exception handling in MSVC](https://docs.microsoft.com/en-us/cpp/cpp/exception-handling-in-visual-cpp?view=vs-2019#feedback)
* Content Source: [docs/cpp/exception-handling-in-visual-cpp.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/cpp/exception-handling-in-visual-cpp.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@TheJCAB 
The phrase "C++ exception handling is the default" refers to the default exception handling setting in Visual Studio C++ projects. This could be made more clear.

When you compile at the command line and don't specify an exception handling model, you get the compiler's default exception handling model. The default model fully supports structured exception handling, and a limited, non-standard form of C++ exception handling. It does not unwind stack objects outside of `try` blocks, but it does transfer control to a matching `catch` block. Your example will work in spite of the warning, though non-trivial examples usually do not. For fully C++ conforming safe stack unwinding, you must specify `/EHa`, `/EHs`, or the recommended form, `/EHsc`.

So, why isn't `/EHsc` the default? Because thirty-some years ago, MSVC was a C compiler that supported structured exceptions by default. When it became a C++ compiler, and C++ got exception handling, you had to tell the compiler to use that instead of the default. It has been that way ever since, even though only a tiny fraction of the projects built use SEH, and a majority use standard C++ exceptions. 

An update should appear in a day or so. Automation will close this issue when the changes are moved to the publishing queue.

**Comment by TylerMSFT** [comment]
I assume the update was published. Automation didn't close the issue. Closing since no other communication in over a year.
