### ISSUE TITLE
Samples are not updated for Visual Studio 2019.

### ISSUE THREAD

**Issue by energysteven** [MicrosoftDocs/cpp-docs#2097]
Please post a list of samples that have been updated for use with Visual Studio 2019. There appear to be enough changes in the Visual Studio 2019 IDE that makes the samples more trouble than it's worth.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6703184d-efb9-65e6-b9ef-31882e7e1e2b
* Version Independent ID: 27d915fa-1a40-947e-05f0-fc9413c42ad4
* Content: [Visual Studio C++ Samples](https://docs.microsoft.com/en-us/cpp/overview/visual-cpp-samples?view=vs-2019#feedback)
* Content Source: [docs/overview/visual-cpp-samples.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/overview/visual-cpp-samples.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@energysteven 
In most cases, when you load these sample projects, they get updated automatically to match your version of Visual Studio, and the code works the same as always. Some samples are specific to capabilities exposed by a particular OS (such as Windows Phone) and will not work on other, more recent platforms. The samples are provided as-is. We have no plans to update them because of limited staffing. However, anyone is welcome to submit a PR with an update to an existing sample.
