### ISSUE TITLE
	严重性	代码	说明	项目	文件	行	禁止显示状态 错误	LNK1104	无法打开文件“opencv_nonfree420d.lib”	CASTLE	D:\VS2015 Projects\CASTLE\CASTLE\LINK	1	

### ISSUE THREAD

**Issue by huang123-o** [MicrosoftDocs/cpp-docs#2104]
严重性	代码	说明	项目	文件	行	禁止显示状态
错误	LNK1104	无法打开文件“opencv_nonfree420d.lib”
请问为啥出现这样的问题呀

**Comment by corob-msft** [comment]
@huang123-o 
I'm sorry this problem is causing you trouble. The problem sounds like a support question, not a documentation issue. You might find answers on the [OpenCV forums](https://answers.opencv.org/questions/). If you think this problem is caused by Visual Studio or Microsoft C++, then you can ask for help on [Developer Community](https://developercommunity.visualstudio.com/spaces/62/index.html). I wish you luck in finding a solution.
