### ISSUE TITLE
VS2019 overzealous in reporting this error 

### ISSUE THREAD

**Issue by peirick** [MicrosoftDocs/cpp-docs#2105]
Some cryptographic libraries (e.g. tweetnacl) are dependent on following behavior:

    u32 mask = (u32)-carry; // carry == 0 or 1

its trying to do the following

| carry | mask                     |
| 0     | 0 == (u32)-0           |
| 1     | 0xffffffff == (u32)-1  |

Negation of an unsigned integer is as far as i know well-defined and shouldn't be an error.
A workaround would be the following:

    u32 mask = ~(u32)carry + 1; // carry == 0 or 1

Maybe VS2019 can do a special handling of that case?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 22300050-7469-d631-7ee8-e611fcedcef7
* Version Independent ID: b1ddfd62-1aa1-b8b9-470a-d3c054736c98
* Content: [Compiler Warning (level 2) C4146](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-2-c4146?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev16.query%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(C4146)%26rd%3Dtrue%26f%3D255%26MSPPError%3D-2147217396&view=vs-2019#feedback)
* Content Source: [docs/error-messages/compiler-warnings/compiler-warning-level-2-c4146.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/error-messages/compiler-warnings/compiler-warning-level-2-c4146.md)
* Product: **visual-cpp**
* Technology: **cpp-diagnostics**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@peirick 

> Negation of an unsigned integer is as far as i know well-defined and shouldn't be an error.

Negating an unsigned value is regularly seen in naive or suspect code, which is why it's flagged. If you have reviewed the code and found it behaves as you intend, then you can disable the warning locally:

```cpp
#pragma warning( push )
#pragma warning( disable : 4146 )
void function_that_raises_C4146() {
    // code that causes the warning
}
#pragma warning( pop )
```

If you think the logic for when to raise the warning should change, then that's not a documentation issue, it's a product suggestion. Fortunately, you can make a product suggestion right from Visual Studio. On the menu bar, choose **Help > Send Feedback > Suggest a Feature**. Often, it pays to search first to see if someone else has suggested the same thing, so you can upvote it. If it's a new idea, then poke the **Suggest a feature** button and fill in the **Report a problem** dialog. It will post on the [Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html) site, where an engineer will take a look. Perhaps someday it will become a feature. Good luck!
