### ISSUE TITLE
Can't get a PostBuildEvent to fire in a build.proj file

### ISSUE THREAD

**Issue by johndaintree** [MicrosoftDocs/cpp-docs#2139]
I've been following the documentation (which I guess is listed below) to add a PostBuildEvent to my project, but I  just cannot get it to fire. My complete build.proj is inserted below. The three referenced projects are correctly built but I don't see the PostBuildEvent's Message anywhere. What have I missed?

Here's my build.proj:

```
<Project Sdk="Microsoft.Build.Traversal">

  <ItemGroup>
    <ProjectReference Include="native/Dyalog.Net.Bridge.Host.csproj" />
    <ProjectReference Include="managed/Dyalog.Net.Bridge.csproj" />
    <ProjectReference Include="tests/tests.csproj" />
  </ItemGroup>

<ItemDefinitionGroup>
  <PostBuildEvent>
    <!-- <Command>copy junk junk2</Command> -->
    <Message>Making a copy of STUFF</Message>
  </PostBuildEvent>
</ItemDefinitionGroup>

<PropertyGroup>
  <PostBuildEventUseInBuild>true</PostBuildEventUseInBuild>
</PropertyGroup>

</Project>

```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f2d851c-5106-cc23-f4cb-564cbe7a0dda
* Version Independent ID: 1b54ee0c-be98-023e-cdee-030b43f6974d
* Content: [How to: Use Build Events in MSBuild Projects](https://docs.microsoft.com/en-us/cpp/build/how-to-use-build-events-in-msbuild-projects?view=vs-2019)
* Content Source: [docs/build/how-to-use-build-events-in-msbuild-projects.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/how-to-use-build-events-in-msbuild-projects.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@johndaintree 
I'm sorry your project's giving you trouble. Given some environmental clues, the first thing that occurs to me is that you're looking at the wrong documentation. This article assumes you're building a C++ project, and that you've included some C++-specific .props files that support the `PostBuildEvent` described here. If that isn't the case for you, then you might want to look at [Build events](https://docs.microsoft.com/en-us/dotnet/core/tools/csproj#build-events) instead. It describes defining pre- and post-build events in SDK projects, which sounds closer to what you're trying to do. 
I'm closing this issue, since it doesn't seem applicable to this particular article. If you think otherwise,  let me know, and I can reopen it.
