### ISSUE TITLE
Open a file Issue

### ISSUE THREAD

**Issue by Stricklyspeaking** [MicrosoftDocs/cpp-docs#2157]
In the instructions above if you open a system CMD dialog and type the command devenv.exe you get a notice saying this is not a recognized command.
If you open VS 2019 V 16.6 V 5. and then select TERMINAL to get a Power Shell you can use this command to open a project. Probably has to do with getting the proper paths in place.

I am working with a project taken from git that has the CMakeList.txt file in the folder. This project will build fine on a Linux system. When the project is opened in VS I see CMake Error: Could not find CMAKE_ROOT !!!  So additional work is needed to get the project in a mode that you can work with it.   

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 296f6914-b366-1ab8-4c08-6d51fc7212fa
* Version Independent ID: 04aec2e0-f39a-2e52-6a09-354222d47146
* Content: [Create and configure a Linux CMake project in Visual Studio](https://docs.microsoft.com/en-us/cpp/linux/cmake-linux-project?view=vs-2019)
* Content Source: [docs/linux/cmake-linux-project.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/linux/cmake-linux-project.md)
* Product: **visual-cpp**
* Technology: **cpp-linux**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by corob-msft** [comment]
@Stricklyspeaking 
I'm sorry the documentation wasn't clear on the kind of command window required. I've got a fix in for that that should appear in a day or so. To run *devenv.exe*, you should invoke it from a [Developer command prompt](https://docs.microsoft.com/cpp/build/building-on-the-command-line?view=vs-2019#developer_command_prompt_shortcuts) window. That window will have the appropriate environment set to launch the tools. I don't know if this will address your other issue. That one could be caused by trouble parsing your *CMakeLists.txt* file. For issues of that kind, you'll get more support on the [Developer Community](https://developercommunity.visualstudio.com/spaces/62/index.html) site.
