### ISSUE TITLE
qsort_s conflicts with C11 spec.

### ISSUE THREAD

**Issue by diamondo25** [MicrosoftDocs/cpp-docs#2162]
This is not entirely related to the documentation, but maybe a warning could be added.
As shown on https://en.cppreference.com/w/c/algorithm/qsort , `qsort` has now a more secure sibling, `qsort_s`:

```cpp
void qsort_s(
   void *base,
   size_t num,
   size_t width,
   int (__cdecl *compare )(void *, const void *, const void *),
   void * context
);
```

This function is incompatible with Visual C++'s `qsort_s`:
```cpp
errno_t qsort_s( void *ptr, rsize_t count, rsize_t size,
                 int (*comp)(const void *, const void *, void *),
                 void *context );
```

The `comp` callback in C11 has the definition of (a, b, context), whereas in Visual C++ it is (context, a, b).
The function also doesn't return an error. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e7abbe4f-f12e-dc7b-07c7-502fcc816d96
* Version Independent ID: 63a1ca6b-3901-ac1f-a514-e4c5cc08fd3c
* Content: [qsort_s](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/qsort-s?view=vs-2019#feedback)
* Content Source: [docs/c-runtime-library/reference/qsort-s.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/c-runtime-library/reference/qsort-s.md)
* Product: **visual-cpp**
* Technology: **cpp-ucrt**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by corob-msft** [comment]
As I recall, the [Safe CRT functions](https://docs.microsoft.com/en-us/cpp/c-runtime-library/security-enhanced-versions-of-crt-functions?view=vs-2019) developed by Microsoft were proposed to the C Standard committee some 16 or more years ago, and the committee subsequently adopted many of them under the same names - but with slightly different signatures and behavior. That left Microsoft in a bind, since the functions Microsoft created had been shipping for quite some time under those names. You can't overload functions in C. That's part of why MSVC makes no claim to C11 compatibility, or at least, not yet. So far the only C11 standard library functions supported are ones required by later C++ standards. This issue bears thinking about.
