### ISSUE TITLE
application

### ISSUE THREAD

**Issue by ShoujinDong** [MicrosoftDocs/cpp-docs#2184]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b965be6-8dfd-db91-84e3-345e70d7c302
* Version Independent ID: 291bf1e4-c8f7-12e9-3f38-f54bbd822bc7
* Content: [Create an Android Native Activity App](https://docs.microsoft.com/en-us/cpp/cross-platform/create-an-android-native-activity-app?view=vs-2019)
* Content Source: [docs/cross-platform/create-an-android-native-activity-app.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/cross-platform/create-an-android-native-activity-app.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@ShoujinDong 
I don't see a description of a problem in the documentation here. Is the issue that we say "app" instead of "application" in some contexts? The use of "app" was suggested by the product management team for consistency with "app store" usage on mobile devices. If there is another problem here, let me know, and I'll reopen this issue.
