### ISSUE TITLE
The documentation of abort/_set_abort_behavior should mention legacy behavior

### ISSUE THREAD

**Issue by Donpedro13** [MicrosoftDocs/cpp-docs#219]
In some circumstances, the Universal CRT's `abort` will use the Win32 function `ExitProcess` to end the current process. Due to implementation details, this will call back some global destructors, which clearly violates the C++ standard. For details, see the [bug report](https://developercommunity.visualstudio.com/content/problem/236146/stdabort-erroneously-calls-back-global-destructors.html) I've filed about this phenomenon. In this bug report, I was told by Steve Wishnousky (@stwish-msft) that this is legacy behavior required because of compatibility reasons.

I think this should definitely be mentioned in the documentation page of both [`abort`](https://github.com/MicrosoftDocs/cpp-docs/blob/master/docs/c-runtime-library/reference/abort.md) and [`_set_abort_behavior`](https://github.com/MicrosoftDocs/cpp-docs/blob/master/docs/c-runtime-library/reference/set-abort-behavior.md).

**Comment by tlemo** [comment]
>
> The intent of abort is clear: to terminate the program without any cleanup


+1. There's a both pragmatic and conceptual need for a standard, portable
fail-fast primitive.

Debating the finer points for where/how the DLLs fit into the overall
picture sounds like an interesting topic but it's a red herring regarding
abort(). Preserving broken behavior for back compat reasons is
understandable (up to a point) but it doesn't change the fact that that
it's it's a bug.

I'd urge the CRT team to take a closer look at this. Quoting from the
original bug report:

we found a large amount of code is dependent on the CRT calling
> ExitProcess, primarily because it allows threads in other DLLs to continue
> to run.


No, you don't want to allow other threads to run in a corrupted process
state.

**Comment by corob-msft** [comment]
Unless I bring it to their attention, the product team probably won't see any discussion here. If you want to argue for changes in the UCRT, which is maintained by the VC team but is now owned (in the sense of deciding what goes in and what can change) by the Windows team, I recommend you hash it out in the [Developer Community](https://developercommunity.visualstudio.com/spaces/62/index.html) forum, which does get read by the people who can make such decisions. 

I'll agree the **abort** behavior is most problematic in a DLL that acts like a C++ library. But the DLL issue is hardly a red herring. After all, there's no reason to assume that a DLL is even written in C++, and the behavior of its runtime support is unknown. You can link any DLL at load time and call into it like a static library as long as it presents an appropriate ABI interface and you have the required header definitions, but you might have no idea what's under the hood. You can't make any assumptions about its runtime termination behavior, though [a well written DLL will leave dynamic memory alone for the system to deal with](https://msdn.microsoft.com/library/windows/desktop/ms682583(v=vs.85).aspx) on process termination. And even if a DLL is written in C++, remember, it's an independent image, and it gets its own copy of the CRT and runtime support, which means it gets its own runtime initialization code as well as its own cleanup code, which independently constructs statics and globals on init and calls their destructors on termination.  

If you terminate a DLL without giving it a chance at an orderly disconnection from your process via a DLL_PROCESS_DETACH message, if that DLL that doesn't strictly adhere to the DLL guidelines, perhaps it could conceivably put other clients of that DLL in an inconsistent state. I don't know, but I'd guess that's why **ExitProcess** is called as a last option in the **abort** implementation, and not **TerminateProcess**. And it's why I'd draw a really big caveat around a recommendation to call **TerminateProcess** if you load your own **abort** handler. Don't go there unless you know what you're terminating, and that it's okay to do so.

Just an idea, if you do own the DLL code, and you want **abort** behavior in it as well as your app, you could create an abort handler in the DLL to tell it to terminate itself without cleanup and then invoke it in whatever function you set with **_set_abort_handler** in your app. I haven't thought through all the details, but it seems doable. Or you could avoid creating global objects and independent statics in the DLL in the first place.

**Comment by tlemo** [comment]
>
> I'll agree the abort behavior is most problematic in a DLL that acts like
> a C++ library. But the DLL issue is hardly a red herring. After all,
> there's no reason to assume that a DLL is even written in C++, and the
> behavior of its runtime support is unknown.


Correct, which is one of the reasons I said that DLLs are not special (and
a red herring): hybrid processes are not uncommon - you can have a
combination of native code, managed runtimes and JITTed code, etc. DLLs are
just a mechanism to load a mix of code & data into a process - but the
latter (the process) is the "program" in the Win32 world.

I'd love to see the C++ committee continuing the trend towards stricter and
clear specification of core concepts (similar to the treatment of threading
and memory models). But in this case the situation is already fairly well
defined:





* [support.start.term]The function abort() has additional behavior in this
International Standard:— The program is terminated without executing
destructors for objects of automatic, thread, orstatic storage duration and
without calling functions passed to atexit() (3.6.3).*

> If you terminate a DLL without giving it a chance at an orderly
> disconnection from your process via a DLL_PROCESS_DETACH message, if that
> DLL that doesn't strictly adhere to the DLL guidelines, perhaps it could
> conceivably put other clients of that DLL in an inconsistent state.


I'm not sure what this mean. A process can abruptly terminate for a
multitude of reasons (you can't prevent that), so a robust system must
account for that already.

**Comment by corob-msft** [comment]
I'll grant you the common process argument. I was trying to figure out what kind of DLL process would require a thread still running in this situation, and as you imply, it all seemed far-fetched. So I went and looked more closely at the UCRT source code published in the Windows SDK, which was enlightening. 

As near as I can tell, it's not possible to execute the **abort** implementation code path that calls **ExitProcess** in a release build, unless perhaps you go and edit the registry or your image to set a global flag (`FLG_APPLICATION_VERIFIER`) that is, shall we say, *unusual* for a release build. Just eyeballing what's going on in the source code in exit.cpp (in the ucrt\startup directory), this looks like an issue where **ExitProcess** is called only for debug builds,  specifically (according to the comments) so analysis tools have a chance to run. Otherwise, **TerminateProcess** gets called. 

Am I reading this correctly? As near as I can tell, you can only get the complained-about **abort** behavior when you follow a particular sequence in dealing with the termination handling UI, and only in debug builds.

**Comment by tlemo** [comment]
Thanks for looking into it. Unfortunately, hitting the _exit(3) path is as
easy as clearing the _CALL_REPORTFAULT flag:


*_set_abort_behavior(0, _WRITE_ABORT_MSG | _CALL_REPORTFAULT);*

This is not uncommon in environments where the debug dialogs are not
desirable (here's a quick example
<https://github.com/google/googletest/blob/43776990663c08c4d207658bc5756058da1040bf/googletest/src/gtest.cc#L4655>).
Then, the _exit() implementation is problematic (as in trying to do way too
much). In particular, by default it will call ExitProcess() for desktop
applications (the function comment for should_call_terminate_process() is
relevant here).

That ship has sailed though. My concern, and the reason I chimed in here,
was the attempt to rationalize the current behavior as conformant: it is
not, and a word of caution seems appropriate (the OP's request).

**Comment by corob-msft** [comment]
An update is visible now.
