### ISSUE TITLE
No project type

### ISSUE THREAD

**Issue by montablac** [MicrosoftDocs/cpp-docs#2198]
After installing the "Mobile development with C++" workload on both the 2017 and 2019 community version of Visual Studio, the openGL ES template does not appear, please update the document with more detailed steps

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e9d1fa38-809e-5525-1241-d2dca23c705d
* Version Independent ID: a3b2385f-5cf3-7ac6-ebce-d71dc39c83d9
* Content: [Build an OpenGL ES application on Android and iOS](https://docs.microsoft.com/en-us/cpp/cross-platform/build-an-opengl-es-application-on-android-and-ios?view=vs-2019#feedback)
* Content Source: [docs/cross-platform/build-an-opengl-es-application-on-android-and-ios.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/cross-platform/build-an-opengl-es-application-on-android-and-ios.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@montablac 

Sorry you're having trouble. I expect the problem is either that you haven't installed the iOS components, or you have the Android filter set in your New Project dialog.

Hidden in the first paragraph of the Requirements section is this sentence: "*To get the OpenGL ES templates*, and to build for iOS, include the optional C++ iOS development tools." If you didn't install the iOS components, you can use the **Install more tools and features** link at the bottom of the list of templates to launch the Visual Studio Installer and add them to Visual Studio.

The next problem is that you won't see the OpenGLES Application template if you have "Android" selected for your Platform filter in the New Project dialog. I consider this a bug in the template - it's missing the Android tag. You either need to select iOS or All platforms in the center drop-down filter above the list of templates. Once your solution is created, you don't actually have to build the iOS project; it's safe to delete that project from the solution if you only want to build for Android.
