### ISSUE TITLE
Use of Mutex as a condition for execution

### ISSUE THREAD

**Issue by amadlover** [MicrosoftDocs/cpp-docs#2199]
Use of a mutex as a condition for thread execution threw me off. Is a specific reason for using a mutex over boolean

**Comment by corob-msft** [comment]
@amadlover 
I'd use a mutex to avoid a race condition, but you didn't say which page had the problem, so I can't be more specific. Is there a particular page you have in mind?

**Comment by amadlover** [comment]
Hello.

Thank you for responding.

https://docs.microsoft.com/en-us/cpp/parallel/sample-multithread-c-program?view=vs-2019

I clicked on the create issue on Github link on the page to create this issue. I thought it would have linked the webpage here. 

The line in question is the last line of BounceProc, while (run mutex == wait_timeout) 

This allowed to set a timeout value (frame rate). Is this why a mutex lock was used?

Best regards,
Nihal Kenkre.

**Comment by amadlover** [comment]
Hello

**Comment by corob-msft** [comment]
@amadlover 
I'm sorry, I'd passed your question along to someone more expert than me when you asked it last year, and didn't get a response, so I wasn't reminded to follow up. My understanding is the per-thread `BounceProc` uses the `hRunMutex` result to check when the user presses a 'q' key, to make the screen drawing loop exit by something other than a timeout. The user input comes in on a separate thread, and a mutex makes communicating the signal to the drawing thread nicely atomic. `WaitForSingleObject` either returns because the timeout passed or the mutex got released in the `ShutDown` function. If it was released, the loop exits.
The code doesn't seem erroneous, so I'm closing the issue. Thanks for the report to take a look.
