### ISSUE TITLE
LNK2019 Unresolved external symbol _main

### ISSUE THREAD

**Issue by v-radelg** [MicrosoftDocs/cpp-docs#2207]
@yyccz123 commented 16 hours ago

LNK2019 Unresolved external symbol _main

I follow the prompts step by step, but the above error

This symbol is referenced in the function "int __cdecl invoke_main (void)" (? Invoke_main @@ YAHXZ)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eda99bc7-483b-e53c-1035-886f4d0955f4
* Version Independent ID: a6fdba4d-53e4-9f1a-2352-bc68ef491069
* Content: [Walkthrough: Create a traditional Windows Desktop application (C++)](https://docs.microsoft.com/en-us/cpp/windows/walkthrough-creating-windows-desktop-applications-cpp?view=vs-2019#feedback)
* Content Source: [docs/windows/walkthrough-creating-windows-desktop-applications-cpp.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/windows/walkthrough-creating-windows-desktop-applications-cpp.md)
* Product: **visual-cpp**
* Technology: **cpp-windows**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@yyccz123

Error `LNK2019 Unresolved external symbol _main` occurs when you choose **Console Application (.exe)** instead of **Desktop Application (.exe)** in the **Windows Desktop Project** dialog. 

You can fix your project without recreating it. Use the **Project** > **DesktopApp Properties** menu to open the Properties dialog for your project. Set the **Configuration** dropdown to **All Configurations**. Set the **Platform** dropdown to **All Platforms**. Select the **Configuration Properties** > **Linker** > **System** property page. Change the value of the **SubSystem** property to **Windows (/SUBSYSTEM:WINDOWS)**. Choose **OK** to save your project properties. Then rebuild your project.

**Comment by yyccz123** [comment]
Thank you,the problem has been solved.
I recreated it and choose Console Application (.exe) instead of Desktop Application (.exe) .
