### ISSUE TITLE
No "unreachable code" warnings for if (false) or while (false)

### ISSUE THREAD

**Issue by emuzychenko** [MicrosoftDocs/cpp-docs#2218]
It was a very good idea to remove warning C4127 for "if (true)" or "while (true)". But "if (false)" or "while (false)" (except of "do...while (false)" generate unreachable code, with no warnings even with /W4 /Wall.

I think that constructions like "while (false)" or "if (false)" should cause "unreachable code" warning. For the second case, it makes sense to show a suggestion to use "if constexpr" instead.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a88a50e7-ed43-5fe5-e3f7-7e243af2e290
* Version Independent ID: 7ed7dfe9-7959-4e04-30d0-1c39e33af8e8
* Content: [Compiler Warning (level 4) C4127](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-4-c4127?view=vs-2019)
* Content Source: [docs/error-messages/compiler-warnings/compiler-warning-level-4-c4127.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/error-messages/compiler-warnings/compiler-warning-level-4-c4127.md)
* Product: **visual-cpp**
* Technology: **cpp-diagnostics**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@emuzychenko 

That's a fine suggestion, but you're making it in the wrong place. If you want to make a product suggestion, you can do it right in Visual Studio: Use the **Help** > **Send Feedback** > **Suggest a Feature** menu command. Or, use the **This product** Feedback button on this documentation page. That will take you to the C++ Developer Community page, where the product development team will see your idea. Since this issue isn't about a problem in the documentation, I'm closing it. If the development team makes changes to the product that mean this page needs to be updated, they will let us know. Good luck!
