### ISSUE TITLE
Worthless. "Enter Name of compiler"  I am using whatever compiler Microsoft put there. I dont know its name and I don't know how to find it out. This page gives no help.

### ISSUE THREAD

**Issue by PeadarO** [MicrosoftDocs/cpp-docs#2219]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 01d1fc7d-eeb2-d7c6-3d79-0a69732864a3
* Version Independent ID: 8e53ef60-ff33-38af-8ee9-73a6bf8b8853
* Content: [How to: Create a C++ Project from Existing Code](https://docs.microsoft.com/en-us/cpp/build/how-to-create-a-cpp-project-from-existing-code?view=vs-2019)
* Content Source: [docs/build/how-to-create-a-cpp-project-from-existing-code.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/how-to-create-a-cpp-project-from-existing-code.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@PeadarO 

The document makes an unstated assumption that you can already build your existing code somehow; you just want to do it in Visual Studio now. If that isn't true, and all you have is a bunch of code you've never built before, you can still bring it into VS. You just have to pick the right options in the wizard. 

It sounds like you may have chosen to use an external build system on the Specify Project Settings page when you didn't mean to. When you tell the wizard you want to use an external build system, you're saying you want to keep building the code with the same tools you already use, you just want to do it from inside Visual Studio. Such builds typically involve a either a compiler or makefile command line, with switches to tell whether to build debug or release code, or clean up the build artifacts. You should be able to read your existing build files or command lines to see what compiler tools are in use for each kind of build, and copy those command lines into the wizard. 

Since you don't seem to know what those command lines are, it sounds like you're trying to create a project from a bunch of source files that you haven't built before. In that case, you should tell the wizard to use the Visual Studio build system. It already knows how to find the MSVC compiler (called CL.exe, by the way), other tools, and standard libraries and header files. You'll only have to specify any special symbols you want to define, or extra (non-standard) include paths used by your code, if any. Fill in either or both of those two fields, if you need to, and you're good to go. You can safely ignore fields that are irrelevant, like the .NET ones if you're building ordinary native code.

Good luck with your code project.

**Comment by PeadarO** [comment]
Thank you for replying Colin, I know I wasn't clear in what I said.  I’ll
just fill you in on what I am trying to do.

I have used Visual Studio for many years, maybe 25 years (I have been a
developer since 1981). Recently I have written a Chatroom and I hope to use
it for people who speak minority languages around the world to come
together and talk. It is written in VC++ with a Linux server to manage the
hole punching through the firewall and to manage the database and so on. It
uses Inno to install the client remotely on a user’s machine from a
standard XML website.  It has FFmPeg compression for video, Opus/Speex for
compressing sound and AecSDKDemo for Acoustic Echo Cancellation. These last
three are the only issues I‘m not fully happy with yet. Otherwise I have
the whole system running.

I want to make an Android version of the client and I believe that Visual
Studio would be the best way to do it because that is my background. I can
easily create an empty program in VC++ and compile and deploy it to a
device.

I have downloaded the usual “Visual Studio” Android C++ samples from
GitHub. These are hello-jni, hello-neon, hello-oboe, teapots, san-angeles
and so on but the ones that look very interesting to me are;
native-activity, native-audio, native-codec, camera and audio-echo. If I
could run these I should be able to make an android client and also,
hopefully use those compressors for video and sound to replace the ones I
have been using up to now.

I am trying to use the “Visual Studio” option “File->New->Project From
Existing Code” and choosing one of the samples, e.g. camera. This morning I
was getting ‘jni.h’ not found.  That’s the Java Native Interface header
file.  The only way around this was to install OpenJDK and put its
directories into the project.

That got rid of the problem. Now when I try to make a program based on
‘camera’ it is saying “Two or more files with the name of
‘android_main.cpp’ will produce outputs to the same location”.

Rather than continue nitpicking through errors, I would just like to ask
you this;

Is there a way to get the camera example (or any example) to run or be
cloned or is there any way to create a program using that code?. Is there
any tutorial that can show me how to get any of the examples to run? Thank
you for your patience Colin and thank you again in advance for any help.

Peadar

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by corob-msft** [comment]
@PeadarO 

Interesting. While it might be possible to get one of the JNI apps running by using the Project from Existing Code wizard, you might have to set some additional options beyond what the wizard shows in order for the tools to be found, and you wouldn't have access to the debugger or emulator from within VS without even more work.

I think I'd take a different approach. I'd use one or two of the existing cross-platform templates in Visual Studio as my starting point.

Maybe you've already done this, but have you [set up the VS workload for mobile development with C++](https://docs.microsoft.com/cpp/cross-platform/install-visual-cpp-for-cross-platform-mobile-development?view=vs-2019)? It's been a while since I've done it myself, so I don't recall every detail, but I found that if I'd also already installed the JDK, NDK, and other bits, I also needed to update the paths to the tools in the **Tools** > **Options** dialog under **Cross Platform** > **C++** > **Android**. I set up the [Google Android emulators to use Hyper-V](https://docs.microsoft.com/xamarin/android/get-started/installation/android-emulator/hardware-acceleration?pivots=windows), since the HAXM approach limited other things I could do on my machine. (Also: [emulator troubleshooting](https://docs.microsoft.com/xamarin/android/get-started/installation/android-emulator/troubleshooting?pivots=windows).) And just eyeballing the Xamarin docs, it's possible you might need to [change which JDK you're using](https://docs.microsoft.com/xamarin/android/get-started/installation/openjdk) as well. It's possible that the OpenJDK is now installed by the Mobile development with C++ workload by default, but I'm not sure about that.

After getting the cross-platform mobile stuff set up, I'd load up the template for **Basic Application (Android, Ant)**, then build and deploy and debug the app, just to make sure it all works with an emulator and with an actual device.

And then I'd treat that Basic Application project as my empty project, and stuff in all the JNI code from whatever example app I wanted to build. I'd probably just copy the code into my project directory, then use the "Add item" command a few times to add the copied source files. There are also VS templates for Android library projects, that you can copy library code into. This approach would let me avoid having to actually track down all of the project settings in VS required for building these things from scratch. Which is possible, I'm sure, just not something I'd choose to do if it was avoidable. 

I suspect this approach will work better than using the Open Existing Code method to get started. It's also possible I'm sending you on a wild errand. I hope not. It's just what I'd try first. And if it didn't work, I'd start scouring [StackOverflow](https://stackoverflow.com/questions/tagged/visual-studio%20android%20c%2b%2b) and [Developer Community](https://developercommunity.visualstudio.com/search.html?f=&type=question+OR+problem+OR+idea&type=question+OR+problem+OR+idea&c=&redirect=search%2Fsearch&sort=relevance&q=android) for answers. Good luck with your project.

**Comment by PeadarO** [comment]
Thank you very much Colin, I have read all that you said and I'll give it a
run tomorrow. I'll keep you informed of any developments. Thanks again.
Peadar.

**Comment by PeadarO** [comment]
Thanks again Colin. I have finally despaired of getting the "Project from
existing code" to work and I am going to try to follow the steps you have
given me. You mentioned "Basic application(Android, Ant)". That always
creates a Java program and I am hoping to make a c++ project. Did you mean
to say "Native Activity Application?" or are you saying that i can create a
project with the Java "Hello world" in it and then add in the C++program
from the samples?  -   Peadar

**Comment by corob-msft** [comment]
@PeadarO 
Yes, you're right, use the Native Activity Application template as a base for C++ projects, or possibly the OpenGLES app template (which unfortunately isn't listed if you specify Android in the drop-down template filters - specify iOS instead). If you use the latter, you can just remove the OpenGLESApp.iOS.StaticLibrary and OpenGLESApp.iOS.Application projects from the solution. Also, it pays to either connect your device or start your emulator, and possibly start a trace window, before attempting to deploy and debug from VS. I can never get VS to connect unless the target has already communicated with something on the PC at least once.

**Comment by PeadarO** [comment]
Colin, I'll probably stop this after today and try Android studio. It's
clear that these examples can't be made work. Just one question Colin. Are
you aware of any example program in C++ which can be compiled in Visual
Studio and which will run on Android? Looking at GitHub it certainly seems
that no one there ever got any of them to work. I'll keep looking at GitHub
today and after that I'll stop wasting your time. Thank you for your
patience anyway Colin. Peadar

**Comment by corob-msft** [comment]
Sure, I've built all the C++ NDK samples in Visual Studio 2015 and 2017. I've only built the OpenGLES app for Android in VS2019, but it did work last time I tried it. I installed Android Studio to use the graphical SDK Manager, but nothing else. I used AVD Manager to create and start the emulators. Coding, deploying, and debugging in VS worked fine, but as I mentioned previously, I had to start the emulator in AVD Manager first before VS could connect to it. Good luck!
