### ISSUE TITLE
extern "C" and exception throwing

### ISSUE THREAD

**Issue by mwinterb** [MicrosoftDocs/cpp-docs#2227]
This is probably a bit of a silly question. The documentation for `/EHsc` says "the compiler assumes that functions declared as `extern "C"` never throw a C++ exception". Is marking a function that's declared as `extern "C"` `noexcept(false)` (e.g. `extern "C" void foo() noexcept(false);`) enough to cause the compiler to reverse that assumption? Output from the compiler says "yes", but I don't know if that's a guarantee or an accident of the implementation.

I agree that this is a weird scenario.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eb92ec5e-333d-0411-3ab3-18232334cf13
* Version Independent ID: c8b73b3d-a151-1556-890b-9653a9a19f56
* Content: [/EH (Exception handling model)](https://docs.microsoft.com/en-us/cpp/build/reference/eh-exception-handling-model?view=vs-2019#feedback)
* Content Source: [docs/build/reference/eh-exception-handling-model.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/reference/eh-exception-handling-model.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@mwinterb 
As far as I know, the noexcept specification isn't part of the signature, so it's not communicated by name decoration. The declaration syntax is all the compiler has to go on outside of the current translation unit. So, under `/EHsc`, it makes the default assumption that an `extern "C"` function won't throw, but if it also sees `noexcept(false)` then it generates code as if the function could throw. It behaves analogously under `/EHs`: a function declared both `extern "C"` and `noexcept` causes the compiler to generate code on the assumption that it doesn't throw, instead of the default assumption that it could.

**Comment by mwinterb** [comment]
@corob-msft Thank you. Sorry for the delay in getting back to you. I knew, absent LTCG, that only the declaration syntax would impact the determination of a function not throwing, I just didn't know if the "but if it also sees `noexcept(false)`" part was guaranteed. And it sounds like it is. Thank you.
