### ISSUE TITLE
_MBCS and _UNICODE are not discussed

### ISSUE THREAD

**Issue by noloader** [MicrosoftDocs/cpp-docs#2236]
Hi Everyone. I was looking at [cpp-docs/docs/preprocessor/predefined-macros.md](https://docs.microsoft.com/cpp/preprocessor/predefined-macros). I noticed neither `_MBSC` or `_UNICODE` are discussed.

There is a discussion of `_MBSC` or `_UNICODE` at [Generic-Text Mappings in tchar.h](https://docs.microsoft.com/en-us/cpp/text/generic-text-mappings-in-tchar-h).

It may be a good idea to add them to the list. I wanted to cite this list, but the discussion is missing.

(Edit by @corob-msft to point link at documentation instead of source file.)

**Comment by corob-msft** [comment]
@noloader 

These macros, while ubiquitous, aren't mentioned in this particular document because they're not predefined by the compiler. You have to define them yourself if you want them, just like `DEBUG` (as opposed to `_DEBUG`). The confusion may arise because they're usually defined for you by template-created projects, they're required for certain library behavior, and you can set them in a projects Property Pages dialog.

**Comment by corob-msft** [comment]
@noloader 

Also, it's helpful if you use the feedback control at the bottom of the public documentation page to raise an issue. It fills in an issue template with info we need for bug assignments and tracking. Thanks!
