### ISSUE TITLE
Example code for exporting functions will not generate a lib file due to lack of export prefix

### ISSUE THREAD

**Issue by chebastian** [MicrosoftDocs/cpp-docs#2274]
## Issue
Following along with the sample and building the MathLibrary project will only produce a dll since the implementation of the library functions are not prefixed with the __declspec(dllexport) nor the defined MATHLIBRARY_API macro.

## Suggested solution:
Add MATHLIBRARY_API prefix to sample function implementations

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 08c574a2-cef0-ab13-7375-55851f966ef6
* Version Independent ID: fe3421c7-e9f4-4986-589f-fadaedce583e
* Content: [Walkthrough: Create and use your own Dynamic Link Library (C++)](https://docs.microsoft.com/en-us/cpp/build/walkthrough-creating-and-using-a-dynamic-link-library-cpp?view=vs-2019)
* Content Source: [docs/build/walkthrough-creating-and-using-a-dynamic-link-library-cpp.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/walkthrough-creating-and-using-a-dynamic-link-library-cpp.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@chebastian 
Thanks for writing in. I apologize for taking so long to get back to this issue. I'm not sure why you didn't initially get a library file built when you ran through the walkthrough, though I have some ideas.

First off, the function definitions don't need to have the `__declspec(dllexport)` added via the MATHLIBRARY_API macro, because that would be redundant. The compiler will apply `__declspec(dllexport)` to the function *definitions* because the function *declarations* already said to do that. You'd only need to do this if your .cpp implementation file doesn't include the header file with the declarations.

Second, if you've followed the instructions, you're already generating an import library when you build your DLL. It should be in the same output directory as the DLL. (That is, it's in the Debug directory under the Solution folder, *not* the Debug folder under the Project folder.) If it isn't there, then there's something wrong in your project properties, or possibly your source code. It could be that your project's Configuration Type isn't Dynamic Library. It could be you don't define MATHLIBRARY_EXPORTS in the Preprocessor Definitions for every possible configuration combination. It could be that your .cpp implementation file doesn't include the header file with the MATHLIBRARY_API declarations. This Stack Overflow question has several solutions you could try: [Build Succeeded, but no .lib file gets created](https://stackoverflow.com/questions/3950509/build-succeeded-but-no-lib-file-gets-created). Not all of the solutions are correct - in particular, the one that has you do what you suggest here in this issue isn't needed.

Since investigation finds the issue and the associated PR aren't needed, I'm closing both. Thanks for making the effort; I'm sorry it wasn't necessary.
