### ISSUE TITLE
The feedback footer is weird

### ISSUE THREAD

**Issue by angusgraham** [MicrosoftDocs/cpp-docs#2304]
Here's a picture:
![image](https://user-images.githubusercontent.com/11641291/87200760-11fd4680-c2b2-11ea-9082-a0188e50f59d.png)
The box labeled "Submit and view feedback for" contains a button labeled "This page" but if you click it, it takes you to a github page where you cannot view feedback (you can only submit it).
Then there's another link labeled "View all page feedback" but it's outside the box.

**Comment by corob-msft** [comment]
@angusgraham 
Yes, it's weird. We can no longer display the feedback directly on the article, due to some privacy law requirements, IIRC, so our Docs infrastructure team provided a way to see it with yet another link. It would be useful to see existing open issues when you're adding one, to see if it's already reported or if a clarifying comment was made. I understand this area is under further development, but for now, this is what's available. Since the Docs infrastructure team is aware of the issue, I'm closing this one rather than forwarding it, but thought you deserve to know you're not the only one who's noticed this issue.
