### ISSUE TITLE
BEGIN_MESSAGE_MAP does not work for 'virtual public' base classes

### ISSUE THREAD

**Issue by rtischer8277** [MicrosoftDocs/cpp-docs#2322]
The BEGIN_MESSAGE_MAP macro needs to be updated so it works with modern C++'s virtual public base classes. The virtual base is defined as "means most derived object contains only one base class subobject of that type". Without this ability, each MFC derived classes will create its own instance of base class variable.  Modern C++'s 'virtual public' handles this smoothly and MFC ought to reflect that.

The workaround is to the variable static.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94f162df-10f0-153a-9fae-8d403a4fce11
* Version Independent ID: cf67e45a-140c-c097-00f6-48f92665ef5b
* Content: [Message Map Macros (MFC)](https://docs.microsoft.com/en-us/cpp/mfc/reference/message-map-macros-mfc?view=vs-2019#begin_message_map)
* Content Source: [docs/mfc/reference/message-map-macros-mfc.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/mfc/reference/message-map-macros-mfc.md)
* Product: **visual-cpp**
* Technology: **cpp-mfc**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by corob-msft** [comment]
@rtischer8277 
This sounds like a product suggestion, rather than a documentation issue. [Visual Studio has a built-in facility for making product suggestions like this one](https://docs.microsoft.com/visualstudio/ide/suggest-a-feature?view=vs-2019). You can also suggest this change directly on the Visual Studio C++ [Developer Community](https://developercommunity.visualstudio.com/spaces/62/index.html) website, where other developers can see your proposal and upvote it. I'm closing this as unrelated to the docs, but don't let that stop you from proposing this change where it will have the greatest impact. Best of luck.
