### ISSUE TITLE
Add support for #ident directive

### ISSUE THREAD

**Issue by shadowC0der** [MicrosoftDocs/cpp-docs#2327]
I am getting C4274 error when compiling my code, the Visual Studio 2019 C++ compiler doesn't recognize #ident -- other compilers provide this support.  Using #ident (or #pragma ident) allows storing software version information (as described by IEEE 828-2012 Software Configuration Management and other IEEE software standards) in the comment region of the ELF.  The Microsoft recommendation is to remove #ident (and store version identification string in data region of ELF) reveals Visual Studio C++ compiler does not consider IEEE standards important, and would not serve well in the commercial software engineering industry.  Using the #ident directive is more desired as it avoids occupying data space and is not loaded during execution.

I request Microsoft add support for #ident directive.

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7fa9fab7-31c3-fcaf-1f68-2176d199c44c
* Version Independent ID: 1c94de8f-d5da-91de-bd50-1515dcd5a51f
* Content: [Compiler Warning (level 1) C4274](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-1-c4274?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev16.query%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(C4274)%26rd%3Dtrue&view=vs-2019)
* Content Source: [docs/error-messages/compiler-warnings/compiler-warning-level-1-c4274.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/error-messages/compiler-warnings/compiler-warning-level-1-c4274.md)
* Product: **visual-cpp**
* Technology: **cpp-diagnostics**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@shadowC0der 
Thanks for making a suggestion here. The `#pragma ident` deprecation warning appeared in Visual Studio 2002, some 18 years ago. The linker doesn't support .comment segments in executable files in PE-COFF format as far as I can tell. Since your suggestion doesn't appear to be about the documentation, the Docs team can't do much about it it. To get the attention of the development team, you should use the *other* feedback button at the bottom of the C4274 article - the one that says **This product**. That will take you to the Visual Studio C++ [Developer Community](https://developercommunity.visualstudio.com/spaces/62/index.html) website, where you can make a product proposal. If it's voted up by other developers, the odds that it will be implemented increase. Best of luck!
