### ISSUE TITLE
Using vcpkg on a per project basis

### ISSUE THREAD

**Issue by tester0077** [MicrosoftDocs/cpp-docs#2339]
After finding vcpkg recently, I found it useful for one project, but because I usually have several projects - including some legacy projects -  in various stages of progress, I need to sort out how to best apply vcpkg in my environment.
The legacy projects will need to use specific versions of certain common libraries different from those projects currently in progress to avoid complications

My simplified source tree will looks something like

```
root --+- wxWidgets  3.1.1 -+- MSVC 2010 --- proj1
	   |                +- MSVC 2015 --- proj2
	   |
	   +- wxWidgets 3.1.3  -+- MSVC 2017 -+- proj3
	                        |             +- proj4
	                        +- MSVC 2019 -+- proj5
	                                      +- proj6
					      +- proj7
```
Assuming  proj 1, 2, 3 & 4 are legacy projects and each will need a specific version of some libraries.
As I understand it, MSVC 2010 does not support vcpkg, so there ought to be no impact on that project.
Proj 5, 6, & 7 are in development and therefore will be set to use a common subject of all the libraries.
My question is: how many instances of vcpkg do I need to install and where do I place their 'base' directory?
A rather detailed set of commands would be most appreciated

**Comment by corob-msft** [comment]
@tester0077 
I'm sorry it's giving you difficulty. We're not set up to handle support questions in the Docs team, and this doesn't sound like an issue with the documentation *per se*. Since [vcpkg](https://github.com/Microsoft/vcpkg) (usually) builds libraries from sources, it sounds like you want to have one vcpkg instance per build toolset, build the preferred version of the library once per build toolset, and then share the resulting library binaries with every project that uses that particular build toolset and library version. Based on your diagram, I'd guess that's four instances. If you have questions about the use of vcpkg itself, you can raise issues on the Visual Studio C++ [Developer Community](https://developercommunity.visualstudio.com/spaces/62/index.html) website. Best of luck.

**Comment by tester0077** [comment]
Thank you for your clarification.
There are so many places to ask, it sometimes is not clear which is the 'best' place to start.
In a way your solution makes sense, and is what I expected. My problem was to figure out just how to go about it, and for that scenario, IMO, there should be an example in the docs
