### ISSUE TITLE
provide some formula. it will be easier for understand ex=  range of char is 1 byte |  if we put the value at the given formula like| 2^n-1| 2^8-1=128||because we know that the value of 1 byte is 8 bit so i am just putting the this value at n

### ISSUE THREAD

**Issue by Abhijeet05061998** [MicrosoftDocs/cpp-docs#2365]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a3252f3-2390-77d1-75ee-00ff08584173
* Version Independent ID: 53786641-f25d-638f-18d5-8c7e19712776
* Content: [Data Type Ranges](https://docs.microsoft.com/en-us/cpp/cpp/data-type-ranges?view=vs-2019)
* Content Source: [docs/cpp/data-type-ranges.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/cpp/data-type-ranges.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@Abhijeet05061998 
It appears that the more common form of question we get isn't that **`long long`** has a range from -2<sup>63</sup> to 2<sup>63</sup> - 1, which programmers can readily determine, but rather that it's -9,223,372,036,854,775,808 to 9,223,372,036,854,775,807, which doesn't as easily come to mind. That's why we write these the way we do.

**Comment by Abhijeet05061998** [comment]
I can fully understand why you writen all the value. But my point of view is. it possible to remember these long number all the time during programming. So that's why I told you just put this (2^n-1) formula behind those particular value. Correct me if I'm wrong
Thankyou 😊
