### ISSUE TITLE
"Override a virtual function" doesn't work

### ISSUE THREAD

**Issue by sanbrother** [MicrosoftDocs/cpp-docs#2372]
Reference: https://docs.microsoft.com/en-us/cpp/ide/overriding-a-virtual-function-visual-cpp?view=vs-2017
The 'overrides' tab is empty. I am sure that base class have some virtual methods.
I'm using VS2017 community edition. Could anyone help me figure out why? Thanks a lot.

**Comment by corob-msft** [comment]
@sanbrother 
It didn't work the way I expected, either. This seems like it could be a product issue, rather than a documentation issue. I recommend reporting the problem on the Visual Studio C++ [Developer Community](https://developercommunity.visualstudio.com/spaces/62/index.html) website. That's where the product development team looks for issues. You can use the **Help** > **Send Feedback** > **Report a Problem** menu command in the IDE to get started. If it turns out that it's not a product bug, and we need to update the docs. the dev team will let us know. If you enter an issue there, would you mind putting a link to it in this issue for follow-up? Thanks, and good luck.

**Comment by sanbrother** [comment]
@corob-msft Thank you very much. I post this issue to the Developer Community, and wish it would be fixed soon.

[The link to this issue](https://developercommunity.visualstudio.com/content/problem/1155078/override-a-virtual-function-doesnt-work.html)
