### ISSUE TITLE
How to avoid C26437 warning when slice is required? 

### ISSUE THREAD

**Issue by TonyRietwyk** [MicrosoftDocs/cpp-docs#2388]
[Enter feedback here]

The page explains what slicing is, but does not explain how to avoid the warning when the slice is actually required?  Eg, does using a static_cast avoid the warning? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 627fa04e-452e-99f3-3110-9b3ce879c9d1
* Version Independent ID: d8dc1078-5e1c-9d89-7318-44c24ccff1ae
* Content: [C26437](https://docs.microsoft.com/en-us/cpp/code-quality/c26437?view=vs-2019)
* Content Source: [docs/code-quality/c26437.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/code-quality/c26437.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@TonyRietwyk 
That's true. You'll find that we don't describe what to do if you want the behavior that code analysis warns about but not the warning in any other articles, either. Instead, elsewhere we describe [how to create a ruleset that doesn't include a particular warning](https://docs.microsoft.com/cpp/code-quality/using-rule-sets-to-specify-the-cpp-rules-to-run?view=vs-2019), and we also explain [how to disable specific warnings](https://docs.microsoft.com/cpp/preprocessor/warning?view=vs-2019) at the function level. I'm closing this issue, as I don't expect we'll address it.

A `static_cast<base_type>(derived_type)` is an explicit "I know what I'm doing" marker, It might work here, though I don't know. I'm very suspicious of claims that slicing is required, instead of, say, constructing a new instance of the needed base type from the derived type and using that instead. You can't make mischief in the sliced members if they're not there in the first place.
