### ISSUE TITLE
Analysis issues - "what should be done" sample codes.

### ISSUE THREAD

**Issue by Slyware** [MicrosoftDocs/cpp-docs#2417]
Hi.

I appreciate the online documentation fetched from Visual Studio for my C++ developments.
For example, when clicking on an error given by the compiler or the static analysis (Clang), we get a page like this one:
[C26485 NO_ARRAY_TO_POINTER_DECAY](https://docs.microsoft.com/en-us/cpp/code-quality/c26485?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev16.query%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(C26485)%26rd%3Dtrue&view=vs-2019)

A sample code is given for "what we shouldn't do". But I regret one thing: **There is no sample code for "what should be done", how to correct the issue.** I previously worked with tools whose documentation was done this way.
I imagine it's a large piece of work but it would give a great added value to your products.

Kind regards.
Sylvestre.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a414c668-e7c2-0e5d-f58f-9ab68abf76e9
* Version Independent ID: 25fa5dbb-7c65-57f3-eaa4-a422c79cb4f1
* Content: [C26485](https://docs.microsoft.com/en-us/cpp/code-quality/c26485?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev16.query%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(C26485)%26rd%3Dtrue&view=vs-2019)
* Content Source: [docs/code-quality/c26485.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/code-quality/c26485.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@Slyware 
I understand and support your notion that warning docs should incorporate instructions on how to fix the issue. We try to do that now. Sometimes it's easy to say what to do to fix an issue. In other cases, it's tantamount to saying "you need to rearchitect your code away from this problem-prone paradigm." There may not be one simple transformative answer, so you get handwaving instead. That's the case in this article. Any number of solutions *could* work better, but we don't show use of one over another because we don't know which one will work best, or even well, in your situation. In some other old articles, we just plain didn't include a "how to fix it" example. We'll try to address those when we come across them, or when someone complains. Thanks for the validation.
