### ISSUE TITLE
Exceptions do provoke run-time penalties. 

### ISSUE THREAD

**Issue by DBJDBJ** [MicrosoftDocs/cpp-docs#2418]
There is also a WG21 paper on that ...
 http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2019/p1640r1.html

No point in digging further ... you know all the issues quite well.  Perhaps best described in one place by one H. Sutter: http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2019/p0709r4.pdf

Perhaps Herb should amend that page?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 808812eb-d44a-e405-70ed-4d15ed9be975
* Version Independent ID: a3144c13-db26-9dbc-30d8-ae6ca52457af
* Content: [Modern C++ best practices for exceptions and error handling](https://docs.microsoft.com/en-us/cpp/cpp/errors-and-exception-handling-modern-cpp?view=vs-2019)
* Content Source: [docs/cpp/errors-and-exception-handling-modern-cpp.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/cpp/errors-and-exception-handling-modern-cpp.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@DBJDBJ 
It's true, exceptions are not free. In current implementations, they're not "zero-cost abstractions" even by the non-intuitive meaning for that phrase. MSVC includes some of the exception handling machinery overhead to support Structured Exception Handling by default even when C++ standard exception handling is disabled.

This article points out that adopting a consistent exception approach saves programmer time and mental energy, potentially reducing the cost of code creation and maintenance, and the likelihood of defects. It also correctly points out that you have to profile your code to know how this will affect your particular situation. Is it code that will run trillions of times on millions of machines? Is it meant for tiny IoT devices with a constrained energy budget? Is it something your company's IT department will run overnight once a month? The argument for exceptions in Modern C++ is cheerleading, not a mandate. A little hyperbole deserves a pass.

Herb's code style suggestions of always throwing static or constexpr types by value at least reduces some potential EH overhead. The distinction of reserving exceptions for exceptional code paths, using assertions and static analysis for broken code, and using fail_fast for unrecoverable errors is a subtle one. It's good advice, and probably worthy of an entire article of its own. I'll leave this issue here as a potential doc idea, but I have to be upfront, and say it's low priority and probably won't be addressed anytime soon.

**Comment by DBJDBJ** [comment]
Thanks Rob,

"Exceptions or no exceptions" is splitting apart the C++ world into two opposing fractions ([as we speak](https://thephd.github.io/freestanding-noexcept-allocators-vector-memory-hole)).
That page is (excuse moi) just plain silly C++ in 2020. It should at least add the part about "exceptions are not for local error handling" universally accepted wisdom. With code example. As it stands now that page says: Just use exceptions and you will be OK. Plain wrong.

Herbs paper P0709R4 is not "Herb's code style suggestions", it is very deep core language change exactly because of deeply rooted problems with std exceptions; you got me confused over there?

**Comment by corob-msft** [comment]
I'm using "suggestions" for style changes programmers can make *now* to improve their programs, independent of P0709R4, which won't be part of C++ until 2023 at the earliest.

Don't be afraid to propose new language or a sample for an article in a PR. It's okay to make your arguments about what's "plain wrong" in a more concrete fashion. We encourage it. As I mentioned, rewriting an article like this one is unlikely to be a priority for us until we get a change on the order of adoption of P0709R4.

**Comment by DBJDBJ** [comment]
Thanks Rob ... unfortunately, it seems it is hard to have a dialogue with you. Kind regards ...
