### ISSUE TITLE
Change maximum nr pages CMFCPropertySheet

### ISSUE THREAD

**Issue by jelledus** [MicrosoftDocs/cpp-docs#2426]
Hi,

I wrote code to nicely display a large amount of property pages on one sheet using the PropSheetLook_Tree.
The issue I'm facing is that I cannot seem to create the sheet with more than 99 pages. I have found similar issues online here:

https://social.msdn.microsoft.com/Forums/sqlserver/en-US/bf782cf1-724b-4981-a972-06e7610fad95/add-more-than-99-pages-to-cpropertysheet?forum=vcgeneral

https://groups.google.com/g/microsoft.public.vc.mfc/c/aJqGvFG6kqQ

I cannot find anything in Microsoft Documentation about a set limitation to the number of pages. 
Is there anyway I can circumvent this? Note: I'm not looking for ways to circumvent my design; I simply want to know if it's possible to add more than 99 pages to a sheet.

Regards,
Jelle

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cbbd43e6-fbf9-7dbd-a865-7ab6650f7af5
* Version Independent ID: 10e29a8e-4689-757f-8a6a-0811737e1295
* Content: [CPropertySheet Class](https://docs.microsoft.com/en-us/cpp/mfc/reference/cpropertysheet-class?view=vs-2019)
* Content Source: [docs/mfc/reference/cpropertysheet-class.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/mfc/reference/cpropertysheet-class.md)
* Product: **visual-cpp**
* Technology: **cpp-mfc**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by corob-msft** [comment]
@jelledus 

Interesting question. A little investigation shows that this isn't an MFC- or ATL-specific limitation, which is why it's not documented here. The limitation is built into Windows itself. You can find the `CPropertySheet::DoModal` implementation in *%VCToolsInstallDir%atlmfc\src\mfc\dlgprop.cpp* around line 903. It does some bookkeeping and calls the Windows `PropertySheetW` function (line 958) to do the actual work. If you look up the [`PropertySheetW`](https://docs.microsoft.com/en-us/windows/win32/api/prsht/nf-prsht-propertysheetw) function in the Windows API docs, you'll see it documents the 99 page limitation and the -1 error value returned. My guess is, since the limitation is per parent window, there'd be no easy way to circumvent the limit within a single control. Sorry there's no more hopeful answer.
