### ISSUE TITLE
Open new binary file direction are incorrect

### ISSUE THREAD

**Issue by chazste** [MicrosoftDocs/cpp-docs#2436]
I came to this page wanting to open a "New" binary editor. This page describes how to do that, but following the directions the New file dialog does not have a drop down on the open button.  Either these directions are incorrect or the feature is now broken in visual studio. I can't quite tell, but the screen shot appears to be from Visual Studio 6.

The directions for opening an existing binary file are correct.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3406b4da-3d4f-a3c8-a946-675cf3ff7bdc
* Version Independent ID: 3781d0ac-47eb-50bf-9b13-4b5d5c6bcea0
* Content: [Binary Editor (C++)](https://docs.microsoft.com/en-us/cpp/windows/binary-editor?view=vs-2019)
* Content Source: [docs/windows/binary-editor.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/windows/binary-editor.md)
* Product: **visual-cpp**
* Technology: **cpp-windows**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@chazste 

It appears that the feature is present in the new file open dialog in Visual Studio 2017, and is no longer present in Visual Studio 2019. I don't know if this represents an intentional change or not. It's unlikely to have been removed by accident. The way to find out is to ask a question on the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html) board. That's where product (as opposed to documentation) questions should be addressed.

I'll leave this open as a documentation issue, since that sentence about opening a new file with the binary editor may need to be deleted for VS 2019.

**Comment by corob-msft** [comment]
I asked about this in Developer Community here: [Should New File dialog be missing dropdown on Open button for "Open With" editor choice?](https://developercommunity.visualstudio.com/content/problem/1177719/should-new-file-dialog-be-missing-dropdown-on-open.html)

**Comment by corob-msft** [comment]
Well, it took a while, but this issue is now fixed in Visual Studio 2022 version 17.0. I'll put in a mention about VS2019 in the doc.
