### ISSUE TITLE
Does vcpkg support vscode with cmake ON WINDOWS?

### ISSUE THREAD

**Issue by bit7** [MicrosoftDocs/cpp-docs#2458]
I gotta say trying to get vcpkg to work with cmake in vscode is really frustrating.  I'm pretty sure I got it working once at work when I started a simple test project to test it out.  But now at home, I'm following the same instructions and I just can't get my code to see the SDL.h header in an include statement.

I don't think I've ever been this angry.  Seriously guys!  Make this work better!

**Comment by corob-msft** [comment]
@bit7 
Sorry it's giving you a hard time. I believe this is supposed to work, and has worked for others, but I'm not qualified to say more about it since I haven't used that combination of tools. We don't have documentation about that particular combo in the cpp-docs repo, since VS Code docs live in a separate repo, so I'm closing the issue here. Perhaps @TylerMSFT can comment with pointers.

**Comment by itodirel** [comment]
@bit7 can you please provide us a repro? Is this issue in Visual Studio, or Visual Studio Code?

**Comment by bobbrow** [comment]
The C++ extension can usually find your vcpkg installed headers if you've run the `vcpkg integrate install` command on your machine.  Then you add the `${vcpkgRoot}` variable to your `includePath` in `c_cpp_properties.json` and the extension should find your headers.  (In new folders, this include path addition is automatic assuming that the integrate install command has run)

Usually the step that is forgotten when setting up multiple machines is `vcpkg integrate install`.  Can you check and make sure that this was done?
