### ISSUE TITLE
If I follow this Walkthrough, step 5 gives me compiler warning C4273

### ISSUE THREAD

**Issue by josuemb** [MicrosoftDocs/cpp-docs#2463]
If I follow this Walkthrough, step 5 gives me compiler warning C4273

![image](https://user-images.githubusercontent.com/373653/93157332-a24f7180-f6cf-11ea-85b0-6d52babb8180.png)

MyRobotLibrary.h

```cpp
#pragma once

#ifdef MYROBOTLIBRARY_EXPORTS
#define MYROBOTLIBRARY_API __declspec(dllexport)
#else
#define MYROBOTLIBRARY_API __declspec(dllimport)
#endif

extern "C" MYROBOTLIBRARY_API void say_hello();
```

MyRobotLibrary.cpp

```cpp
#include "pch.h"
#include "MyRobotLibrary.h"
#include <iostream>

void say_hello()
{
    std::cout << "Hello";
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 08c574a2-cef0-ab13-7375-55851f966ef6
* Version Independent ID: fe3421c7-e9f4-4986-589f-fadaedce583e
* Content: [Walkthrough: Create and use your own Dynamic Link Library (C++)](https://docs.microsoft.com/en-us/cpp/build/walkthrough-creating-and-using-a-dynamic-link-library-cpp?view=vs-2019)
* Content Source: [docs/build/walkthrough-creating-and-using-a-dynamic-link-library-cpp.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/walkthrough-creating-and-using-a-dynamic-link-library-cpp.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@josuemb 

Sorry you're having trouble. Other readers usually don't run into this problem. I couldn't find a step 5 that seemed to correspond with something that would cause a build warning. The C4273 warning usually means you're not defining your symbol for *PROJECT*_EXPORTS when you build your DLL, or it's defined inconsistently. The symbol definitely should not be defined when you build your client.
Closing as a support request rather than a doc issue.
