### ISSUE TITLE
Windows XP platform tools support in Visual studio 2019

### ISSUE THREAD

**Issue by nallanavijayakumar** [MicrosoftDocs/cpp-docs#2481]
Recently we migrated our VC++ tools to Visual studio 2019 from 2010. While testing we found out that the VS2019 doesn't support XP and we followed below doc and installed "v141_xp" platform toolset and compiled our application. It worked in XP after this change. But later we found that when we install "v141_xp" on top of existing VS2019 it uses the existing MSVC compiler (14.26.28801). But when the developers have "v141" (VS2017) platform toolset installed in their PC and when we select "v141_xp" toolset option in visual studio 2019 project properties, its compiling with VS2017 MSVC compiler (14.16.27023). 

So Is it OK to use "v141_xp" platform toolset option on top of VS2019 (without installing v141 toolset) which uses VS2019 MSVC compiler during complication? If Yes then the name (**C++ Windows XP Support for VS 2017 (v141) tools [Deprecated]**)of the "v141_xp" option in visual studio installer is misleading. Or there should be some documentation in below link which says this.
If No, then it should automatically select **MSVC v141 - VS 2017 C++ x64/x86 build tools (v14.16)** option when we select **C++ Windows XP Support for VS 2017 (v141) tools [Deprecated]**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 651c91cd-a0c3-f631-7bab-707ea4f1827b
* Version Independent ID: bfd995d2-6875-2301-ef78-4446ed268845
* Content: [Configuring Programs for Windows XP](https://docs.microsoft.com/en-us/cpp/build/configuring-programs-for-windows-xp?view=vs-2019)
* Content Source: [docs/build/configuring-programs-for-windows-xp.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/configuring-programs-for-windows-xp.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@nallanavijayakumar 

I'm sorry to hear you're experiencing inconsistent behavior. This is an interesting issue that sounds like a bug in the platform toolset system for the v141_xp tools. I would have expected the VS 2019 build system to consistently use the VS 2017 compiler and tools when v141_xp is selected as the toolset. As such, I don't think it's a docs bug, or at least, not yet. I recommend reporting this as a product issue on the Visual Studio C++ [Developer Community](https://developercommunity.visualstudio.com/spaces/62/index.html) site. Instructions for creating a good bug report are found in [How to report a problem with the Microsoft C++ toolset](https://docs.microsoft.com/cpp/overview/how-to-report-a-problem-with-the-visual-cpp-toolset). Include a reference to this docs issue in your report. If by some chance the behavior is intentional, then the dev team will let the docs team know what needs to be updated. Thanks for taking the time to report this issue!

**Comment by nallanavijayakumar** [comment]
Thanks you for your reply. Posted the question in developer forum (https://developercommunity.visualstudio.com/content/problem/1196734/windows-xp-platform-tools-support-in-visual-studio-2019.html)

**Comment by corob-msft** [comment]
Closing, pending developer feedback.

**Comment by anzz1** [comment]
I am unable to request reactivation of the issue in the developer forum, as I encounter this error when trying to do so:  

![image](https://user-images.githubusercontent.com/13628128/159508883-fec58e95-4e3d-407d-98f3-f2c6ccdcca4f.png)

**Comment by corob-msft** [comment]
@anzz1 
When you install the v141_xp toolset in Visual Studio 2019, a bug appears to let you build using the v142 compiler if you haven't upgraded from the v141 toolset. While this may work, it is not a tested scenario and is not supported by Microsoft. As such, we don't document that it works, and we recommend the support channels for workarounds. Since the dev team determined that the bug is too low a priority to fix, recourse is limited. I'd recommend installing the v141 toolset in this situation, but this is also not a tested or supported solution, so we can't document it as such. Apologies.

**Comment by anzz1** [comment]
That answers the question well though, that it might or might not work but it's undefined, unsupported behaviour and hence not recommended. Thanks.

**Comment by deniskak** [comment]
@corob-msft I was trying to download build tools 141 for XP but the only one available is 150:
![image](https://user-images.githubusercontent.com/2041572/207585832-29ffffb4-aa32-4512-8cc8-9d50c4f709c3.png)

Would you be able to share a direct link to it or is XP completely abandoned now? Thank you.

**Comment by mirh** [comment]
Check the visual studio installer/setup

**Comment by deniskak** [comment]
@mirh @corob-msft I did check the VS 2019 setup. I can't download 1.41 from the Msft website anymore per my screenshot above. The earliest available one is 1.50, which does not have XP build tools:
![image](https://user-images.githubusercontent.com/2041572/207711620-e3e991a0-255a-47ba-9d0a-7bfe44dd4192.png)

I do understand the issues with outdated XP but there are still cases when customers need XP support.

**Comment by corob-msft** [comment]
@deniskak 

Did you check under the **Individual components** tab in the VS Installer? The Optional list to the right of your screen shot does not list everything that's available for VS 2017. 

The naming conventions the team adopted don't help, since it's the IDE that's version 15.0, while the matching compiler and library toolset are version 14.1. Versions for VS 2019 are 16.0 for the IDE, toolset 14.2, and VS 2022 is 17.0, toolset 14.3. It's confusing, to say the least.
