### ISSUE TITLE
MS STL appears to work very well without C++ exceptions

### ISSUE THREAD

**Issue by DBJDBJ** [MicrosoftDocs/cpp-docs#2507]
@corob-msft , soory Colin you know what I think about this kind of statements:

" ... Even though Windows and Visual C++ support SEH, we strongly recommend that you use ISO-standard C++ exception handling (/EHsc or /EHs). It makes your code more portable and flexible... "

> After accepting [P1640R1](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2019/p1640r1.html) I think one can not just proceed using C++ exceptions.

This is for some people emotional issue because some other people are now loudly saying: "Why using C++ at all if one of the key paradigms is not feasible to use?"

I personaly do use MS STL that (appears to) work very well without C++ exceptions; by instead rising SE. AFAIK there is/was no official test but I/we can not spot destructors not being called?

HTH

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eb92ec5e-333d-0411-3ab3-18232334cf13
* Version Independent ID: c8b73b3d-a151-1556-890b-9653a9a19f56
* Content: [/EH (Exception handling model)](https://docs.microsoft.com/en-us/cpp/build/reference/eh-exception-handling-model?view=vs-2019#default-exception-handling-behavior)
* Content Source: [docs/build/reference/eh-exception-handling-model.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/reference/eh-exception-handling-model.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@DBJDBJ 

The intent of recommending C++ standard exception handling is for portability, in comparison to the Windows-specific and non-standard SEH mechanisms. The standard library uses standard C++ exception handling exclusively.

It's true that much of the standard library can be used without enabling exception handling. Member functions that are marked `noexcept` can safely be used without exception wrappers. The `noexcept` keyword is a kind of compiler contract that says "please terminate the program rather than let an exception escape this function." Callers can safely skip wrapping those calls in `try` blocks.

You can use stack-based objects to avoid heap allocations that might throw. If you use the standard `new` operator, you can get `std::bad_alloc` exceptions. You may also see this exception if the default allocator is called internally by some container types. It's possible in MSVC to [swap the standards-conforming `new` out for a non-throwing `new`](https://docs.microsoft.com/cpp/cpp/new-and-delete-operators?view=vs-2019) by linking the non-standard *nothrownew.obj* into your project. Once again, this isn't a portable solution.

There are some threading, string, and stream functions that throw. Basically, you'll have to check the declarations and docs for everything you want to call, to see what it might do. 

This doesn't seem like an actionable issue for a docs change to **`/EH`**, so I'm closing it.

**Comment by DBJDBJ** [comment]
@corob-msft I am avtually not interested in "portable C++" :) Neither many projects are. Simply most of the customers are on Windows. I might even argue SEH is standard for Windows.

On the issue of MS STL, I know it is impossible for you to read other people prose but here is [my short reverse engineering](https://github.com/DBJDBJ/kernel_ms_stl/blob/master/readme.md) (of the open source) MS STL working with SEH.

On the issue of MS Docs: one simple: "What if no any /EH is used" remark somewhere might do a lof good to a lot of people. Adjacent problem here is that VisualStudio raises the generations unaware of actual CL switches used or not used or what are they for actually. 

Thank you for your time
