### ISSUE TITLE
/Gh causing stack overflow

### ISSUE THREAD

**Issue by Kohit** [MicrosoftDocs/cpp-docs#2527]
[Enter feedback here]
Topic #2278 mentioned that the _penter function must compile along,
I countered another problem,
I need to use functions from other libraries in _penter function, for example
```
void myfunc(){
   // function from dbghelp.lib
   SymFromAddr(GetCurrentProcess(), dwAddr, &dwDisplacement, pSymbol);
}

_penter(){
   ... // save registers
   myfunc();
   ... // pop registers
}
```
I have compiled this file along, event tried to compile a static library(containing dbghelp.lib).
Both way, when the program runs, SymFromAddr would trigger _penter, which causing a stack overflow.

Is there a way to told the compiler not to trigger _penter in the following function calls? 
gcc's way:
```
__attribute__((no_instrument_function))
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8c088b59-1569-0026-999f-1347e3b110ef
* Version Independent ID: 9a298c01-cde2-7b38-15a1-c0af03716a00
* Content: [/Gh (Enable _penter hook function)](https://docs.microsoft.com/en-us/cpp/build/reference/gh-enable-penter-hook-function?view=vs-2019)
* Content Source: [docs/build/reference/gh-enable-penter-hook-function.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/reference/gh-enable-penter-hook-function.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@Kohit 
I'm sorry, we don't do product support in this repo's issues - it's meant for reporting documentation bugs. You'll have much better luck in the [Docs Q&A C++](https://docs.microsoft.com/answers/topics/c++.html) forum. One option might be to [set your app's stack size](https://docs.microsoft.com/cpp/build/reference/f-set-stack-size) to something bigger than the default, but my guess is that's not the real problem. Stack overflows are usually caused by runaway recursion, or oversized locals. Good luck!
