### ISSUE TITLE
Confuse about warning hint

### ISSUE THREAD

**Issue by zchrissirhcz** [MicrosoftDocs/cpp-docs#2530]
Hi,
MicrosoftDocs/cpp-docs Team

I'm using VS2019 community for C++ open source project [ncnn](https://github.com/tencent/ncnn). VS2019 give a "friendly warning" which I think should not be a warning.

To reproduce, consider this snippet:
```c++

void load_weights(const char* filename, std::deque<Section*>& dnet)
{
    FILE* fp = fopen(filename, "rb");
    if (fp == NULL)
        file_error(filename);

    int major, minor, revision;

    fread_or_error(&major, sizeof(int), 1, fp, filename);
    fread_or_error(&minor, sizeof(int), 1, fp, filename);
    fread_or_error(&revision, sizeof(int), 1, fp, filename);
    if ((major * 10 + minor) >= 2)
    {
        uint64_t iseen = 0;
        fread_or_error(&iseen, sizeof(uint64_t), 1, fp, filename);
    }
    else
    {
        uint32_t iseen = 0;
        fread_or_error(&iseen, sizeof(uint32_t), 1, fp, filename);
    }

    for (auto s : dnet)
    {
        if (s->name == "convolutional")
        {
            read_to(s->bias, s->filters, fp);
            if (s->batch_normalize)
            {
                read_to(s->scales, s->filters, fp);
                read_to(s->rolling_mean, s->filters, fp);
                read_to(s->rolling_variance, s->filters, fp);
            }

            if (s->layer_type == "Convolution")
                read_to(s->weights, (size_t)(s->c) * s->filters * s->size * s->size, fp);
            else if (s->layer_type == "ConvolutionDepthWise")
                read_to(s->weights, s->c * s->filters * s->size * s->size / s->groups, fp);
        }
    }

    fclose(fp); // ! Considier this line
}
```

![image](https://user-images.githubusercontent.com/3831847/95858881-5d7f2f00-0d90-11eb-89fd-ac4bdbbfac51.png)

For the last line, VS2019 just give warning hint: C6387, complaining `fp` may be NULL. However, is has been check in the beginning of this function:
```c++
    if (fp == NULL)
        file_error(filename);
```

I think this is a wrong warning. Any idea or suggestion? Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 725a4cd3-5880-a22b-c148-c594231a3ff3
* Version Independent ID: 295baf60-5b4e-162f-bc23-0675213477fc
* Content: [Using the C++ Core Guidelines checkers](https://docs.microsoft.com/en-us/cpp/code-quality/using-the-cpp-core-guidelines-checkers?view=vs-2019)
* Content Source: [docs/code-quality/using-the-cpp-core-guidelines-checkers.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/code-quality/using-the-cpp-core-guidelines-checkers.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@zchrissirhcz 

Thanks for writing to report your concern. The analysis behavior looks correct to me. Unless your `file_error` function terminates the program or throws an exception, execution appears to continue when `fp` is null. At the end of `load_weights`, you call `fclose(fp)` unconditionally. If `fp` is null, then `fclose` calls the invalid parameter handler, which causes a runtime error message. That's why the C6387 warning is issued. If you know this execution path is impossible, then you may safely ignore the warning. The analyzer can't always figure that out.

We're not equipped to handle support or product questions, and this doesn't look like a problem in the documentation, so I'm closing the issue.
