### ISSUE TITLE
CLR / .NET hint missing

### ISSUE THREAD

**Issue by Slesa** [MicrosoftDocs/cpp-docs#2532]
[Enter feedback here]
Would be nice to get a hint, that I additionally have to manually search the CLR package in order to produce .NET code

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f6c6f6a-188a-7110-962c-89ff8e00eee9
* Version Independent ID: ffa45840-7fbb-b9c2-0dd9-43eb95b760cc
* Content: [Install C and C++ support in Visual Studio](https://docs.microsoft.com/en-us/cpp/build/vscpp-step-0-installation?view=vs-2019)
* Content Source: [docs/build/vscpp-step-0-installation.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/vscpp-step-0-installation.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@Slesa 
I'm sorry you had some difficulty finding the components you needed. There are too many possible combinations to list them all, so the ones that don't have current marketing love are relegated to the phrase "and more." Support for building .NET components in C++ isn't deprecated, but it's much more limited than it used to be. You both have to install the .NET development workload, and under C++ development, choose the optional C++/CLI support component. Since keeping the clutter to a minimum as a goal, I'm not going to add this particular combination to the docs.
