### ISSUE TITLE
"Constexpr instead of "static const"?

### ISSUE THREAD

**Issue by yves-dolce** [MicrosoftDocs/cpp-docs#2538]
Shouldn't
_A variable (data member) marked as literal in a /clr compilation is the native equivalent of a static const variable._
be
_A variable (data member) marked as literal in a /clr compilation is the native equivalent of a `constexpr` variable._
?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 007f8d15-e31d-20ac-ab45-7ecb4956db42
* Version Independent ID: 9b06b70a-ea63-101c-7e94-f4dec0e0558c
* Content: [literal (C++/CLI and C++/CX)](https://docs.microsoft.com/en-us/cpp/extensions/literal-cpp-component-extensions?view=vs-2019)
* Content Source: [docs/extensions/literal-cpp-component-extensions.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/extensions/literal-cpp-component-extensions.md)
* Product: **visual-cpp**
* Technology: **cpp-cli**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@yves-dolce 
I'm confused by the intent of the original sentence. Since it says "the native equivalent" I'd assume it means the equivalent of a .NET type modifier, but data members can't be both `static` and `const` in C# apps. `literal` is the C++/CLI equivalent of C# `const` for data members. They turn into the same type in the app metadata. The closest analog for `literal` in standard C++ is `constexpr`. However, just like you can't have a `static const` in C#, you can't have a `constexpr` data member in C++/CLI. I've cleaned this up, and the result should be published tomorrow.
