### ISSUE TITLE
Issue calling `_stat` on newer versions of Windows 10

### ISSUE THREAD

**Issue by FrankAtHexagon** [MicrosoftDocs/cpp-docs#2539]
Hi everyone. Was the behavior of the `_stat` call changed between Windows 10 version 1803 and 1903?

File paths containing foreign characters are not being evaluated properly on Windows 10 version 1903, even though the machine is set to the correct locale.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f0c5bbf-0996-d5ac-650b-f67b118c6a5a
* Version Independent ID: 74d7d3aa-3ca0-f977-ca4d-52c89865b2ed
* Content: [_stat, _stat32, _stat64, _stati64, _stat32i64, _stat64i32, _wstat, _wstat32, _wstat64, _wstati64, _wstat32i64, _wstat64i32](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/stat-functions?view=vs-2019)
* Content Source: [docs/c-runtime-library/reference/stat-functions.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/c-runtime-library/reference/stat-functions.md)
* Product: **visual-cpp**
* Technology: **cpp-ucrt**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by corob-msft** [comment]
@FrankAtHexagon 

I'm sorry to hear the function is giving you trouble. Support for a UTF-8 code page was added in the Windows 10 1803 (build 17134) version of the UCRT, so it's now a fully-supported locale, and works with MBCS conversions. The maximum possible length of an MBCS character was increased for this to work. That's the only change I'm aware of that's even peripherally related to `_stat`, and it appears to predate the issue you've seen. 

The best place to ask this question, especially if you think you've discovered a defect in the library, is on [Developer Community](https://developercommunity.visualstudio.com/spaces/62/index.html). Since I don't see anything obvious to address in the docs, I'm closing this issue. If you raise the question there, and the response calls for a doc change, please revisit this issue to let us know. Thanks, and good luck!

**Comment by FrankAtHexagon** [comment]
Awesome, thanks for your response!
