### ISSUE TITLE
c++latest clarification on what preview means

### ISSUE THREAD

**Issue by NBlad** [MicrosoftDocs/cpp-docs#2552]
In VS2019 one can current specify C++14/C++17/C++ latest.  The C++latest option is prefixed by "Preview - Features from the Latest C++..."
Normally, we would not consider features that were in "preview" for production code.  When will a C++20 selection be available such that we can adopt a non-preview version?  Should you provide a selection such that C++20 conformant features are available distinct from draft standards?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d606e0aa-36fd-97f2-6e65-af0f9b05b24c
* Version Independent ID: 207d361a-397e-d687-8828-a152ebc4e572
* Content: [Microsoft C++ language conformance table](https://docs.microsoft.com/en-us/cpp/overview/visual-cpp-language-conformance?view=vs-2019)
* Content Source: [docs/overview/visual-cpp-language-conformance.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/overview/visual-cpp-language-conformance.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@NBlad 

The wording about "preview features" is used because features, functionality, and keywords might change during the standardization process. It has a different meaning here than a "preview release" of the compiler, which we don't recommend for use in production. Since the September 2020 draft C++ standard was voted on and adopted as the final ISO C++20 standard, it's not a moving target anymore. Completed features now conform to the final standard, not a draft preview, and won't change in the future.

The product team has previously announced that the **`/std:c++20`** option will be enabled when the C++20 language and library implementations are "feature complete." I don't know when that will happen, but I don't expect it for some months yet, since the option isn't in the 16.8 release currently in preview, and several features aren't done yet.

The C++20 features that are available now under **`/std:c++latest`** option are considered ready for use in production code by the product team, unless the release notes say otherwise, [You can check our documentation for the C++20 features implemented so far](https://docs.microsoft.com/cpp/overview/visual-cpp-language-conformance?view=vs-2019). The, **`/std:c++latest`** option doesn't expose any features planned for C++23 yet.

However, what our product team considers production ready and what you consider production ready may differ. If you prefer to wait for the **`/std:c++20`** option, there's nothing wrong with that. Many customers stick with a single version of the compiler toolset for a long time, and do extensive validation before adopting an update. That's why we provide long-term servicing releases. The longer you wait, the more bugs are likely to be found and fixed in the toolset. The downside is, you're missing out on new features for a while. Where to draw that line is different for different customers. I hope this helps with your decision making.
