### ISSUE TITLE
Targeting older Windows versions

### ISSUE THREAD

**Issue by awjanb** [MicrosoftDocs/cpp-docs#2566]
There already was an closed issue about targeting windows 7, but the "fix" is still completely unclear.

The current wording is unclear or plain wrong. It states: "The Windows 10 SDK supports writing code for Windows 7 SP1 and later". It used to state Windows 7 instead. How both can be true at the same time is anyone's guess. If one statement applies to a specific Win 10 SDK, and the other to a different version, please specify this. However, afaik, neither statement makes sense. To my knowledge, you can use any Windows 10 SDK to target any Windows version back to Vista, as long as you set WINVER etc correctly. This is corroborated by various discussions on Stack Overflow and similar sites where people ask just this.

Currently, this page is very conflicting to https://docs.microsoft.com/en-us/cpp/porting/modifying-winver-and-win32-winnt and https://docs.microsoft.com/en-us/windows/win32/WinProg/using-the-windows-headers. Please make sure the documentation is consistent, so developers can actually tell if they can or cannot deploy an app built with the Windows 10 SDK to Vista/7/whatever.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17a35bc2-4bae-9562-e954-d90324105997
* Version Independent ID: 6aeca9d8-d1d8-9026-918a-7ca47ac3dead
* Content: [How to: Use the Windows 10 SDK in a Windows Desktop application](https://docs.microsoft.com/en-us/cpp/windows/how-to-use-the-windows-10-sdk-in-a-windows-desktop-application?view=msvc-160)
* Content Source: [docs/windows/how-to-use-the-windows-10-sdk-in-a-windows-desktop-application.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/windows/how-to-use-the-windows-10-sdk-in-a-windows-desktop-application.md)
* Product: **visual-cpp**
* Technology: **cpp-windows**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@awjanb 

Sorry for the confusion. This article appears to reflect the current state of support, so I don't think it needs to change.

It appears that the confusion lies in what OS targets the *current* toolset and SDK supports, and the full set of OS targets that are listed in the headers. Both the [current Windows SDK](https://developer.microsoft.com/en-us/windows/downloads/windows-10-sdk/) and the current version of Visual Studio and the MSVC toolset support Windows 7 SP1 and later, as of this writing.

As versions of Windows go out of extended support, newer versions of the Windows SDK and Visual Studio no longer claim to support those older versions of Windows. Extended support only targets the last service pack of the specified OS. Windows 7 SP1 officially went out of extended support last January. It's likely that one of the next SDK revisions will only claim to support Windows 8.1 and later. If other articles say there's current support for something older than the list on the latest Windows SDK page, that means those articles haven't been updated. 

That's the story on official support. However, it's rare that something is actively changed in the Windows SDK to *prevent* code that you build with a later SDK from working in apps all the way back to Windows XP, as long as you only call APIs that were supported back then. Sometimes older SDK tools are dropped, or headers are changed in a way that's not compatible with the older MSVC toolset. Whether your app will still build and run on an old OS is a matter of which parts of the SDK have changed, and what's changed in your compiler toolset.

Like the Windows SDK, the current MSVC toolset (16.7 as of today is the latest version of the 142 toolset) doesn't officially support building code for OSes older than Windows 7 SP1. That's not saying your code *won't* work on older OSes, just that it's not supported. Once again, it's a matter of the OS APIs that the code generated by the current compiler relies on. The current compiler may have been updated to generate code that requires something in the OS that wasn't in XP, Vista, or Windows 7 before SP1.

What *is* supported in recent versions of Visual Studio, is using an older MSVC toolset. You can compile using an older toolset that *does* support older OS code. The [Update WINVER and _WIN32_WINNT](https://docs.microsoft.com/en-us/cpp/porting/modifying-winver-and-win32-winnt) article describes the preprocessor macros you use to target these older OSes. However, just because you *can* set those values in code compiled with the latest toolset, it doesn't mean that code will actually build or run.  You have to build with a toolset that supports the versions of the OS you want to target to be sure it will run. Visual Studio supports using older toolsets in the current version of VS. You just have to install the older toolset and the matching SDK. You can install toolsets back as far as 10.0, and the Windows 7.1 SDK, and target Windows XP or Windows Server 2003 if you like. For information, you can read [Configuring Programs for Windows XP](https://docs.microsoft.com/en-us/cpp/build/configuring-programs-for-windows-xp?view=msvc-160) and [Use native multi-targeting in Visual Studio to build old projects](https://docs.microsoft.com/en-us/cpp/porting/use-native-multi-targeting?view=msvc-160).

**Comment by awjanb** [comment]
Hi Colin,

thanks for the explanation. Even if you are technically correct, I tend to disagree. The same Windows SDK version that was still available when 7 was supported cannot suddenly not support Windows 7. Basically, the problem is that this article categorically states, that any Windows 10 SDK does not support Windows 7. Which is technically simply not true, it's only true in terms of lifetime support etc. If you are a new developer trying to find out if you can still target 7 (or 2008R2) at all when you use Windows 10 SDK (which, incidentally, you almost HAVE to if you want to use C++20 features to do compiler errors in older SDKs), this is very very misleading, as it states it as indisputable fact that it's not possible.

Would you consider rewording this: "The Windows 10 SDK supports writing code for Windows 7 SP1 and later" so that it states something like "The Windows 10 SDK supports writing code for any Windows version since Version 7 which still has active lifetimes support." At least that way people can tell there is a grey zone.

Also, a quick point about toolsets: I don't think your explanation for those is correct. Which toolsets I can/have to use isn't dictated by the OS at all, it's dictated by the availability of redistributables and whether I deploy them with my application. Of course, it's indirectly linked to OS because redistributables might not be available (funnily enough though, redistributables don't seem to list ANY OS restrictions).

**Comment by corob-msft** [comment]
The language we use doesn't appear to be helping. We're making an important distinction between what's *supported*, and what targets it's *possible to build for*. We use *supported* to mean Microsoft has tested this combination and verified that it works, and will provide support if you need it, for certain OS targets. This is not a statement about what targets it's *possible to build for*, which might include unsupported ones. We can't say that the current version of the SDK *supports* some older, out of support OS targets, because even if that works, it's *unsupported*. Microsoft makes no guarantees about it. You can't call Microsoft product support and expect to get help with issues relating to those targets. You *might* get help, but not as a matter of obligation.

The other common misapprehension about the Windows 10 SDK is that there is only one of them. Some of the earliest Windows 10 SDKs are themselves no longer supported. There have been a lot of them so far I've lost count, but I think more than ten. Our documentation describes the "current" one (10.0.19041.0) and its official level of support. (There's an even more recent version available in preview.) Sure, earlier versions of the Windows 10 SDK supported older OSes. The current one doesn't. The next one doesn't. When we say "The Windows 10 SDK" in the C++ docs, we mean the one that the latest version of the Visual Studio Installer will put on your machine by default. You can choose to include several older versions as optional components in your install. (There are five Windows 10 SDKs available in the current installer.) You'll need to do this to enable builds that target those recently out-of-support OSes. You can get even older SDKs if you need them, but you have to download them yourself from the MSDN Library site.

Not trying to be obtuse, here, but rather, exact. We've said what we mean about support. If we can clarify that, I'm open to suggestions. We can and do say it's possible to use certain toolsets and SDK combinations to target older OSes. Several of these toolsets are still in support for Visual Studio, even though the OSes they target are not. For example, you can use the VS 2019 installer to install the v141_xp toolset, and build for Windows XP. (It does say it's deprecated, but it's still available.) 

The redistributables story is something else entirely. Currently, there's one and only one in regular support (it covers VS 2015 through VS 2019), and a couple more in extended support. Several older ones are also available for download. The current one works on all OSes targeted by all binaries built by a v140 or later toolset. That includes some OSes that are out of support. I guess support is a matter of which product is being supported.

**Comment by awjanb** [comment]
Hi Colin,

thanks for taking time to respond in such detail. As you might have surmised from my last post, I did/do understand now that support in this case simply means support in terms of "we are giving you support" and not "this is possible". The basic problem is that this is the only doc page which explicitly talks about which SDK can be used to create applications for which target system.

I'd suggest simply avoiding mentioning the specific cut-off version. As you mentioned yourself, you have to update this document everytime a Windows version EOL support ends. Not to mention you are not specifically addressing the Server versions. Instead, simply stating that the SDK supports writing code for all supported Windows versions might be a better option. It saves you from updating it and it doesn't confuse anyone simply wanting to check technical compatibility (instead of official support).

**Comment by awjanb** [comment]
While I have you here anyways ;) Could you please confirm that the SDK supports creating application for Server 2012 and R2. As mentioned earlier, the docs rarely mention Server version at all. I think it's generally assumed that people know which Server version related to which Windows version. I'm specifically asking because this page lists "supported operating systems" and does not list 2012 or R2 as fully supported. But maybe that is only meant to say that you cannot use the SDK to build on a machine with this OS. Again, a bit confusing.
