### ISSUE TITLE
alignment rule

### ISSUE THREAD

**Issue by Cyan4973** [MicrosoftDocs/cpp-docs#2581]
The "Alignment" documentation of Microsoft Visual Studio states that :

> By default, the compiler aligns class and struct members on their size value: (...) long long, double, and long double on 8-byte boundaries.

The documentation doesn't explains if this is valid for `win64` and/or `win32`.
It's certainly valid for `win64`. But what about `win32` ?

Asking because, on `win32`, the default allocator `malloc()` returns memory areas aligned on **4**-bytes boundaries. Yet, if at the same time `long long` and `double` require alignment on 8-byte boundaries, this seems to violate one of the contract conditions of `malloc()` : 

> If allocation succeeds, returns a pointer that is suitably aligned for __any__ object type with fundamental alignment.

(source : https://en.cppreference.com/w/c/memory/malloc)

I'm receiving contradictory statements about the situation of alignment of `long long` on `win32`. What is it exactly ?
Could the documentation better mention if it's applicable for `win64`, `win32` or both ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c7ada89-39df-87fc-1b38-ee2f68529796
* Version Independent ID: 40bd6b1a-43b4-e8b4-9040-6333e6c49b6f
* Content: [Alignment](https://docs.microsoft.com/en-us/cpp/cpp/alignment-cpp-declarations?view=msvc-160)
* Content Source: [docs/cpp/alignment-cpp-declarations.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/cpp/alignment-cpp-declarations.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@Cyan4973 
Thanks for the report. The documentation applies regardless of the platform architecture. Your confusion is probably based on the fact that this statement,
> on win32, the default allocator `malloc()` returns memory areas aligned on **4**-bytes boundaries.

is incorrect. We specify the alignment for both 32-bit and 64-bit platforms in the [`malloc`](https://docs.microsoft.com/cpp/c-runtime-library/reference/malloc?view=msvc-160) documentation as being on 8-byte and 16-byte boundaries, respectively. I couldn't find any instances where these values are specified otherwise in the C++ docs. 

The alignment of allocations on the heap is independent of alignment of automatics on the stack, but both should always be suitably aligned for fundamental types. You may need to overalign memory for heap instances of larger SSE/AVX types.

I'm not seeing any work to be done here, so I'm closing the issue. If you don't agree, I'm open to further discussion.

**Comment by Cyan4973** [comment]
Thanks for the clear answer @corob-msft .
This confirms `long long` alignment of 64-bit on `win32`.

I'm receiving reports from `win32` users that `malloc()` returns memory areas aligned on 4-bytes boundaries, not 8,
but maybe these reports are incorrect in some ways.
So I will try to gather more elements on this topic.

Regards
