### ISSUE TITLE
CString methods reference

### ISSUE THREAD

**Issue by PaltryProgrammer** [MicrosoftDocs/cpp-docs#2583]
I am unable to locate the web page which lists the CString class methods
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b95afb3-52a8-384a-0f56-0ca891273f49
* Version Independent ID: 028dbc17-1b01-d64d-3f90-598e85a5bc2b
* Content: [Using CString](https://docs.microsoft.com/en-us/cpp/atl-mfc-shared/using-cstring?view=msvc-160)
* Content Source: [docs/atl-mfc-shared/using-cstring.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/atl-mfc-shared/using-cstring.md)
* Product: **visual-cpp**
* Technology: **cpp-mfc**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by corob-msft** [comment]
@PaltryProgrammer 
I'm sorry you're having trouble finding the documentation you're looking for. There's no page listing `CString` methods, because `CString` is one of several **`typedef`** aliases for specialized template types based on `CStringT`. You program using `CString`, but the underlying type and member functions are documented in [`CStringT` Class](https://docs.microsoft.com/cpp/atl-mfc-shared/reference/cstringt-class?view=msvc-160). It's explained in the first few sentences of this article.
