### ISSUE TITLE
Terme confusion in "Exceptions versus assertions"

### ISSUE THREAD

**Issue by Tudyx** [MicrosoftDocs/cpp-docs#2595]
[Enter feedback here]
In "Exceptions versus assertions" paragraph, shouldn't be "logical error" instead of "run-time error" in the phrase "Exceptions and asserts are two distinct mechanisms for detecting run-time errors in a program" ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 808812eb-d44a-e405-70ed-4d15ed9be975
* Version Independent ID: a3144c13-db26-9dbc-30d8-ae6ca52457af
* Content: [Modern C++ best practices for exceptions and error handling](https://docs.microsoft.com/en-us/cpp/cpp/errors-and-exception-handling-modern-cpp?view=msvc-160)
* Content Source: [docs/cpp/errors-and-exception-handling-modern-cpp.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/cpp/errors-and-exception-handling-modern-cpp.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@Tudyx 

Thanks for the question. The use of "run-time error" here distinguishes both exceptions and assertions from "compile-time errors." A logic error means something is wrong with your code, something you can usually discover with an assert. As explained later in the paragraph, an exception usually isn't a logic error. Exceptions can handle cases where your code is perfectly fine, but something outside the expected execution flow happened. The exception handler gives you a chance to fix it and try again. You can't really do that with a logic error.

Since the article seems okay to me, I'm going to leave it.
