### ISSUE TITLE
This Code doesnt even Build Can you please post the correct Code............

### ISSUE THREAD

**Issue by RobertChilewskiGit** [MicrosoftDocs/cpp-docs#2597]
[Enter feedback here]
This Code doesnt build............... wow like wow!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eda99bc7-483b-e53c-1035-886f4d0955f4
* Version Independent ID: a6fdba4d-53e4-9f1a-2352-bc68ef491069
* Content: [Walkthrough: Create a traditional Windows Desktop application (C++)](https://docs.microsoft.com/en-us/cpp/windows/walkthrough-creating-windows-desktop-applications-cpp?view=msvc-160&viewFallbackFrom=vs-2019)
* Content Source: [docs/windows/walkthrough-creating-windows-desktop-applications-cpp.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/windows/walkthrough-creating-windows-desktop-applications-cpp.md)
* Product: **visual-cpp**
* Technology: **cpp-windows**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@RobertChilewskiGit 

I'm sorry you're having trouble. I just followed the article's instructions in Visual Studio 2019 version 16.8, and the code from the complete listing at the end of the article both builds and runs fine. If it's not working for you, it might be due to any number of causes. Common ones include not having the C++ workload option installed, missing the Windows SDK, and typos or omissions in the source code file, This isn't a support forum, but we do have places you can ask questions, such as our [C++ Docs Q&A](https://docs.microsoft.com/answers/topics/c++.html) site. If another attempt doesn't work, give the forum a try. Good luck!

**Comment by RobertChilewskiGit** [comment]
Trying to close Cleanup some of this stuff thanks!
