### ISSUE TITLE
Understanding where and how settings are stored

### ISSUE THREAD

**Issue by rkhoury** [MicrosoftDocs/cpp-docs#2633]
Hello!

Many thanks for these docs.  What I was looking for (and am finding it very hard to find) was where these properties are stored, and what XML tag is associated with the setting.  It would be nice to have this information coupled to the content of this page somehow (unless it's already presented in another page with all relevant context).

Many thanks again.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 69b82557-4a26-70f9-c7ae-ca21c91318ec
* Version Independent ID: d93c9b26-7bde-7186-0d27-b37ade129b3c
* Content: [Advanced Property Page (Project)](https://docs.microsoft.com/en-us/cpp/build/reference/advanced-property-page?view=msvc-160)
* Content Source: [docs/build/reference/advanced-property-page.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/reference/advanced-property-page.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@rkhoury 

We document the content of [Property Page XML rule files](https://docs.microsoft.com/en-us/cpp/build/reference/property-page-xml-files?view=msvc-160) generally, but we don't list them specifically. Few people who come to this page are looking for that information. We also don't want to encourage editing those files, since there are few easier ways to completely munge your VS build system in a potentially hard-to-diagnose way. You might need to reinstall VS to fix it.

To answer your question, a quick search of the Property pages rule file directory indicates the Advanced properties are controlled by the *`%VSINSTALLDIR%MSBuild\Microsoft\VC\<version>\<locale>\general_advanced.xml`* file. 

The way these properties are transformed to be recorded in your [solution and project files](https://docs.microsoft.com/en-us/cpp/build/reference/project-and-solution-files?view=msvc-160) can be complicated. Some properties are straightforward, and just set a corresponding tag value in your [*`.vcxproj`* file](https://docs.microsoft.com/en-us/cpp/build/reference/vcxproj-file-structure?view=msvc-160) directly. Others take a more convoluted route, and may set or modify a constellation of values. You may have to read a bunch of  imported *`.targets`* and *`.props`* files to follow all of the XML rules that transform your Property Pages UI input into the values stored in your project file or elsewhere. How that works in a general way is documented at a relatively advanced level in the various pages linked from [MSBuild on the command line - C++](https://docs.microsoft.com/en-us/cpp/build/msbuild-visual-cpp?view=msvc-160) and [MSBuild reference for C++ projects](https://docs.microsoft.com/en-us/cpp/build/reference/msbuild-reference-cpp?view=msvc-160). 

I appreciate your suggestion and the reason for it. However, I'm disinclined to add the information you requested for the reasons given above - it's potentially hazardous in inexperienced hands. Thanks!
