### ISSUE TITLE
strcpy_s cannot return the documented value

### ISSUE THREAD

**Issue by plangevin** [MicrosoftDocs/cpp-docs#2639]
The documentation clearly explains the possible return value of strcpy_s (EINVAL and ERANGE).  It is also the case for strcat_s and other string manipulation routines.

But after many tests, there seems to be no way that strcpy_s return these error codes when parameter validation fails.  It either succeed or exit the application (With code 0xc0000417).

In debug, it pops a dlg with error description with the option to "Abort", "Retry" or "Ignore".  Retry allows me to debug the application but either abort and ignore will make the application exits with code 0xc0000417.  In release, application always exits with code 0xc0000417.

I understand that using _set_invalid_parameter_handler or _set_thread_local_invalid_parameter_handler allows me to change some validation behavior but in most cases, using this method is somewhat dangerous in a large application.

So the issue here would be that because the native behavior of strcpy_s cannot return when validation fails, the return value description should be removed. It should also be clear that by default, strcpy_s exits the application when parameters are not valid.

I think that the return values (ERANGE and EINVAL) should be a "good practice" for those who uses custom parameter handlers.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d50b132-e9c1-1242-946e-7d04b68bc83b
* Version Independent ID: baf557db-7d11-c7cb-d696-e9e55f991fcf
* Content: [strcpy_s, wcscpy_s, _mbscpy_s, _mbscpy_s_l](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/strcpy-s-wcscpy-s-mbscpy-s?f1url=%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(STRING%252Fstrcpy_s);k(strcpy_s);k(SolutionItemsProject);k(DevLang-C%252B%252B);k(TargetOS-Windows)%26rd%3Dtrue&view=msvc-160)
* Content Source: [docs/c-runtime-library/reference/strcpy-s-wcscpy-s-mbscpy-s.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/c-runtime-library/reference/strcpy-s-wcscpy-s-mbscpy-s.md)
* Product: **visual-cpp**
* Technology: **cpp-ucrt**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by corob-msft** [comment]
@plangevin 

By default, *all* UCRT functions call the invalid parameter handler when a validation check fails. The UCRT checks for a thread-local default handler, then a global default handler, and then falls back to calling the `_invoke_watson` handler. Once `_invoke_watson` is called, there's no way to continue execution. The Ignore or Continue options on the first chance exception handler (the one that lets you invoke the debugger) are treated as other names for Abort. Yes, it's confusing; contrary to expectations, these buttons are not how you continue execution for invalid parameters (though they do work for assertions). If the `__fastfail` intrinsic is available, your app exits with FAST_FAIL_INVALID_ARG, which I think is reported as 0xC0000409 with a parameter of 5. Otherwise, it exits with error `STATUS_INVALID_CRUNTIME_PARAMETER` (0xC0000417). Basically, the only way to continue execution is if you set your own invalid parameter handler, and write it to continue execution on validation faults. In that case, you'll get the error values returned as described. That's why the **Return values** section is written the way it is, with the boilerplate about "If execution is allowed to continue" before listing the error return values.
