### ISSUE TITLE
Possibly incorrect C28125

### ISSUE THREAD

**Issue by pedro-w** [MicrosoftDocs/cpp-docs#2660]
Visual Studio 16.8.3 gave me this warning for `InitializeCriticalSection`. However the documentation for that page does not mention that it needs to be in a try..except block, unlike the cited example `ProbeForRead` which clearly does.
Should the documentation for `InitializeCriticalSection` be modified or is this a false alarm?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5d2b1c0c-5ebe-91bf-0e5a-f5c4d0fb24a6
* Version Independent ID: 5cff5cec-9e6b-161f-36c1-6a6130b61ee0
* Content: [C28125](https://docs.microsoft.com/en-us/cpp/code-quality/c28125?f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(C28125)%26rd%3Dtrue&view=msvc-160)
* Content Source: [docs/code-quality/c28125.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/code-quality/c28125.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@pedro-w 

Function declarations that include the SAL `_Maybe_raises_SEH_exception_` annotation cause warning C28125, and `InitializeCriticalSection` has it. It's because it can raise a `STATUS_NO_MEMORY` exception in Windows XP and Windows Server 2003, [according to the docs](https://docs.microsoft.com/windows/win32/api/synchapi/nf-synchapi-initializecriticalsection). However, the docs also say it always succeeds on Vista or later. So, depending on your target platform, it may or may not require a try-except wrapper. Conditionally ignore or disable the warning at your discretion, if your code only targets Vista or later.
 
Since the `InitializeCriticalSection` docs are reasonably clear about the exception conditions, I'm disinclined to submit a PR to the Windows docs team. Likewise, the listed functions in [C28125](https://docs.microsoft.com/cpp/code-quality/c28125) aren't intended to be exhaustive. As you found, other functions may cause the warning.
