### ISSUE TITLE
I get this warning when using smart pointers but the documentation doesn't mention them

### ISSUE THREAD

**Issue by Mikejo5000** [MicrosoftDocs/cpp-docs#2662]
Moved issue to C++
Old issue: [https://github.com/MicrosoftDocs/visualstudio-docs/issues/2393](https://github.com/MicrosoftDocs/visualstudio-docs/issues/2393), opened by @jscarrott

I have a weakPtr bar, and a function foo that takes bar and locks it returning a sharedPtr or throws an exception if the weakPtr is expired. I then call a function baz on that sharedPtr all in one line. 
A bit like this foo(bar)-&gt;baz()
This gives a C26486 warning.
I solved it by returning a const r-value reference from foo, which makes sense as foo is checked to return a valid pointer and it is qualified that it never changes. Still, it would have been nice for the documentation to point me in the right direction with the new lifetime checker warnings.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 643028e2-07c7-b058-2aea-25f26cd0028e
* Version Independent ID: 5432439c-27d2-88ca-f81a-27d0bf938ac2
* Content: [C26486](https://docs.microsoft.com/en-us/cpp/code-quality/C26486?view=msvc-160)
* Content Source: [docs/code-quality/c26486.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/code-quality/c26486.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @kylereedmsft
* Microsoft Alias: **kylereed**

**Comment by corob-msft** [comment]
@Mikejo5000 Thanks, Mike!

**Comment by Thieum** [comment]
I would appreciate more examples too! I have a case where this warning pops, and even after reading [the associated document](https://github.com/isocpp/CppCoreGuidelines/blob/master/docs/Lifetime.pdf), it's not obvious how I can fix this warning: 

    SpectroModels ToValue(std::wstring_view value) noexcept
    {
        if (value == L"PPO") // C26486
        {
            return SpectroModels::PPO;
        }

        if (value == L"Specim") // C26486
        {
            return SpectroModels::Specim;
        }

        return SpectroModels::None;
    }
    
From what I can tell of the associated document, string_view may be a edge case that is not fully supported (de facto vs de jure note) , but it is not clear if the warning is relevant in my specific case, or if it can be discarded.

**Comment by corob-msft** [comment]
@Thieum 
The issue with a `string_view` is that it doesn't own the `string` it's a view into, so it could be invalidated while you hold a copy of the caller's `string_view` in your function. If you know that can't happen, it's safe to ignore or disable the warning. If you can't prove it's impossible, then you may want to change `ToValue` to take a `wstring` or `wstring&` instead of a `wstring_view`, and construct the `wstring` from the `wstring_view` before you make the call, suitably wrapped in a check for allocation failure, of course.

**Comment by Thieum** [comment]
@corob-msft I see! Thanks for the info, I'm not sure how to transfer this information in the warning description, or if it's worth it, but your answer was really helpful!

**Comment by kylereedmsft** [comment]
While it’s true that string_view doesn't own the memory, it’s assumed for the sake of analysis that function parameters are not invalidated during the duration of the call. To assume otherwise would mean that any parameter passed by reference could possibly be invalidated which would not be useful.

This looks like a false positive in the analysis. I don’t see any case where the string_view is being used outside of its valid lifetime. My hunch is something is wrong with the operator== call simulation in the analysis. Please file a bug on Developer Community so the C++ static analysis team can take a look.

**Comment by TimShererWithAquent** [comment]
We're closing this based on author input.
