### ISSUE TITLE
Lack of information and example for ODBC use.

### ISSUE THREAD

**Issue by bob4gd** [MicrosoftDocs/cpp-docs#2667]
[Enter feedback here]
Poor documentation due to lack of examples of how to use the connection to ODBC, specifically, when the ODBC is defines as a system's DSN.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e7a77292-eca7-75d7-f6e5-e43f6708ebb1
* Version Independent ID: 85d4825d-4957-cfb6-7ea2-0cfbcbec632e
* Content: [Connecting to a Data Source](https://docs.microsoft.com/en-us/cpp/data/odbc/connecting-to-a-data-source?view=msvc-160)
* Content Source: [docs/data/odbc/connecting-to-a-data-source.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/data/odbc/connecting-to-a-data-source.md)
* Product: **visual-cpp**
* Technology: **cpp-data**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@bob4gd 

I'm sorry you're having trouble finding what you need. Example snippets are interspersed through some of the MFC ODBC reference, such as the [CDatabase class](https://docs.microsoft.com/cpp/mfc/reference/cdatabase-class) documentation. The ODBC content in the C++ documentation is specifically about the MFC wrapper classes for ODBC, with some complete example ODBC apps found in our [sample code archive](https://github.com/Microsoft/VCSamples/tree/master/VC2012Samples/ODBC%20Database%20sample). If you want to access ODBC without the MFC wrappers, there's more information available in the [SQL ODBC reference](https://docs.microsoft.com/sql/odbc/reference/odbc-programmer-s-reference?view=sql-server-ver15), which goes into more detail about the underlying ODBC APIs. You may also have some luck searching for specifics on [StackOverflow](https://stackoverflow.com/).

Your request is otherwise both too broad and too specific to address. I apologize that we don't have the resources to expand on the existing MFC ODBC documentation, so I have to close the issue.
