### ISSUE TITLE
Project files are source files

### ISSUE THREAD

**Issue by rondarz** [MicrosoftDocs/cpp-docs#2691]
I object to the recommendation to edit the *.proj files in the UX. Not only does working with the UX make the file unmaintainable over time (mostly because of duplications per configuration/platform), I consider the project files as source code -- the developer should understand every line, duplications between projects should be shared via props and target files, etc. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 825f837e-aced-b5bd-719e-af3e5199c3c0
* Version Independent ID: 7663ace3-0f28-5eb1-6fd8-0fa9c10da834
* Content: [.vcxproj and .props file structure](https://docs.microsoft.com/en-us/cpp/build/reference/vcxproj-file-structure?view=msvc-160)
* Content Source: [docs/build/reference/vcxproj-file-structure.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/reference/vcxproj-file-structure.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@rondarz 
It would take a very generous reading of this article to suggest we recommend manual editing of .vcxproj files. In fact, we specifically recommend you *don't* edit these files. Paragraphs two, three, and four are all about why you shouldn't edit them, and alternatives to editing them, including the use of props and targets files. Basically, this article exists to keep the people who were ignoring this advice from getting in even bigger trouble. As for whether to edit .vcxproj files in the Visual Studio editor, there's no reason not to, other than it being a pain to unload and reload the project. It's a fully capable XML editor. 
I feel the article captures our recommendation intent, so I'm closing this issue.

**Comment by rondarz** [comment]
Somehow the work *not* did not make it into my comment. What I'm saying is that you *should* be telling people to edit the files, not to let the UX manage them. These files are source code -- just as important as the code you write. In fact, you've gone to great lengths in .NET 5.0 to make the C# project files editable in the UX, readable and maintainable.

**Comment by corob-msft** [comment]
@rondarz 
Ah, that makes more sense as an issue. Unfortunately, it's not really a doc issue, at least, not to begin with. 
The problem here is that the design of the vcxproj files is overconstrained in comparison to normal MSBuild project files. The file format was created to have feature parity with the previous vcproj files, which required some extensions. It uses a custom serializer to make the two-way interaction with the Property Pages UI work. Basically, it's brittle and easy to get wrong in ways that cause hard-to-diagnose problems. Right now, the default docs attitude is "don't touch it, you'll break it." The only way the recommendation about editing the file directly would change as you prefer is if the vcxproj file interaction with VS became much more robust. That's an engineering problem. And the way to push that kind of change is by making a [product feature request on Developer Community](https://developercommunity2.visualstudio.com/report?entry=suggestion&space=62&q=ssh2+keygen&sort=relevance). And it's not like that isn't already an engineering goal; it's just that there's a lot of legacy code involved. Anyway, I don't see any value in reopening the doc issue as long as the product has these constraints.
