### ISSUE TITLE
security concern on MFC language resource DLL

### ISSUE THREAD

**Issue by guliteb** [MicrosoftDocs/cpp-docs#2699]
Hi,
MFC is looking for a possible resource DLL from the same directory where the original .exe is located, named with ApplicationNameXXX.dll, where ApplicationName is the name of the .exe or .dll using MFC, and XXX is the three-letter code for the language of the resources. 

If MFC can find this it uses resources of the resource DLL instead of the original PE file. An attacker who could provide MFC exe along with a maliciously crafted resource-DLL, disguised as a language specific DLL for the exe. This would lead to arbitrary code execution.

Does Microsoft regard it as a security hole? OR if there is any method to disable the side loading of language specific DLL in MFC ?

Any comment is appreciated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 967ec961-edf3-c892-90ef-5d39506885b2
* Version Independent ID: 7bfc2dfb-a307-230c-c5d6-ade607dbddc4
* Content: [Localized Resources in MFC Applications: Satellite DLLs](https://docs.microsoft.com/en-us/cpp/build/localized-resources-in-mfc-applications-satellite-dlls?view=msvc-160&source=docs)
* Content Source: [docs/build/localized-resources-in-mfc-applications-satellite-dlls.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/localized-resources-in-mfc-applications-satellite-dlls.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@guliteb 

That's an interesting question. Resource-only localization DLLs normally don't contain any code. An attacker would need to successfully plant a DLL in the executable's directory, and that DLL would have to attempt a targeted buffer overrun with carefully created resources to cause arbitrary code execution - a non-trivial exercise. I recommend you ask the engineering team on [Developer Community](https://aka.ms/feedback/suggest?space=62) rather than here in the docs issues board. I'm closing the issue because your question doesn't seem like something this document is intended to address.
