### ISSUE TITLE
this function can throw an exception.  Possible exceptions should be documented.

### ISSUE THREAD

**Issue by JSilverst** [MicrosoftDocs/cpp-docs#2711]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd275428-7d38-81c5-fd17-da892b5b8679
* Version Independent ID: d5552132-e4e2-3f47-ddf1-e3c4dc9dbc6e
* Content: [fopen, _wfopen](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/fopen-wfopen?view=msvc-160)
* Content Source: [docs/c-runtime-library/reference/fopen-wfopen.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/c-runtime-library/reference/fopen-wfopen.md)
* Product: **visual-cpp**
* Technology: **cpp-ucrt**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by corob-msft** [comment]
@JSilverst 

That's an unexpected complaint. These C runtime library functions already document that they can invoke the invalid parameter handler, which can cause a debug break in debug code (which may be reported as an exception in Visual Studio), or force program termination in release code, but they can't throw a C++-style exception, because C doesn't support such exceptions. The implementation has an explicit `throw()` exception specification, which means that no calling code will ever see a thrown C++-style exception from these functions. Have you seen evidence to the contrary?

**Comment by JSilverst** [comment]
I reviewed the documentation, which presented a complicated scenario for handling invalid arguments.  My program, running in release mode, simply died because I had an upper case "w" in the call to fopen.  There was no warning or notification of any kind.   My program checks for failure to open a file, and a simple error return would have allowed normal handling and termination with a diagnostic notice, if necesssary.

 Note that the throw() is not on the fopen code but the common_fsopen and common_fopen_s code.  But users should not have to read through the source code to use standard library routines.

Perhaps the library documenation for each routine should specify exactly what kinds of errors could blow up programs.

I also have a problem with a program not simply returning an error code when invoked with invalid data, instead of making an exceptional exit, even when not throwing an exception.  But that is just my crusty opinion.

**Comment by corob-msft** [comment]
@JSilverst 

I'm afraid the resolution of your issue isn't going to be very satisfying. I'm going to close this issue, because based on your description, the behavior you've seen is precisely as described in the documentation. 

The parameters to library functions must satisfy certain preconditions. You're responsible for making sure the preconditions are met. If they aren't, then your program has a bug. The philosophy of the CRT is, it's better to terminate immediately rather than let buggy code continue to run, with unknown consequences. In the Microsoft implementation, CRT functions do this by calling the default invalid parameter handler function, which terminates the program. Your program can override this default behavior by substituting your own invalid parameter handler. If you do, you can implement a policy to let execution continue, in which case, the CRT routine will return with an error value set in `errno`, such as `EINVAL` or `ERANGE`, as documented, which you can test and handle as you like. Hundreds of functions in the CRT have this behavior, and they've all been described this way in the docs for decades. As you can imagine, there's no way to anticipate all the ways programmers can write buggy code, so we only mention ones that have come up so often they're practically cliche, such as buffer overruns.

One way to get ahead of these situations is to always make sure you compile cleanly at warning level **`/W4`**. The compiler diagnostics sometimes check CRT function parameters at this level, and might report an issue like yours before you even get as far as running your code. I don't know if the bug you reported is tested for specifically, but similar ones are.

Best of luck in your coding.
