### ISSUE TITLE
Missing change of link option /SUBSYSTEM:WINDOWS 

### ISSUE THREAD

**Issue by gnilsson2** [MicrosoftDocs/cpp-docs#2718]
For 
Microsoft Visual Studio Community 2019
Version 16.8.4

You need to change the link option to /SUBSYSTEM:WINDOWS 

Or did I make some mistake following the instruction ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eda99bc7-483b-e53c-1035-886f4d0955f4
* Version Independent ID: a6fdba4d-53e4-9f1a-2352-bc68ef491069
* Content: [Walkthrough: Create a traditional Windows Desktop application (C++)](https://docs.microsoft.com/en-us/cpp/windows/walkthrough-creating-windows-desktop-applications-cpp?view=msvc-160&viewFallbackFrom=vs-2019)
* Content Source: [docs/windows/walkthrough-creating-windows-desktop-applications-cpp.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/windows/walkthrough-creating-windows-desktop-applications-cpp.md)
* Product: **visual-cpp**
* Technology: **cpp-windows**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@gnilsson2 
Sorry the example gave you trouble. If you follow the instructions, the created project automatically sets **`/SUBSYSTEM:WINDOWS`** for you in the **Configuration Properties** > **Linker** > **System** section of the project property pages. You'd only need to set this property if you'd accidentally selected **Console application** in the **Windows Desktop Project** dialog, instead of **Desktop application**. It's easy to miss that step.
