### ISSUE TITLE
It would be better if the MultiplyWithTiling() is executed with dynamic values of tiles and dynamic sizes of the matrix.

### ISSUE THREAD

**Issue by emlalith** [MicrosoftDocs/cpp-docs#2720]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39be8c8d-f265-c724-c20d-d7e372aef2e9
* Version Independent ID: e4b0102e-aa17-0c3b-e9fc-f04c334e64e7
* Content: [Walkthrough: Matrix Multiplication](https://docs.microsoft.com/en-us/cpp/parallel/amp/walkthrough-matrix-multiplication?view=msvc-150)
* Content Source: [docs/parallel/amp/walkthrough-matrix-multiplication.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/parallel/amp/walkthrough-matrix-multiplication.md)
* Product: **visual-cpp**
* Technology: **cpp-parallel**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by corob-msft** [comment]
@emlalith 
Thanks for the suggestion. I'd never allow magic numbers in a code review for production code, for example, but sometimes our demonstration code takes shortcuts in the interest of brevity and clarity. That's why there's just some fixed input matrices and tile sizes in one monolithic function in the example. As the cliché goes, some things are left as an exercise for the reader.
