### ISSUE TITLE
Uninitialized pointer error incorrect reported.

### ISSUE THREAD

**Issue by wesleyolis** [MicrosoftDocs/cpp-docs#2729]
Incorrectly generates an error, this statement, will typically never get to executing the second or condition, if the first
or condition is to true. 

  Node* item = findItem(&n16, items[i]);

            if (item == NULL || item->value != items[i]) {
                break;
            }
            
            Or 
            
              if (item == NULL || item->value != 0) {
                break;
            }
            generates C4703

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 626d8085-2b49-d7a2-2aa4-0b31ab4d923d
* Version Independent ID: be6239f8-2f1b-5cd5-2ff9-fd374646e446
* Content: [Compiler Warning (level 4) C4703](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-4-c4703?f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(C4703)%26rd%3Dtrue&view=msvc-160)
* Content Source: [docs/error-messages/compiler-warnings/compiler-warning-level-4-c4703.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/error-messages/compiler-warnings/compiler-warning-level-4-c4703.md)
* Product: **visual-cpp**
* Technology: **cpp-diagnostics**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@wesleyolis 

Thanks for the report. This doesn't sound like a documentation issue, so I'm closing it. Warning 4703 isn't guaranteed to be correct. The compiler doesn't do an in-depth analysis of called functions as part of this analysis, which might be in a separate translation unit. It just makes a conservative assumption about data flow in the current function. Without seeing more, I can't be certain, but my guess is the warning arises because the compiler doesn't assume that `item` is guaranteed to be initialized by the call to `findItem`. 

If you know this code is fine, then you can disable the warning locally by using a [warning pragma](https://docs.microsoft.com/cpp/preprocessor/warning?view=msvc-160), or globally on the command line by using the [**`/wd`**](https://docs.microsoft.com/cpp/build/reference/compiler-option-warning-level?view=msvc-160) compiler option. (The link also includes directions for use in Visual Studio.) To disable it locally in your source code, use a `#pragma warning( push )` followed by a `#pragma warning( disable: 4703 )` before the function that causes the error. You can re-enable it after the function by using `#pragma warning( pop )`. You can disable the warning globally by adding **`/wd4703`** to your compiler command line options, or the equivalent in the Visual Studio Property Pages dialog.

If you think the compiler is doing the wrong thing entirely, then you can use **Help** > **Send Feedback** > **Report a Problem** within Visual Studio to create a bug report. Maybe it really is misbehaving. The product engineers read that feedback, and can respond directly. Best of luck.
