### ISSUE TITLE
Define module machine type and target machine type more clearly

### ISSUE THREAD

**Issue by ThomasBeckerStratasys** [MicrosoftDocs/cpp-docs#2733]
The error I see on my computer is "fatal error LNK1112: module machine type 'x64' conflicts with target machine type 'X86'".

Your description of the error does not make it clear which is the source and which is the destination. All I know is there is a mismatch somewhere, but don't know whether my library is not what I expected or my application.

I'm not sure if this is correct, but changing

"Similarly, if you create one module with the x64 compiler and another module with the x86 compiler, and try to link them, the linker will generate LNK1112."

to

"Similarly, if you create a library module with the x64 compiler and an executable module with the x86 compiler that uses the library and try to link them, the linker will generate "fatal error LNK1112: module machine type 'x64' conflicts with target machine type 'X86'"."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28b48e91-bcbc-7851-f30d-c625576354b2
* Version Independent ID: 5e017ad3-b859-c5e3-5cf4-41afe7f04ffe
* Content: [Linker Tools Error LNK1112](https://docs.microsoft.com/en-us/cpp/error-messages/tool-errors/linker-tools-error-lnk1112?view=msvc-160)
* Content Source: [docs/error-messages/tool-errors/linker-tools-error-lnk1112.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/error-messages/tool-errors/linker-tools-error-lnk1112.md)
* Product: **visual-cpp**
* Technology: **cpp-diagnostics**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@ThomasBeckerStratasys 
The target machine type refers to what's being built. (In Visual Studio, it's the platform type listed in the Solution Platforms dropdown in the toolbar.) The linker found that one of the modules you specified (which might be a LIB or OBJ file) was built for an architecture that's incompatible with your target machine.

Because you don't need to specify the target architecture to the linker, if you don't, it will assume you're trying to build something targeting the same machine type as the first object file it encounters (say, an x86 object). If it later encounters an object file that's built for a different machine type, but it's a type that allows the previous object type (say, an ARM64-x86 hybrid type), then the linker updates the target type to the more inclusive type, and keeps going. But when it tries to link in a later object file that's built for an incompatible machine type (say, x64), you'll get the LNK1112 error. That's why the sentence you've complained about is vague about linking modules. Both are inputs to your target executable or library, One of them matches the linker's target machine type, and one doesn't. The second one, whichever type it may be, is the one that triggers the error.

In your case, the target machine type has either been specified as x86, or set to x86 by the first encountered module, and then the linker found another object to link that was built for x64. That module caused the error. The way to interpret the error depends on your intent. Were you trying to build an x86 executable? Then the x64 module is a problem. Rebuild it for x86, if you can, or point your LIBRARY path to the x86 version's location. Were you trying to build for x64? Then your problem is either the target architecture you specified, or if you didn't specify one (which is the most common case, since normally you don't need to), the problem is the x86 module earlier on your link command line. In that case, you must find and change the x86 object file or library to an x64 version.
