### ISSUE TITLE
"Unix Makefiles" Generator is not supported

### ISSUE THREAD

**Issue by quang319** [MicrosoftDocs/cpp-docs#2738]
I'm using VS Studio 2019 Enterprise on Windows and I am editing the cmakesettings.json file. While trying to change the `generator` to `Unix Makefiles`, I am getting an error saying that is not supported and hovering over the `generator` field, I can confirm that this is not one of the options that are listed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 292b6ea2-afb0-8a77-7748-6d39286890ce
* Version Independent ID: 55816d6b-9600-c31c-01df-b53c2f185319
* Content: [Customize CMake build settings in Visual Studio](https://docs.microsoft.com/en-us/cpp/build/customize-cmake-settings?view=msvc-160#cmake-generator)
* Content Source: [docs/build/customize-cmake-settings.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/customize-cmake-settings.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@quang319 
I'm sorry you're having difficulty. Unlike your experience, I haven't had that trouble in a new CMake project in Visual Studio. I can see and set the **Unix Makefiles** choice under **Advanced** > **CMake generator** in the graphical CMake Settings editor. I'm running a typical install of Visual Studio 2019 version 16.8.3. It's relatively recent, but I think the Unix Makefiles generator option has been around for a long time. I don't know what could cause the behavior you're seeing.

Since this seems like it's a support issue and not a documentation issue, I'm going to close it. I can recommend several resources for help. One is the [C++ Forum on Microsoft Docs Q&A](https://docs.microsoft.com/en-us/answers/topics/c%2B%2B.html). Another is the C++ section of Visual Studio [Developer Community](https://aka.ms/vsfeedback/browsecpp). And you can also try your question on [Stack Overflow](https://stackoverflow.com/questions/tagged/visual-c++). Best of luck solving your issue.
