### ISSUE TITLE
delete return line, no error.

### ISSUE THREAD

**Issue by a44281071** [MicrosoftDocs/cpp-docs#2742]
```

// This is ok for Visualstudio 2019, no error.
int main()
{
    PlayGames(); 
}

```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 679aa978-f344-f08f-3d01-6c6814c2020f
* Version Independent ID: 671d83cc-56b0-e4fe-7482-a60b6030cfd0
* Content: [Walkthrough: Building a Project (C++)](https://docs.microsoft.com/en-us/cpp/ide/walkthrough-building-a-project-cpp?view=msvc-160)
* Content Source: [docs/ide/walkthrough-building-a-project-cpp.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/ide/walkthrough-building-a-project-cpp.md)
* Product: **visual-cpp**
* Technology: **cpp-ide**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@a44281071 
Thanks for writing in. You're right, it's always been the case that you don't need a `return` statement in `main`. That's not really what the article is about, though. It's just using the `return` statement as a simple way to cause an error, so you can see how it's presented in Visual Studio. Since this doesn't appear to be a documentation issue, I'm closing it.
