### ISSUE TITLE
Question about how to using __pragma (section,xx) properly

### ISSUE THREAD

**Issue by lygstate** [MicrosoftDocs/cpp-docs#2744]
https://github.com/MicrosoftDocs/cpp-docs/blob/master/docs/preprocessor/section.md#L0-10

When I creating pull request at https://github.com/jerryscript-project/jerryscript/pull/4482
There is a question about how to using section pragma properly:
```
#define JERRYX_MSVC_DECL_SECTION_FUNCTION_POINTER(sec_name, func_name)    \
  __pragma (data_seg (push))                                              \
      __pragma (section (sec_name, read)) __declspec(allocate (sec_name)) \
          JERRYX_MSCV_EXTERN_C jerryx_msvc_section_function_t             \
              func_name##_section = func_name;                            \
  __pragma (data_seg (pop))                                               \
      __pragma (JERRYX_MSVC_INCLUDE_SYM (func_name##_section))
```
vs

```
#define JERRYX_MSVC_DECL_SECTION_FUNCTION_POINTER(sec_name, func_name)    \
      __pragma (section (sec_name, read)) __declspec(allocate (sec_name)) \
          JERRYX_MSCV_EXTERN_C jerryx_msvc_section_function_t             \
              func_name##_section = func_name;                            \
      __pragma (JERRYX_MSVC_INCLUDE_SYM (func_name##_section))
```
Which is the correct?
Do we need  __pragma (data_seg (push))    __pragma (data_seg (pop)) pair?

**Comment by corob-msft** [comment]
@lygstate 
That's a good question. The compiler doesn't seem to behave the same as the description in the [data_seg pragma](https://docs.microsoft.com/cpp/preprocessor/data-seg?view=msvc-160) documentation. The `push` and `pop` parameters to `data_seg` don't appear to have any useful effect, and data definitions all go in the default data segment unless prefixed by a `__declspec(allocate)` specifier. I've sent a question to the dev team to see if I can find out more.

**Comment by corob-msft** [comment]
@lygstate 
I was misreading the docs, and they do in fact behave as described. As a result, I'm closing the issue.

In your macro, you don't need the `__pragma (data_seg (push))` and `__pragma (data_seg (pop))`, because you don't change the current `data_seg` section inside the push-pop pair.

By itself, declaring a section name by using `__pragma (section (sec_name, read))` doesn't place later data in that section. The currently active `data_seg` is unchanged by this pragma. Since you use `__declspec(allocate (sec_name))` explicitly on your data declaration, it also doesn't affect the current `data_seg` value. The current data section stays the same throughout.

If instead your macro changed the current `data_seg` value by using something like `__pragma( data_seg( sec_name )`, you could allocate data in `sec_name` without using the explicit `__declspec(allocate (sec_name))` in front, but you would need the `__pragma (data_seg (push))` and `__pragma (data_seg (pop))` operations to save and restore the default section name.

I hope this clears things up. Best of luck.
