### ISSUE TITLE
Conversion from System::String to CString

### ISSUE THREAD

**Issue by AlexKubiesa** [MicrosoftDocs/cpp-docs#2746]
I just wanted to mention that the conversion from wide character System::String to multibyte CString is dependent on the current thread's locale. For example, having `Thread::CurrentCulture` equal to something more uncommon like `en-DE` means that strings including certain characters (the degree symbol, micro symbol, superscript two, superscript three) don't stay the same after a round trip from CString to System::String back to CString. This is because the strings are (perhaps wrongly) converted to UTF-8 and then reinterpreted as multibyte ANSI.

I was badly caught out by this recently and I think it would be worth including this information on the page to prevent others from suffering the same.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd575689-da23-4f4e-3d7c-63ce6ba63a31
* Version Independent ID: 8656c596-5e50-4b20-c828-849aec8ac28e
* Content: [How to: Convert Between Various String Types](https://docs.microsoft.com/en-us/cpp/text/how-to-convert-between-various-string-types?view=msvc-160)
* Content Source: [docs/text/how-to-convert-between-various-string-types.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/text/how-to-convert-between-various-string-types.md)
* Product: **visual-cpp**
* Technology: **cpp-windows**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
@AlexKubiesa , thank you very much for calling that out. I'll add that information. Appreciate you helping other people who will use this page.

**Comment by TylerMSFT** [comment]
@StephanTLavavej, can you look at the repro I sent you for this.

**Comment by TylerMSFT** [comment]
@AlexKubiesa, I talked to an engineer for this area and he relayed the following info to me, which I'll summarize here:

When dealing with narrow strings ("C"-style strings) and wide strings ("Unicode" strings), legacy C and Windows apps use a concept of *code pages* rather than Unicode encodings. .NET strings are UTF-16, but ATL's `CStringA` is a narrow string, and the conversion from wide to narrow is performed by the [WideCharToMultiByte]( https://docs.microsoft.com/windows/win32/api/stringapiset/nf-stringapiset-widechartomultibyte) Win32 function. When converting a C-style CHAR* (important: a C-style CHAR* is a .NET byte*) to a string, the opposite Win32 function [MultiByteToWideChar]( https://docs.microsoft.com/windows/win32/api/stringapiset/nf-stringapiset-multibytetowidechar) is called.

Per the documentation, both functions rely on the Windows concept of a code page, not the .NET concept of a culture. To change the system code page, use the Region setting (Control Panel > Region > Administrative Tab > Change system local).

On an en-US version of Windows, the code page defaults to 1033 [en-US]. If you install a different language of Windows, you'll get a different code page here. Or you can change it after the fact using this control panel.

However, there's a mismatch in the way that `CStringA` performs wide to narrow conversion and the way that `gcnew string(CHAR*)` performs narrow to wide conversion.

`CStringA` passes **`CP_THREAD_ACP`** ("use the current thread code page") to the narrowing conversion method, but `string.ctor(sbyte*)` passes **`CP_ACP`** ("use the current system code page") to the widening conversion method. I suspect that on your machine, the system and thread code pages are out of sync, causing round-trip data corruption, though I don't know what would cause this.

There's a constant definition you can include in your C program to get it to use **`CP_ACP`** (like .NET) instead of **`CP_THREAD_ACP`**. Maybe setting that in your .vcxproj would solve the problem? For more information, see [this article](https://social.msdn.microsoft.com/Forums/vstudio/en-US/f3820781-c418-40bf-8c4f-7250001e5b68/visual-studio-2015-update-1-implicit-string-narrow-wide-conversion-and)

Another thing you might try is pinvoke the Windows API `GetThreadLocale` and form the returned `LCID` create a `CultureInfo` object, and then use `CultureInfo.TextInfo` to get the code page you can use in the conversion.

I hope this is of some assistance.

**Comment by AlexKubiesa** [comment]
@TylerMSFT thanks for the info, that mostly tallies with my understanding but also included some things I wasn't aware of.

The issue is not so much my computer, but rather the computers of my application's users. I am developing/maintaining a C++/CLI MFC application and certain users do have a different region setting from their system locale (e.g. an English system with "English (Germany)" region setting).

Thanks very much for the article you linked - I think I will try defining the `_CONVERSION_DONT_USE_THREAD_LOCALE` flag mentioned there, because I am looking for a fix that won't require me to rewrite lots of existing code, and will stop future developers from shooting themselves in the foot, because it's very easy to forget about narrowing conversions when the conversion from `System::String^` to MFC `CString` happens implicitly.

**Comment by AlexKubiesa** [comment]
Unfortunately, setting `_CONVERSION_DONT_USE_THREAD_LOCALE` didn't work for me, because we're dynamically linking against MFC, and mfc.dll doesn't have the constant defined.

Is there a version of mfc.dll where `_CONVERSION_DONT_USE_THREAD_LOCALE` is defined?

**Comment by TylerMSFT** [comment]
That's an interesting question, but you're probably asking in the wrong place. For product questions like this, I'd recommend the [Visual Studio C++ Developer Community site](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdevelopercommunity.visualstudio.com%2Fspaces%2F62%2Findex.html&data=04%7C01%7CTyler.Whitney%40microsoft.com%7Cd3cffc989f794cfd0f6408d87a01fb1a%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637393496212049983%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=cFCBgl37zPHZW3TXmQVorAl6wSSuOWS5B%2BSMKftbH%2BY%3D&reserved=0).

**Comment by AlexKubiesa** [comment]
Thanks Tyler, I have asked the question there now.
