### ISSUE TITLE
Can only create native activity app up to API level 7.1

### ISSUE THREAD

**Issue by Paulm-Unity** [MicrosoftDocs/cpp-docs#2753]
When creating native activity app in Visual Studio it doesn't allow setting target API level to anything higher than 7.1

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b965be6-8dfd-db91-84e3-345e70d7c302
* Version Independent ID: 291bf1e4-c8f7-12e9-3f38-f54bbd822bc7
* Content: [Create an Android Native Activity App](https://docs.microsoft.com/en-us/cpp/cross-platform/create-an-android-native-activity-app?view=msvc-160)
* Content Source: [docs/cross-platform/create-an-android-native-activity-app.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/cross-platform/create-an-android-native-activity-app.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@Paulm-Unity 
Thanks for reporting the issue. This seems like an installation issue, as I've created native activity apps targeting API level 25. Have you checked the API packages enabled in the SDK Manager? Other than suggesting you see if there's a more recent version of the NDK and other tools available through the Visual Studio Installer, I don't have a ready solution for you. We don't usually provide product support through the docs issues board. Your question is more likely to get answered on the [Developer Community](https://aka.ms/vsfeedback/browsecpp) site, where the dev team looks for issues. If we're informed of a solution we can add to the docs, we'll address it. Until then, I'm closing the issue here.

**Comment by Paulm-Unity** [comment]
API Level 25 is for Android 7.1
Visual studio is not allowing to target any API levels above 25, that is the issue I am referring to.
For example I can not target API level 29, which is Android 10.

**Comment by corob-msft** [comment]
I understand what you're saying. The properties that define the Android targets (or at least, the friendly names) only go up to API level 25 in Visual Studio 2019 16.2 and later (so far). You could define your own, I think, You could add a project properties file, or edit the *`Android.Tools.Props`* file (after backing it up, of course) in *`%VSInstallDir%MSBuild\Microsoft\MDD\Android\V150\`* to update the various properties to point to later SDK/NDK locations and add more friendly names. I set the paths in **Tools > Options > Cross Platform > C++ > Android** to the SDK and NDK locations that get installed by the Google SDK Manager, but apparently that wasn't enough, and I don't have time to track it down further.

To get an update for Visual Studio so you don't have to roll your own props file update, I'd recommend asking for one on [Developer Community](https://aka.ms/vsfeedback/browsecpp). Best of luck.
