### ISSUE TITLE
Long == Int64?

### ISSUE THREAD

**Issue by jamotaylor** [MicrosoftDocs/cpp-docs#280]
I thought that a long was Int64 - in which case the max value for long should be 9,223,372,036,854,775,807

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 262486b8-5d80-2c0b-f2eb-40c86aaf6a61
* Version Independent ID: 26b45954-2bcc-263f-7522-0c72941141bb
* Content: [Integer Limits](https://docs.microsoft.com/en-gb/cpp/cpp/integer-limits)
* Content Source: [docs/cpp/integer-limits.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/cpp/integer-limits.md)
* Product: **visual-cpp**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by corob-msft** [comment]
In MSVC, both `long` and `int` are 32-bits types. I know that isn't true of all C++ implementations, but that's because it's something the standard leaves up to implementers. If you need a 64-bit integer, `long long` is that size in MSVC, or you can use one of the portable definitions from \<cstdint>, such as `int64_t`.
