### ISSUE TITLE
Difference between /DYNAMICBASE and /HIGHENTROPYVA is unclear

### ISSUE THREAD

**Issue by DrakeCoker** [MicrosoftDocs/cpp-docs#282]
The description of this option and /HIGHENTROPYVA are very similar.  The distinction between them could use a little more verbage.  From the doc, I can't tell what it is.  From experimentation, it seems like both are required to have a discernible effect.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c025efd8-f221-3ef4-f0a0-c5917ae8714c
* Version Independent ID: 68c46f87-c1b8-2648-e0b8-0377452b7e88
* Content: [-DYNAMICBASE](https://docs.microsoft.com/en-us/cpp/build/reference/dynamicbase)
* Content Source: [docs/build/reference/dynamicbase.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/reference/dynamicbase.md)
* Product: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
Thanks for taking the time to suggest an improvement. It's not really the point of the document to explain ASLR in depth, but it probably ought to at least explain what it is in a sentence or two, and why we do it by default. /HIGHENTROPYVA is a little bit better, but still doesn't explain the basics. 

If you look at the popular books on Windows programming, they sometimes mention the benefits of virtual address layout optimization, so the linker doesn't have to rebase DLLs when your app is loaded. The problem is, this made it easy for attackers to guess the location of specific functions that they could use via a stack overwrite to compromise your app and then the machine. /DYNAMICBASE basically throws VA layout optimization out the window, to load DLLs at random-ish virtual addresses specifically to thwart this kind of attack. The /HIGHENTROPYVA switch is an additional option to /DYNAMICBASE that can be set for 64-bit apps, to take advantage of the far larger 64-bit address space for randomizing the virtual addresses that DLLs get loaded at. 

I'll add a task to my backlog to add this info to the docs, for people with questions like yours.

**Comment by DrakeCoker** [comment]
Hi Colin,

Thanks for the detailed response!  Just a little background in case it is helpful.

I’m a compiler author.  One of our customers needed a patch and, after receiving it, started getting errors on Windows 10 that hadn’t been seen before.  Only on Windows 10 and only with the patched runtime system (our compiler is half native and half interpretive).  After much debugging, it turned out there was a long-standing DWORD / QWORD confusion that had been benign up until that point.  We fixed it, but were still confused as to why the error had never been seen before. 

After digging around, I discovered that turning HIGHENTROPYVA off “fixed” the problem (i.e. avoided it).  This made sense.  But then examining the released runtime vs. the patched runtime showed that the difference was actually DYNAMICBASE was off on the released version but on in the patched version.  This sent me running to read about DYNAMICBASE, and I couldn’t really see how it varied from HIGHENTROPYVA from the documentation.  Hence my request to you.  I understand the ASLR concept, but not how these two options differ.  From your response, it sounds like HIGHENTROPYVA is 64-bit only while DYNAMICBASE is either 32 or 64.  This makes sense as jumping to 64-bit addresses can expose some dormant bugs (just like mine).

By the way, the mystery turned out to be that the released runtime was digitally signed while the patched runtime was not.  Apparently the signing tool strips or fails to propagate the DYNAMICBASE setting!  Sounds like I have a potential bug to report to them too.  

Cheers,
Drake

**Comment by corob-msft** [comment]
Interesting. You shouldn't be able to set the HIGHENTROPYVA flag without the DYNAMICBASE flag in the PE header. That ought to trigger a loader error, unless I miss my guess. However, there's probably nothing stopping you from setting the flags that way in a DLL header yourself, which might lead to the issues you saw. The linker should complain, at least, if the /HIGHENTROPYVA option does not enable the /DYNAMICBASE option automatically by default. Perhaps this is how to describe the relationship of the linker options: /DYNAMICBASE enables ASLR for 32-bit or 64-bit apps. /HIGHENTROPYVA is an extra option for /DYNAMICBASE that expands the VA space used for ASLR on 64-bit apps. 

In hindsight, perhaps there should only have been a /DYNAMICBASE linker option, with an optional :HIGHENTROPYVA argument.

**Comment by DrakeCoker** [comment]
Yea, interesting.  We just were using defaults, which seems to be both on.  The signing tool strips out DYNAMICBASE but leaves HIGHENTROPYVA untouched.

I imagine evolution explains why they are two separate options, especially if DYNAMICBASE is an on/off bit somewhere (haven’t checked myself).

Thanks again

**Comment by corob-msft** [comment]
I was curious and asked around, and got the word from the people who work on the Windows Loader that it's okay for an image to have the /HIGHENTROPYVA flag set and not the /DYNAMICBASE flag. It should not cause an error, but the resulting image will not have ASLR enabled. Likewise, from the linker guys, I learned that /HIGHENTROPYVA only requires /LARGEADDRESSAWARE, not /DYNAMICBASE. So if your app got errors at runtime, this combination of flags should not have been at fault.

Whether your app signing tool is broken or not is beyond the scope of the docs here; I'd recommend bringing that up in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/) forums.  I'll still work on clarifying what we say about these linker options, though, because that's a legitimate gripe.

**Comment by DrakeCoker** [comment]
Thanks for the update Colin.  Your discoveries are consistent with the behavior we observed.

Further research here found that the signing tool intentionally turns off DYNAMICBASE as that causes problems with one of the products in our portfolio, unrelated to the products I’m involved with.

Cheers

**Comment by corob-msft** [comment]
Updates are live.

**Comment by DrakeCoker** [comment]
The changes read well to me.  Nice job.
