### ISSUE TITLE
Add class from typelib for MFC class is removed?

### ISSUE THREAD

**Issue by gast128** [MicrosoftDocs/cpp-docs#3001]
see https://docs.microsoft.com/en-us/cpp/mfc/reference/add-class-from-typelib-wizard?view=msvc-160

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 57a63ad9-deda-1d5b-3baf-c99c01f1f1c6
* Version Independent ID: c8b71ab6-df66-dee0-25b1-34ce0bb0cab4
* Content: [Automation Clients: Using Type Libraries](https://docs.microsoft.com/en-us/cpp/mfc/automation-clients-using-type-libraries?view=msvc-160)
* Content Source: [docs/mfc/automation-clients-using-type-libraries.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/mfc/automation-clients-using-type-libraries.md)
* Product: **visual-cpp**
* Technology: **cpp-mfc**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by corob-msft** [comment]
@gast128 
Unfortunately, this documentation is out of date. It doesn't reflect the fact that the various class wizard templates were deprecated and removed sometime during the Visual Studio 2017 timeframe. We need to make that announcement more prominent in a few articles, including this one.

I know it doesn't help solve your problem, but you can add your voice to the complaints about the missing wizard by taking this [survey](https://www.surveymonkey.com/r/QDWKKCN).

Since there's no way to complete this particular task using a template in Visual Studio 2019, you'll have to do it manually. Fortunately, it's not hard, just tedious. Derive a class from [`COleDispatchDriver`](https://docs.microsoft.com/cpp/mfc/reference/coledispatchdriver-class?view=msvc-160) and fill in the methods using [`InvokeHelper`](https://docs.microsoft.com/cpp/mfc/reference/coledispatchdriver-class?view=msvc-160#invokehelper) calls for each ordinal. (If you have a copy of VS 2015, the wizards are still available there. If you have a lot of headers to generate, it might be worth installing 2015 to create them.) 

```cpp
// CHelp2.h - wrapper for Help2 interface from vshelp80.tlb

#import "C:\\Program Files (x86)\\Common Files\\Microsoft Shared\\MSEnv\\\\vshelp80.olb" no_namespace

class CHelp2 : public COleDispatchDriver
{
public:
    CHelp2() {} // Calls COleDispatchDriver default constructor
    CHelp2(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
    CHelp2(const CHelp2& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

    // Attributes
public:

    // Operations
public:

    // Help2 methods
public:
    void Contents()
    {
        InvokeHelper(0x1, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
    }
    void Index()
    {
        InvokeHelper(0x2, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
    }
 // . . . Other methods go here . . .
    void InitializeSettingsToken(LPCTSTR bstrSettingsToken)
    {
        static BYTE parms[] = VTS_BSTR;
        InvokeHelper(0x21, DISPATCH_METHOD, VT_EMPTY, NULL, parms, bstrSettingsToken);
    }

    // Help2 properties
public:

};
```

**Comment by gast128** [comment]
Thx. Somehow the other link where the removal from VS2019 was announced has disappeared from my post. I have an older wizard generated Excel wrapper file which I have to safeguard then for the rest of my life.
