### ISSUE TITLE
CSimpleStringT::GetString() is an undocumented public member that undermines performance

### ISSUE THREAD

**Issue by johndog** [MicrosoftDocs/cpp-docs#3031]
This is both a doc issue and a design feedback issue.

Referring to [CSimpleStringT::GetString()](https://github.com/MicrosoftDocs/cpp-docs/blob/master/docs/atl-mfc-shared/reference/csimplestringt-class.md#-csimplestringtgetstring).

This page only documents the const version of the function.  If this is all you read, you'd think it was safe to use the GetString() function everywhere, to get the const string.  In fact, there is _also_ a non-const version of the function, which will fork the shared buffer (if indeed it is shared), returning a non-const string, and it is also public.  That's the version of the function you get if you call the same function on a non-const object.  
The design doesn't seem right:  these are overloads with different semantics.  The overloads should have had different names; the const version should have been available as a synonym to operator LPCXSTR(), so that there is a functional alternative to the cast.  The const version of the _intended_ semantic probably should have used  const_cast (presume it is safe to do so) to call the non-const instance, so that the buffer is always forked if necessary, to offer the same guarantee that no other instance will change the buffer returned by GetString().

The documentation problem is at least as serious, it misleads as to the presumed fundamental purpose of the GetString() function (making sure the buffer you have is unique to your instance)

**Comment by mwinterb** [comment]
I saw this issue title and started panicking as my codebase does call GetString everywhere so I went to see that for myself... but I'm not seeing in atlsimpstr.h or cstringt.h where the non-const overload of GetString is defined. And Intellisense and debugger step into are both only showing the const overload even when the object is non-const. I manually searched through these versions:
14.28.29333 <-- 16.8.5
14.28.29910 <-- 16.9.5
14.29.30037 <-- 16.10
14.29.30129 <-- 16.11 Preview 1

Intellisense and debugger was only checked with 16.10. Since you have a microsoft.com email address, are you looking at an in-development version? Or possibly a private fork where someone wanted to just call GetString() instead of the zero-parameter version of GetBuffer()? Or on what line and version of atlsimpstr.h is it defined?

**Comment by corob-msft** [comment]
@johndog 
As @mwinterb notes, there's no non-const `GetString` in `CSimpleStringT` I can find. In fact, the only non-const `GetString` member functions I can see anywhere in the code base are an unrelated pure virtual entry in `IFilterChunkValue` and its implementations in `CFilterChunkValueImpl` and `CMFCFilterChunkValueImpl`. I'm closing the issue as not-repro for now. If you can point to the header that contains the offending member function, I'll reopen the issue.

**Comment by johndog** [comment]
Okay, that's a relief.  It didn't occur to me to look at other versions of the file.  

The version of atlsimpstr.h I was looking at (and compiling with) is at C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\VC\Tools\MSVC\14.28.29515\atlmfc\include\atlsimpstr.h.  

This is the non-const implementation:

```
	PXSTR GetString()
	{
		CStringData* pData = GetData();
		if( pData->IsShared() )
		{
			Fork( pData->nDataLength );
		}

		return( m_pszData );
	}
```

According to About, I have 16.9 Preview 1 installed.  If your comments are accurate, it must no longer be there.  Was this change there temporarily?

**Comment by johndog** [comment]
I found this was caused by an errant local update to the atlsimpstr.h header (GetBuffer() was replaced with GetString() during a refactor), so this is a non-issue, appropriately closed.  

Sorry for the distraction...
