### ISSUE TITLE
/GT required for thread_local variables used in coroutines

### ISSUE THREAD

**Issue by PeterWilliamNorth** [MicrosoftDocs/cpp-docs#3035]
**this option is required for coroutines**
This option should be emphasized for coroutines.;cppreference sample @ https://en.cppreference.com/w/cpp/language/coroutines
_thread_local int g_i{1};
task resuming_on_new_thread(std::jthread& out) {
  std::cout <<g_i++<< "Coroutine started on thread: " << std::this_thread::get_id() << '\n';
  co_await switch_to_new_thread(out);
  // awaiter destroyed here
  std::cout <<g_i++<< "Coroutine resumed on thread: " << std::this_thread::get_id() << '\n';
}_
returns **incorrectly** (the thread_local **g_i** on thread 5308 refers to the same thread_local as on thread 3860) without /GT, 
_1Coroutine started on thread: 3860
New thread ID: 5308
2Coroutine resumed on thread: 5308_
and **correctly** with /GT. two separate **g_i** variables are used, one per thread, (but /GT triples the number of CPU cycles)
_1Coroutine started on thread: 12828
New thread ID: 3036
1Coroutine resumed on thread: 3036_
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c978b45-b19a-cba2-3142-9ef1a00d308c
* Version Independent ID: ac45f3ed-01ea-64fd-b0a9-54c62885cabf
* Content: [/GT (Support fiber-safe thread-local storage)](https://docs.microsoft.com/en-us/cpp/build/reference/gt-support-fiber-safe-thread-local-storage?view=msvc-160)
* Content Source: [docs/build/reference/gt-support-fiber-safe-thread-local-storage.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/reference/gt-support-fiber-safe-thread-local-storage.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@PeterWilliamNorth 

Thanks for the report. I'm assured by Gor Nishanov, author of some of the coroutines support in MSVC and Clang, that /GT is not required unless you're doing things that would also require /GT in the absence of coroutines. In his lightly edited words:

> /GT is not needed for C++ coroutines, since the compiler is aware of where the suspend points are and does not cache the thread locals across them. /GT is needed for fibers, since there a thread switch can happen during any function call. If the compiler incorrectly caches the thread_local in a C++20 coroutine, a bug should be filed to fix the compiler. I know at some point Clang was caching thread-id and was reporting the same thread even after the resumption on a different thread. I am not aware of such bugs in MSVC.

If you think you've found a compiler bug, we'd appreciate it if you'd file it on [Developer Community](https://aka.ms/vsfeedback/browsecpp). [We have instructions here](https://docs.microsoft.com/cpp/overview/how-to-report-a-problem-with-the-visual-cpp-toolset). Since this issue doesn't look like a documentation issue, I'm closing it.
