### ISSUE TITLE
Show the Values of EXIT_SUCCESS and EXIT_FAILURE

### ISSUE THREAD

**Issue by txwizard** [MicrosoftDocs/cpp-docs#305]
While I know it's documented in the CRT header files, this page would be more useful if it showed their values. While I can understand why you might be reluctant to do so, since these are baked into the CRT headers (stdlib.h), probably haven't changed in 40 years, and are unlikely to ever change, I think a case can be made for showing them here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 576e8433-e1a3-b18a-b728-9d52aec5d61b
* Version Independent ID: ea6e9d1f-7403-9975-5575-a3860edc1495
* Content: [EXIT_SUCCESS, EXIT_FAILURE](https://docs.microsoft.com/en-us/cpp/c-runtime-library/exit-success-exit-failure)
* Content Source: [docs/c-runtime-library/exit-success-exit-failure.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/c-runtime-library/exit-success-exit-failure.md)
* Product: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
Thanks for the suggestion. I'm curious though, why would you ever care what the values are? If you consistently use the manifest constants as parameters and as comparators, you never need to know their actual values. And while it's true that these values aren't likely to change, when we put manifest constants' values in the docs, that's just another point of failure and confusion if they ever do get updated. I just changed a few values in another one of the global constants topics for precisely that reason. For example, MB_LEN_MAX is now 5, not 2 as previously documented, probably due to the maximum length of a multibyte UTF-8 character being much longer than the maximum length of Shift-JIS or Big5 multibyte characters.

**Comment by corob-msft** [comment]
Rather than put these definitions in the docs, I recommend the use of the F12 key in the VS IDE to answer these kinds of questions. Closing.

**Comment by matthew45052** [comment]
EXIT_SUCCESS should never change.  In shell scripting, an exit code of 0 from an executable is success (and non-zero is failure).  It's been this way for as long as I know on both Unix and Windows.  Changing it would break way too many programs.
