### ISSUE TITLE
Integer Limits Wrong

### ISSUE THREAD

**Issue by Tatruonghoang** [MicrosoftDocs/cpp-docs#3063]
Dear Microsoft Team,
I view your site about [Integer Limits] but i see LONG_MAX value is same INT_MAX.
I think LONG_MAX will bigger than INT_MAX.
This site have some value of type interger and long is same. I think it is an error in your documents.
Please review and fix it if it is an error. If it is not error, please send me detail information why LONG_MAX value is same INT_MAX.
My English gramma is a little bad but i think you can understand.

Best regard!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 262486b8-5d80-2c0b-f2eb-40c86aaf6a61
* Version Independent ID: 26b45954-2bcc-263f-7522-0c72941141bb
* Content: [Integer Limits](https://docs.microsoft.com/en-us/cpp/cpp/integer-limits?view=msvc-160)
* Content Source: [docs/cpp/integer-limits.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/cpp/integer-limits.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@Tatruonghoang 
In the Microsoft compiler, both **`int`** and **`long`** types are the same size: 32 bits, or 4 bytes. Since both **`int`** and **`long`** are the same size in the Microsoft implementation, that's why `LONG_MAX` and `INT_MAX` are the same. The C and C++ standards don't specify these sizes. The standards only specify the size relationships: **`long long`** >= **`long`** >= **`int`** >= **`short`**. The actual size of a type depends on the compiler. Compilers on other platforms may use a different size for the **`long`** type (often 64 bits). So, for portable code, avoid use of **`long`**. I'd use **`int`** for 32-bit quantities, and **`long long`** for 64-bit quantities. These types have the same sizes across all the major compilers for Windows, MacOS, and Linux.
