### ISSUE TITLE
vcpkg  do not install only download and after is done.

### ISSUE THREAD

**Issue by mastercomputer17** [MicrosoftDocs/cpp-docs#3067]
PS C:\DEV\vcpkg> .\bootstrap-vcpkg.bat
Downloading https://github.com/microsoft/vcpkg-tool/releases/download/2021-02-24-d67989bce1043b98092ac45996a8230a059a2d7e/vcpkg.exe -> C:\DEV\vcpkg/vcpkg.exe
Done.

PS C:\DEV\vcpkg>

**Comment by corob-msft** [comment]
@mastercomputer17 
I'm sorry you're having trouble. Unfortunately, this looks like a product support issue, rather than a documentation issue, so I'm going to close it. The best places to look for solutions to product questions are in the [Microsoft Docs Q&A forum for C++](https://docs.microsoft.com/en-us/answers/topics/c%2B%2B.html), or on the [Developer Community](https://aka.ms/vsfeedback/browsecpp) site. Best of luck.
