### ISSUE TITLE
Compilation Error on "Defined Pure Virtual Functions" example. 

### ISSUE THREAD

**Issue by bliepert** [MicrosoftDocs/cpp-docs#3072]
For the following code snippet:
```
class base
{
public:
    base() {}
    virtual ~base() = 0 {}; // pure virtual, and defined!
};

class derived : public base
{
public:
    derived() {}
    ~derived() {}
};

int main()
{
    derived aDerived; // destructor called when it goes out of scope
}
```
I get the error:
```
$ g++ test.cpp -o test -Wall -std=c++17
test.cpp:5:21: error: pure-specifier on function-definition
    5 |     virtual ~base() = 0 {}; // pure virtual, and defined!
      | 
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e6bca69d-cd65-193b-f62d-c20c8c69f7ad
* Version Independent ID: 1c8b8221-4c4f-93e5-6af6-ca460247a6d4
* Content: [Abstract classes (C++)](https://docs.microsoft.com/en-us/cpp/cpp/abstract-classes-cpp?view=msvc-160)
* Content Source: [docs/cpp/abstract-classes-cpp.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/cpp/abstract-classes-cpp.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@bliepert 
True enough. This section needs a **Microsoft-specific** marker, since it's a Microsoft extension that lets you define a pure virtual function this way. Microsoft, gcc, and Clang compilers all produce a linker error for the sample when the function is pure virtual but not defined. Clang implements, but warns on, the Microsoft extension that allows the definition.

**Comment by corob-msft** [comment]
An update should appear within a day.
