### ISSUE TITLE
CPU and GPU should be get executed after setting the Debugger Type to "Auto"

### ISSUE THREAD

**Issue by yanghhhhhhh** [MicrosoftDocs/cpp-docs#3082]
Based on the steps under "[Debugging the GPU Code](https://docs.microsoft.com/en-us/cpp/parallel/amp/walkthrough-debugging-a-cpp-amp-application?view=msvc-160#debugging-the-gpu-code)"

**Step7 need updated:**
On the menu bar, choose **Debug > Start Debugging**.  From 16.10 Preview2, behavior as below:

- The function “sum_kernel_tiled” get executed, but the line 30 cannot be catch.
- The GPU function get executed and the Line 67 and Line 70 should also get executed after setting the Debugger Type to "Auto". 

![Reprosteps](https://user-images.githubusercontent.com/69227520/114503632-35e62200-9c60-11eb-8cb1-06bdbad00dd7.gif)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec054a56-bc4a-198e-6fc1-8a9fbb78c2c2
* Version Independent ID: 0bb33ae4-3fb1-8683-b3c2-6773e3b20cfb
* Content: [Walkthrough: Debugging a C++ AMP application](https://docs.microsoft.com/en-us/cpp/parallel/amp/walkthrough-debugging-a-cpp-amp-application?view=msvc-160)
* Content Source: [docs/parallel/amp/walkthrough-debugging-a-cpp-amp-application.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/parallel/amp/walkthrough-debugging-a-cpp-amp-application.md)
* Product: **visual-cpp**
* Technology: **cpp-parallel**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by corob-msft** [comment]
@yanghhhhhhh 
I can't tell if the behavior you're seeing is intentional or not. It might be a bug. Since this is a preview release, we don't have updated documentation for it. For assistance with changed product behavior, I recommend checking the [Developer Community](https://developercommunity.visualstudio.com/search?space=62) site. If the documentation needs to be updated, the developers should let us know.
