### ISSUE TITLE
write a cpp or a python script to add a source file (.c) generated by the user

### ISSUE THREAD

**Issue by CppProgrammer23** [MicrosoftDocs/cpp-docs#3088]
Hi,
I have written a function in Cpp and when I invoked it, t will generated (create) a "c" file  but this "c" file isn't included in the vcxproj-filters file. so I want to write a script (or maybe add some lines of code in this function) so the "c" file will be added in to the vcxproj-filters. 
how is it possible?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e25f255e-d4d7-0c99-0efc-09dd85252a8b
* Version Independent ID: 471a514f-a4d3-d14f-d780-7b77f53c9675
* Content: [Vcxproj.filters files](https://docs.microsoft.com/en-us/cpp/build/reference/vcxproj-filters-files?view=msvc-160)
* Content Source: [docs/build/reference/vcxproj-filters-files.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/reference/vcxproj-filters-files.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@CppProgrammer23 
I'm not sure I understand your question. The default filter behavior already supports *`.c`* extensions, and the filter will put those files in the Source folder in VS. If you're asking how to add a newly generated source file to an existing project, that's a different question. I'm not sure how to do that while the project is loaded, though I'm sure it's possible, since VS can do it. If the project isn't loaded, you can add the new file to the *`.vcxproj`* file in the ItemGroup with the ClCompile entries as another entry.

This question seems more appropriate for [Microsoft Docs Q&A](https://docs.microsoft.com/en-us/answers/topics/c%2B%2B.html) or possibly [Developer Community](https://aka.ms/vsfeedback/browsecpp) than the Docs issues board, since it's not a question we'd address in this document. That's where I'd go for more support. Best of luck.
