### ISSUE TITLE
CHtmlEditCtrl documentation is unprecise

### ISSUE THREAD

**Issue by WowItsDoge** [MicrosoftDocs/cpp-docs#3093]
The [CHtmlEditCtrl](https://docs.microsoft.com/de-de/cpp/mfc/reference/chtmleditctrl-class?view=msvc-160) provides Web Browser functionality for MFC applications.

Can the documentation be specified, which browser is used technicaly?
Is it the old Internet Expolorer, or the new Edge (on Chromium basis)?

Thanks for your time!

**Comment by corob-msft** [comment]
@WowItsDoge 

Good question. I haven't heard from the product team about this, but I'd recommend you consider all the existing MFC HTML classes to be deprecated. I wouldn't recommend using the native MFC web controls unless you're rendering HTML 3 or possibly HTML 4. The best way to create modern web controls is through the WebView2 runtime interface. We have some content on [Getting started with WebView2](https://docs.microsoft.com/en-us/microsoft-edge/webview2/gettingstarted/win32) that you might find useful.

Speaking directly to your question, it's difficult to document the existing MFC HTML classes as corresponding to a particular browser. Technically, the web controls aren't loaded from an installed browser. The MFC classes instead use COM interfaces supplied by the Windows MSHTML.DLL and SHDOCVW.DLL system components. On a recent copy of Windows 10, the CHtmlView-loaded web browser control sends a user agent string that makes it look like Internet Explorer 7, with no JS support to speak of. Far too much code relies on these interfaces for them to go away, but the underlying technology may change in the future. That's why I'm hesitant to add anything about the technology in these docs - it relies on Windows components that are subject to change without notice, and aren't part of the MFC library. So, I'm closing the issue.

**Comment by WowItsDoge** [comment]
Thank you for your answer!
