### ISSUE TITLE
ABOUT THE DOCUMENTATION

### ISSUE THREAD

**Issue by SAINT-CHRIS** [MicrosoftDocs/cpp-docs#3111]
[is the C documentation an update of ANSI/ISO C17? ]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 139d8805-bfe6-1aa7-c24f-f31afab77b43
* Version Independent ID: ff72cf3f-2332-aa0b-1fad-0ce6bfaf30d3
* Content: [C Language Reference](https://docs.microsoft.com/en-us/cpp/c-language/c-language-reference?view=msvc-160)
* Content Source: [docs/c-language/c-language-reference.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/c-language/c-language-reference.md)
* Product: **visual-cpp**
* Technology: **cpp-c-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@SAINT-CHRIS 
I'm not sure I understand your question. The C language hasn't changed much since it was first standardized in 1989. Microsoft's implementation of ANSI C89 (also known as ISO C90) was reasonably faithful, but not perfectly compliant with the C89 standard. Some compiler switches could be used to make the compiler more or less conforming. Microsoft did not implement all the changes made in ISO C99, except for the ones required for C++ conformance. Now that ISO C17 has made some of those features optional, the compiler is closer to conforming, and additional work has been done to improve C11 and C17 conformance, as noted in [What's new for C++ in Visual Studio version 16.8](https://docs.microsoft.com/en-us/cpp/overview/what-s-new-for-visual-cpp-in-visual-studio?view=msvc-160#whats-new-for-c-in-visual-studio-version-168). The C documentation has been updated to reflect the current compiler's behavior. Most pages have had no updates, because the C features they describe haven't changed in decades. I hope that answers your question, but if not, feel free to clarify what you're looking for.
