### ISSUE TITLE
Behavior on system / cpu that does not support the enhanced instruction set

### ISSUE THREAD

**Issue by Thieum** [MicrosoftDocs/cpp-docs#3114]
It is not obvious from the article what is the behavior of a program that is compiled with a specific enhanced instruction set, on a system that does not support it. Does it
 - fallback to a version of the code that does not use the specific instructions ? (fat binary behavior)
 - fails with an illegal op exception or equivalent ?
 - enters undefined behavior territory ?

Does this behavior is the same across the different versions of the compiler ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba360ffb-9bd7-1f1d-59a6-2470e73b5e0f
* Version Independent ID: 9547430b-2596-7d71-89e0-fbbafe187160
* Content: [/arch (x86)](https://docs.microsoft.com/en-us/cpp/build/reference/arch-x86?view=msvc-160&source=docs)
* Content Source: [docs/build/reference/arch-x86.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/reference/arch-x86.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@Thieum 

Good question. The answer is implicit rather than spelled out in the docs. As the documentation puts it, "you should consult the documentation for a particular processor or test for instruction set extension support using `__cpuid` before executing code using an instruction set extension." In other words, the instruction set you ask for is the instruction set you get.

> Does it
> - fallback to a version of the code that does not use the specific instructions ? (fat binary behavior)

The compiler doesn't generate a processor check or create fallback code for you. That would lead to bigger, slower-loading executables, which is contrary to expectations, so we'd be explicit about it if that were the case. Take our silence to mean "no."*

> - fails with an illegal op exception or equivalent ?
> - enters undefined behavior territory ?

If you run your app on a processor that doesn't support opcodes you've used, you should expect invalid opcode processor traps. Like other processor traps, Windows catches these and raises a structured exception. If you catch the exception, you should terminate your app, rather than try to keep running by using code written to a simpler processor standard.

If you want to ship one binary that's got code for different levels of processors, that's totally doable, but you have to do it yourself. One good approach is to split your processor-specific code out into its own DLL. You can build copies of that DLL for all the architectures you want to support, install them all with your app, and then load the one built for the processor you find with `__cpuid` at runtime.

\* I've heard the CRT library might test at runtime for floating-point support, and use different code for certain math functions, depending on what it finds. I might also be wrong about this, since that behavior started back when x87 co-processors were a thing, and that hasn't been true for decades.

**Comment by Thieum** [comment]
@corob-msft Thanks a lot for all the info, it's a lot clearer now!
