### ISSUE TITLE
I'm puzzled: this looks exactly what I need for Xamarin iOS storyboard editing

### ISSUE THREAD

**Issue by petemidg32** [MicrosoftDocs/cpp-docs#3118]
Hi 
My Xamarin Forms project's iOS part has a launch screen in a storyboard, and since verson 16.9 I can no longer edit it.
It says 'use xcode'. I have no idea how to perform that operation in a proper manner.
Then I found this page. It looks exactly what I need (and everyone else using c# Xamarin Forms).
I am very keen that this could be made available to coders using c# not c++.
Please advise.
Thanks
Pete Midgley.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c83a717-6517-b6fc-a3fe-b0859d16c8f5
* Version Independent ID: 64096bcf-4469-fdb4-5e82-8dbac44a76f0
* Content: [Sync changes between Xcode and Visual Studio](https://docs.microsoft.com/en-us/cpp/cross-platform/sync-changes-between-xcode-and-visual-studio?view=msvc-160)
* Content Source: [docs/cross-platform/sync-changes-between-xcode-and-visual-studio.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/cross-platform/sync-changes-between-xcode-and-visual-studio.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@petemidg32 
I'm sorry to hear you're having trouble. The Visual Studio UI for syncing a C++ iOS project sends commands to a small Node.js server program installed on your Mac called [`vcremote`](https://www.npmjs.com/package/vcremote). This server applet has some specific knowledge of C++ projects and directories, so it can find and copy source and header files, and transmit debug information. I doubt that it can be used as-is to sync Xamarin app project files. My guess is that Xamarin has something similar, but since I don't know, I'm invoking my colleague @davidbritch to see if he knows of a solution.

**Comment by petemidg32** [comment]
Thanks for that Colin; I’ve seen and used some of David Britch’s stuff so have my own experience of his expertise!
Regards
Pete Midgley

**Comment by davidbritch** [comment]
@petemidg32 

The iOS designer was removed in 16.9 and so your only option is now to use the storyboard designer in Xcode, on a Mac, to update the storyboard.

**Comment by corob-msft** [comment]
@petemidg32 
Since this isn't really an issue for the C++ documentation, I'm closing it. For product issues and ideas, I recommend using the feedback tools built into the IDE. Your feedback goes to the development team that can make things happen. Best of luck!
