### ISSUE TITLE
NMAKE DOCS

### ISSUE THREAD

**Issue by runette** [MicrosoftDocs/cpp-docs#3122]
I have a serious question. How man yman hours did you dedicate to creating documentation that looks good enough to Project Managers but actually tells me nothing?

How can you have a commands section that does not list the commands?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0bb1aa3-a4ac-1bb5-f232-54eed4fca4c1
* Version Independent ID: da4631dd-bb32-73e7-83e6-7c1336a6c526
* Content: [Commands in a Makefile](https://docs.microsoft.com/en-us/cpp/build/reference/commands-in-a-makefile?view=msvc-160)
* Content Source: [docs/build/reference/commands-in-a-makefile.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/reference/commands-in-a-makefile.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@runette 

I appreciate that your expectations weren't met here. If you're looking for the nmake command-line *options*, you'll find them in the [NMAKE Options](https://docs.microsoft.com/en-us/cpp/build/reference/running-nmake?view=msvc-160#nmake-options) section of the [Running NMAKE](https://docs.microsoft.com/en-us/cpp/build/reference/running-nmake) article. I can see that the title of the article may not convey the content, since it really is mostly about the command-line options and return values.

Speaking of commands, that might represent some semantic confusion. When we talk about nmake *commands*, we mean the commands you can put in your makefile, which includes literally anything you can invoke from the command prompt. That's not only tough to enumerate, it's different for every machine. Presumably you'd have common ones for Visual Studio like cl.exe, csc.exe, or link.exe, but nmake is equally happy to invoke gcc.exe or clang.exe. Or notepad.exe, for that matter. If instead you're asking for a list of common build labels such as "clean", "debug", or "release", remember those labels are totally arbitrary and are defined by you in your makefile.

Taking your question about documentation development effort seriously, it's hard to say how long it took, since this content was written back in the '90s, if not earlier. It's only been touched to migrate it to new content systems since then. As nmake is not a tool in active development with changes that need updated docs, we've occasionally fixed doc bugs, but that's about it. Unfortunately, our time is limited, and we tend to spend it on new content or content with high traffic, and nmake doesn't qualify on either count.

**Comment by corob-msft** [comment]
@runette 

You may contact the [Microsoft data protection officer](https://docs.microsoft.com/compliance/regulatory/gdpr-data-protection-officer) by filling out the webform at [https://aka.ms/privacyresponse](https://aka.ms/privacyresponse). The first link has more details and additional contact options.

I apologize that our feedback procedure may have given you an expectation of privacy that wasn't delivered. At the bottom of every page in the C++ documentation, there's a Feedback section, with buttons for feedback on the product or on the current page. The "This page" button takes you to our public GitHub repository, where you can enter an issue in a pre-filled form. You must be logged into GitHub to create an issue. Just like any other GitHub issue in a public repo, the issue is public, and it's associated with your public GitHub profile. There's no way to create a private issue through this mechanism, or to send private messages on GitHub. The only exposure of your personally identifiable information is what you've chosen to make public through your GitHub profile. 

If you like, I can delete your issue. It won't appear with your profile information attached; it will only show that issue #3122 was deleted.

**Comment by runette** [comment]
@corob-msft 

Note that I DID NOT click on the facebook links or the github links. I filled in this form

<img width="213" alt="Screenshot 2021-05-07 at 09 05 07" src="https://user-images.githubusercontent.com/2239795/117418745-aefd3000-af13-11eb-9a6d-5c104878f1f2.png">

So you can see why I was very surprised to see this comment on GH.

Please delete this issue. It is a matter of principle.

**Comment by corob-msft** [comment]
@runette 

Only you will see this message, and only in the form of a notification mail from GitHub, if you have it enabled.

I'm also surprised by your report, to the point of considering it bizarre, if not impossible. I have not been able to reproduce the effect. The helpful page verbatim reporting has gone to a different database in the past. It doesn't track the same info that the page feedback control does, and it doesn't record your GitHub user name, just a session ID. That makes it difficult to believe it could generate a GitHub issue as if it came from you. There won't be any channel for follow-up, but I will investigate.
