### ISSUE TITLE
Please do tell what header file is included in what product. 

### ISSUE THREAD

**Issue by Utkarsh22Ahuja** [MicrosoftDocs/cpp-docs#3132]
Please do tell what header file is included in what product. For example I am not able to find fstream in Visual Studio. I found multiple articles that said it now included in CRT windows SDK package. The problem is "exactly what package is it in?" Please give this guide and products included in Visual Studio 2019 installer. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b80fe2cc-1eed-3dd3-245f-4cdab6c597aa
* Version Independent ID: 02b8a72c-8f5a-81d9-556f-7aac882f03ec
* Content: [&lt;fstream&gt;](https://docs.microsoft.com/en-us/cpp/standard-library/fstream?view=msvc-160)
* Content Source: [docs/standard-library/fstream.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/standard-library/fstream.md)
* Product: **visual-cpp**
* Technology: **cpp-standard-libraries**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by corob-msft** [comment]
@Utkarsh22Ahuja 

C++ support isn't installed by default when you [install Visual Studio](https://docs.microsoft.com/en-us/visualstudio/install/install-visual-studio?view=vs-2019). To [install C and C++ support in Visual Studio](https://docs.microsoft.com/en-us/cpp/build/vscpp-step-0-installation?view=msvc-160) you have to select one of the C++ workloads in Visual Studio Installer, such as **Desktop development with C++**. 

The `<fstream>` header is part of the C++ standard library (STL) that's automatically installed if you select a C++ workload in Visual Studio Installer. There's no way to install C++ support that doesn't also install these headers. There's no other component or package you need to get them. The same is true of the CRT headers. They live in the Windows SDK, but it's installed by default when you install C++ in Visual Studio.

If you're really curious about the individual components available in each edition of Visual Studio, that information is available [here](https://docs.microsoft.com/en-us/visualstudio/install/workload-and-component-ids?view=vs-2019). It's probably not much use unless you're an administrator trying to create a custom installation image for a lot of machines.

Since this isn't information that needs to be in any particular header document, I'm closing your issue.
