### ISSUE TITLE
More examples with dllexport (class, typedef, using)

### ISSUE THREAD

**Issue by Thieum** [MicrosoftDocs/cpp-docs#3150]
It would be nice to have more usage examples for dllexport, and its usage within a macro:

```
#define DllImport   __declspec( dllimport )
#define DllExport   __declspec( dllexport )

DllExport void func();
DllExport int i = 10;
DllImport int j;
DllExport int n;

class DllExport S
{
};

typedef DllExport T S;

using T = S DllExport; // ??? not so sure how to use dll export with using - that's the info I was looking for.

```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b536f720-0b84-9bb0-51a8-c58c653f10f1
* Version Independent ID: a778134d-f07c-0c55-694f-536f891b048b
* Content: [dllexport, dllimport](https://docs.microsoft.com/en-us/cpp/cpp/dllexport-dllimport?view=msvc-160&source=docs)
* Content Source: [docs/cpp/dllexport-dllimport.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/cpp/dllexport-dllimport.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@Thieum 

Perhaps we've not been clear enough about what it means for types to have `__declspec(something)` applied to them. The named type keeps that attribute, and you don't normally need to repeat it when you use the type name.

That's why your example doesn't quite make sense to me. What are you trying to do with the extra `DllExport` in your `typedef` and `using` examples? It seems redundant:

```cpp
#define DllImport   __declspec( dllimport )
#define DllExport   __declspec( dllexport )

class DllExport S
{
};

typedef S T1; // T1 is now a typedef for S, including its dllexport attribute

using T2 = S; // T2 is now an alias for S, including its dllexport attribute
```

There's no way I know of to create either a typedef or an alias that adds `__declspec(dllexport)` to a type that isn't itself declared that way, if that was your intent.

**Comment by Thieum** [comment]
@corob-msft aah it seems it was a useless tradition in our codebase to annotate the typedefs that way. I'm really unsure of where it comes from, and since it generates no warning, it's been kept that way. Thanks a lot for pointing this out, it will help us clean this up!
