### ISSUE TITLE
/experimental:module- not working in MSVC 14.29 (VS 2019 16.10)

### ISSUE THREAD

**Issue by go2sh** [MicrosoftDocs/cpp-docs#3166]
I have a problem with the MSVC 14.29 version from VS 2019 16.10. I can't disable module support by providing /experimental:module- with -std=c++latest. Is this option still supported with the c++20 updates in 14.29?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eafb784a-a44d-2615-c449-8e8883f73c9f
* Version Independent ID: c9921c34-8437-8988-98fb-28c1049ecfb6
* Content: [/experimental:module (Enable module support)](https://docs.microsoft.com/en-us/cpp/build/reference/experimental-module?view=msvc-160)
* Content Source: [docs/build/reference/experimental-module.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/reference/experimental-module.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@go2sh 
I'm not aware of such changes in the 14.29 toolset, but given that's the servicing release, it's not impossible. I recommend asking this question on the Visual Studio [C++ Developer Community](https://aka.ms/vsfeedback/browsecpp) board. Closing as a product question rather than a doc issue, though that could change depending on what you learn.
