### ISSUE TITLE
translation suggestion to zh-tw 

### ISSUE THREAD

**Issue by Yang09701194** [MicrosoftDocs/cpp-docs#3196]
I open issue for zh-tw to  `cpp-docs.zh-tw` repo 2 years ago, and I have a fork: https://github.com/Yang09701194/cpp-docs.zh-tw .  If I want to open `zh-tw cpp doc` issue now, where can I post?  Orginal repo seems not found now.

**Comment by corob-msft** [comment]
@Yang09701194 
I'm sorry, in April the localization repos were made private. There's no easy way to create an issue about a localization problem now. 

If you have a localization issue, you can report it here. If it's a problem in the English sources, we'll fix it. If it's a translation or formatting problem, we'll report it to the localization team so they can fix it. This problem seems like bad formatting from automatic translation, so I've created a bug report for the localization team. I'll resolve this issue when I hear back from them.

Note to self: tracking issue ceapex.visualstudio.com/CEINTL/_workitems/edit/440964
Mentioning @JasonCard for loc visibility.

**Comment by Yang09701194** [comment]
Thank you for the information, I really appreciate your help.

**Comment by JasonCard** [comment]
Hi @Yang09701194 
Thank you for your feedback and contribution. This is currently a common known issue from Machine Translation for Traditional Chinese (zh-tw). However, this issue has been put into backlog as non-critical formatting issue that would not be efficient to fix all individual instances. This formatting issue will be systematically resolved later this year once we migrate to a new localization system.

Hi @corob-msft 
Thank you for your help to escalate this issue to our team. Please go ahead to close this issue.

**Comment by Yang09701194** [comment]
Thank you for the reply and help.  I can close the issue.
