### ISSUE TITLE
when is this actually defined?

### ISSUE THREAD

**Issue by SwissFrank** [MicrosoftDocs/cpp-docs#3197]
I am getting warning C4013: "alignof" undefined.  Your page gives no suggestion as to when it would be undefined, except if language extensions have been disabled which I am not doing.

Also, forcing me to create an account, log in, type in a further emailed verification code is putting too many barriers in the way of me simply giving you valuable feedback.  It lessens my interest in bothering to do so in the future.  Given all the effort you're putting me through to improve your offering, what do I get out of it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e2bb3ebf-3916-1509-086d-091e938dd15b
* Version Independent ID: a1aad343-6b13-622e-0e7b-c80041455f2e
* Content: [alignof Operator](https://docs.microsoft.com/en-us/cpp/cpp/alignof-operator?view=msvc-160)
* Content Source: [docs/cpp/alignof-operator.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/cpp/alignof-operator.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@SwissFrank 

I'm sorry it's giving you trouble. Thanks for taking the time to register. You now have a GitHub account, which might be useful in other contexts, too.

The **`alignof`** keyword is available in all C++ **`/std`** modes, including the default. It's available in C as an alias for **`_Alignof`** under **`/std:c11`** and **`/std:c17`** if you have `#include <stdalign.h>` in your source code. (C didn't adopt the **`_Alignof`** keyword until C11. The **`__alignof`** form is available in the default C compiler as a Microsoft extension to C89. That's what might be turned off by **`/Za`**.) 

Generally speaking, keywords aren't defined anywhere, they're built into the parser. The error message indicates that the parser doesn't expect the **`alignof`** keyword to appear where you're using it, because it decided it was an identifier, not a keyword. That suggests to me you're compiling your code as C in the default mode.

So first, I'd verify that you're compiling as C++, if your code is in fact C++. Code compiled as C doesn't support the **`alignof`** keyword by default.

If you're compiling C, make sure you're using at least the **`/std:c11`** switch, and verify that you've included `<stdalign.h>` to define the **`alignof`** alias. And it would probably help to look at the [C documentation for alignment](https://docs.microsoft.com/en-us/cpp/c-language/alignment-c?view=msvc-160) instead of the C++ documentation.

In general, we don't provide troubleshooting for every possible way you can get an error in the docs, because it's not practical. I'm working on updates for the C11/C17 docs, and I'll include a link from the C++ docs for people who aren't getting the right documentation when they search.
