### ISSUE TITLE
Incorrect API doc for _swprintf 

### ISSUE THREAD

**Issue by NBorthwick** [MicrosoftDocs/cpp-docs#3199]
[Enter feedback here]
_swprintf does not take the arguments as listed here
int swprintf(
   wchar_t *buffer,
   size_t count,
   const wchar_t *format [,
   argument]...

Instead the actual definition is:
    _CRT_STDIO_INLINE int __CRTDECL _swprintf(
        _Pre_notnull_ _Always_(_Post_z_) wchar_t*       const _Buffer,
        _In_z_ _Printf_format_string_    wchar_t const* const _Format,
        ...)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a209539e-aeec-2bb4-5887-c4cf90467204
* Version Independent ID: ed0abe24-9562-5db6-29dc-c7ad7588081a
* Content: [sprintf, _sprintf_l, swprintf, _swprintf_l, __swprintf_l](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/sprintf-sprintf-l-swprintf-swprintf-l-swprintf-l?f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(STDIO%252Fsprintf);k(sprintf);k(DevLang-C%252B%252B);k(TargetOS-Windows)%26rd%3Dtrue&view=msvc-160)
* Content Source: [docs/c-runtime-library/reference/sprintf-sprintf-l-swprintf-swprintf-l-swprintf-l.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/c-runtime-library/reference/sprintf-sprintf-l-swprintf-swprintf-l-swprintf-l.md)
* Product: **visual-cpp**
* Technology: **cpp-ucrt**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
Hi @NBorthwick, You raise an issue with `_swprintf()` but use `swprintf()` as the example. So, I'm not sure I'm addressing exactly what you were trying to point out.

But here goes: in a .C file, the version of swprintf() used is `swprintf(wchar_t* buffer, size_t _bufferCount, wchar_t* format)` because, per the remarks in that topic, `swprintf` conforms to the ISO C standard which has `size_t count` as the second parameter. The other, non-standard version still exists: `swprintf(wchar_t* buffer, wchar_t* format)` To use that one you define `_CRT_NON_CONFORMING_SWPRINTFS` before including stdio.h

The topic documents the one conforming to the ICO C standard version, not the non-standard version.

Please reopen if I misunderstood what you were pointing out.
