### ISSUE TITLE
Is there docs about how to create and use DLL for Windows Universal?

### ISSUE THREAD

**Issue by moyanming** [MicrosoftDocs/cpp-docs#320]
Hi all,
I want to create Windows Universal APP for ARM platform. Is there docs about how to create the DLL used by C/C++ and reference this DLL by a Windows Universal APP? There are a large number of C/C++ code for Win32 and those code should can be used by UWP for ARM.

Best regards.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 08c574a2-cef0-ab13-7375-55851f966ef6
* Version Independent ID: fe3421c7-e9f4-4986-589f-fadaedce583e
* Content: [Walkthrough: Create and use your own Dynamic Link Library (C++)](https://docs.microsoft.com/en-us/cpp/build/walkthrough-creating-and-using-a-dynamic-link-library-cpp)
* Content Source: [docs/build/walkthrough-creating-and-using-a-dynamic-link-library-cpp.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/walkthrough-creating-and-using-a-dynamic-link-library-cpp.md)
* Product: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
Hi, @moyanming - 

I recommend you take a look at [How to: Use Existing C++ Code in a Universal Windows Platform App](https://docs.microsoft.com/en-us/cpp/porting/how-to-use-existing-cpp-code-in-a-universal-windows-platform-app) first, and see if that meets your needs for use of existing code. Compiling the code for ARM platforms is even easier: just choose ARM in your solution's build configuration. There are a few [common ARM migration issues you might run into](https://docs.microsoft.com/en-us/cpp/build/common-visual-cpp-arm-migration-issues), but most are easy to deal with. Picking up an ARM DLL in your ARM UWP app is as simple as adding a reference to the DLL in your app project. There's nothing special about the ARM build output, other than it needs to run on an ARM platform and link to ARM binaries. You can also recompile your existing UWP DLL code for ARM; just change the project configuration to generate ARM32 or ARM64 code. As long as it's already UWP-compatible and there isn't anything platform-specific in the code, such as inline assembly or intrinsics, it should work. If you don't see ARM options in the configuration drop-down, you may need to run the Visual Studio installer and choose the ARM toolsets and libraries in the Individual Components section first. [Ideally, you'd build your app to target all architectures all the time anyway](https://docs.microsoft.com/en-us/windows/uwp/packaging/device-architecture).

I'm closing this issue, since this looks like there are existing docs that meet your needs, even if they aren't exactly parallel to this one.

**Comment by moyanming** [comment]
Hi @corob-msft ,
Thank you for your recommendation. 
I have test that reference the DLL from a Visual C++ UWP project successfully, but I can't reference the DLL from a C# UWP project. It seems that there is no docs about Visual C++ Windows Universal templates. I found that there are several different templates within the Visual C++ Windows Universal, but I can't find docs about how to do with those templates.
For example:
1. How to create DLL for Windows Universal?
2. How to reference the DLL from a C# Windows Universal (or, C++ Windows Universal) project?
Because the Window Universal supports all the architectures: x86, x64 and ARM, so the DLL can be compiled by selected the different architecture.

**Comment by moyanming** [comment]
BTW, there is not enough docs about "[Universal Windows Apps (C++)](https://docs.microsoft.com/en-us/cpp/windows/universal-windows-apps-cpp)".
Why the template called "Windows Universal" but not "Universal Windows"?
![qq 20180703124639](https://user-images.githubusercontent.com/13234209/42199142-5beb0cb6-7ebf-11e8-94a4-7f5e28be51b3.jpg)

**Comment by corob-msft** [comment]
I have no idea why the template category is named Windows Universal. It doesn't make sense to me, either.

As far as I know, a WinRT component written in any language should be callable by C# WinRT code, as long as the component exposes only standard WinRT types. This isn't something I have tried, so I can't tell you more.

The C++/WinRT docs are owned by the Windows / UWP team, not the C++ team, so you won't find those docs in this repo. If you'd like to make a suggestion for new C++ WinRT interop documentation, the best place to do that is at https://github.com/MicrosoftDocs/windows-uwp.
