### ISSUE TITLE
DELAYLOAD data import workaround (how is this actually done wtih C++? __asm?)

### ISSUE THREAD

**Issue by mick-p1982** [MicrosoftDocs/cpp-docs#3200]
> Imports of data can't be supported. A workaround is to explicitly handle the data import yourself by using LoadLibrary (or by using GetModuleHandle after you know the delay-load helper has loaded the DLL) and GetProcAddress.

If data is imported it's probably implemented by generating additional code to an invisible pointer. So how does that pointer actually get set? This article doesn't say, but suggests there's a "manual" way. Is it in the PE import table? It could use more detail than just leading us to think there's a solution. (Edited: Does the DELAYLOAD option just refuse to link in this case? Or can the program be patched at runtime to avoid bugs? I.e. Is the article suggesting abandoning DELAYLOAD or some kind of runtime patching it doesn't get into?)

P.S. Why doesn't DELAYLOAD offer a simpler option where instead of wrapping functions the consuming program/module can just call a "Load" routine before it touches anything in the DLL? (This hypothetical routine would be generated by the compiler for each instance of the import library.)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 155172a5-829f-1869-ce1d-288427b234dc
* Version Independent ID: 3933275f-c1f8-e13b-8213-3a972fec3a70
* Content: [Linker support for delay-loaded DLLs](https://docs.microsoft.com/en-us/cpp/build/reference/linker-support-for-delay-loaded-dlls?view=msvc-160)
* Content Source: [docs/build/reference/linker-support-for-delay-loaded-dlls.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/reference/linker-support-for-delay-loaded-dlls.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by mick-p1982** [comment]
Found some concrete evidence: https://stackoverflow.com/questions/5232912/how-to-use-delay-loading-with-a-dll-that-exports-c-classes

```
LINK : fatal error LNK1194: cannot delay-load 'two.dll' due to import
of data symbol '"__declspec(dllimport) const TwoClass::`vftable'"
(__imp_??_7TwoClass@@6B@)'; link without /DELAYLOAD:two.dll
```

**Comment by corob-msft** [comment]
@mick-p1982 
Interesting questions, but probably boring answers. Delay loaded functions work because you don't know or (usually) care whether you're calling a function indirectly through a pointer fixed up at load time or through an pointer that was fixed up later at run time. The linker can work that magic with a helper function behind the scenes, so your delay-loaded calls look just like regular implicitly-loaded calls.

Data is a little tougher. If you declare some variable `__declspec(dllimport)` in your client app, it removes the indirection in the caller. You access the data directly, without going through a pointer. Those data addresses get patched up at load time. There isn't any indirection through a table that the helper can patch later when the DLL gets delay-loaded. So, to use data from a delay-loaded DLL, you have to explicitly get the data addresses yourself at run time, using `GetProcAddress` as described by the docs. It's exactly the same thing you'd do to reference data in any explicitly loaded DLL:

```
// This example assumes mydll.dll exports int nMyData
// Do something that loads the DLL first, then call:
HMODULE hMyDll = GetModuleHandle("mydll.dll");
if (NULL != hMyDll)
{
    int* pnMyData = static_cast<int*>(GetProcAddress(hMyDll, "nMyData"));
    // . . . do stuff with the pointer to data
}
```

As you discovered, the linker won't link if there are direct data references to DLLs you tell it to delay-load.

If you want to make a product suggestion, there's a feature built in to Visual Studio under **Help** > **Send Feedback** > **Suggest a Feature**.

**Comment by mick-p1982** [comment]
Thanks @corob-msft I just felt the docs are a bit too mysterious on this topic and there's not much information out there on this subject (maybe because people normally find out the hard way by getting a LNK1194 error instead of proactively seeking out the answer). In this day and age maybe traditionally obtuse or incorrect MSDN docs can be easily patched up or elaborated on, I don't know.

Without knowing if it's a hard error or not it's not clear if use of `__declspec(dllimport)` has to be qualified on data or not to enable /DELAYLOAD use of the library. It seems it must based on that LNK1194 error, and maybe things get more dicey when the data is something like a vtable. Yesterday I modified a library that exported data to offer a preprocessor macro to put it into a /DELAYLOAD friendly mode. (Instead of using `GetProcAddress` it just has a "delayload" function that would simultaneously load the library and fill out the needed data fields, that are provided as an argument. I still think it would be possible to support data if an option was given to manually load the library... instead of the "too clever by half" approach of using function call magic.)
