### ISSUE TITLE
No more tool for typelib import in VS2019

### ISSUE THREAD

**Issue by Thierry-TGMDev** [MicrosoftDocs/cpp-docs#3203]
Hello
Ok, the tool is removed. So can you explain how one can write program to do Word Automation ? I used this feature to generate Word doc programatically with MFC/C++ since years. And now, I can not start new  projects !!!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c4eb019-2eb2-4eae-1642-92de76e13229
* Version Independent ID: 75c0a6b2-41c1-d9b5-5b00-d4a5a6639367
* Content: [Add Class from Typelib Wizard](https://docs.microsoft.com/en-us/cpp/mfc/reference/add-class-from-typelib-wizard?view=msvc-160)
* Content Source: [docs/mfc/reference/add-class-from-typelib-wizard.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/mfc/reference/add-class-from-typelib-wizard.md)
* Product: **visual-cpp**
* Technology: **cpp-mfc**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by corob-msft** [comment]
@Thierry-TGMDev 
I appreciate your concern about the removed feature. If you'd like to see it return, you can make a suggestion in Visual Studio. Use the **Help** > **Send Feedback** > **Suggest a Feature** menu command.

I understand the feature was dropped because it wasn't widely used, and because it's not hard to do by hand. If you'd rather not do it by hand because of the sheer size and number of interfaces, that's understandable. In that case, I'd recommend you create the files using the wizard in an older version of Visual Studio, then copy them into your new projects. I'm sorry I don't have a better solution for you.

I'm closing this as a product issue.

**Comment by Thierry-TGMDev** [comment]
Hello

 

I have no other choice than do what you propose. It just looks very strange to me. Am I alone in the world to do Word Automation ? I use Visual Studio to automatically generate Word document and the users of these application are extremely satisfied to see their job done in a few seconds by the PC, instead of copy/pasting existing documents and spending time to do boring jobs.

 

Why are you removing useful code already written and debugged during years ? It’s something I have difficulty to understand. But it’s your choice, I guess I got to work that way

 

Best regards

 

Thierry
