### ISSUE TITLE
setting up MSVC Environment - page says "use a developer command prompt shortcut," but not where to get it

### ISSUE THREAD

**Issue by Patrick5** [MicrosoftDocs/cpp-docs#3206]
I would like to set up a command prompt environment, in particular to use the nmake command.  

[This page](https://docs.microsoft.com/en-us/cpp/build/setting-the-path-and-environment-variables-for-command-line-builds?view=msvc-160) ostensibly addresses that.  It says:
"Even a simple Visual Studio installation may set twenty or more environment variables."
and because of that
"we strongly recommend that you use a developer command prompt shortcut or one of the customized command files to set them."   
**This is precisely what I would like to do.** Where do I get the mentioned developer command prompt shortcut?

The above page links to another page [here](https://docs.microsoft.com/en-us/cpp/build/building-on-the-command-line?view=msvc-160) but that is unhelpful in that it only points us back to our starting page above. The two pages form a circular loop that unfortunately does not include the necessary information they seemingly address.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fbbe18ff-e775-1259-78fb-53681be876c2
* Version Independent ID: 2e3dbd10-3e65-e65f-8f59-909800f5bf62
* Content: [Set the Path and Environment Variables for Command-Line Builds](https://docs.microsoft.com/en-us/cpp/build/setting-the-path-and-environment-variables-for-command-line-builds?view=msvc-160)
* Content Source: [docs/build/setting-the-path-and-environment-variables-for-command-line-builds.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/setting-the-path-and-environment-variables-for-command-line-builds.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@Patrick5 

I'm sorry you're having trouble finding the information you're looking for. The page you've complained about really ought to just be a section on the other page you reference, since that one has the instructions you're looking for.

The developer command prompt shortcuts (DCPs, for short) are normally installed in the Windows **Start** menu. That's described on the [Use the Microsoft C++ toolset from the command line](https://docs.microsoft.com/en-us/cpp/build/building-on-the-command-line?view=msvc-160) page, in the section titled [Developer command prompt shortcuts](https://docs.microsoft.com/en-us/cpp/build/building-on-the-command-line?view=msvc-160#developer_command_prompt_shortcuts).

If you want to know where one of these shortcuts lives on disk, you can right-click the shortcut in the **Start** menu, then choose **More** > **Open file location** on the pop-up menu. The shortcuts themselves just invoke the command processor with one of the developer command prompt *`.bat`* command files and any appropriate parameters. (You can see this for yourself if you right-click the shortcut file you found at that file location, choose **Properties**, and look under the **Shortcut** tab for **Target**.) For example, on my machine, the primary DCP invokes:

```
%comspec% /k "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\VsDevCmd.bat"
```

The x64 native DCP invokes:

```
%comspec% /k "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
```

All of this is documented later on the [Use the Microsoft C++ toolset from the command line](https://docs.microsoft.com/en-us/cpp/build/building-on-the-command-line?view=msvc-160) page. You can invoke any of these same *`.bat`* command files in a plain command window to turn it into a developer command prompt. We recommend you only do that once per window. 

Hope that's enough to get you started.

**Comment by corob-msft** [comment]
Closing as fixed. The referenced document has been folded into the [Use the Microsoft C++ toolset from the command line](https://docs.microsoft.com/en-us/cpp/build/building-on-the-command-line?view=msvc-160) page.
