### ISSUE TITLE
Using a custom LLVM (clang-cl) with CMAKE.

### ISSUE THREAD

**Issue by AA11BB22** [MicrosoftDocs/cpp-docs#3207]
[Enter feedback here]

I have built Clang 12.0 and would like to use that instead of Clang 11.0 that is provided by Visual Studio Installer.

Is there any way to specify LLVMToolsVersion through CMAKE?

Example.

`cmake -S . -B build -T ClangCl -DCMAKE_C_COMPILER="C:\\Program Files\\LLVM\\bin\\clang.exe" -DCMAKE_CXX_COMPILER="C:\\Program Files\\LLVM\\bin\\clang++.exe"`

Error.

![image](https://user-images.githubusercontent.com/16478055/122496322-21d2ee00-d01e-11eb-8ceb-ac3988678dff.png)

Seems like it demands Clang 11.0.

I have tried -DLLVMToolsVersion=12.0, and it didn't work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 47cabdd4-5ef1-1c19-4a82-5448a5901e8a
* Version Independent ID: 56fd7d96-62ec-07df-40df-aaf155d504d3
* Content: [Clang/LLVM support in Visual Studio projects](https://docs.microsoft.com/en-us/cpp/build/clang-support-msbuild?view=msvc-160&viewFallbackFrom=vs-2019)
* Content Source: [docs/build/clang-support-msbuild.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/clang-support-msbuild.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@AA11BB22 

I'm sorry you're having trouble. MSBuild requires you to [set the `LLVMInstallDir` and `LLVMToolsVersion` properties](https://docs.microsoft.com/en-us/cpp/build/clang-support-msbuild?view=msvc-160&viewFallbackFrom=vs-2019#custom_llvm_toolset) to use a custom Clang toolset location and version. So, if you can [set MSBuild properties](https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-properties?view=vs-2019) on the CMake-generated command line, then I suppose it's possible. That's where I'd start. 

This issue seems like a support question rather than a documentation issue, so I'm closing it. Good luck with your project.
