### ISSUE TITLE
Where is the easy version?

### ISSUE THREAD

**Issue by anyonecan** [MicrosoftDocs/cpp-docs#3229]
Those instructions did result in an application with a window, but I'd like to do it Visually, like VB6 or maybe C#. Looking around I see that there used to be a "CLR' package for this, but it has been removed.

What is the way to do this now?

Thanks,

John

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eda99bc7-483b-e53c-1035-886f4d0955f4
* Version Independent ID: a6fdba4d-53e4-9f1a-2352-bc68ef491069
* Content: [Walkthrough: Create a traditional Windows Desktop application (C++)](https://docs.microsoft.com/en-us/cpp/windows/walkthrough-creating-windows-desktop-applications-cpp?view=msvc-160)
* Content Source: [docs/windows/walkthrough-creating-windows-desktop-applications-cpp.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/windows/walkthrough-creating-windows-desktop-applications-cpp.md)
* Product: **visual-cpp**
* Technology: **cpp-windows**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@anyonecan 
There are several C++ framework libraries that have visual designers in Visual Studio, but I wouldn't call any of them easy. The oldest is MFC. It has visual designers to build apps that have the classic Windows look, but it's hard to take advantage of some of the newest Windows features in an MFC app. We used to support creation of C++/CLI apps, but dropped that in VS 2015. These apps were .NET Framework apps that used the C++/CLI dialect of C++ to emulate managed languages. There's the more recent C++/CX, which targets UWP apps, and like C++/CLI, modifies the C++ language to be closer to the managed .NET languages. It lets you use XAML visual designers just like C# or VB. Most C++ UWP project templates in Visual Studio generate C++/CX projects. C++/CX is loosely deprecated in favor of C++/WinRT, which doesn't modify the C++ language itself, but we don't have app templates that use C++/WinRT. While you can create an app with C++/WinRT, the templates are for creating components that you'd use in, say, a C# app. 
Since your issue isn't one that suggests we need to change this particular doc, I'm closing it.

**Comment by anyonecan** [comment]
Hi Colin,

Thanks for the rundown on the options. I may have to look at C# for the
most straightforward path.

John
