### ISSUE TITLE
Accessing local environment variables in section VisualStudioRemoteSettings

### ISSUE THREAD

**Issue by dmenendez-gruposantander** [MicrosoftDocs/cpp-docs#3234]
[Enter feedback here]

CMakeSettings.json used to allow macros referencing the local machine environment, e.g. 
"remoteCMakeListsRoot": "/sandbox/${env.USERNAME}/${projectDirName}/src" would find the Windows *local* environment variable USERNAME

However, using CMakePresets.json, I've lost that capability, e.g.  
"microsoft.com/VisualStudioRemoteSettings/CMake/1.0": {
          "sourceDir": "/sandbox/$env{USERNAME}/$ms{projectDirName}/src",

$env{USERNAME} tries to access the Linux *remote* environment $USERNAME, which is not what I need.

Is it possible to access the local environment variables, as opposed to the remote environment variables, inside VisualStudioRemoteSettings vendor section?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 64d317ae-6e03-8bb6-2b2c-4d1b9ecf3080
* Version Independent ID: cab1289c-b480-e674-106f-f37d3a3f198f
* Content: [CMakeUserPresets.json](https://docs.microsoft.com/en-us/cpp/build/cmake-presets-json-reference?view=msvc-160)
* Content Source: [docs/build/cmake-presets-json-reference.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/cmake-presets-json-reference.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@dmenendez-gruposantander 
That's a good question, but it's one I'd pose on [Developer Community](https://aka.ms/vsfeedback/browsecpp) instead. I'm closing this as a product question. We don't state it explicitly, but examples like the one for `sourceDir` imply that environment variables are evaluated in the context of the remote system, which is not unexpected, since that's also where the commands run. I don't know of a way to access the host's environment variables from the target machine, but perhaps someone on the product team can give a more definitive answer.
