### ISSUE TITLE
Module documentation is yet to be updated for Visual Studio 2019 version 16.10

### ISSUE THREAD

**Issue by pjmlp** [MicrosoftDocs/cpp-docs#3240]
As per https://docs.microsoft.com/en-us/cpp/overview/visual-cpp-language-conformance?view=msvc-160 C++20 modules are now fully supported (minus possible bugs), yet the documentation describing how to use them still reflects the state of the compiler back in year 2019 (not to mix with the VS name).

Additionally it would be nice to have some overview of how to use C++20 modules alongside typical Windows development workflows of frameworks provides out of the box alongside Visual C++, a kind of best practices tips.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad1fef9a-9c55-a8ab-faf4-8b9ceb9ff688
* Version Independent ID: 0eadb3ed-bb38-58bc-b335-687b10f0fd31
* Content: [Overview of modules in C++](https://docs.microsoft.com/en-us/cpp/cpp/modules-cpp?view=msvc-160)
* Content Source: [docs/cpp/modules-cpp.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/cpp/modules-cpp.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by TylerMSFT** [comment]
More modules documentation was added since this was opened such as [Overview of modules in C++](https://learn.microsoft.com/en-us/cpp/cpp/modules-cpp?view=msvc-170), [Named modules tutorial (C++)](https://learn.microsoft.com/en-us/cpp/cpp/tutorial-named-modules-cpp?view=msvc-170), [Tutorial: Import the C++ standard library using modules from the command line](https://learn.microsoft.com/en-us/cpp/cpp/tutorial-import-stl-named-module?view=msvc-170)
We don't have resources to do "C++20 modules alongside typical Windows development workflows of frameworks provides out of the box alongside Visual C++, a kind of best practices tips." unfortunately.
