### ISSUE TITLE
printf-wprintf char type mixup

### ISSUE THREAD

**Issue by KeveNagy** [MicrosoftDocs/cpp-docs#3245]
[Enter feedback here]

Under **Type conversion specifier** the second paragraph ends with these words ...
"Character and string arguments that are specified by using C and S are interpreted as wchar_t and wchar_t* by printf family functions, or as char and char* by wprintf family functions. This behavior is Microsoft-specific."

Naming convention suggests that it is actually the other way around, printf family interpreting as char while wfrintf family as wchar_t.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 78bd3fde-7eae-a126-f330-563d912a1fab
* Version Independent ID: b6f2df29-3154-05ec-4c9b-9dbd8c316dd3
* Content: [Format Specification Syntax: `printf` and `wprintf` Functions](https://docs.microsoft.com/en-us/cpp/c-runtime-library/format-specification-syntax-printf-and-wprintf-functions?view=msvc-160#type-conversion-specifier)
* Content Source: [docs/c-runtime-library/format-specification-syntax-printf-and-wprintf-functions.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/c-runtime-library/format-specification-syntax-printf-and-wprintf-functions.md)
* Product: **visual-cpp**
* Technology: **cpp-ucrt**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by corob-msft** [comment]
@KeveNagy 

Thanks for taking the time to comment. The `printf` family treat `c` and `C` (or `s` and `S`) type specifiers the same way the standard specifies: `c` and `s` consistently specify narrow characters, while `C` and `S` specify `wchar_t` characters. The `wprintf` family do the opposite of what the standard specifies, namely, `c` and `s` specify `wchar_t` characters, while `C` and `S` specify narrow characters. That's what the sentence you quote is talking about, and it looks correct to me.

The library behaves this way for historical reasons, since the CRT `wprintf` implementations predate the creation of the `C` and `S` specifier variants. We briefly tried supporting the standard in `wprintf` family functions during VS2015 previews. So much existing code broke that we had to back that change out. 

I'm closing the issue as not requiring a change. If you think more clarification is needed, you're welcome to make your case here.

**Comment by KeveNagy** [comment]
@corob-msft 
Thank you for the detailed explanation. With this background information in mind, the current behaviour and the documentation make perfect sense. I agree that no related change of any kind is required. 
However, this section of the documentation could benefit from the addition of a sentence like _"The wprintf family intentionally do the opposite of what standard printf specifies, namely, c and s refer to wchar_t characters, while C and S specify narrow characters"_. This would clarify the confusion I fell victim to. It is not a request though, just a suggestion.

**Comment by TylerMSFT** [comment]
@KeveNagy , I added a clarifying comment per your suggestion: "For historical reasons, the `wprintf` functions use **`c`** and **`s`** to refer to `wchar_t` characters, and **`C`** and **`S`** specify narrow characters". This change should be live by end of day Thurs, 12/22.
