### ISSUE TITLE
The C++ spec has no "constant" production in the tokens list, MS docs do

### ISSUE THREAD

**Issue by AndrewRayCode** [MicrosoftDocs/cpp-docs#3246]
On this page: https://docs.microsoft.com/en-us/cpp/preprocessor/grammar-summary-c-cpp?view=msvc-160

The production `token` is defined as:

```
token:
    keyword
    identifier
    constant
    operator
    punctuator
```

Note the use of `constant` in this list.

However, in the [C++ reference](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2010/n3092.pdf) in section 2.7 "Tokens", (page 19 using the page numbers at the bottom), the production for token is listed as:

```
token:
    identifier
    keyword
    literal
    operator
    punctuator
```

The language reference does not include `constant`. What is `constant`, and why is it included in the Microsoft language reference?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 20eddc0a-768d-0b56-88a9-22bfbfa76ffd
* Version Independent ID: 3a0fef89-7eb4-37fc-1675-419cf5a7e804
* Content: [Preprocessor grammar summary (C/C++)](https://docs.microsoft.com/en-us/cpp/preprocessor/grammar-summary-c-cpp?view=msvc-160)
* Content Source: [docs/preprocessor/grammar-summary-c-cpp.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/preprocessor/grammar-summary-c-cpp.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@AndrewRayCode 

You've spotted a difference between the C and C++ standards. The C standards use the `constant` production name, while the C++ standards use `literal`. There are some minor differences between those production rules, mostly having to do with boolean types in C++, which don't exist as such in C. Since the preprocessor documentation is shared between the Microsoft C and C++ language references, we've occasionally been forced to choose between standards for how to document things. Usually, C++ wins. In this case, we might have used the C `constant` token because it predates the C++ `literal` token, though that's just a guess on my part.

Does this production rule make a difference to something you're coding? We're mostly attempting an explanation in sufficient detail for everyday use, and not trying to restate the standards for language implementers.

**Comment by AndrewRayCode** [comment]
Ah, I didn't notice until now that the title of the doc says "C/C++". This page is the first result in Google for "cpp preprocessor grammar".

I'm trying to write a parser+preprocessor (using PEG) for the shading programming language GLSL. The GLSL spec says that the preprocessor grammar is based on the C++ grammar, so I went Googling for a cpp preprocessor grammar to start from, especially for the expression statements.

The microsoft docs seem like a decent starting point. It's not exactly what I'm looking for, as most of the productions aren't fully defined. I was hoping I wouldn't have to read all of the spec docs to figure out the preprocessor grammar. If there are differences between the c and c++ preprocessor grammars in the doc that require knowing both specs intimately, I might need to find additional resources to help me create a preprocessor grammar.
