### ISSUE TITLE
vcvars command fails

### ISSUE THREAD

**Issue by jbarlow83** [MicrosoftDocs/cpp-docs#3250]
Using the command in cmd.exe fails:
```
PROMPT> %comspec% /k "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat"
'C:\Program' is not recognized as an internal or external command,
operable program or batch file.
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45e8226e-799c-2e3b-01c6-d7603141d5ca
* Version Independent ID: 4f7cd478-ffcc-bec5-b61a-e17085ccd6f5
* Content: [Use the Microsoft C++ toolset from the command line](https://docs.microsoft.com/en-us/cpp/build/building-on-the-command-line?view=msvc-160)
* Content Source: [docs/build/building-on-the-command-line.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/building-on-the-command-line.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@jbarlow83 

Sorry you're having trouble. Given the error message, it seems like cmd.exe thought the file path wasn't escaped correctly. It's as if the trailing double-quote is missing. I just copied and pasted the command you supplied above into a new instance of cmd.exe, and it worked for me. I don't see anything wrong with what you've posted here. Since this looks like a product support issue, rather than a documentation issue, I'm closing it.

I recommend either [Microsoft Docs Q&A](https://docs.microsoft.com/en-us/answers/topics/c%2B%2B.html) or [Developer Community](https://aka.ms/vsfeedback/browsecpp) for product behavior questions like yours. Best wishes for your success.
