### ISSUE TITLE
How do I remove a property defined in the local context

### ISSUE THREAD

**Issue by kgold2** [MicrosoftDocs/cpp-docs#3287]
I mistakenly changed the property for one project, overriding the property sheet.  How do I revert that?

(Without editing the XML directly, of course.)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cec7ea59-1270-7e09-8240-651d34d7e758
* Version Independent ID: e004b9b0-4031-8bd9-b2bf-247656829ebe
* Content: [/I (Additional include directories)](https://docs.microsoft.com/en-us/cpp/build/reference/i-additional-include-directories?f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(VC.Project.VCCLCompilerTool.AdditionalIncludeDirectories)%26rd%3Dtrue&view=msvc-160)
* Content Source: [docs/build/reference/i-additional-include-directories.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/reference/i-additional-include-directories.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@kgold2 
That's a good question. It's probably better directed at the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/search?space=8) board. As far as I know, once you've edited a property, it sticks unless you set the property to the special value **`<inherit from parent or project defaults>`**. I don't know if this special value is available for all properties, but it will remove the setting from your .vcxproj file for the current configuration and target. Since this isn't something that's actionable in the **`/I (Additional include directories)`** doc, I'm closing this issue.
