### ISSUE TITLE
Latest redistributable is always found with 14.0 not the current VisualStudio version.

### ISSUE THREAD

**Issue by icedtoast** [MicrosoftDocs/cpp-docs#33]
In https://github.com/Microsoft/cpp-docs/blob/606cb8510798c221942833219761f75f2fb9fda3/docs/ide/redistributing-visual-cpp-files.md 
The line:
> The currently installed version is stored in the HKEY_LOCAL_MACHINE\SOFTWARE[\Wow6432Node]\Microsoft\VisualStudio\vs-version\VC\Runtimes\{x86|x64|ARM} key, where vs-version is the version number for Visual Studio (14.0 for Visual Studio 2015, 14.1 for Visual Studio 2017)

Seems to be incorrect, in my testing the redistributable is always installed using a vs-version of 14.0

**Comment by corob-msft** [comment]
Yes, this is my fault for not updating the docs for a change made before the product shipped. The 2017 redistributables key path version remains 14.0 because the new redistributables are binary compatible with 14.0, or so the developers told me back in February. I'll push out a change in a day or so, along with some other fixes coming.

**Comment by ghogen** [comment]
@corob-msft is this fixed?

**Comment by corob-msft** [comment]
Yes, this was fixed some time ago. Closing the loop here.

**Comment by plujon** [comment]
The current VS 2017 redistributables do not use HKEY_LOCAL_MACHINE\SOFTWARE[\Wow6432Node]\Microsoft\VisualStudio\14.0\VC\Runtimes{x86|x64|ARM} at all.

For an example of how this bites, see https://social.msdn.microsoft.com/Forums/sqlserver/en-US/72da6400-7a22-4bcc-b8d3-6423086289f0/visual-c-2015-redistributable-setup-failed-0x80070666-x64-amp-x86 .
