### ISSUE TITLE
More information on property cmakeExecutable needed

### ISSUE THREAD

**Issue by aleksandaratanasov** [MicrosoftDocs/cpp-docs#3303]
I am currently attempting to set a custom (from Kitware) setup with CMake 3.21 using Visual Studio 2017 since the CMake shipped with the IDE is too old and lacks features that I need. Setting the value of the property `cmakeExectuable` (in my case `C:\Program Files\CMake\bin\cmake.exe`) results no change in the behaviour of the IDE, which continues to use its own version of the tool.

I have not tested the property on later versions of Visual Studio since I don't have access to those.

Please provide more information on how to use the property or (if the information is deemed sufficient) verify it actually works. I have posted detailed information (including an example) on [stackoverflow](https://stackoverflow.com/q/68757120/1559401).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4417dbbb-58ad-4417-3a96-c1cb40516ca2
* Version Independent ID: cb5427c7-ee24-c972-bc44-ff890621cbf9
* Content: [CMakeSettings.json schema reference](https://docs.microsoft.com/en-us/cpp/build/cmakesettings-reference?view=msvc-150)
* Content Source: [docs/build/cmakesettings-reference.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/cmakesettings-reference.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@aleksandaratanasov 

I'm sorry you're having trouble. CMake integration was new in Visual Studio 2017, and wasn't as capable as it is in the most recent versions. That said, I'm told what you're doing with `cmakeExecutable` should work, though you may need to make some other changes to get the cache generation to work, too, according to the updated note in #3300, which should be published Monday. There's a note in the docs that says the version of CMake in `cmakeExecutable` has to have an approved version, but as far as I can tell, that means > 3.12.

Since this is the docs issues board, and not a support channel, I recommend asking about your issue on [Developer Community](https://aka.ms/vsfeedback/browsecpp). You're more likely to get knowledgeable help there. I'm going to close this, but if you learn something that would be useful in documentation, please add a comment here. We will reopen the issue.

**Comment by aleksandaratanasov** [comment]
I posted this and on multiple other location because I am not sure if it's a bug (in the integration itself) or inaccuracy in the documentation (hence submitting this issue). I know that CMake integration was new in 2017 (and in many aspects still feels new in Visual Studio even today) but "should work" is not a very accurate term. I will keep looking for a solution. Right now I am slowly moving away from VS in order to speed up my workflow but if I find something related to the documentation and this issue, I will create a new issue with the respective data.
