### ISSUE TITLE
Please remove std::

### ISSUE THREAD

**Issue by murali-marimekala** [MicrosoftDocs/cpp-docs#333]
Hi,

You have already included "#include &lt;iostream&gt;" header in each program. 
Any specific reason why you use std:: before each and every variable or cout? 

Thanks,
Murali

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2793a25f-ffc1-ecb3-53ca-809bfd3fb04b
* Version Independent ID: 64e107a6-f625-a6e7-9954-7a2b28597aeb
* Content: [unordered_map Class](https://docs.microsoft.com/en-us/cpp/standard-library/unordered-map-class)
* Content Source: [docs/standard-library/unordered-map-class.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/standard-library/unordered-map-class.md)
* Product: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by murali-marimekala** [comment]
My bad, just realized that "using namespace std" is not present in each program. The documentation is fine or we can use "using namespace std" instead.

**Comment by corob-msft** [comment]
There's something of a skirmish between those who think it's better engineering practice to avoid the ambiguity of using namespaces, and those who hate the extra typing and the clutter of all those fully-qualified names. We show both sorts of examples, because they have been written by people on both sides of the argument.
