### ISSUE TITLE
COM Smart Pointer link is to CComPtr

### ISSUE THREAD

**Issue by amp64** [MicrosoftDocs/cpp-docs#3385]
These docs are for the modern WRL ComPtr class, but for "best practices" it links to an ancient page that describes the ATL CComPtr. Do we really not have a modern document on COM best practices we can link to instead?

Also I am really not a fan of the way this ComPtr members are described. Who can read template signatures? A simple example per method would go a long way to make the usage obvious.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c769cdb9-ab7c-77bd-16b7-8bb686169eff
* Version Independent ID: ff913b70-328c-9d9e-c7ec-ba942db726b1
* Content: [ComPtr Class](https://docs.microsoft.com/en-us/cpp/cppcx/wrl/comptr-class?view=msvc-160)
* Content Source: [docs/cppcx/wrl/comptr-class.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/cppcx/wrl/comptr-class.md)
* Product: **visual-cpp**
* Technology: **cpp-cx**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@amp64 
Thanks for the feedback. I suspect your complaint might be better addressed to the authors of the linked content in Windows Docs. My cursory search didn't find any better article to link. The best discussion I've seen is in this MSDN Magazine article by Kenny Kerr, [Windows with C++ - COM Smart Pointers Revisited](https://docs.microsoft.com/en-us/archive/msdn-magazine/2015/february/windows-with-c-com-smart-pointers-revisited). It could be read as a lengthy critique of WRL COM smart pointers, so it's probably not a good substitute for the link in the ComPtr Class doc.

While as far as I know WRL development isn't specifically deprecated, development effort ended on the WRL when C++/CX was introduced. We don't have the resources to spend on documenting this old and doubly-superseded technology now that C++/WinRT is also available. That's why I'm closing your issue unfixed. My apologies.
