### ISSUE TITLE
Multiple __declspec()'s ?

### ISSUE THREAD

**Issue by johne53** [MicrosoftDocs/cpp-docs#3399]
Can __declspec(noinline) be used in conjunction when exporting or importing things from a DLL? For example, can you specify a function as being both  __declspec(noinline) and also __declspec(dllimport) ?

AFAICT MSVC never inlines stuff that's declared using  __declspec(dllimport) - but some other compilers aren't quite so conscientious :-(

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05525d61-d729-6516-0e7f-6259efc3a645
* Version Independent ID: 25e5c287-1b74-e960-b7f7-95332072682b
* Content: [noinline](https://docs.microsoft.com/en-us/cpp/cpp/noinline?view=msvc-160)
* Content Source: [docs/cpp/noinline.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/cpp/noinline.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@johne53 

Yes, you can apply both attributes to the same function, though it seems redundant, since the importer of a function from a DLL doesn't know how it's implemented and would have no way to inline it. If the function is defined in a header, I suppose it could be inlined, but that leads to other issues. However, if the question is about the behavior of non-MSVC compilers, I can't say what they'd do. 
 
I'm closing the issue, as this info seems too specific to warrant adding to the `noinline` article.

**Comment by johne53** [comment]
Shortly after my original post, someone drew my attention to this MSDN page which explains that dllimport / dllexport functions CAN be inlined:-

  https://docs.microsoft.com/en-us/cpp/cpp/defining-inline-cpp-functions-with-dllexport-and-dllimport

But presumably MSVC only be deems them to be "inline-able" if they're specifically declared using inline?  It'd be great to get some clarification on this. What's happening with Visual Studio's other compiler (Clang) is that it'll try to inline any DLL functions defined in a header file, even if it's not specifically declared using **inline**. And as you said, that just leads to other problems which I'd never seen when using MSVC. The Clang devs are willing to fix all this. They just need to know what the rules are.

**Comment by corob-msft** [comment]
I'm having trouble wrapping my head around the problem. If a function is defined in a header, and it's not inlined, then you get an ODR violation if it's included more than once. (MSVC will report LNK2005.) This doesn't seem to have any relation to whether it's imported from or exported by a DLL, since clients will create their own implementation from the header, and won't call anything from the DLL.

MSVC inlining behavior depends on the **`/Ob`** optimization level. The compiler may well consider header-defined free functions as candidates for inlining even without an explicit `inline` keyword, if they're not referred to through pointers anywhere. **`/Ob3`** is the most aggressive about inlining. The heuristic depends mainly on function size, IIRC. I guess this means whether you see an error for header-defined functions may depend on the optimization level.

I'm confused about the ask here. If the Clang implementers want to match the inlining heuristics of MSVC, it would be better to contact the dev team through [Developer Community](https://aka.ms/vsfeedback/browsecpp) than to ask the docs team to turn the docs into a specification. We're vague about some things on purpose, because the product team specifically want to discourage people from taking dependencies on undocumented behavior that might subsequently change, breaking those folks' code.

**Comment by johne53** [comment]
Thanks Colin and I agree that the Developer Community would be a better place for this question so I've opened a thread about it.
