### ISSUE TITLE
What I Said (not feedback)

### ISSUE THREAD

**Issue by JaybobPlayz** [MicrosoftDocs/cpp-docs#3412]
[Enter feedback here]
I don't even know how this solution is meant to help with the LNK2019 error, it's confusing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab7d8d70-709a-67c8-799f-399ba8a6c38c
* Version Independent ID: ba5ba087-422c-4974-db42-4ae343defb3f
* Content: [Linker Tools Error LNK2019](https://docs.microsoft.com/en-us/cpp/error-messages/tool-errors/linker-tools-error-lnk2019?f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(LNK2019)%26rd%3Dtrue&view=msvc-160)
* Content Source: [docs/error-messages/tool-errors/linker-tools-error-lnk2019.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/error-messages/tool-errors/linker-tools-error-lnk2019.md)
* Product: **visual-cpp**
* Technology: **cpp-diagnostics**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@JaybobPlayz 
Sorry you're having difficulty. This is one of the most common errors programmers see. There are *lots* of ways this error can happen, so we list the most common causes in (very) approximate order of occurrence. Programmers at every level read this article; it can be hard to explain what's gone wrong in the program to novices in ways that don't annoy experienced programmers with extraneous detail.

To solve a LNK2019 error, the first thing you need is to have a complete understanding of everything in the paragraph following **Possible causes**. You'll need to know the difference between a declaration and a definition, and what a symbol is. You should know that object files can have both symbol definitions and references to external symbols, and that the linker's job is to connect those up. And if there's a reference to a symbol in one object file that isn't defined in another object file being linked, the linker reports that as a LNK2019 error. Those are the basics.

To solve your linker error problem, you'll need to reason about why the linker didn't find a definition for a symbol among the object files and libraries you told it to link together. You have to start doing some detective work. You might need to locate where that symbol is defined, or see if its definition matches its declaration, or find out why the object file that defines it didn't get picked up by the linker. We list a bunch of possibilities, and you may have to go through them like a checklist. 

We don't explain all of the basic stuff in depth in this article, because this is an error reference, not a build debugging tutorial. So, I'm closing your issue, not because you didn't have an issue, but because the article isn't meant to do things other than what it does now.
