### ISSUE TITLE
IntelliSense problem with some c++11 feature

### ISSUE THREAD

**Issue by nkx111** [MicrosoftDocs/cpp-docs#342]
I write the hello.cpp:
#include &lt;iostream&gt;
int main(int argc, char* argv[])
{
	const int t = 10;
	auto a = t;
	constexpr int b = t + 20;
	std::cout &lt;&lt; "Hello a and b: "&lt;&lt; a &lt;&lt;", "&lt;&lt; b &lt;&lt; std::endl;
	return 0;
}

and the CMakeLists.txt:
project (hello-cmake)
SET(CMAKE_CXX_FLAGS "-std=c++1y")
add_executable(hello-cmake hello.cpp)

Then "a", "constexpr int" will have a red under-mark at below, though the compilation is successful. My visual studio version is 15.7.5. My gdbserver is on local wsl.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 296f6914-b366-1ab8-4c08-6d51fc7212fa
* Version Independent ID: 04aec2e0-f39a-2e52-6a09-354222d47146
* Content: [Configure a Linux CMake project in Visual Studio](https://docs.microsoft.com/en-us/cpp/linux/cmake-linux-project)
* Content Source: [docs/linux/cmake-linux-project.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/linux/cmake-linux-project.md)
* Product: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by mikeblome** [comment]
@nkx111 thanks for bringing this to our attention. There seem to be some issues with remote Intellisense in Visual Studio 15.8. You can ignore the red squigglies as long as the program is compiling. I'm going to close this because it's not really a documentation issue. Feel free to post on Developer Community if you like: https://developercommunity.visualstudio.com/spaces/62/index.html.
