### ISSUE TITLE
Can't find V141 toolset for XP

### ISSUE THREAD

**Issue by LenShustek** [MicrosoftDocs/cpp-docs#3425]
I'm installing Visual Studio Community 2017 (15.9.39), trying to follow the instructions
 "In the Individual components tab, under Compilers, build tools, and runtimes, choose C++ Windows XP Support for VS 2017 (v141) tools [Deprecated]"
but I find no option exactly like that listed under "Compilers, build tools, and runtimes". 
I do see something like "Windows XP C++ support" without a version number, which I'm going to try instead. If that's what we should be using to compile for XP, you should change your instructions.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 651c91cd-a0c3-f631-7bab-707ea4f1827b
* Version Independent ID: bfd995d2-6875-2301-ef78-4446ed268845
* Content: [Configuring Programs for Windows XP](https://docs.microsoft.com/en-us/cpp/build/configuring-programs-for-windows-xp?view=msvc-160)
* Content Source: [docs/build/configuring-programs-for-windows-xp.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/configuring-programs-for-windows-xp.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@LenShustek 
I'm sorry you've run into a problem here. I expect the source of your difficulty is that your default documentation view is currently set to Visual Studio 2019. To see the documentation as it's meant for Visual Studio 2017, you have to change the **Version** control on the Docs page, which usually appears as a drop-down above the Table of Contents to the left . If you're looking at the Visual Studio 2017 documentation, you'll see it describes the required component as "Windows XP support for C++". 
I'm closing this issue because the documentation is correct, though discovery might be difficult.
