### ISSUE TITLE
Should DllGetActivationFactory be omitted?

### ISSUE THREAD

**Issue by davidmatson** [MicrosoftDocs/cpp-docs#3500]
I thought the DllGetActivationFactory export was only for activating WinRT objects and not needed just to expose a COM object. Is that understanding accurate? If so, should the DllGetActivationFactory function & export be omitted from this doc page?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5ff38587-44d4-291e-92f2-1835bae646b2
* Version Independent ID: d03537dc-cad6-9888-dcc7-6881c00a479c
* Content: [How to: Create a Classic COM Component Using WRL](https://docs.microsoft.com/en-us/cpp/cppcx/wrl/how-to-create-a-classic-com-component-using-wrl?view=msvc-160)
* Content Source: [docs/cppcx/wrl/how-to-create-a-classic-com-component-using-wrl.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/cppcx/wrl/how-to-create-a-classic-com-component-using-wrl.md)
* Product: **visual-cpp**
* Technology: **cpp-cx**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@davidmatson 
Interesting question. Since the entry point is guarded by a build flag for classic COM components, it will only appear as an export if you're *not* building as a plain old COM component. And if you're building the component for WinRT, then you'll need it. In other words, it's not wrong, though it could be distracting given the context. Since we're looking at long-deprecated WRL content that's been available as-is for a decade, I'm disinclined to change it.
