### ISSUE TITLE
Name in Visual Studio does not match the name in Docs

### ISSUE THREAD

**Issue by orenweil** [MicrosoftDocs/cpp-docs#3510]
Name in Visual Studio does not match the name in Docs
in Visual Studio is "Randomized base address" and not "use address space layout redomization" 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 777b381a-baf8-f9a9-970e-5fef4157f79d
* Version Independent ID: 392e117d-61e3-b17e-36cc-8fe738ef3e42
* Content: [/DYNAMICBASE (Use address space layout randomization)](https://docs.microsoft.com/en-us/cpp/build/reference/dynamicbase-use-address-space-layout-randomization?view=msvc-170&viewFallbackFrom=vs-2019)
* Content Source: [docs/build/reference/dynamicbase-use-address-space-layout-randomization.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/reference/dynamicbase-use-address-space-layout-randomization.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@orenweil 
The phrase in parentheses is descriptive, not the name of the project property in the IDE. You'll find that's true for almost all of the compiler and linker options. We identify the name of the property used to set this option in Visual Studio down in the [**To set this linker option in Visual Studio**](https://docs.microsoft.com/en-us/cpp/build/reference/dynamicbase-use-address-space-layout-randomization?view=msvc-170&viewFallbackFrom=vs-2019#to-set-this-linker-option-in-visual-studio) section. That's why I'm disinclined to change the description here. But I do appreciate that you've taken the time to make the suggestion. Thanks!
