### ISSUE TITLE
Undefined references in documentation

### ISSUE THREAD

**Issue by dfisk** [MicrosoftDocs/cpp-docs#3522]
" under VC++ Directories," ...  Where is that ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b46cf831-faea-6357-0e06-3284f114c879
* Version Independent ID: 0345affe-ce33-c438-d3e4-d134f905d084
* Content: [Common macros for MSBuild commands and properties](https://docs.microsoft.com/en-us/cpp/build/reference/common-macros-for-build-commands-and-properties?view=msvc-170)
* Content Source: [docs/build/reference/common-macros-for-build-commands-and-properties.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/reference/common-macros-for-build-commands-and-properties.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by dfisk** [comment]
![image](https://user-images.githubusercontent.com/60303/141658323-bfb089c8-f7e8-40a7-87a3-881daf6c1f77.png)

**Comment by dfisk** [comment]
"To display all of the currently available macros, in the Property Pages dialog, under VC++ Directories"

I do not see the "Property Pages dialog, under VC++ Directories"

**Comment by corob-msft** [comment]
@dfisk 
Thanks for including the screenshot. It shows me that you are in fact looking at what's under **VC++ Directories**. We're using "under" [as a preposition in sense 3a on Merriam-Webster's dictionary site](https://www.merriam-webster.com/dictionary/under), as in: "under the heading VC++ Directories". From this screen, just follow the remainder of the directions: choose the drop-down arrow at the end of a property row.  (I'd pick Executable Directories just because it's first.) Click on Edit and then in the edit dialog box, choose the Macros button.
