### ISSUE TITLE
SHGetKnownFolderPath API dynamically search DLL questions

### ISSUE THREAD

**Issue by meichunwu** [MicrosoftDocs/cpp-docs#3534]
When we put a program under **C:\ProgramData** and use the below 2 APIs to get system folder, we found it will dynamically **search API required DLL in program folder** (C:\ProgramData\profapi.dll& wldp.dll) , if required DLL is not existed in program folder, then **search required DLL in system folder** (C:\WINDOWS\SysWOW64\profapi.dll & wldp.dll).  
1.	What's the design by OS to trigger this behavior ? 
2.	How we limit API dynamically search OS API required DLL in system folder 
3.	If put a **Not signed DLL and rename as API required DLL name** under program folder , OS will search and load those Not signed DLLs, does it's expected by OS  (ie. Rename Not signed DLL and rename profapi.dll or wldp.dll , put into C:\ProgramData, API dynamically search and load C:\ProgramData\profapi.dll)

 **PWSTR localdata, programdata = NULL;
 HRESULT result1 = SHGetKnownFolderPath(FOLDERID_LocalAppData, NULL, NULL, &localdata);
 HRESULT result2 = SHGetKnownFolderPath(FOLDERID_ProgramData, NULL, NULL, &programdata);**

**Comment by corob-msft** [comment]
@meichunwu 
This Issues board is for problems related to the documentation for the C++ compiler and related tools. We don't handle general support questions here. Since this doesn't seem like a documentation bug, I'm closing this issue.

For control over DLL path search order, you can use [`LoadLibraryEx`](https://docs.microsoft.com/windows/desktop/api/LibLoaderAPI/nf-libloaderapi-loadlibraryexa). For more information, see [Dynamic-Link Library Search Order](https://docs.microsoft.com/windows/win32/dlls/dynamic-link-library-search-order). If this article doesn't address your questions, then I recommend you ask your question on [Microsoft Docs Q&A](https://docs.microsoft.com/en-us/answers/products/windows) or [Developer Community](https://aka.ms/vsfeedback/browsecpp).  Best of luck.
