### ISSUE TITLE
Function doesn't work

### ISSUE THREAD

**Issue by dholstei** [MicrosoftDocs/cpp-docs#3535]
I'm a bit flustered here, I entered the example exactly as called out in my Makefile and get:
`.\Makefile.mak(71) : fatal error U1000: syntax error : ')' missing in macro invocation`
Where the invocation is
```
test: libLvXml.c
  $(CC) $(CFLAGS) -c $(?) $(INCLUDES) -DTEST
  $(LINKER) /out:test.exe $(LIB) $(LIBS) $(substi Hello,Hey,Hello World!)
```
Note, the Makefile works fine if I explicitly insert `libLvXml.obj`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: faa9fdb3-b97e-488b-49d9-264d1f378eb8
* Version Independent ID: 804c80b5-eefe-9385-9706-1c935cdb70df
* Content: [subst, substi NMAKE functions](https://docs.microsoft.com/en-us/cpp/build/reference/nmake-function-subst?view=msvc-170&source=docs)
* Content Source: [docs/build/reference/nmake-function-subst.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/reference/nmake-function-subst.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@dholstei 
Sorry you're having trouble. If you check the version on the copy of nmake you're running, is it one that supports `substi`? This macro requires an nmake version that starts with 14.30 or higher.

@dpaoliello Do you have any other insights?

**Comment by dpaoliello** [comment]
Yeah, that looks like the error that an old version of NMake (prior to VS2022) would raise.

**Comment by corob-msft** [comment]
I didn't catch the version omission in those articles before. That's definitely worth adding.

**Comment by corob-msft** [comment]
@dholstei 
I've added the version requirements to the documentation, which should be updated sometime Monday. While I acknowledge you're flustered, your description otherwise looks like a support request rather than a Docs issue, so I'm closing it. We have better forums for support, either in [Microsoft Docs Q&A](https://docs.microsoft.com/en-us/answers/topics/c%2B%2B.html) or [Developer Community](https://aka.ms/vsfeedback/browsecpp). [StackOverflow](https://stackoverflow.com/questions/tagged/visual-c++) is also a good resource. Best of luck with your code.
