### ISSUE TITLE
SHGetKnownFolderPath API will load unsigned DLL

### ISSUE THREAD

**Issue by meichunwu** [MicrosoftDocs/cpp-docs#3539]
I have found SHGetKnownFolderPath API will search and load those **No signed DLLs** in program C:\ProgramData\profapi.dll ( copy a no signed dll and rename as profapi.dll under program folder “C:\ProgramData” ) , does it's expected ?

**Comment by corob-msft** [comment]
@meichunwu 
I'm sorry, I don't know much about the expected behavior of [`SHGetKnownFolderPath`](https://docs.microsoft.com/en-us/windows/win32/api/shlobj_core/nf-shlobj_core-shgetknownfolderpath) other than what's in the documentation. It's not part of the C++ docs, so I'm closing this issue. You'll have a better chance of getting your Win32 API questions answered on [Windows Developer Support](https://developer.microsoft.com/windows/support) or [Microsoft Docs Q&A](https://docs.microsoft.com/en-us/answers/products/windows) for Windows, Good luck!
