### ISSUE TITLE
Broken MSBuild Macros VS2022

### ISSUE THREAD

**Issue by dlamanna** [MicrosoftDocs/cpp-docs#3542]
For MSVS 2022 (Version 17.0.1), many of these macros seem to no longer work. Most importantly for me:

- $(OutDir)
- $(TargetPath)
- $(TargetDir)
- $(PlatformShortName)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b46cf831-faea-6357-0e06-3284f114c879
* Version Independent ID: 0345affe-ce33-c438-d3e4-d134f905d084
* Content: [Common macros for MSBuild commands and properties](https://docs.microsoft.com/en-us/cpp/build/reference/common-macros-for-build-commands-and-properties?view=msvc-170&viewFallbackFrom=vs-2019)
* Content Source: [docs/build/reference/common-macros-for-build-commands-and-properties.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/reference/common-macros-for-build-commands-and-properties.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@dlamanna 
I see some of these properties (`$(OutDir)`, `$(PlatformShortName)`), possibly depending on the project configuration, but not the others. @olgaark, do you have insight here?

**Comment by olgaark** [comment]
@dlamanna @corob-msft Not sure I understand what exactly is not working, but if you are trying to use common properties to define some other properties outside of a target and see them being empty, it means that your properties are defined too early in the project, before the common properties get their values.

To see the order of all properties, open a developer command prompt and run (change SolutionDir, Configuation and Platform values as needed)

`msbuild /p:Configuration="Debug";Platform="x64";SolutionDir="c:\MySolution\" /pp:out.txt <your project>`

out.txt will contain the "preprocessed" project with all imports expanded so you can search it and see the order of the defined properties.

**Comment by corob-msft** [comment]
Thanks, Olga.

@dlamanna
The properties you've mentioned aren't available until certain .props or .targets files have been included by the build system. They won't be available to use in every property exposed in the IDE, or elsewhere in your .vcxproj file, or your own .targets or .props files until their definitions have been included.

The `$(PlatformShortName)` property comes from Platform.default.props, which is available in your .vcxproj after this import:

`  <Import Project="$(VCTargetsPath)\Microsoft.Cpp.Default.props" />`

The `$(Outdir)` property comes from Microsoft.Cpp.MSVC.Toolset.Common.props, which is available in your .vcxproj after it imports this .props file:

`  <Import Project="$(VCTargetsPath)\Microsoft.Cpp.props" />`

`$(TargetPath)` and `$(TargetDir)` come from Microsoft.CppCommon.targets, imported by this line in your .vcxproj file:

`  <Import Project="$(VCTargetsPath)\Microsoft.Cpp.targets">`

Since you haven't mentioned the context where you tried to use the properties, I can't be more specific about what's happening in your build, or why the properties aren't available where you're trying to use them. That verges on a product support question, which we don't address in cpp-docs/issues. As such, I'm closing this issue. 

If you've updated a project from an earlier version, and properties that used to work don't work in VS2022, then that might be a bug. In that case, I recommend you follow the process described in [How to report an issue](https://docs.microsoft.com/cpp/overview/how-to-report-a-problem-with-the-visual-cpp-toolset?view=msvc-170). The development team uses reports on [Developer Community](https://aka.ms/vsfeedback/browsecpp) to track product issues, and they'll follow up. They'll let us know if the documentation needs to be updated, too. Thanks for helping us improve the product.
