### ISSUE TITLE
C5050 warning on use of 'import std.memory'

### ISSUE THREAD

**Issue by rtischer8277** [MicrosoftDocs/cpp-docs#3564]
In a module unit I should be able to 'import std.memory' without incurring the C5050 warning, given that the Visual Studio 22 settings are correct. Here is the resulting command line that fails with C5050:

`/JMC /experimental:module /permissive- /ifcOutput "x64\Debug\" /GS /W4 /Zc:wchar_t /ZI /Gm- /Od /sdl /Fd"x64\Debug\vc143.pdb" /Zc:inline /fp:precise /D "_DEBUG" /D "_CONSOLE" /D "_UNICODE" /D "UNICODE" /errorReport:prompt /WX- /Zc:forScope /RTC1 /Gd /MDd /std:c++latest /FC /Fa"x64\Debug\" /nologo /Fo"x64\Debug\" /Fp"x64\Debug\ExImCore.pch" /diagnostics:column `

Are these command line options correct? Or is the warning caused by a bug?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9fe706e6-2d81-6a6a-4aa6-399e14943372
* Version Independent ID: 918d287f-c642-9858-b1a1-e197716f91de
* Content: [Compiler Warning C5050](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/c5050?view=msvc-170&source=docs)
* Content Source: [docs/error-messages/compiler-warnings/c5050.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/error-messages/compiler-warnings/c5050.md)
* Product: **visual-cpp**
* Technology: **cpp-diagnostics**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@rtischer8277 
I'm sorry you're having trouble with your build. Unfortunately, there isn't enough information in your report to tell you what's gone wrong. More importantly, this isn't the right place to ask, either. If you think the product may have a bug (as opposed to a bug in the docs) then you should [report the issue on Developer Community](https://docs.microsoft.com/cpp/overview/how-to-report-a-problem-with-the-visual-cpp-toolset?view=msvc-170). Since this otherwise sounds like a product support question best handled by Developer Community, I'm closing the issue.

**Comment by rtischer8277** [comment]
np. I have submitted the bug on Developer Community. Once I get it resolved, I'll be sure and circle back here and see if I can add anything to this doc page.
