### ISSUE TITLE
Lack Of Screen Shots

### ISSUE THREAD

**Issue by JarrodSimner** [MicrosoftDocs/cpp-docs#3568]
[Enter feedback here]
I'm using Visual Studio 2019 for C#, but the feedback is in regards to accessing online documentation regarding using the platform. 
Expandable screen shots would make your documents a lot more useful. There are a lot of different options in the visual studio IDE, which makes them extremely hard to find. Optional expandable screenshots (so they don't clutter everything for those people that don't need visual aids) would make it a lot easier to navigate. 
The same would go for code demonstration examples. There are some examples here and there, but a lot more would make your product more accessible to more people (have these expandable too). The easier your make it for people to use, the more programmers will migrate to your platform. There just seems to be waaaaay too many words (which are good), but not enough for the visual learning style type of learner. I'd imagine that most people would be visual learners in this line of work. 
Don't get me wrong, the IDE is good, the debugger is extremely reliable (which is a massive thing).
Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed59e5e2-fd9a-167a-2db0-f088cb24233c
* Version Independent ID: fb205f89-37fb-4323-316f-8841a6315b2e
* Content: [/DEBUG (Generate Debug Info)](https://docs.microsoft.com/en-us/cpp/build/reference/debug-generate-debug-info?view=msvc-160)
* Content Source: [docs/build/reference/debug-generate-debug-info.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/reference/debug-generate-debug-info.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
Hi, @JarrodSimner, and thanks for the feedback.

I agree with you completely. There are few things I'd like to see more than plenty of visual walkthroughs, screenshots, and animations of our product. And yet I find myself removing them more than I add them when I update the documentation for each version. I'm working hard on describing the UI in text instead, for reasons that have to do with the extraordinary costs of maintenance of images when compared to text. 

Here's why: It takes time to set up the product to capture a screenshot. Usually we spin up a VM with a fresh install of the product, so it's uncluttered with old projects. We try to capture images of the key points to follow the text of an article. Then we edit them to add call-outs or highlight boxes as needed to illustrate the steps. It can take a few hours of captures and editing to get the content for a single article. When we're done, the images often get picked up by a localization team that might recreate the same screenshots in several locales. They might either follow the same procedures and capture screenshots, or they might use Photoshop to just redo the text in the image. When we publish a single article with just three or four screenshots, those images might easily represent three or four or more person-days of effort, all told. Only a few articles merit that treatment these days. Product installation, our initial tutorials, some IDE walkthroughs. 

A big problem is, the product isn't static. With a new version comes new themes, new menu items, new controls around the window edges. We may need to recreate all those images in an existing article for the new version. We can leave the old images in the article, but it puts readers off, because it doesn't look like their version. It's stale. Maybe some dialog control locations or menu actions have changed, so we have to update the steps and the image call-outs to match. Basically, we have to spend the same amount of time on updating existing screenshots as we spent on them originally. And every new article we add screenshots to becomes an ongoing source of these maintenance costs. This issue got significantly worse when the development team switched to a continuous improvement model. Previously, UI changes only happened for major version upgrades. Now they can happen with any minor version update, too.

If we had the same team staffing we had when most of our docs were written, we might have more visual content. When I started on the C++ docs a decade ago, I was the seventh writer on the team. We had our own editor, and there was a separate team for doing the charts, graphs, and screenshots. Then came the dark times. Now there are just two of us on the C++ docs team. For a while, it was just me. We have a huge content backlog, and we're lucky if we can stay on top of it for long. We are looking for every way we can to get content out without making more work for ourselves later. That means, no screenshots if we can avoid them. Text is quick to write and easy to localize. Text procedures are less likely to go stale between versions. We get more articles done, and more articles updated, when we stick to text. Our calculations are strictly economic. 

I would love to live in the pretty world of visuals for everything in the docs. A picture is worth a thousand words. If only it didn't cost as much or more than a thousand words! We try to make do with a hundred words, instead. So, I'm closing your issue, not because I want to, but because realistically, I have to.

**Comment by JarrodSimner** [comment]
@corob-msft I can appreciate that mate. Here I was thinking that there would be thousands of workers behind this product. With the effort you’ve put in to your reply, you’ve inspired me to put more effort into reading the docs! Thanks for the reply.
