### ISSUE TITLE
Semicolon in commands

### ISSUE THREAD

**Issue by ltorok** [MicrosoftDocs/cpp-docs#3579]
Hello
what is mean semicolon in end of command and next number 2: mt.exe -manifest MyLibrary.dll.manifest -outputresource:MyLibrary.dll**;**2

It is mark for option 2 or is part of command?

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5d235826-020d-09c6-1984-9491524debf6
* Version Independent ID: 6c3ca9ab-2589-07af-39c5-f14e01b5ac4a
* Content: [How to: Embed a Manifest Inside a C/C++ Application](https://docs.microsoft.com/en-us/cpp/build/how-to-embed-a-manifest-inside-a-c-cpp-application?view=msvc-140)
* Content Source: [docs/build/how-to-embed-a-manifest-inside-a-c-cpp-application.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/how-to-embed-a-manifest-inside-a-c-cpp-application.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@ltorok 
I guess it does look unusual to have a semicolon there. The constant after the semicolon is part of the arguments to the `-outputresource` option of the `mt.exe` command. There's more documentation for the manifest tool (mt.exe) and its options here: [Mt.exe](https://docs.microsoft.com/en-us/windows/win32/sbscs/mt-exe). The examples in that article use an optional `#` character after the semicolon. 
I'm closing the issue, since I don't see a problem in the documentation to be addressed.
