### ISSUE TITLE
Examples would help

### ISSUE THREAD

**Issue by mfstanton** [MicrosoftDocs/cpp-docs#358]
When looking at a file it would be helpful to have an annotated example of what the contents of a stream file would look like should an inquiring mind want to know. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 75473f76-6f26-c392-3ba2-a70d8980a96a
* Version Independent ID: acfb03b7-5d68-e23d-93f8-b911ba09410d
* Content: [What a Stream Is](https://docs.microsoft.com/en-us/cpp/standard-library/what-a-stream-is)
* Content Source: [docs/standard-library/what-a-stream-is.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/standard-library/what-a-stream-is.md)
* Product: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
Hi, @mfstanton - 
This particular document doesn't really seem like the place for that. Since a stream is just an ordered sequence of data, such as the character codes from your keyboard, or the positions and state from your mouse, or the bytes from a file, or from the network. It's all a matter of context. I'd look for descriptions of a particular stream's content in the documents that describe that kind of stream.
