### ISSUE TITLE
What will happen if Mask==0

### ISSUE THREAD

**Issue by kevinjwz** [MicrosoftDocs/cpp-docs#363]
"If a set bit is found, the bit position of the first set bit found is returned in the first parameter."
The remark here is not very clear. If Mask==0, will *Index be written some value, or left unchanged?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b9a85d1-fd99-7639-14ca-78f241efb69d
* Version Independent ID: 6f8cda00-2028-7de7-0afe-a7b8835b4e1c
* Content: [_BitScanForward, _BitScanForward64](https://docs.microsoft.com/en-us/cpp/intrinsics/bitscanforward-bitscanforward64)
* Content Source: [docs/intrinsics/bitscanforward-bitscanforward64.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/intrinsics/bitscanforward-bitscanforward64.md)
* Product: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
Hi, @kevinjwz -

If the return value of the intrinsic is zero, then the value pointed to by the first out parameter is *unspecified*. By not specifying the behavior, the documentation is telling you in very few words that you should make no assumptions, and write your code so that it doesn't matter whether the value is changed or not when a _BitScanForward or _BitScanForward64 intrinsic call returns zero. Otherwise, your code enters the realm of *unspecified behavior*. Not good.

We usually don't say much about unspecified behavior. It would clutter up our documentation without adding much value if we tried to be explicit about it everywhere. We rely on you to recognize where a lack of specification is significant. For example, we mention *errno* where it matters, but not where it doesn't. Thus you can assume that if it wasn't mentioned, it won't be set with a value that's informative about this particular call, but you can't assume that it's unchanged. It's unspecified. Out parameters are similar; their behavior under error conditions is usually unspecified. That's what's going on here.

**Comment by kevinjwz** [comment]
Thanks for your reply!
Intel C++ Compiler also have been supporting these intrinsics for years. However their reference says:

> unsigned char _BitScanForward(unsigned __int32 *p, unsigned __int32 b);
Sets *p to the bit index of the least significant set bit of b or **leaves it unchanged if b is zero**. The function returns a non-zero result when b is non-zero and returns zero when b is zero.

https://software.intel.com/en-us/cpp-compiler-18.0-developer-guide-and-reference-miscellaneous-intrinsics

So, there are some intrinsics in Visual C++ and ICC (and also gcc and clang) that have the same name and signature, but they are not necessarily compatible, in other words, no such "x86 intrinsics standard", right?

**Comment by corob-msft** [comment]
Odds are the MSVC and ICC behavior on Intel architectures is identical. Normally, we don't even document intrinsics that are the same as the hardware vendors' version. The only reason this intrinsic is mentioned in the Microsoft docs is because there's a matching Microsoft-specific ARM implementation, where there isn't a parallel native instruction that I'm aware of. But the general principal is true: do not rely on intrinsics being the same from compiler to compiler, even if they have the same name and signature.

**Comment by kevinjwz** [comment]
Very helpful to me! Thanks!
