### ISSUE TITLE
Status of defect reports may need improvement

### ISSUE THREAD

**Issue by frederick-vs-ja** [MicrosoftDocs/cpp-docs#3660]
### On C++03/11 Core language features (Defect reports)
Most DRs in the section of "C++17 Core language features (Defect reports)" sections should be considered applied to C++03/11, and it seems that MSVC applies these DRs to C++14 mode. Some DRs are listed in "C++20 Core language features".
- The following DRs should be move to **C++03/11 Core language features (Defect reports)**
  - P0702R1 Fixing class template argument deduction for initializer-list ctors
  - P0588R1 Simplifying implicit lambda capture (but it also clarifies that structured bindings can't be captured in C++17)
  - P1825R0 Merged wording for P0527R1 and P1155R3, more implicit moves
  - P0929R2 Checking for abstract class types
  - P0962R1 Relaxing the range-for loop customization point finding rules
  - P0859R0 CWG 1581: When are constexpr member functions defined
  - P1009R2 Array size deduction in new-expressions
  - P1286R2 Contra CWG DR1778
  - P1358R0 CWG 2310: Type completeness and derived-to-base pointer conversions
  - P1969R0 CWG 2382: Array allocation overhead for non-allocating placement new
  - P1969R0 CWG 2441: Inline function parameters

### On C++17 Core language features (Defect reports)
- The following DRs should stay in **C++17 Core language features (Defect reports)**. Some DRs are listed in "C++20 Core language features" and should be moved here.
  - P0961R1 Relaxing the structured bindings customization point finding rules
  - P0969R0 Allowing structured bindings to accessible members
  - P1771R1 [[nodiscard]] for constructors
  - P1968R0 CWG 2282: Consistency with mismatched aligned/non-over-aligned allocation/deallocation functions
  - P1969R0 CWG 2280: Matching a usual deallocation function with placement new

### On C++17 Standard library features (Defect reports)
- The following DRs should be categorized as **C++17 Standard library features (Defect reports)**
  - P0682R1 Repairing Elementary String Conversions
  - P1164R1 Making create_directory() Intuitive
  - P2162R2 Inheriting from std::variant
And we should note that P2162R2 without the feature test macro has been implemented since VS 2019 16.0.

### On C++20 Standard library features (Defect reports)
- The following DR should be moved to **C++20 Standard library features (Defect reports)**
  - P2259R1 Partial LWG issue resolution: repairing Input Range Adaptors and counted_iterator

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d606e0aa-36fd-97f2-6e65-af0f9b05b24c
* Version Independent ID: 207d361a-397e-d687-8828-a152ebc4e572
* Content: [Microsoft C/C++ language conformance](https://docs.microsoft.com/en-us/cpp/overview/visual-cpp-language-conformance?view=msvc-170)
* Content Source: [docs/overview/visual-cpp-language-conformance.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/overview/visual-cpp-language-conformance.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@frederick-vs-ja 

Thanks for the report. I couldn't find an authoritative source that mapped DRs to which versions of the Standard they should be applied to. The list below is all the info I could find while attempting to verify your suggestions.

I found that these DRs were mentioned as fixes against the C++17 standard in [P2131R0 Changes between C++17 and C++20 DIS](https://wg21.link/p2131r0), but not as fixes to earlier standards:
- P0702R1 Fixing class template argument deduction for initializer-list ctors (Modifications to existing features)
- P1825R0 Merged wording for P0527R1 and P1155R3, more implicit moves ("This change is intended as a defect resolution against C++17.")
- P1009R2 Array size deduction in new-expressions ("This change is intended as a defect resolution against C++17.")

"Additionally, the following otherwise unlisted papers were accepted as defect resolutions against C++17:"
- P0588R1 Simplifying implicit lambda capture (but it also clarifies that structured bindings can't be captured in C++17)
- P0859R0 CWG 1581: When are constexpr member functions defined
- P0929R2 Checking for abstract class types
- P0962R1 Relaxing the range-for loop customization point finding rules
- P1286R2 Contra CWG DR1778

It's possible that some of the changes above apply under the default **`/std:c++14`** option, but the internal documentation the compiler team sent to me indicated that these changes were guarded by the **`/std:c++17`** option.

The remaining issues in this list were referred to the CWG, and are mentioned in [C++ Standard Core Language Defect Reports and Accepted Issues](http://www.open-std.org/jtc1/sc22/wg21/docs/cwg_defects.html):

Issues with "DRWP" status (A DR issue whose resolution is reflected in the current Working Paper. The Working Paper is a draft for a future version of the Standard.)
- P1771R1 [[nodiscard]] for constructors

Issues with "CD5" status (A DR/DRWP or Accepted/WP issue not resolved in C++17 but included in the Committee Draft advanced for balloting at the July, 2019 WG21 meeting.)
- P1358R0 CWG 2310: Type completeness and derived-to-base pointer conversions
- P1969R0 CWG 2382: Array allocation overhead for non-allocating placement new

Issues with "C++20" status (a DR/DRWP or Accepted/WP issue not resolved in CD5 but included in ISO/IEC 14882:2020.)
- P1969R0 [CWG 2441](https://wg21.link/CWG2441): Inline function parameters
- P1969R0 CWG 2280: Matching a usual deallocation function with placement new
- P1968R0 CWG 2282: Consistency with mismatched aligned/non-over-aligned allocation/deallocation functions

The library team reported P2162R2 as a C++23 feature, and not specifically as a defect report. They also told me it was governed by /std:c++17, which might be why it was grouped in the C++17 library features, probably because it already worked in the Microsoft STL as of the C++17 feature check. 

It does make sense to create a category for C++17 Standard library features (Defect reports) and put P0682R1 and P1164R1 in there. Similarly, I can move P2259R1 into C++20 Standard library features (Defect reports). I'll move P2162R2 into C++23 Standard library features to match the STL team's labeling, pending further investigation.

The remaining changes you've proposed don't seem justified. Can you tell me more about the source of your information for these changes? Thanks!

**Comment by corob-msft** [comment]
@frederick-vs-ja 
I've fixed the sections I've verified, so I'm closing this issue. However, I'll reopen it if you have documented support for the other changes you mentioned. Let me know what you find out.
