### ISSUE TITLE
Please consider un-deprecating the `_ReadBarrier` intrinsic

### ISSUE THREAD

**Issue by Const-me** [MicrosoftDocs/cpp-docs#3666]
It appears to be the best way to guarantee instructions order with modern optimizing C++ compilers, VS2022 in that case.

See [this stackoverflow question](https://stackoverflow.com/q/70846543/126995) for a use case and a demo.

That’s neither inter-thread communication nor hardware access. Other workarounds do exist like `volatile` keyword or C++ atomics, but they all come at cost, they cause values to be evicted from registers into stack. The `_ReadBarrier` compiles into nothing i.e. free performance-wise, but it does the job by preventing instructions reordering.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee4a0e5b-e0a4-b337-c981-3ef47e1d78f7
* Version Independent ID: 5f89a8cd-b8c6-25ee-1519-1c2dd1f18ff7
* Content: [_ReadBarrier](https://docs.microsoft.com/en-us/cpp/intrinsics/readbarrier?view=msvc-170)
* Content Source: [docs/intrinsics/readbarrier.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/intrinsics/readbarrier.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@Const-me 

I appreciate your suggestion, but you're making it in the wrong place. The documentation team doesn't have much influence on the product itself. If you'd like the development team to take your idea up, then you should let them know directly by creating an issue in the [C++ Developer Community](https://aka.ms/vsfeedback/browsecpp) forum. Check first to see if someone else has made a similar suggestion, which you can upvote. The more upvotes, the more likely the product team is to consider a change. Best of luck.

**Comment by Const-me** [comment]
@corob-msft Hi. But the product works just fine now.

The only thing which needs to be changed is the documentation, to remove the deprecation warning.

Does it still count as influence on the product?

**Comment by corob-msft** [comment]
@Const-me 
The documentation team doesn't decide what's deprecated. We added the deprecation note because the product team told us to. Those intrinsics aren't deprecated because they're going away, they're deprecated in favor of using platform-independent code. I suspect it's because the compiler now has ARM targets that don't have exactly the same kinds of memory ordering facilities, and emulation of these intrinsics in x64 code running on ARM has performance penalties. So, if you want the deprecation warning removed, talk to the product team about why it's deprecated, and they will let us know if we should change the docs.

**Comment by Const-me** [comment]
@corob-msft Got it, thanks.
