### ISSUE TITLE
VCRUNTIME140D APP.dIl was not found.

### ISSUE THREAD

**Issue by adrwstn** [MicrosoftDocs/cpp-docs#3670]
After following the guide I ended up with a "VCRUNTIME140D APP.dIl was not found" error upon attempting to run the Client application. I tried this with UWP DLL and Client application templates as well and had the same result.

Would love to know how to resolve this?

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 08c574a2-cef0-ab13-7375-55851f966ef6
* Version Independent ID: fe3421c7-e9f4-4986-589f-fadaedce583e
* Content: [Walkthrough: Create and use your own Dynamic Link Library (C++)](https://docs.microsoft.com/en-us/cpp/build/walkthrough-creating-and-using-a-dynamic-link-library-cpp?view=msvc-170)
* Content Source: [docs/build/walkthrough-creating-and-using-a-dynamic-link-library-cpp.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/walkthrough-creating-and-using-a-dynamic-link-library-cpp.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@adrwstn

I'm sorry you're having difficulty. This issues board isn't meant for support questions, so you'll probably have more luck on [Microsoft Docs Q&A](https://docs.microsoft.com/en-us/answers/topics/c%2B%2B.html) or the [C++ Developer Community](https://aka.ms/vsfeedback/browsecpp) board.  The vcruntime140d.dll is required by all debug executables, since it has the basic C/C++ runtime startup support in it. I'm not even sure how I'd specify a different name to get the effect you're seeing, other than by explicitly adding "vcruntime140d app.dll" to the dependencies. At any rate, I'm closing your issue as a support issue, not a problem to be solved with a change to the documentation. I wish I could be more help.
