### ISSUE TITLE
Parsing command-line arguments concerns

### ISSUE THREAD

**Issue by mdell-seradex** [MicrosoftDocs/cpp-docs#3682]
I have a few concerns regarding [Parsing C++ command-line arguments](https://docs.microsoft.com/en-us/cpp/cpp/main-function-command-line-args?view=msvc-170#parsing-c-command-line-arguments), specifically because these rules are used to parse .NET command line arguments as well, that I would like to raise.

I don't know if this is truly the proper place to raise this, but I was directed to this location to review these rules.

1. Regular, non-programmer, users do not think in terms of programming and therefore would not think of the `\` character as an escape character.  As such they would not attempt to apply these rules by default.  Typically the `\` is used in a Microsoft Windows style path, and a `"` is not a valid character in paths within Windows.  Most would think that `MyApp.exe "C:\MyFolder\"` is completely valid.
2. These rules are inconsistent in the fact that sometimes `\` is an escape character, specifically only when dealing with the `"`, instead of always being an escape character as is the case within C based languages.
3. Other executables created by Microsoft, that are originally older than these escape character rules, do not follow it.  An excellent example of this is the "Dir" command.  `dir "C:\My Folder\" /ogne` is a valid command that lists directories first, followed by files in order of name then extension, and gives the same results as `dir "C:\My Folder" /ogne`.  One the other hand `dir "C:\My Folder /ogne` is not a valid command in that it produces no results.  Note that I removed that trailing `"` as according to these rules `\"` should transform the `"` into being treated as a literal character instead of ending the string for that parameter.  Since `"` is not valid in a path and would actually produce an incorrect path if it were, I removed it to produce an equivalent command where the path parameter is not closed off.

I think it would make more sense to have this be controlled by the developer instead of being enforced on us.  The default behaviour could be to follow this rules, but allow the developer to opt out of it, perhaps by settings some flag in the parsing routine.

Note that I did raise this as a bug in .NET, but they closed it as "not a bug" and said that they were correct because they were following these rules.
Yes, the user could specify the path without the ending `\`, but several tools that provide paths to use automatically end paths with a `\`, such as the "Macros" in Visual Studio's Pre and Post-build Event Command Line.  As you can see below, several Macro values end in a `\` and many contain spaces which makes the use of `"` required.  Just essentially arbitrarily appending an extra `\` to those seems wrong and is too easy to forget to do.
![image](https://user-images.githubusercontent.com/40300659/152448548-442d88c2-b9ac-43ab-ae8b-aad1d945a51b.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e0c5ec8f-dc90-d0bd-5aa5-1340ccc877c3
* Version Independent ID: 19646aca-3da3-14e8-ea9a-fcb3020cf51c
* Content: [`main` function and command-line arguments (C++)](https://docs.microsoft.com/en-us/cpp/cpp/main-function-command-line-args?view=msvc-170)
* Content Source: [docs/cpp/main-function-command-line-args.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/cpp/main-function-command-line-args.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by mdell-seradex** [comment]
Note that if there is a better place to submit this, please let me know.

Thank you

**Comment by corob-msft** [comment]
@mdell-seradex

I'm sorry to say there probably isn't a good place to make your suggestion. I'm closing your issue because it's not a documentation issue. If you'd like to raise a product issue for the C++ team, you can do that on [Developer Community](https://aka.ms/vsfeedback/browsecpp). I'm not aware of a good public forum to communicate with the Windows development team.

The command-line parsing behavior is based on a combination of how Windows' cmd.exe parsing works with how the C runtime startup code works. It's worked this way for more than 25 years, at least since Windows 95 introduced long paths. Any change would break untold numbers of apps, so making any change is an uphill battle.

Not all apps use the C runtime startup code, so they're free to use different behavior with the command-line string that Windows provides when their process is started. You can customize the C runtime startup argument parsing behavior yourself, so you're not limited to the standard command-line interpretation. If you link the `noarg.obj` file to your app, that turns off the default argument processing. You can get the raw command-line string directly by using the Windows [`GetCommandLine`](https://docs.microsoft.com/en-us/windows/win32/api/processenv/nf-processenv-getcommandlinea) function. This is the same call the C runtime startup code uses to get the command line.

If you're using cmd.exe to launch your app, you should be aware that the command line may have already gone through one layer (or in the case of a batch file, two layers) of escape interpretation. Windows also has a function [`CommandLineToArgvW`](https://docs.microsoft.com/en-us/windows/win32/api/shellapi/nf-shellapi-commandlinetoargvw) that acts just like the C runtime argument processor.

**Comment by mdell-seradex** [comment]
@corob-msft Thank you for taking your time to review and respond.
I am honestly extremely surprised that ANY apps really on these (IMHO) janky rules.  It just seems like they would cause more headaches instead of helping.  You can see from my example how one app, albeit run inside a command window, does not follow these rules, and that app has existed much longer than these rules have.  I would think that escaping a `"` by specifying it as `""` as some other things do, would be simpler and make more sense.  It would also be consistent behaviour for the character.  Likely the best way would be to have some way to specify an escape character, or how quotes should be altered to be treated as a literal character.

Note that I was essentially directed here from that area (the Developer Community), however it was from the .NET section.
They did not even try to suggest redirecting the request to the C++ group/section.

In the end, I did write my own command line parser, but I thought I would try raising my concerns with another group.

At least, if this does not get purged, this provides something that could allow others to become aware of, and to consider what makes more sense to them.

Again, thank you.
