### ISSUE TITLE
not Multi-Platform

### ISSUE THREAD

**Issue by lhksoft** [MicrosoftDocs/cpp-docs#3699]
[Enter feedback here]

In VS2022 I get a lot of these warnings, but when I follow the instructions and make my enums 'enum class'-enums, it all compiles well in VS but as soon i try to compile this code in linux (using gpp) I will get errors in there.

I code multi-platform code; code that must compile and link for Win10 and also in linux.
So I gues this is typically MSW desired, but not GTK (don't know about the other platforms). I compile using the c++14 standard.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: acf7794d-48cb-0ace-c071-59c9a8ccf2b0
* Version Independent ID: d15818cc-3f5f-e618-6c8b-78ca0bbf7443
* Content: [c26812](https://docs.microsoft.com/en-us/cpp/code-quality/c26812?f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(C26812)%26rd%3Dtrue&view=msvc-170)
* Content Source: [docs/code-quality/c26812.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/code-quality/c26812.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@lhksoft 
Thanks for the feedback. Warning C26812 implements one of the [ISO C++ Core Guidelines](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#enum3-prefer-class-enums-over-plain-enums) warnings. These guidelines are published by the ISO C++ committee and are meant to be compiler independent. An `enum class` declaration shouldn't cause a problem for gcc. Without context, I couldn't tell you what's wrong there, and this isn't a support forum. Sorry I can't be more help. Since I don't see a problem I can address in our documentation, I'm closing the issue.
