### ISSUE TITLE
Example in C4686 does not work

### ISSUE THREAD

**Issue by tiagomacarios** [MicrosoftDocs/cpp-docs#3714]
The example listed for warning C4686 does not work does not trigger the warning: https://godbolt.org/z/1rK6EszWc

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dcb5fec6-3bee-29c7-dd4c-9663f0a72604
* Version Independent ID: eac28ce4-7d5b-14eb-3804-6143304f3aab
* Content: [Compiler Warning (level 3) C4686](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-3-c4686?view=msvc-160&viewFallbackFrom=vs-2017)
* Content Source: [docs/error-messages/compiler-warnings/compiler-warning-level-3-c4686.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/error-messages/compiler-warnings/compiler-warning-level-3-c4686.md)
* Product: **visual-cpp**
* Technology: **cpp-diagnostics**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@tiagomacarios 

Thanks for the report. The warning was added to Visual C++ 2003, at which time I'm sure the example could demonstrate it. It's still emitted in at least one place in the parser, but it's likely that compiler changes have made this warning effectively unreachable at least as far back as VS 2017, and possibly earlier. I spied this comment (undated but before mid-2017, as far back as the Git history goes) in the parser code where the warning is emitted:
```
// This warning is currently disabled. It was intended to catch cases in which the function return
// convention changes (from C-style to C++-style). This can happen if if the function is
// specialized (but not called) when the return type is undefined (in which case the compiler will
// assume that it is a C-style return) and then later when it is called the return type defined. I
// am not 100% that this code still works but I am not currently inclined to change it - especially
//as it is off-by-default.
```
It looks like the case where "the compiler will assume that it is a C-style return" may be hard to exercise. It may have been true at the time, but now it appears to only happen in circumstances where specialized return types are impossible, such as `extern "C"` blocks.

The dev team doesn't maintain test suites that exercise every diagnostic the compiler can emit. I definitely don't recommend treating the documentation as a specification for creating such tests. We document several diagnostics that the compiler no longer emits, because some readers use old compilers that do emit those warnings. If we're aware of when that change happened, we'll include a comment to that effect. However, the dev team are not in the habit of telling us when diagnostics are obsolete. They barely tell us about new ones.

**Comment by gdr-at-ms** [comment]
> We document several diagnostics that the compiler no longer emits, because some readers use old compilers that do emit those warnings.

Maybe one thing we could consider is to have the doc clearly label the warnings that are no longer emitted by current toolset.  I understand that it may be not possible to have an exhaustive list of such diagnostics, but overtime we should be able to get close to that ideal.

> If we're aware of when that change happened, we'll include a comment to that effect. However, the dev team are not in the habit of telling us when diagnostics are obsolete. They barely tell us about new ones.

It sounds like this might be a communication gap. Would you mind having a request to the toolset team to have a document for newly added diagnostics or removed diagnostics akin to what is done for the "conformance improvements page" for each release?

**Comment by TylerMSFT** [comment]
Thank you for your patience as we work through our backlog. We have received more issues than we can manage at this time. We are closing issues based on their severity, how broadly applicable they are, and whether there is enough information provided to act on the issue. If you believe that this issue should not have been closed, please add a comment explaining why by 3/1/2024. We appreciate your contribution and encourage you to propose changes using public PRs, or submit feedback through our updated control at the top of the page, as we phase out Git Issues for this repo. For more information on our feedback systems, see https://aka.ms/ContentUserFeedback.
