### ISSUE TITLE
No iterator for CArray

### ISSUE THREAD

**Issue by PieterSchumacher** [MicrosoftDocs/cpp-docs#3724]
CArray does not offer an iterator and lacks support for functional programming paradigms. 
To iterate over this object, the only way AFAIK is to create a for/while loop which extracts the first index with .GetCount(),
increments it each loop and accesses the object with []-notation.
Kind of frustrating, to be honest, doesn't exactly make it encouraging to use when it forces one and only one paradigm.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86ca9f18-f27f-6526-2a65-491251020ca6
* Version Independent ID: 9777adf9-55e2-c981-b488-06220c87deb9
* Content: [CArray Class](https://docs.microsoft.com/en-us/cpp/mfc/reference/carray-class?view=msvc-170)
* Content Source: [docs/mfc/reference/carray-class.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/mfc/reference/carray-class.md)
* Product: **visual-cpp**
* Technology: **cpp-mfc**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by corob-msft** [comment]
@PieterSchumacher 

I understand your frustrations. The MFC library was first released in 1992, which means the design for `CArray` is now thirty years old. It predates the public release of the (originally independent) STL by a couple of years. Iterators weren't added to the C++ standard until years later. Iterators are just one of many modern programming paradigms that MFC doesn't support well, if at all. Since there isn't much we can do about it in the documentation, I'm going to acknowledge your complaint, then close the issue as not actionable. If you want to propose an update to the MFC code itself, you can do that in the IDE: open **Help** > **Send Feedback** > **Suggest a Feature** and make your case. If it gets enough upvotes on [Developer Community](https://aka.ms/vsfeedback/browsecpp), it's just possible it could be added to the product. Best of luck.
