### ISSUE TITLE
This page does not look like my freshly installed VS 2019 16.11.10

### ISSUE THREAD

**Issue by anyonecan** [MicrosoftDocs/cpp-docs#3746]
VS 2016 seemed to break itself on an update, I tried to install again, but it failed. Uninstalled and installed and that went ok.

When I load the project I worked on yesterday, it will not compile, and shows 

Error	MSB8041	MFC libraries are required for this project. Install them from the Visual Studio installer (Individual Components tab) for any toolsets and architectures being used.	Project1	C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets	479	

I've tried adding MFC and using templates as suggested on this page, but the examples have the same problem.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0128902a-afb9-2399-a378-3d5d6ca046b4
* Version Independent ID: 484ada2f-c1ed-1a3d-9d19-5bbfcb1cc705
* Content: [Creating an MFC Application](https://docs.microsoft.com/en-us/cpp/mfc/reference/creating-an-mfc-application?view=msvc-160)
* Content Source: [docs/mfc/reference/creating-an-mfc-application.md](https://github.com/Microsoft/cpp-docs/blob/main/docs/mfc/reference/creating-an-mfc-application.md)
* Product: **visual-cpp**
* Technology: **cpp-mfc**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by corob-msft** [comment]
@anyonecan 

I'm sorry you're having trouble. I don't see a difference between the UI in Visual Studio 2019 and the images in [Creating an MFC Application](https://docs.microsoft.com/en-us/cpp/mfc/reference/creating-an-mfc-application?view=msvc-160). 

The error message suggests you run the Visual Studio Installer and reinstall the MFC library that matches your build configuration. You'll find those if you choose **Modify** for Visual Studio 2019 on the main installer page, then select the **Individual Components** tab, then search for "MFC". Select either **C++MFC for latest v142 build tools (x86 & x64)** or **C++MFC for latest v142 build tools with Spectre Mitigations (x86 & x64)**, depending on whether you're building with Spectre mitigations or not. Choose **Install while downloading**, then close out of the installer. See if that helps.

If this component is already installed, but the behavior changed as the result of an update, odds are good that it's a product bug, not a documentation issue. To report a product issue, you can go to the **Help** menu in the IDE, select **Send Feedback** and then select **Report a Problem**. Or you can enter an issue on [Developer Community](https://aka.ms/vsfeedback/browsecpp) and search for similar issues and solutions that may have already been posted. 

I'm closing this, as it doesn't appear to be a documentation issue. Best of luck.

**Comment by anyonecan** [comment]
Hello Colin,

It got to the point where I had to work on that program some more so I
tried your suggestion but still got an error message similar to

MSB8041 MFC libraries are required for this project.

There is a useful discussion at
https://developercommunity.visualstudio.com/t/msb8041-mfc-libraries-are-required-for-this-projec/1321059

That reveals that

   1.

   If you just build with the Platform Toolset: Visual Studio 2019 (v142),
   please install:
   MSVC v142 - VS 2019 C++ x64/x86 build tools (v14.28)
   C++ MFC for latest v142 build tools (x86 & x64)
   C++ ATL for latest v142 build tools (x86 & x64)

After making sure I had all 3 of these (I didn't at first; I have no idea
why they got lost and things quit working), my program compiled. The
discussion also suggests that the error message be made more useful. The MS
reply was 'please submit a suggestion'. I would, but there is no link on
the page. I tried from the IDE, 'help, submit feedback' as you suggested,
but that told me that the feedback thingee had disconnected from VS 2019
and that I could continue un-connected. I did that, and it said I should
report a problem from the IDE. Maybe later.

John

**Comment by corob-msft** [comment]
@anyonecan 

Thanks for the update. I don't know how much more info can be crammed into the command-line build output error message, but we do have an article that a search for MSB8041 should take you to immediately: [MSBuild error MSB8041](https://docs.microsoft.com/en-us/visualstudio/msbuild/errors/msb8041?view=vs-2022). I can update this article, since I wrote it. I see that I left out the ATL component descriptions there. I don't think that the MSB8041 error message is the one you'll see if you have the wrong or missing MSVC build tools, so that shouldn't need to be addressed by this error doc.

There's another thing to note: When you first installed Visual Studio or Visual Studio Build Tools, and chose the Desktop development with C++ workload, it should have selected a version of the MSVC build toolset as one of the optional components by default. (You can add more if you target more than x86/x64.) However, for MFC and ATL support, you need to manually select the C++ MFC and ATL library components. (You can add them later by running the installer, choosing **Modify** for your VS version, then selecting them under the **Individual components** tab.) If you choose the components labeled **Latest**, then the installer will update them to the latest version whenever you apply an update to VS. However, if you install a *specific version number*, then the installer will *not* update that component when you update VS. It assumes that you meant what you said with that version choice, and doesn't try to second guess you. So, in your case, if you installed **MSVC v142 - VS 2019 C++ x64/x86 build tools (v14.28)**, you won't get updates to the build tools if you update Visual Studio, but if you install **MSVC v142 - VS 2019 C++ x64/x86 build tools (Latest)**, you *will* get updates.
