### ISSUE TITLE
Not found option

### ISSUE THREAD

**Issue by superkid200** [MicrosoftDocs/cpp-docs#375]
Compiler Options category is missing from C/C++ category

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 89431f9e-838a-2a66-2e0b-346bd22b8cb6
* Version Independent ID: 099eeea8-2713-0307-e497-6412c2732f50
* Content: [Setting Compiler Options](https://docs.microsoft.com/en-us/cpp/build/reference/setting-compiler-options)
* Content Source: [docs/build/reference/setting-compiler-options.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/reference/setting-compiler-options.md)
* Product: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
I think I understand the source of your confusion. There are nine compiler options categories under C/C++, from **General** to **Advanced**, plus an **All Options** page that collects all of the options in one place, and a **Command Line** page that shows the command line that the options turn into. There isn't one named **Compiler Options**, which is why it's styled as plain text and in lower case, not bold like other UI elements. I hope this clears the meaning up for you.
