### ISSUE TITLE
The pinned array example is ignoring element 0 

### ISSUE THREAD

**Issue by rochar** [MicrosoftDocs/cpp-docs#3768]
Hi,

In the example, the statement  `pin_ptr<Byte> p = &arr[1];   // entire array is now pinned`. 

I think the intended is `pin_ptr<Byte> p = &arr[0];   // entire array is now pinned`.

Thanks
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0259481-60e5-611e-7cff-6c5c431e1b08
* Version Independent ID: 33caa807-8ccc-d371-2578-a984f58b204b
* Content: [How to: Pin Pointers and Arrays](https://docs.microsoft.com/en-us/cpp/extensions/how-to-pin-pointers-and-arrays?view=msvc-170)
* Content Source: [docs/extensions/how-to-pin-pointers-and-arrays.md](https://github.com/Microsoft/cpp-docs/blob/main/docs/extensions/how-to-pin-pointers-and-arrays.md)
* Product: **visual-cpp**
* Technology: **cpp-cli**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@rochar 
Thanks for commenting. The use of `&arr[1]` here is intentional, since the point of the article is that pinning any sub-object is sufficient to pin the entire object, including `arr[0]`. Not that this is a good way to pin the array, but rather, to explain why the entire array is pinned even if you only pinned one element in it. I hope that clarifies the intent.
