### ISSUE TITLE
Error C2956 needs a description page.

### ISSUE THREAD

**Issue by ET3D-ET3D** [MicrosoftDocs/cpp-docs#3797]
It's an unclear error and there's no indication of how it can be solved. This should be documented with an example of correct usage.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a94c8021-cfac-d43a-6dda-9bd51fcf18e9
* Version Independent ID: 77f3bf3a-7ba2-cc0f-58f8-b078ea919c56
* Content: [Compiler errors C2900 Through C2999](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-errors-2/compiler-errors-c2900-through-c3499?view=msvc-170)
* Content Source: [docs/error-messages/compiler-errors-2/compiler-errors-c2900-through-c3499.md](https://github.com/Microsoft/cpp-docs/blob/main/docs/error-messages/compiler-errors-2/compiler-errors-c2900-through-c3499.md)
* Product: **visual-cpp**
* Technology: **cpp-diagnostics**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@ET3D-ET3D 

Thanks for the request. We're working on it. The short answer is, don't use placement new syntax with a signature that matches one of the default `operator new` allocators. It causes problems (such as a memory leak or a crash) either in the deallocator called implicitly by the compiler on allocation failure or in the `delete` call for whatever you allocated. It's okay to use placement new syntax for non-allocating placement new (of course) and for `operator new` allocators you write with other signatures (extra parameters, etc.). One signature in particular (`void * operator new(size_t, size_t)`) is problematic, because it used to be acceptable to invoke via placement new syntax, but C++14 changed the rules.

**Comment by ET3D-ET3D** [comment]
Thanks. I was just trying to align a char array allocation, and found https://developercommunity.visualstudio.com/t/using-c17-new-stdalign-val-tn-syntax-results-in-er/528320, which suggests to me that the error is a result of a (three year old) compiler bug. The post did offer a solution, so there's at least that.

**Comment by corob-msft** [comment]
@ET3D-ET3D 

Yes, the bug in the DevCom issue you cite is that you don't get a diagnostic when you directly invoke `::operator new` with one of the standard allocator signatures. The "workaround" is just as dangerous as the code that raises the error, but arguably worse because the compiler doesn't tell you. Your code still has a new/delete signature mismatch that you can't even see, because it's generated by the compiler as part of the exception handling code for the constructor. That's even if you remember to invoke the matching `::operator delete` correctly for your aligned allocator, which is easy to forget. Undefined behavior abounds here. 

If you want to do a special alignment on a char array, I'd recommend you define a struct that contains your array, and apply an `alignas(power_of_two)` specification to the struct. Then use plain old new and delete calls. The compiler will take care of the alignment for you behind the scenes, and your code will be cleaner. (If you want to get fancy, define `operator[]` on your struct to get rid of an indirection level.)

**Comment by corob-msft** [comment]
I'm sorry to be the bearer of [bad news](https://docs.microsoft.com/en-us/cpp/overview/visual-cpp-language-conformance?view=msvc-170#note_M).

**Comment by ET3D-ET3D** [comment]
Ah, so it's bad OS design. ;)

Thanks a lot for all of this, it's been illuminating.

**Comment by corob-msft** [comment]
A C2956 article is complete and should be visible sometime tomorrow.
