### ISSUE TITLE
property pages

### ISSUE THREAD

**Issue by alicera** [MicrosoftDocs/cpp-docs#3799]
https://docs.microsoft.com/zh-tw/cpp/build/reference/vcpp-directories-property-page?view=msvc-170

my project is create by File > New > file , add a *.cpp file
Then I click right click on solution Explorer no find any property pages.
If I git clone other project and click right click on solution Explorer no find any property pages.

But create by File > New > project , I can fin d the property pages.

**Comment by corob-msft** [comment]
@alicera 

The Property Pages dialog box described in the article shows what you'll see if you select a **Project** node in Solution Explorer. Project Properties require a *`.vcxproj`*  file (a Microsoft Visual C++ native project file based on MSBuild) to host the properties. If there is only a C++ file in your solution, you'll see the properties of the file, not the properties of a project. Not all solution types support Property Pages. For example, a CMake project uses *.`json`* files such as *`CMakePresets.json`* instead of Property Pages. I hope this helps clear up any confusion. Best of luck with your code.
