### ISSUE TITLE
could not find library

### ISSUE THREAD

**Issue by alicera** [MicrosoftDocs/cpp-docs#3802]
I have a cmake project from existing code.[spdlog](https://github.com/gabime/spdlog)
When I build it with visual studio, it show could not find fmt (library).
How can I import library https://github.com/fmtlib/fmt

I search some example, but it seem to use cpp not the cmake. So I cant find the interface
![image](https://user-images.githubusercontent.com/59388989/160527335-8376779c-d10f-4c26-9824-78c2bffa106e.png)
Does it use another method to search library for cmake project?
https://subwaymatch.medium.com/opencv-410-with-vs-2019-3d0bc0c81d96

**Comment by corob-msft** [comment]
@alicera 

I'm sorry, we don't have the bandwidth to do customer support here. For adding common libraries to your projects, I recommend [vcpkg](https://vcpkg.io/). For general programming and development questions, I recommend [Microsoft Docs Q&A](https://docs.microsoft.com/en-us/answers/topics/c%2B%2B.html). For issues with Visual Studio and the toolsets, I recommend asking on [Developer Community](https://aka.ms/vsfeedback/browsecpp). [StackOverflow](https://stackoverflow.com/) is also an excellent resource. Since this doesn't appear to be an issue in documentation, I'm closing it. Good luck with your project.

**Comment by alicera** [comment]
I think it is easy. But I dont know how to start with visual studio.
I just git clone https://github.com/gabime/spdlog with visual studio.
And run the cmakelist to build. If I need some library on cmakelist. Like fmt. I build it by myself because I have some fix with fmt. fmt will produce fmt.lib.
Now visual studio 2019 IDE how to include fmt.lib?
