### ISSUE TITLE
"scroll to find and open the folder for your version of Visual Studio"

### ISSUE THREAD

**Issue by sharrop** [MicrosoftDocs/cpp-docs#3805]
[Enter feedback here]
I cannot parse this sentence:
"On the desktop, open the Windows Start menu, and then scroll to find and open the folder for your version of Visual Studio, for example, Visual Studio 2019."

Are you saying that I should:
A. Open Visual Studio and find a folder within Visual Studio?
B. Find the folder in which Visual Studio is installed (...somehow)?
C. Just navigate to an installed version of Visual Studio in the Start Menu (nothing else)?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45e8226e-799c-2e3b-01c6-d7603141d5ca
* Version Independent ID: 4f7cd478-ffcc-bec5-b61a-e17085ccd6f5
* Content: [Use the Microsoft C++ toolset from the command line](https://docs.microsoft.com/en-us/cpp/build/building-on-the-command-line?view=msvc-160#developer_command_prompt)
* Content Source: [docs/build/building-on-the-command-line.md](https://github.com/Microsoft/cpp-docs/blob/main/docs/build/building-on-the-command-line.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@sharrop 

If you're using Windows 11, there's an extra step after "open the Windows Start menu" and before "and then scroll to find and open the folder", namely, "choose the All apps button". The document was written before the UI changes for Windows 11, and since it doesn't mention Windows 10 specifically, we didn't spot it in our sweep to update UI descriptions.

**Comment by corob-msft** [comment]
Windows 11 issue addressed.
