### ISSUE TITLE
add find_package function page

### ISSUE THREAD

**Issue by alicera** [MicrosoftDocs/cpp-docs#3806]
https://docs.microsoft.com/en-us/cpp/build/cmake-projects-in-visual-studio?view=msvc-160

I see the visual studio document.
I don't find the find_package() method with visual studio.
Assume not use vcpkg.
Assume not use vcpkg.

Here is my experiment for minum reproduce:

method 1 (without visual studio 2019)
I build a cmake project and the cmakelist.txt is 
```
cmake_minimum_required(VERSION 3.19)
find_package(opencv REQUIRED)
```
I build the opencv by myself. And I set the env to windows 
build it on command prompt 2019.

method 2 (with visual studio 2019)
I build a cmake project and the cmakelist.txt is 
```
cmake_minimum_required(VERSION 3.19)
find_package(opencv REQUIRED PATHS D:/TEST/opencv/release NO_DEFAULT_PATH)
```

Are there other ways to assign the path with visual studio 2019, besides the method 2?

**Comment by corob-msft** [comment]
@alicera 
I'm sorry about the delayed response. If you don't or can't use vcpkg, Visual Studio doesn't have another way to search for your packages. As far as I know, you have to specify the location to [`find_package`](https://cmake.org/cmake/help/latest/command/find_package.html) as you've done in your example. Since this seems like a support question rather than a documentation issue, I'm closing it. Good luck with your code.
