### ISSUE TITLE
Pointers and enums take up storage too.

### ISSUE THREAD

**Issue by patricksmyth** [MicrosoftDocs/cpp-docs#3808]
There is no mention of pointer types or enums on this page.
It could do with an explanation of how much memory a pointer or an enum takes up.
I know you can argue they are not basic types but where else is this information?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83386aa8-a4c9-6363-e3e3-981ddb73d9dd
* Version Independent ID: 426ed853-7ac3-cfbc-1bd9-9c6365da4a53
* Content: [Storage of basic types](https://docs.microsoft.com/en-us/cpp/c-language/storage-of-basic-types?view=msvc-170)
* Content Source: [docs/c-language/storage-of-basic-types.md](https://github.com/Microsoft/cpp-docs/blob/main/docs/c-language/storage-of-basic-types.md)
* Product: **visual-cpp**
* Technology: **cpp-c-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@patricksmyth 

That's a good question. The problem here is, the answer isn't fixed. The size of an enumeration type may depend on the enumeration member range. In C++, you can specify an underlying representation for an enum class type, though I don't think that's possible in C. The size of a pointer type depends on the target architecture: in MSVC, it's 4 bytes in code for 32-bit platforms, and 8 bytes in code for 64-bit platforms. You can determine the size at runtime for pointers or enum types by using the `sizeof` operator.

**Comment by patricksmyth** [comment]
These seem like good explanations to me. My issue is that the documentation does not tell me this and I think it probably should.

**Comment by TylerMSFT** [comment]
Thank you for your patience as we work through our backlog. We have received more issues than we can manage at this time. We are closing issues based on their severity, how broadly applicable they are, and whether there is enough information provided to act on the issue. If you believe that this issue should not have been closed, please add a comment explaining why by 3/1/2024. We appreciate your contribution and encourage you to propose changes using public PRs, or submit feedback through our updated control at the top of the page, as we phase out Git Issues for this repo. For more information on our feedback systems, see https://aka.ms/ContentUserFeedback.
