### ISSUE TITLE
Docs for Windows::Foundation::ActivateInstance and friends are missing

### ISSUE THREAD

**Issue by DJm00n** [MicrosoftDocs/cpp-docs#3811]
I trying to find docs for `Windows::Foundation` methods from `roapi.h` (C++ wrappers):

There should docs for several methods from Windows::Foundation namespace:

- `Windows::Foundation::Initialize`
- `Windows::Foundation::Uninitialize`
- `Windows::Foundation::ActivateInstance`
- `Windows::Foundation::RegisterActivationFactories`
- `Windows::Foundation::RevokeActivationFactories`
- `Windows::Foundation::GetActivationFactory`

Methods with same names are present from `ABI::Windows::Foundation` namespace (need to clarify for which purpose they are).

I only have found this so far: https://docs.microsoft.com/en-us/windows/win32/api/roapi/nf-roapi-initialize

Seems docs for these C++ wrappers are missing.

PS: Docs for C-style methods are here - https://docs.microsoft.com/en-us/windows/win32/api/roapi/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 91f44a05-929c-8ed0-4949-0adb55786a6c
* Version Independent ID: 98e7b850-5ac6-f9b5-02b2-6177b8ce4109
* Content: [Windows::Foundation Namespace](https://docs.microsoft.com/en-us/cpp/cppcx/wrl/windows-foundation-namespace?view=msvc-170)
* Content Source: [docs/cppcx/wrl/windows-foundation-namespace.md](https://github.com/Microsoft/cpp-docs/blob/main/docs/cppcx/wrl/windows-foundation-namespace.md)
* Product: **visual-cpp**
* Technology: **cpp-cx**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by stevewhims** [comment]
Hi, @DJm00n, I'm triaging this as a writer who works on the Windows SDK (and the Windows App SDK). Looking in those SDKs, I couldn't find a header file that defines the APIs you mention (I could find one place where one of those APIs was *called*).

So it's not clear to me where those APIs come from. You mention that they're "C++" wrappers. But I'd need to know which SDK header file they're in in order to be able to document them. The ABI:: APIs are for the application binary interface of the Windows Runtime. So those wouldn't be APIs we'd doc, either.

-Steve

**Comment by stevewhims** [comment]
I'm unable to close this issue, so assigning back to @TylerMSFT just to close. :)
