### ISSUE TITLE
found a bug

### ISSUE THREAD

**Issue by sumang13** [MicrosoftDocs/cpp-docs#3824]
[Enter feedback here]
The realloc function reports an error.

invalid conversion from 'void*' to 'long int*' [-fpermissive]

I'm guessing you forgot to add (long *).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b80bdfbd-3324-0b2e-7fac-35d19bac8233
* Version Independent ID: 8566607c-e99e-4c57-fede-4fe256f25cd9
* Content: [realloc](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/realloc?view=msvc-170)
* Content Source: [docs/c-runtime-library/reference/realloc.md](https://github.com/Microsoft/cpp-docs/blob/main/docs/c-runtime-library/reference/realloc.md)
* Product: **visual-cpp**
* Technology: **cpp-ucrt**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by corob-msft** [comment]
@sumang13 

The [`realloc`](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/realloc?view=msvc-170) function returns a `void *` type. C++, unlike C, requires an explicit cast from `void *` to the type you assign allocated memory to. In other words, change your code like this to cast the return values of `malloc` or `realloc` to the type you actually use:

```
// declare a pointer to long and allocate space for 4 long elements
long * pli = static_cast<long *>(malloc(4 * sizeof(long)));
// make the memory allocation larger to hold 16 long elements
pli = static_cast<long *>(realloc(pli, 16 * sizeof(long)));
```

Since this doesn't appear to be a documentation problem, I'm closing the issue.
