### ISSUE TITLE
Ambiguous information

### ISSUE THREAD

**Issue by Ma-XX-oN** [MicrosoftDocs/cpp-docs#383]
> The difference between _malloca and _alloca is that _alloca always allocates on the stack, regardless of the size. 

Does this mean that if `_malloca()` fails to allocate on the stack, it will try to allocate on the heap?  If so, what is the tipping point to move allocation from the stack to the heap?  Failure points and possible alternatives should be fully specified.  The **Return Value** section doesn't clarify this information:

> A stack overflow exception is generated if the space cannot be allocated. The stack overflow exception is not a C++ exception; it is a structured exception.

Cannot be allocated on the stack?  Or stack/heap?  Please be more explicit.  Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 55bba62c-ab27-2f7a-de3a-e603895a08e4
* Version Independent ID: b710b0f8-b23b-e268-b21d-de12b3047d03
* Content: [_malloca](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/malloca)
* Content Source: [docs/c-runtime-library/reference/malloca.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/c-runtime-library/reference/malloca.md)
* Product: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@Ma-XX-oN I'm sorry about any confusion. Since the **_malloca** documentation doesn't say it retries failed stack allocations on the heap, or vice versa, you can safely conclude that it does not. That's the kind of advanced behavior that would definitely be documented. It would be strange to specifically state all the advanced things that the implementation doesn't do. Where would you stop?

You can see the implementation for yourself by looking at the definition of **_malloca** in \<malloc.h>. It's a macro, and in retail builds, it switches between a call to either `_alloca` or `malloc` , allocating from the stack if the request is less than or equal to **_ALLOCA_S_THRESHOLD**, and from the heap if the request is larger. In debug builds, it just calls `malloc`. A stack overflow exception is generated if the space cannot be allocated, whether the allocation is attempted from the stack or the heap, so there's no need to call out heap and stack behavior separately in the Return Value section.

Since this behavior matches a straightforward reading of the documentation, I'm not sure what to change.  For clarity, I could add a comma and a preposition here:

> **_malloca** allocates *size* bytes from the program stack, or from the heap if the request exceeds a certain size in bytes given by **_ALLOCA_S_THRESHOLD**.

Would this help?
