### ISSUE TITLE
ARM64 assembler exception handling

### ISSUE THREAD

**Issue by GameGameNoGG** [MicrosoftDocs/cpp-docs#3844]
I'm looking into writing some arm64 assembler code, and was wondering if there is something like this: [.PUSHREG](https://docs.microsoft.com/ms-my/cpp/assembler/masm/dot-pushreg?view=msvc-160) 
for arm64 assembler, i.e. directives that have to be set for proper exception handling?

**Comment by corob-msft** [comment]
The Microsoft ARM64 armasm assembler doesn't support the same directives as the ML/ML64 assemblers. It [supports a subset](https://docs.microsoft.com/en-us/cpp/assembler/arm/arm-assembler-directives?view=msvc-170) of the [standard armasm directives](https://developer.arm.com/documentation/dui0802/b/Directives-Reference/Alphabetical-list-of-directives). The examples of unwind codes I've seen are just the raw instructions, as shown in [ARM64 exception handling](https://docs.microsoft.com/en-us/cpp/build/arm64-exception-handling?view=msvc-170). Hope that's useful. Since the issue here doesn't appear to be a doumentation issue, I'm closing it.

**Comment by GameGameNoGG** [comment]
Thanks for taking time.
