### ISSUE TITLE
The sample code which generates a warning and the supposed fix are exactly the same...

### ISSUE THREAD

**Issue by dbowser** [MicrosoftDocs/cpp-docs#3866]
Maybe I am missing something but I fail to see any difference between the two code samples.
I am getting the warning when I am bounds checking the index so would really like to know more about what is happening here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a1d6c74-a51c-b51b-17a8-23ec1c2f68e1
* Version Independent ID: d7a63ea5-0aa0-bd24-1e04-7f5a0b51037c
* Content: [C6385](https://docs.microsoft.com/en-us/cpp/code-quality/c6385?view=msvc-170)
* Content Source: [docs/code-quality/c6385.md](https://github.com/Microsoft/cpp-docs/blob/main/docs/code-quality/c6385.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@dbowser 
There is a small but significant difference on the fifth line of the examples, which is the difference between staying in bounds and stepping past the end of the array. Off-by-one errors are fairly common when you use indexes in `for` loops, which is why it's often a good idea to use a [range based `for`](https://docs.microsoft.com/en-us/cpp/cpp/range-based-for-statement-cpp?view=msvc-170) instead. It's a more invasive fix, which is why it's not illustrated here, but it's probably better from a software engineering standpoint. Raw loops are an invitation to consider use of containers and algorithms, too. I'm closing the issue as it doesn't seem to require a fix. Best of luck with your code.
