### ISSUE TITLE
BK4504 help needs to mention and help with Visual Studio headers sometimes triggering it.

### ISSUE THREAD

**Issue by jb-wisemo** [MicrosoftDocs/cpp-docs#3869]
Note that this warning is sometimes generated by at the `mshtml.h` header included with Visual Studio 2015, and possibly other Microsoft supplied files.  No known workaround has been given.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 368fe708-accd-c31f-89f0-10f11264a5dc
* Version Independent ID: 1971168a-3a07-730c-9c89-a2a8b1a8ac8b
* Content: [BSCMAKE Warning BK4504](https://docs.microsoft.com/en-us/cpp/error-messages/tool-errors/bscmake-warning-bk4504?f1url=%3FappId%3DDev14IDEF1%26l%3DEN-US%26k%3Dk(BK4504)%26rd%3Dtrue&view=msvc-170)
* Content Source: [docs/error-messages/tool-errors/bscmake-warning-bk4504.md](https://github.com/Microsoft/cpp-docs/blob/main/docs/error-messages/tool-errors/bscmake-warning-bk4504.md)
* Product: **visual-cpp**
* Technology: **cpp-diagnostics**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@jb-wisemo 
Thanks for the report. The BSCMake tool hasn't been used by Visual Studio for tracking symbols since 2005. As far as I'm aware, its only practical use thereafter was for some third party code analysis tools that are now effectively obsolete. The doc does mention some possible workarounds, such as [`#pragma component (browser, off)`](https://docs.microsoft.com/en-us/cpp/preprocessor/component?view=msvc-170) wrapped around includes of problematic headers. While we'll attempt to address any egregious defects in the documentation for BSCMake, this info doesn't appear to meet that bar.
