### ISSUE TITLE
how to edit a property sheet

### ISSUE THREAD

**Issue by ArsMasiuk** [MicrosoftDocs/cpp-docs#3874]
It is unclear how to edit a property sheet.
When saved, it is always empty.
Can I export properties of a certain project and then apply the sheet for all the projects in the solution?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4d14bcc9-b174-5949-035e-678a3939f031
* Version Independent ID: 03017dba-6921-5b6e-b6df-05a9d955da3d
* Content: [Share or reuse Visual Studio project settings - C++](https://docs.microsoft.com/en-us/cpp/build/create-reusable-property-configurations?view=msvc-170)
* Content Source: [docs/build/create-reusable-property-configurations.md](https://github.com/Microsoft/cpp-docs/blob/main/docs/build/create-reusable-property-configurations.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@ArsMasiuk 

I'm sorry it's giving you trouble. When I create a new *`.props`* file in the IDE as described in the article, it has some boilerplate in it:
```
<?xml version="1.0" encoding="utf-8"?> 
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ImportGroup Label="PropertySheets" />
  <PropertyGroup Label="UserMacros" />
  <PropertyGroup />
  <ItemDefinitionGroup />
  <ItemGroup />
</Project>
```
If you just create an empty file and try to load it using the **Add Existing Property Sheet** command, then it's not going to work in the IDE. It needs at least this boilerplate to start with.

There are two ways to edit a *`.props`* file: The easiest way is to open it from the Property Manager pane in the IDE. It will launch the Property Pages dialog box. Any changes you make to the properties pane will be stored in the file as soon as you save it. Until you save it, it's in the pending change state, so you'll still see the changes in the IDE, but the file on disk won't reflect those changes yet. You can save the file by selecting it in the Property Manager pane. Then, either right-click on it to bring up the shortcut menu to choose **Save \[filename]**, or use **Ctrl+S**. 

The other way to edit it is to open the *`.props`* file in the text editor. You can copy the path to the file from the Properties pane, in the **Property Sheet File** property, when the file is selected in Property Manager. It's an XML file in MSBuild format. You have to know a fair amount about the VC project file format to do this correctly, so we don't recommend it in general, but the option is there. Save your changes the usual way.

Normally, when you set properties in a project, it saves those properties in your project's *`.vcxproj`* file. As far as I know, there's no easy way to export specific properties from there as *`.props`* file entries. That'd be an interesting feature. What we suggest is to make a global *`.props`* file first for a new project you want to use as a template, then make all your common properties changes in that property sheet rather than in the project properties file. Then you can copy that *`.props`* file into new projects. This approach is basically what we describe in the article, so there's no change needed.
