### ISSUE TITLE
-O not shown as command line option. Only help is given

### ISSUE THREAD

**Issue by dannycoh** [MicrosoftDocs/cpp-docs#3877]
[Enter feedback here]
The text shows "object_file
The name of the object (output) file."
But there is no "-O" infront of it like any other command line options.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d310125d-c556-88aa-05ad-bc695360b89d
* Version Independent ID: e4a9c9d6-8f16-8540-6a4c-55f37c593b9d
* Content: [ARM Assembler command-line reference](https://docs.microsoft.com/en-us/cpp/assembler/arm/arm-assembler-command-line-reference?view=msvc-170)
* Content Source: [docs/assembler/arm/arm-assembler-command-line-reference.md](https://github.com/Microsoft/cpp-docs/blob/main/docs/assembler/arm/arm-assembler-command-line-reference.md)
* Product: **visual-cpp**
* Technology: **cpp-masm**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@dannycoh 
Some aspects of the command-line options are position dependent. Specifically, if the *object_file* name is the last thing on the command line, it doesn't need the `-o` flag in front of it. That's why it's documented the way it is. If you want to specify the name as an option, rather than as the final filename on the command line, you can use the `-o` option, as shown above in the syntax section. And if you leave the object file name out entirely, armasm generates an obj file based on the name of the source file.
