### ISSUE TITLE
Page may as well not exist

### ISSUE THREAD

**Issue by richardxday** [MicrosoftDocs/cpp-docs#389]
The page gives no description of what the warning message actually means, how it happens, why it occurs or how to fix it.  It gives unsustainable advice that *may* fix it but constantly having to clean your build directories is not a solution.

So this page may as well not exist!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 68eb82e3-8744-48a4-5705-19c0ebf9cc9e
* Version Independent ID: 98207168-c47e-09bb-b181-d4dcc5b16171
* Content: [Linker Tools Warning LNK4020](https://docs.microsoft.com/en-us/cpp/error-messages/tool-errors/linker-tools-warning-lnk4020)
* Content Source: [docs/error-messages/tool-errors/linker-tools-warning-lnk4020.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/error-messages/tool-errors/linker-tools-warning-lnk4020.md)
* Product: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@richardxday Sorry this document isn't telling you what you want to know. Unfortunately, there isn't a lot more information available. The error fires when the linker detects a problem in a PDB record, not when the problem is created in the first place. The reasons for corrupted PDB records are many, but a common cause is more than one process writing to the file at once. This is supposed to be controlled by serialization through a single common mspdbsrv.exe process, but sometimes more than one is running, either left over from an earlier build pass, or created by a multi-process build. That's why we suggest doing a single-process build to see if the problem goes away. If there are incremental build products in your build directories, and one is corrupted in some way, then you may see this warning, which is why we suggest cleaning your build directories and a full rebuild. Sometimes this error appears as a side-effect of some other problem that's already been reported by the compiler or linker, which is why we recommend fixing errors from the top of the list. 

Is there something more specific you'd like us to add?

**Comment by richardxday** [comment]
Thank you for the extra information, all of it is useful and in some form would add value to the page to help people understand what's causing the issue. 

Regarding the issue with parallel builds, doesn't this point to a bug in the build system? I use MSBuild with the /m switch to do parallel builds and am constantly getting this warning. Surely letting two processes write to the same file can cause far worse consequences than this warning implies and should be prevented at all costs? 

If parallel builds are to be supported within MSBuild then it shouldn't lead to negative consequences. 

Thanks, 
Richard.

**Comment by corob-msft** [comment]
Generally speaking, the parallel build just works. For a small fraction, it doesn't. It could depend on things like the antivirus tools you're using, or even the way your drives are configured. That leads me to one more suggestion: in your antivirus tool, whitelist your project's build directories.

If I recall correctly, the developers updated the mspdbsrv binary in something like the 15.4 release, give or take, but I don't know that it fixed every way this issue could manifest itself. If you're using an older version, see if an update fixes things. If not, and you've got a simple, consistent repro case that isn't unique to your machine, I strongly recommend submitting it to the [Developer Community site for C++](https://developercommunity.visualstudio.com/spaces/62/index.html), where it will be directed to the right eyes fairly quickly. There's a whole page on [how to report problems in Visual C++](https://docs.microsoft.com/en-us/cpp/how-to-report-a-problem-with-the-visual-cpp-toolset) for details.
