### ISSUE TITLE
I follow "Enable CMakePresets.json integration in Visual Studio" but there is no CMakePresets.json generated at all!?!

### ISSUE THREAD

**Issue by khteh** [MicrosoftDocs/cpp-docs#3915]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 18671a37-b8d9-b8cd-51fc-c1cd267e6af5
* Version Independent ID: 6f0932ad-998a-9449-dfff-259452ba20d5
* Content: [Configure and build with CMake Presets](https://docs.microsoft.com/en-us/cpp/build/cmake-presets-vs?view=msvc-170)
* Content Source: [docs/build/cmake-presets-vs.md](https://github.com/Microsoft/cpp-docs/blob/main/docs/build/cmake-presets-vs.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@khteh 
I'm sorry you're having difficulty. If you create a new project by using the CMake Project template, it should create a CMakePresets.json file for you. Since this sounds like a support question rather than a documentation question, I'm closing it. For support, I recommend [Microsoft Docs Q&A](https://docs.microsoft.com/en-us/answers/topics/c%2B%2B.html). Best of luck with your code.
