### ISSUE TITLE
To copy the DLL in a post-build event

### ISSUE THREAD

**Issue by shd8698766** [MicrosoftDocs/cpp-docs#3959]
I was able to successfully complete the tutorial but without having to go with the last part: "To copy the DLL in a post-build event", not really an issue, just wondering why.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 08c574a2-cef0-ab13-7375-55851f966ef6
* Version Independent ID: fe3421c7-e9f4-4986-589f-fadaedce583e
* Content: [Walkthrough: Create and use your own Dynamic Link Library (C++)](https://docs.microsoft.com/en-us/cpp/build/walkthrough-creating-and-using-a-dynamic-link-library-cpp?view=msvc-170)
* Content Source: [docs/build/walkthrough-creating-and-using-a-dynamic-link-library-cpp.md](https://github.com/Microsoft/cpp-docs/blob/main/docs/build/walkthrough-creating-and-using-a-dynamic-link-library-cpp.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@shd8698766 
Thanks for your patience on getting a response. Whether you need the post-build copy step depends on how you've organized your projects. If you're building both the DLL and the client in the same solution to the same output directory, then you may not need the post-build event copy to move the DLL to the client executable location - it's already there. However, often you might want to have separate output directories for the various parts of your app. The parts might come from other teams or get built on a different schedule, so you may want to use the copy step to drop the built DLL in a common location for deployment. This is explained in the document, but not emphasized, since it isn't the focus of the article. Hope this helps.
