### ISSUE TITLE
Reading system environment varaibles in launch.vs.json

### ISSUE THREAD

**Issue by max619** [MicrosoftDocs/cpp-docs#3965]
I'm trying to read system-wide environment variable from `launch.vs.json`
Non of this variants works:
```
"miDebuggerPath": "{env:GCC_ARM_TOOLCHAIN_PATH}\\bin\\arm-none-eabi-gdb-py.exe",
```

```
"miDebuggerPath": "{env.GCC_ARM_TOOLCHAIN_PATH}\\bin\\arm-none-eabi-gdb-py.exe",
```

```
"miDebuggerPath": "%GCC_ARM_TOOLCHAIN_PATH%\\bin\\arm-none-eabi-gdb-py.exe",
```

Is it even possible to access environment variables that are not specified in `launch.vs.json` or `CmakeSettings.json`?
This [doc](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/build/launch-vs-schema-reference-cpp.md) does not say anything about such a use case.

I'm using Visual Studio 2019 16.11.15

**Comment by corob-msft** [comment]
@max619 
While it's possible that a bug that was fixed in VS2022 17.0 is preventing access to environment variables defined in `launch.vs.json`, I'd expect something like your second example to work. I'd swap the `\\` directory separators for `/`.
Sorry about the delay in responding. I'm closing the issue; this is more of a product question than a doc issue, and so I recommend asking such questions on [Developer Community](https://aka.ms/vsfeedback/browsecpp) instead.
