### ISSUE TITLE
Correct way to wait for key press...

### ISSUE THREAD

**Issue by aboveyou00** [MicrosoftDocs/cpp-docs#397]
Is there a correct way to wait for a key press? The example on this page shows one way, but it's busy-waiting, which hurts my soul.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1607662b-1491-9baa-da9f-8fd3d3ee2c9a
* Version Independent ID: 42a68574-47ed-5bb3-e7bc-3e1c9e5eb38f
* Content: [_kbhit](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/kbhit)
* Content Source: [docs/c-runtime-library/reference/kbhit.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/c-runtime-library/reference/kbhit.md)
* Product: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@aboveyou00 The `_kbhit` function does one thing: report whether a character is available from the input hardware without blocking. (It may actually block if you've redirected input from a source other than the hardware.) You could sleep, or do other work, between checks of the input buffer state, rather than spin. If you want to get into the Windows API, you could conceivably roll your own event loop with handler callbacks for keyboard and other events, but you probably wouldn't be using `_kbhit` in that case. [Reading Input Buffer Events](https://docs.microsoft.com/en-us/windows/console/reading-input-buffer-events) shows one way to do this.

**Comment by aboveyou00** [comment]
Per your suggestion, I ended up adding a small sleep between checks using the c++11 chrono and thread standard libraries. This worked pretty well for my use case.

Thank you for your help!

**Comment by corob-msft** [comment]
@aboveyou00 Happy to help. :)
