### ISSUE TITLE
Does the MSVC support C++20 modules for Windows driver projects ?

### ISSUE THREAD

**Issue by 0xlay** [MicrosoftDocs/cpp-docs#3989]
### Does the MSVC support C++20 modules for Windows driver projects ?
I enabled C++20 and compiled project, but I took error (C3474 could not open file DriverModule.ifc). I tried to added path in "[Additional Module dependecies]: $(ProjectDir)DriverModule.ifc", but it wasn't fixing error.

I'm using the VS2019 (version 16.11.16).

### DriverModule.ixx
```cpp
 export module DriverModule;
 export int calculate(int x);
```
### DriverModule.cpp
```cpp
 module DriverModule;
    
 int calculate(int x)
 {
     return x + 10;
 }
```
### EntryPoint.cpp
```cpp
 #include <wdm.h>
 import DriverModule;
    
 extern "C" NTSTATUS DriverEntry(PDRIVER_OBJECT DriverObject, PUNICODE_STRING RegistryPath);
    
 NTSTATUS DriverEntry(PDRIVER_OBJECT DriverObject, PUNICODE_STRING RegistryPath)
 {
     UNREFERENCED_PARAMETER(DriverObject);
     UNREFERENCED_PARAMETER(RegistryPath);
     int b = calculate(28);
     KdPrint(("%d", b));
     return STATUS_SUCCESS;
 }
```

**Comment by corob-msft** [comment]
@0xlay 
Sorry it's giving you trouble. I don't know of any reason a driver project would be different from other projects that use modules. This sounds like a support question rather than a documentation issue, so I'm going to close it and recommend you ask on [Developer Community](https://aka.ms/vsfeedback/browsecpp) instead. Good luck with your code.
