### ISSUE TITLE
Are the C command line instructions compatible with 15.8.1?

### ISSUE THREAD

**Issue by JimAMS** [MicrosoftDocs/cpp-docs#401]
I have MS Visual Studio Community 2017, Ver. 15.8.1.  I want to compile C code.  Your instructions at https://docs.microsoft.com/en-us/cpp/build/walkthrough-compile-a-c-program-on-the-command-line   do not get me anywhere.  Are these instructions compatible with Ver. 15.8.1?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e96f0a01-2e3a-6301-bba1-6a50252555b0
* Version Independent ID: 290ca773-a214-e81a-2ba3-c647f2b28a56
* Content: [Walkthrough: Compile a C program on the command line](https://docs.microsoft.com/en-us/cpp/build/walkthrough-compile-a-c-program-on-the-command-line)
* Content Source: [docs/build/walkthrough-compile-a-c-program-on-the-command-line.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/walkthrough-compile-a-c-program-on-the-command-line.md)
* Product: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
Hi, @JimAMS - I'm sorry this is giving you trouble. Can you tell me where in the instructions you ran into difficulty, and what the difficulty was? I've run through the instructions successfully with Visual Studio 2017 version 15.8.1 Community edition, so I know these instructions *can* work, but I won't assert that they *do* work in all situations. Thanks for your help in figuring this out.

**Comment by corob-msft** [comment]
Sure, I understand. The IDE can certainly build and debug C code, but the new project templates are mostly geared toward C++. We don't have any other walkthroughs or tutorials that explicitly focus on C. If you find C tutorials on YouTube or elsewhere, the main differences between VS 2017 version 15.8 and versions back through VS 2015 are going to be in some of the dialog boxes, especially the New Project dialog box. I wouldn't worry much about these differences, since a little exploring will find what's changed. There are no changes to the compiler for C since VS 2015 that you will notice. Also, our support for the newest C standards is minimal. The C compiler is mostly but not entirely C99 compliant. There is no support for new features from C11 or later, if those matter to you.

To build C code in the IDE, it might be easiest to start with an empty project, and add your .c and .h files directly to your project in the Solution Explorer window. By default, Visual Studio assumes that files with a .c extension are C code, and uses the C compiler options. You can also set the option explicitly (which I recommend, to make sure that /TP is *not* set) by using the [/TC](https://docs.microsoft.com/en-us/cpp/build/reference/tc-tp-tc-tp-specify-source-file-type) compiler option, which treats all source files as C code. The link has directions on where to set this option in the IDE.

If there isn't a specific problem with the Walkthrough, then I'm going to close this issue. Good luck!
