### ISSUE TITLE
Visual Studio 15.8.1, class initializer_list, not possible to use 'no const' reference type and iterator one 

### ISSUE THREAD

**Issue by Ignac75** [MicrosoftDocs/cpp-docs#403]
template&lt;class _Elem&gt;
	class initializer_list
	{	// list of pointers to elements
public:
	typedef _Elem value_type;
	`typedef const _Elem& reference; // Why const here?`
	typedef const _Elem& const_reference;
	typedef size_t size_type;
	`typedef const _Elem* iterator;  // Why const here?`
	typedef const _Elem* const_iterator;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8da1b0e5-7cf1-efdf-d931-6042e57ee532
* Version Independent ID: e3ab6a82-eaf0-6122-60a0-5da45c88c042
* Content: [initializer_list Class](https://docs.microsoft.com/en-us/cpp/standard-library/initializer-list-class)
* Content Source: [docs/standard-library/initializer-list-class.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/standard-library/initializer-list-class.md)
* Product: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@Ignac75 This is a question for the language standard committee, because the **const** qualifiers are in the `std::initializer_list` prototypes in section 18.9 of the ISO C++11 standard. An `initializer_list` instance is usually a temporary and may reference an internal static created by the compiler. I could be wrong, but I expect the restrictions are to support this common use and keep you from trying to modify read-only memory.
