### ISSUE TITLE
release no __DATE__ __TIME__

### ISSUE THREAD

**Issue by kouzhudong** [MicrosoftDocs/cpp-docs#4042]
[Enter feedback here]

error C2065: “__DATE__”: 未声明的标识符
error C2065: “__TIME__”: 未声明的标识符

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 302c807b-34ed-c367-be11-c1528666cb75
* Version Independent ID: acf8ddce-337a-1a41-d39e-b7d2b52360cf
* Content: [Predefined macros](https://docs.microsoft.com/en-us/cpp/preprocessor/predefined-macros?view=msvc-160)
* Content Source: [docs/preprocessor/predefined-macros.md](https://github.com/Microsoft/cpp-docs/blob/main/docs/preprocessor/predefined-macros.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@kouzhudong 
I'm sorry you're having trouble. I would start by looking at the command line options for Release builds, to see if something turns these preprocessor macros off. These compiler options are useful for debugging preprocessor issues:

[/C (Preserve Comments During Preprocessing)](https://docs.microsoft.com/cpp/build/reference/c-preserve-comments-during-preprocessing)

[/E (Preprocess to stdout)](https://docs.microsoft.com/cpp/build/reference/e-preprocess-to-stdout)

[/P (Preprocess to a File)](https://docs.microsoft.com/cpp/build/reference/p-preprocess-to-a-file)

I used this test code, which works identically for me in both Debug and Release builds:

```
#include <iostream>

int main()
{
    std::cout << "__DATE__ " << __DATE__ << "\n";
    std::cout << "__TIME__ " << __TIME__ << "\n";
}
```

Since this seems to be a support question rather than a documentation issue, I'm closing it. If you need more help, I recommend [How to report a problem with the Microsoft C++ toolset](https://docs.microsoft.com/en-us/cpp/overview/how-to-report-a-problem-with-the-visual-cpp-toolset) or [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/topics/c%2B%2B.html). Good luck with your code.

**Comment by kouzhudong** [comment]
This is a windows kernel driver.

**Comment by corob-msft** [comment]
There are some compiler differences for kernel code, but mainly in the allowed instructions and libraries, not in the preprocessor. If you can't diagnose the issue, I recommend you create a simple repro, if you can, like my example above, and submit it to [Developer Community](https://aka.ms/vsfeedback/browsecpp).

**Comment by rogxo** [comment]
> This is a windows kernel driver.

For Kernel mode __TIME__ has to be enabled by setting "Project properties" -> "Driver Setting" -> "Driver Model" -> "Allow Date, Time and TimeStamp".

**Comment by kouzhudong** [comment]
thanks, i test it.
