### ISSUE TITLE
Why `std::endl` is used in code examples?

### ISSUE THREAD

**Issue by KZiemian** [MicrosoftDocs/cpp-docs#4046]
Case and point, [_Logical AND operator: `&&`_](https://docs.microsoft.com/en-us/cpp/cpp/logical-and-operator-amp-amp?view=msvc-170), we have in code
```Cpp
cout  << boolalpha
         << "The true expression "
         << "a < b && b < c yields "
         << (a < b && b < c) << endl
         << "The false expression "
         << "a > b && b < c yields "
         << (a > b && b < c) << endl;
```
Why this code show using `std::endl` , which according to this [page](https://cplusplus.com/reference/ostream/endl/) trigger flushing of the stream? It most cases we don't want flushing stream and many people don't even have idea what this mean (my included).

Recommended way that I know is to use `'\n'` instead. If Microsoft team also thinks that in most cases `'\n'` I suggest to replace `std::endl` with `'\n'` everwhere we can, to encurage better coding practices. I volunteer to rewrite all this code, just give me a time.

**Comment by KZiemian** [comment]
I also consider `using namespace std;` to be a bad practice, but this is separate topic.

**Comment by corob-msft** [comment]
@KZiemian 

These two areas, whether to flush output immediately, and whether to use entire namespaces, are not universally agreed upon as good or bad programming practices. The use of both `using namespace std;` and `std::endl` isn't consistent in our documentation because different authors have had different opinions on their usage in context.

Regarding `std::endl`, it's appropriate to flush when writing to `stdout` if interacting with a user. You want your output to be displayed before accepting the next user input. On the other hand, when writing to a file stream, performance considerations may argue against flushing with every line. You may want to flush once per page, per record, or per transaction. So, in response to your question, flushing is sometimes important for interactive code, and avoiding flushing is sometimes important for performance, and there may be exceptions to both cases.

As for `using namespace std;`, the main argument in favor is because it's less typing. The main argument against is to avoid potential namespace collisions and programmer confusion. In small projects that don't use anything other than the standard library, there's no reason to worry about namespace collisions. The compiler will raise error messages in that case. If you like to see the fully qualified names for functions everywhere because you find it reassuring to know exactly which functions you're calling, then don't import namespaces wholesale. The IDE knows where and how each symbol is declared, and it will tell you the fully qualified name if you just hover over the symbol. So, the confusion issue is overblown. It's also safe to add qualifications only when you have actual collisions.

We'd consider changes to either of these uses when they're clearly wrong in our examples, but not if it's just a style preference. We use both styles to avoid picking sides in battles when there isn't true consensus on good engineering practice.
