### ISSUE TITLE
No mention of C compliance

### ISSUE THREAD

**Issue by smujohnson** [MicrosoftDocs/cpp-docs#407]
Hi,

This page shows a giant detailed list of C++ support, but no C mention.  e.g., C99, C11, etc.  This is incredibly frustrating -- cl.exe is a C/C++ compiler, not just a C++ compiler.  Please update your documentation to include C too.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d606e0aa-36fd-97f2-6e65-af0f9b05b24c
* Version Independent ID: 207d361a-397e-d687-8828-a152ebc4e572
* Content: [Visual C++ Language Conformance](https://docs.microsoft.com/en-us/cpp/visual-cpp-language-conformance?view=vs-2017)
* Content Source: [docs/visual-cpp-language-conformance.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/visual-cpp-language-conformance.md)
* Product: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@smujohnson That's true, we don't say much about later C standards conformance, and this is intentional. MSVC includes a C89/C90 compliant compiler, which is invoked by use of the /TC and /Tc compiler option, or implicitly on files that have a .c extension. Support for later C standards is limited to the subset required by the C++ standard. This includes many but not all C99 language features, and only a handful of new C11 language features. For example, some obvious differences exist in the use of `restrict`, `auto`, `static`, and `const`; and `complex` isn't supported as a native type. The UCRT library implements C11 library changes only as they are required for C++17 standard support, with the exceptions noted on this page.

Herb Sutter blogged about [MSVC support of the C99 standard](https://herbsutter.com/2012/05/03/reader-qa-what-about-vc-and-c99/) (and later) six years ago, and as far as I can tell, it still accurately reflects the compiler team's focus. There's competitive pressure to support current C++ standards, but not so much for C. Therefore, there's been no work done on C standards conformance outside the parts required by the C++ standard, and the documentation reflects that.

Sorry there isn't more to say here. It's possible that if you raise an issue on the [C++ Developer Community](https://developercommunity.visualstudio.com/spaces/62/index.html) page, a more up-to-date and definitive statement may be made. If that happens, we'll include the information in the documentation.

If what you *really* want is support for C11/C17/C18 language features, instead of Visual C++ documentation that tells you exactly which of those features are not supported now, if ever, then there may be one easy way to get later C standards support right out of the box in Visual Studio. Try the Clang/C2 toolset, which can be installed as an option by the Visual Studio Installer. It's experimental and very unlikely to be supported in the next major version of MSVC, but it's there now and it works, generally speaking. It's not documented, but I believe you can pass options to enable C compilation, and get whatever level of support CLang supplies.

**Comment by MarcusJohnson91** [comment]
No longer accurate:

https://twitter.com/UlziiLuvsanbat/status/1052976061431013377

**Comment by DBJDBJ** [comment]
Argh, twitter says: "Something went wrong. Try again.." on that link :( 

ps: C and C++ ISO committees are working together to unify many fundamentals between C++20 and C2x ... MSFT team is I am sure very aware of this ... AFAIK this has started with C99, C++11

some info  is here too https://gustedt.wordpress.com/2018/11/12/c2x/

**Comment by MarcusJohnson91** [comment]
@DBJDBJ The link works fine for me, but here's a screenshot for posterity and anyone else that can't see it:

https://i.imgur.com/yNwcHDU.png

**Comment by DBJDBJ** [comment]
@MarcusJohnson91  yes it indeed works (now)  ... thanks.

As for the rest: (whoever We are), We are asking the CL support for C to be documented that is all. We do not ask for full C11 or C18 compliance.

What is especially troublesome is the surprises in behavior when using `extern "C"`  from the CL.  For example: https://stackoverflow.com/q/57431947/10870835

HTH

**Comment by smujohnson** [comment]
DBJDBJ, you are absolutely correct.  My initial complaint was that the documentation was vague and you really have to "dig deep" to find *specific* standard(s) that the C compiler *will* follow.  Currently it seems it's C89 + a hodgepodge smattering of features from newer C standards in order to make the C++ compiler work.

In contrast, the C++ standards that the compiler supports are very nicely documented in bullet-point form in most documents and thus are easy to find without any ambiguity.

**Comment by CodeSwimBikeRunner** [comment]
I started my project using msvc build tools 2019. It's been great. It works so well in vscode, and just using the built in tasks.json and c_cpp_properties.json has been great using 'cl.exe'. However I found a feature that the C standard has but msvc does not have, and I'm a little baffled why not? It's 2019, and these are official features. Why would you not update your compiler to support them?

**Comment by h-vetinari** [comment]
Hey @Blackh0leZ, you mentioned on [twitter](https://twitter.com/UlziiLuvsanbat/status/1052976061431013377) in Oct. 2018 (linked [above](https://github.com/MicrosoftDocs/cpp-docs/issues/407#issuecomment-514836904)) that: 
> I can't yet to commit to specific date for supporting C11, but it's very likely in one of the VS2019 updates. As soon as we have more details, I'll share here

There's been no news since then - could you maybe give us a status update?

**Comment by DBJDBJ** [comment]
VS 2019 is now (by 22 DEC 2019)  equipped with optional CLANG 9.x  ...which has no problems revealing what is its ISO C conformance level .. through `__STDC_VERSION__ ` of course ...  

Still missing from CL ...

**Comment by h-vetinari** [comment]
As an update: the recently posted [roadmap](https://docs.microsoft.com/en-gb/visualstudio/productinfo/vs-roadmap) for visual studio mentions "C11 standard conformant preprocessor in MSVC" as "in progress". The roadmap further qualifies [my bold]:

> This document provides a peek into the work we have planned for Visual Studio through **June 2020**. It captures significant capabilities that we are adding, but it's not a comprehensive feature list. [...]

**Comment by wolf99** [comment]
@h-vetinari and this https://devblogs.microsoft.com/cppblog/announcing-full-support-for-a-c-c-conformant-preprocessor-in-msvc/

@corob-msft I do remember the blog post announcing the "almost but not quite" C99 support. I can't find it now (doubly frustrating as it was the first thing in a long time that actually documented exactly what was supported and what was not) but I had the impression from it that increasing C conformance had been the intention at that time. 

Sad to see MS has returned to the previous default stance here - especially given the number of IoT related features I see are available in VS 2019... Not sure how MS hopes to profit from the IoT sector without at least some accessible documentation for the MSVC compiler.

I must note also that this approach does not seem very joined up with the recent MS push to make Windows the platform of choice for development, the results of which we are enjoying in the WT, WSL and VS Code.

Such documentation must exist somewhere, to allow MSVS engineers to work with the compilers... Please could you even just publish that somewhere permenent and easy to find, maybe a c-docs repo, similar to the cpp-docs one? The good thing about opening up such documentation in such a way is that you don't need to worry too much about the state it is in, the community can help improve if it needs it.

@everyone else
Short answer: real C support in MSVS has apparently returned to "go look elsewhere". I can recommend VS code in combination with Clang or GCC installed in WSL. Or Eclipse has fairly decent C compiler integration and IDE capabilities. Or perhaps a different platform altogether 🤷‍♂️.

Advice for less experienced C developers that look to MSVC to make project compilation and managent easier is just to learn the CLI tools (make, GCC, clang, gdb, etc), it may be a bit of a ramp up but once you have them under your belt you're freed from such concerns and the more you use them the easier it gets.

**Comment by h-vetinari** [comment]
What does "full support for a C/C++ conformant preprocessor in MSVC" mean? The article makes it sound like C99?

Of note, the [roadmap](https://docs.microsoft.com/en-gb/visualstudio/productinfo/vs-roadmap) now shows "C11 standard conformant preprocessor in MSVC" as completed.

But certainly, talking about "full support" should have a C-Standard version attached to it. It would be foolish to hope that they're at C18 already.

**Comment by DBJDBJ** [comment]
Well, clang 9.x inside VStudio 2019 shows clearly what is full 99 support. Was not watching recently but I think they are prety far on C11 support too. 

Maybe by adding clang 9.x into VStudio, "they" conclued the calls for full C99/C11 conformance was responded too?

@wolf99 , this is [the most relevant person](https://devblogs.microsoft.com/cppblog/author/batulmicrosoft-com/) who posted about MSVC C confromance. I can not find that post now.

**Comment by h-vetinari** [comment]
Good news: After rechecking the roadmap mentioned above and following a few links, C11 & C17 are [arriving](https://devblogs.microsoft.com/cppblog/c11-and-c17-standard-support-arriving-in-msvc/) with Visual Studio 2019 version 16.8 Preview 3.

**Comment by DBJDBJ** [comment]
> 
> 
> Good news: After rechecking the roadmap mentioned above and following a few links, C11 & C17 are [arriving](https://devblogs.microsoft.com/cppblog/c11-and-c17-standard-support-arriving-in-msvc/) with Visual Studio 2019 version 16.8 Preview 3.

https://devblogs.microsoft.com/cppblog/c11-and-c17-standard-support-arriving-in-msvc/#comment-1323

**Comment by h-vetinari** [comment]
Opened a follow-up in #2599.

**Comment by DBJDBJ** [comment]
Ok [here is the very recent update](https://docs.microsoft.com/en-us/cpp/build/reference/std-specify-language-standard-version?view=msvc-160) about C11/C17. It is a somewhat minimal update though.

What might be very welcome is to see C (not C++) posts on the CL blog. Perhaps and also simply because WIN32 is still an C API :)
