### ISSUE TITLE
Documentation is not Clear

### ISSUE THREAD

**Issue by aricsoftware** [MicrosoftDocs/cpp-docs#4072]
The second sentence of the remarks says "[i]f the Destination value is equal to the Comparand value." If you mean "if the value that is stored at the address pointed to by Destination,"  please say that; otherwise people would just have to experiment with the functions and create test cases to determine what the function really does instead of reading this documentation. Its very risky to try to interpret what is meant rather than writing what is meant.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aff37b62-065d-a87f-dbd6-c19a52c53555
* Version Independent ID: 1e13568d-81a3-df10-0742-ab49b3f253d6
* Content: [_InterlockedCompareExchange intrinsic functions](https://docs.microsoft.com/en-us/cpp/intrinsics/interlockedcompareexchange-intrinsic-functions?view=msvc-170)
* Content Source: [docs/intrinsics/interlockedcompareexchange-intrinsic-functions.md](https://github.com/Microsoft/cpp-docs/blob/main/docs/intrinsics/interlockedcompareexchange-intrinsic-functions.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@aricsoftware 

I'm sorry you've found the documentation confusing.

The wording here quotes the Win32 documentation for the [InterlockedCompareExchange](https://docs.microsoft.com/en-us/windows/win32/api/winnt/nf-winnt-interlockedcompareexchange) function, and it's similar to the Intel [_InterlockedCompareExchange_HLEAcquire](https://www.intel.com/content/www/us/en/develop/documentation/cpp-compiler-developer-guide-and-reference/top/compiler-reference/intrinsics/intrinsics-for-avx2/intrinsics-for-tsx/intrinsics-for-hardware-lock-elision-operations/hle-acquire-interlockedcompareexchange-functions.html) intrinsic docs. The latter may be especially confusing, since the `comparand` argument can be a value or a pointer to a value, depending on the call, but no distinction is made in the description.

All of these docs use the description "`pointer-argument` value" to mean "the value pointed at by `pointer-argument`" instead of "the address in `pointer-argument`". I'm guessing the latter alternative never occurred to the original writers of these docs, however many years ago that was.

**Comment by corob-msft** [comment]
Updates are live.
