### ISSUE TITLE
Unable to compile example for intrinsic __assume

### ISSUE THREAD

**Issue by diamante0018** [MicrosoftDocs/cpp-docs#4075]
Hello,
I am trying to use one of the examples provided by the document `assume.md`, in particular, the special case `__assume(0)` in the default case of a switch statement.

The document makes the following suggestion to "protect" the code

```C
#define ASSERT(e)    ( ((e) || assert(__FILE__, __LINE__)), __assume(e) )
```
and later shows

```C
#ifdef DEBUG
# define NODEFAULT   ASSERT(0)
#else
# define NODEFAULT   __assume(0)
#endif

   default:
      NODEFAULT;
```

Although the two blocks of code containing the suggestions are separate, I assume the latter is making use of the definition of `ASSERT` immediately declared above (the second definition overall if I take into account the whole document).
This is causing a compilation error on my end. I am not sure if it's caused by me not understanding the document or the *second* macro definition for `ASSERT` being incorrect.

I will try to keep my code as short as possible to show my problem.

```C
#include <stdio.h>
#include <assert.h>

#define DEBUG

#define ASSERT(e)    ( ((e) || assert(__FILE__, __LINE__)), __assume(e) )

#ifdef DEBUG
# define NODEFAULT   ASSERT(0)
#else
# define NODEFAULT   __assume(0)
#endif

enum
{
	VAL_0,
	VAL_1,
};

int main(void)
{
	int a = VAL_0;

	switch(a)
	{
	case VAL_0:
		printf("Value is 0");
		break;
	case VAL_1:
		printf("Value is 1");
		break;
	default:
		NODEFAULT;
	}

	return 0;
}
```

The code above fails to compile with the following error (compiling with cl.exe):
```
cl main.c
Microsoft (R) C/C++ Optimizing Compiler Version 19.32.31332 for x86
Copyright (C) Microsoft Corporation.  All rights reserved.

main.c
main.c(32): warning C4002: too many arguments for function-like macro invocation 'assert'
main.c(32): error C2297: '||': not valid as right operand has type 'void'
```

I made the assumption that I should use the second macro definition for `ASSERT` and that the `assert` showcased in the document comes from `<assert.h>`.
I am simply confused as to what I should do. Ideally, if I should use the first definition for `ASSERT`, could the document specify that so there is no ambiguity? Perhaps, the macro is not defined correctly?
Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 32d3a989-2c4b-6759-4fff-cabd6b1f8d86
* Version Independent ID: 742f6bae-5305-ace5-4711-40654c6fd30b
* Content: [__assume](https://docs.microsoft.com/en-us/cpp/intrinsics/assume?view=msvc-170)
* Content Source: [docs/intrinsics/assume.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/intrinsics/assume.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@diamante0018 
Thanks for the report. It's not your fault, the sample code is broken. I suspect something was lost between when the samples were created and when they were added to the article.

The `assert` with `__FILE__` and `__LINE__` macro arguments can't possibly be correct. The only reason the first sample compiles is because `ASSERT` is never invoked. I found the code sample has been the same [since at least VS 2005](https://web.archive.org/web/20110123202539/http://msdn.microsoft.com:80/en-us/library/1b3fsfxw(v=VS.80).aspx). So, it's been broken for a long time. There's a problem with the logical or expression in the macro, too, since `assert` is effectively `void` and can't be compared to a boolean. The supposedly safe version of the `ASSERT` macro can't work, either. 

It's hard to divine what the original authors intended here. If you want to use `__assume(0)` to mark intentionally unreachable code for optimization, but still catch violations in Debug code, then you probably want something much simpler, like this:

```
#ifdef DEBUG
#define NODEFAULT  assert(0)
#else
#define NODEFAULT   __assume(0)
#endif
```

**Comment by corob-msft** [comment]
Updates are live.

**Comment by diamante0018** [comment]
Much appreciated.
