### ISSUE TITLE
New project file from directory lacks x64 ItemDefinitionGroups

### ISSUE THREAD

**Issue by SpareSimian** [MicrosoftDocs/cpp-docs#4094]
Using 17.2.6, the "New project from existing code" wizard only populates the Win32 project properties in the new vcxproj file. I was building the ICMP example from Boost ASIO.  In the wizard, I'd added $(boost_root) to the additional include directories and tried to build for x64|Debug and discovered this because it couldn't find the Boost headers. Other XML groups do have the x64 XML blocks so I can't just copy the architecture in the Configuration Manager as a partial x64 configuration already exists. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 01d1fc7d-eeb2-d7c6-3d79-0a69732864a3
* Version Independent ID: 8e53ef60-ff33-38af-8ee9-73a6bf8b8853
* Content: [How to: Create a C++ Project from Existing Code](https://docs.microsoft.com/en-us/cpp/build/how-to-create-a-cpp-project-from-existing-code?view=msvc-170)
* Content Source: [docs/build/how-to-create-a-cpp-project-from-existing-code.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/build/how-to-create-a-cpp-project-from-existing-code.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@SpareSimian 
Thanks for the report, and sorry the feature hasn't worked for you. This sounds like a product issue rather than a documentation issue. I'd recommend you report this on [Developer Community](https://aka.ms/vsfeedback/browsecpp) to find out if there's awareness of the issue and a possible workaround. (I'm sure you can work around it by directly editing project files, but that's not nearly as friendly as the open folder feature is supposed to be.) Since there isn't anything to document here yet, I'm closing the issue, but if you provide a link here to your DevCom report, we can follow up later if there's a resolution.

**Comment by SpareSimian** [comment]
Thanks. I've submitted a trouble ticket through the Visual Studio help menu. I'll let you know what comes of it. 

In this case, I don't really need a workaround as the sample I was building works fine in a Win32 build. VS now defaults to the x64 arch or I would never have noticed this. This could be a problem for an application that benefits from the x64 architecture, though. I edit project files all the time but I wanted to report this for the benefit of those who depend on the GUI, particularly newcomers to coding who assume the build system "just works". ;)
