### ISSUE TITLE
Typo in URL of page "Compiler warnings C4800 through C5999"

### ISSUE THREAD

**Issue by studyingegret** [MicrosoftDocs/cpp-docs#4106]
The URL of this page is

> https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warnings-c4800-through-c4999?view=msvc-170

which, by the page's name, should be

> https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warnings-c4800-through-c5999?view=msvc-170

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ddc3041c-b233-bb3f-513f-b3df302b49a2
* Version Independent ID: aad153bd-a417-01fb-f2b7-50842269dcc0
* Content: [Compiler warnings C4800 Through C5999](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warnings-c4800-through-c4999?view=msvc-170)
* Content Source: [docs/error-messages/compiler-warnings/compiler-warnings-c4800-through-c4999.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/error-messages/compiler-warnings/compiler-warnings-c4800-through-c4999.md)
* Product: **visual-cpp**
* Technology: **cpp-diagnostics**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@studyingegret 
Thanks for the report; we're aware of the issue and currently choose to ignore it. The file was named before there were warnings in the 5000-5999 range. When they started to appear, rather than create a new article, it was easier to append them to this article and give it a new title. When there are enough warnings in that range to merit their own article, we'll split them out, and the file name will once again match the content. Until then, only the eagle-eyed such as yourself will notice the discrepancy.
