### ISSUE TITLE
Why does _get_tzname() now return FULL name, not abbreviation, as in docs?

### ISSUE THREAD

**Issue by Pnyxor** [MicrosoftDocs/cpp-docs#4107]
Although the _get_tzname() function was obviously an ancient hack to get around the _tzname[] global value, it DID return "PDT" (in ASCII 1-byte chars), and this is what _all_ the documentation says it should be doing. Now it returns "Pacific Summer Time" (in Unicode). This is NOT what the time zone's name has been called, which is "Pacific Daylight Time". Why the change? How do we insert a _terse_ Time Zone designator into a time format? The Registry has also abandoned the abbreviated name.
Thanks
Richard
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b7e309b-1f99-1165-4a7a-1b3f845798a1
* Version Independent ID: fc1efcc4-521e-0b7f-68bf-c1e307583517
* Content: [_get_tzname](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/get-tzname?view=msvc-170)
* Content Source: [docs/c-runtime-library/reference/get-tzname.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/c-runtime-library/reference/get-tzname.md)
* Product: **visual-cpp**
* Technology: **cpp-ucrt**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
Hi @Pnyxor, I see that this old page needs some updating.
"PDT" is the default value, but the data is updated with the true time zone name. It would only stay as "PDT" if the OS calls to get the time zone failed. 
The reason you've seen a change in the time zone string is because we get the information from the OS and the OS locale team regularly updates the strings returned by the locale APIs. So that's subject to change between OS releases.
I'll update the page to include this info. Thank you for pointing out what you ran into. My updates to this page should be live by the end of the week.
