### ISSUE TITLE
MSVC 19 (2017): long and int

### ISSUE THREAD

**Issue by ax3l** [MicrosoftDocs/cpp-docs#411]
Why does is_same&lt;long, int&gt; return false, although they have the same size on MSVC 19 (2017) for the x86-64 systems? (Other types and comparisons, e.g. to int32_t return false as well.)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99c0c269-54d9-8d08-085a-3de499db93dc
* Version Independent ID: dda4542e-d361-0a00-e9fe-285bf8c53ebb
* Content: [is_same Class](https://docs.microsoft.com/en-us/cpp/standard-library/is-same-class?view=vs-2017)
* Content Source: [docs/standard-library/is-same-class.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/standard-library/is-same-class.md)
* Product: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@ax3l That's expected behavior for `is_same<long, int>`, because **int** and **long** are not the same *type*, even if they have the same storage size and internal representation. The `is_same` test only returns true if a type is truly an alias for another type. Consider this example:

```cpp
// is_same.cpp
#include <type_traits>
#include <iostream>

int main()
{
    std::cout << std::boolalpha;
    std::cout << "std::is_same<int, long>::value = " <<
                  std::is_same<int, long>::value << std::endl;
    std::cout << "std::is_same<int, int32_t>::value = " <<
                  std::is_same<int, int32_t>::value << std::endl;
    std::cout << "std::is_same<long, int32_t>::value = " <<
                  std::is_same<long, int32_t>::value << std::endl;
    std::cout << "std::is_same<long long, __int64>::value = " <<
                  std::is_same<long long, __int64>::value << std::endl;
}
```

The output looks like this:

```
C:\Projects\std\type_traits\is_same>is_same.exe
std::is_same<int, long>::value = false
std::is_same<int, int32_t>::value = true
std::is_same<long, int32_t>::value = false
std::is_same<long long, __int64>::value = true
```

So the compiler can tell if a type is an alias for another type, or if it's a distinct type, even if it may just happen to have the same representation at the machine level. Hopefully this clarifies what `is_same` is for. Thanks for asking!

**Comment by ax3l** [comment]
@corob-msft I see, thanks a lot. I always thought it's the other way around (alias-wise).
