### ISSUE TITLE
Strange text in "Walkthrough: Create and use your own Dynamic Link Library (C++)"

### ISSUE THREAD

**Issue by KZiemian** [MicrosoftDocs/cpp-docs#4111]
On the page [Walkthrough: Create and use your own Dynamic Link Library (C++)](https://docs.microsoft.com/en-us/cpp/build/walkthrough-creating-and-using-a-dynamic-link-library-cpp?view=msvc-170) in the code of the MathLibrary.h header file we can read in the comments on Fibonacci sequence "for some initial integral values a and b". Maybe it should be "integer values a and b"? This feel more natural to me.

Latter we have function signature `void fibonacci_init(const unsigned long long a, const unsigned long long b)` and from what I remember only integer can be arguments of such function, so this would support my guess.

**Comment by corob-msft** [comment]
@KZiemian 
You're not wrong; "integer" is acceptable as a [noun adjunct](https://en.wiktionary.org/wiki/noun_adjunct) applied to "values". "[Integral](https://en.wiktionary.org/wiki/integral)" (definition 2) is the adjective form: "integral values" means "values that are integers". We've used "integral" this way in many places in the documentation. If "integral" is translated incorrectly, we'll update it to "integer", which is almost always translated correctly. Otherwise, we usually leave it alone. Is there a translation issue here?

**Comment by KZiemian** [comment]
I'm not native English speaker and I very rarely see word "integral" used in other sense than this is sentence "integral of function f". I couldn't decided if this is deliberate use of this word or just one of this autocorrector/nuclear typo issues. I checked "integral" in Google Translate, to found if it has some meaning connected to integer numbers, but page of translation "integral" to polish isn't too helpful in this regard. After reading it, I was left with "maybe it has".

If others don't have a problem with this word, neither do I.

**Comment by corob-msft** [comment]
We'll leave it alone, but watch for other complaints. Thanks for the comments, @KZiemian.
