### ISSUE TITLE
Limitations of PInvoke

### ISSUE THREAD

**Issue by wschin** [MicrosoftDocs/cpp-docs#412]
What's the root reason of this effect? I guess that array of bittable is marshaled with InAttribute only (without OutAttribute) by default?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be7907e0-45f6-2333-d4b0-09c2206f2917
* Version Independent ID: ba9200fd-d49e-8d88-0d21-faa82db22c36
* Content: [Calling Native Functions from Managed Code](https://docs.microsoft.com/en-us/cpp/dotnet/calling-native-functions-from-managed-code?view=vs-2017)
* Content Source: [docs/dotnet/calling-native-functions-from-managed-code.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/dotnet/calling-native-functions-from-managed-code.md)
* Product: **visual-cpp**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by corob-msft** [comment]
Hi, @wschin -

That's only part of the answer. The reason you can't *return* a pointer parameter directly when you use PInvoke is because the data it points at is a temporary that was created by the PInvoke marshaller. It's basically doing the same thing behind the scenes as the code you would write if you did your own marshalling, except that it copies the data from a reference type such as a String into an internal variable (and maybe transforms it, say from UTF-16 to ASCII), and that internal copy is freed when the variable goes out of scope as the PInvoke call completes. There's a longer explanation in [Overview of Marshaling in C++](https://docs.microsoft.com/en-us/cpp/dotnet/overview-of-marshaling-in-cpp). You can explicitly apply both InAttribute and OutAttribute to the parameter, and then the parameter itself is converted back to something you can access in managed code - but that converted out parameter is not the same memory the native function writes to, it's something the marshaller converts back for you before it frees the temporary.

I'm closing this issue, as it doesn't seem like it merits a change to the documentation.
