### ISSUE TITLE
It should be noted that _udiv128 can cause EXCEPTION_INT_OVERFLOW

### ISSUE THREAD

**Issue by vrubleg** [MicrosoftDocs/cpp-docs#4121]
`_udiv128` is basically the x86-64 `div` instruction that causes an exception when the result of division is bigger than 64-bit even if you need just the remainder.

Example how to reproduce it:
```
uint64_t Remainder;
_udiv128(1, 1, 1, &Remainder);
```
it is basically equivalent of the:
```
mov rax, 1
mov rdx, 1
mov r10, 1
div r10
```
This program crashes with the `EXCEPTION_INT_OVERFLOW (0xC0000095)` exception.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b4942d1-d3ba-6ac9-b99a-06023ee6697d
* Version Independent ID: d2b669e9-622d-b7e7-57e8-bda054e6478f
* Content: [_udiv128](https://docs.microsoft.com/en-us/cpp/intrinsics/udiv128?view=msvc-170)
* Content Source: [docs/intrinsics/udiv128.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/intrinsics/udiv128.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@vrubleg 
Thanks for the idea. It's true, many of the intrinsics can cause processor traps, usually obvious ones like overflow, divide by zero, floating point errors, or unknown or privileged instruction. We don't include a list in the intrinsics docs because they're not specific to the intrinsics, and because the list is potentially large for each intrinsic. All unmasked processor traps are captured by Windows, which raises a structured exception. There's a list of some of the common exceptions in [GetExceptionCode](https://docs.microsoft.com/en-us/windows/win32/debug/getexceptioncode). If the exception isn't handled by your code, Windows terminates your app and reports the exception as an error code. While you could attempt to capture and handle these exceptions and continue execution, we don't recommend that approach. Instead, we recommend you apply some heuristics to your inputs to avoid overflow or divide by zero situations. This is a long way to say, we don't think it's useful to add individual exceptions piecemeal to the docs, so we don't plan to make any changes. Thanks for understanding.

**Comment by cuzperf** [comment]
@vrubleg Hi, Do you know how to "fix" it, or any workaround
