### ISSUE TITLE
"Use Debug Libraries" correct?

### ISSUE THREAD

**Issue by franji1** [MicrosoftDocs/cpp-docs#4127]
Use Debug Libraries states
"Specifies whether to create a Debug or Release build."

I believe the option to use Debug Libraries is NOT about how to create the current project configuration (there are options for Release vs. Debug configurations), but I believe this option is about utilizing the Debug versions of any (system?) dependent libraries?  It would also be good to explain in detail what those debug libraries actually are, or point me to a place where I can find out what debug libraries are even available?  Common Dialog?  GDI?  Kernel?  MSVC? Networking? MFC?  Also details on how to download the .pdb debug files for those libraries.

Back in the 90's, a typical help system would say things like "Use Debug Libraries - say Yes if you want to use Debug Libraries" in order to look clean and pristine and simple, but most developers need help with complex things.  This is the age of the Internet.  Point me to all the details I need for this option, especially for Native Desktop applications.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 69b82557-4a26-70f9-c7ae-ca21c91318ec
* Version Independent ID: d93c9b26-7bde-7186-0d27-b37ade129b3c
* Content: [Advanced Property Page (Project)](https://docs.microsoft.com/en-us/cpp/build/reference/advanced-property-page?f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(VC.Project.VCConfiguration.VCToolsVersion)%26rd%3Dtrue&view=msvc-160)
* Content Source: [docs/build/reference/advanced-property-page.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/build/reference/advanced-property-page.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@franji1 
The name is something of a misnomer. Contrary to your entirely reasonable expectation, it's not specifically about enabling debug libraries. **Use Debug Libraries** is a complex and wide-ranging build system-specific property that is effectively shorthand for "Make a Debug build" or "Make a Release build". Most properties just set one compiler or linker option or configure specific environment variables. This property is apparently a way for templates to control several Debug or Release settings at once. For example, when set, it sets the Debug information format to "Edit and Continue", turns on incremental linking and the linker's `/SAFESEH` option, and does a few other things depending on the target platform/OS that would require a table to describe, all in addition to enabling debug libraries. From what I gather, this property exists solely for the convenience of the project system implementers so they can have just one conditional switch to check, rather than a whole bunch, when setting up properties for Debug or Release builds. It is not a good idea to alter this property. I'm not even sure why it is exposed, since fiddling with it is potentially a source of inexplicable build weirdness and other bad things.

The upshot is, this isn't the property you think it is, and it's not where to look for information about debug libraries. For that information, you'll want to look at our library-specific pages like [C runtime (CRT) and C++ Standard Library (STL) .lib files](https://docs.microsoft.com/en-us/cpp/c-runtime-library/crt-library-features?view=msvc-170) and [MFC Library Versions](https://docs.microsoft.com/en-us/cpp/mfc/mfc-library-versions?view=msvc-170). As far as I know, there is no one-stop-shop article about all of the various Microsoft debug libraries for everything, everywhere. That's going to be in various platform and technology specific documentation. I'm sorry there's no easy answer for your question.

**Comment by corob-msft** [comment]
Although it's not a fix for the specific issue raised here, questions about this property have been raised before, so I'll expand the text to explain more about what it's for.

**Comment by franji1** [comment]
Minimally the topic paragraph heading and the dialog could be changed?  As you have described, the setting has absolutely nothing to do with “Libraries” or the attributes of those libraries.  It has nothing to do with building a library or linking against any library.  It’s all about the specific build CONFIGURATION.  So possibly rename it to “Use Debug Configurations” or some better wording based on your description?

Mark Franjione
Sr. Software Engineer
Host Engineering, Inc.
