### ISSUE TITLE
Misleading "Advice" in MSVC error documentation.

### ISSUE THREAD

**Issue by bradlitterell** [MicrosoftDocs/cpp-docs#4132]
The page includes this admonition as some sort of best practice:
"Although there is no specific warning for it, we also recommend that you do not use a parent directory path segment to specify your project include directories."

The example also says this:
```
#include "..\headers\C4426.h"  // emits warning C4464

// To fix this issue, specify only the header file name, and add
// the absolute path to 'headers\' to your project's include directories
#include "C4426.h"
```

I don't know who came up with this recommendation, but it's bad advice.  It's very much a standard industry practice to include library prefixes on header files, such as boost:

https://www.boost.org/doc/libs/1_79_0/doc/html/accumulators/reference.html#accumulators_framework_reference

and Microsoft's own WIL library:

https://github.com/microsoft/wil/blob/master/tests/ComTests.cpp

and Google's C++ style guide:

https://google.github.io/styleguide/cppguide.html#Header_Files

Please remove this misleading guidance from this documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eea6cbb5-c2e6-86f1-817f-0920de9d99e0
* Version Independent ID: b645e000-fe3d-187b-671a-46468930fbeb
* Content: [Compiler Warning (level 4) C4464](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-4-c4464?view=msvc-170)
* Content Source: [docs/error-messages/compiler-warnings/compiler-warning-level-4-c4464.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/error-messages/compiler-warnings/compiler-warning-level-4-c4464.md)
* Product: **visual-cpp**
* Technology: **cpp-diagnostics**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@bradlitterell 
Perhaps the advice isn't clear for all readers. My reading of the advice seems unrelated to the examples you cite. There's nothing wrong with an include directive such as `#include "headers\C4426.h"` or the common `#include <sys/types.h>`. The advice is to avoid using parent path segments (`..`) in the include paths in your project environment, because it can be fragile, error-prone, and difficult to share with other developers (who may have installed Boost somewhere different than you did, say). Is that the advice you find objectionable?

**Comment by bradlitterell** [comment]
@corob-msft 
I think you're ascribing a different meaning to the text. 
You are saying "parent path segments" means using `..`, but the text says `there is no specific warning for it...do not use a parent directory path segment`.  Since there IS  a warning specifically for `..`, then a "parent directory path segment", cannot refer to `..`, and must instead refer to `header/`, which is reinforced by the example's advice to remove `header` from the include.

**Comment by corob-msft** [comment]
@bradlitterell 
Yes. I am ascribing exactly the meaning you think I am, because there's no warning message when you use a `..` parent directory path segment in an `INCLUDE` path or in any of the **... Directories** properties in the **VC++ Directories** page in the **Property Pages** dialog for your project in the IDE.

But from the rest of your explanation, I can see what the source of the confusion must be. When the example says "... add the absolute path to 'headers\' to your project's include directories" it means that if, say, the absolute path to the header file is *`C:\Users\username\source\repos\solution\project\headers\C4426.h`*, then you should add *`C:\Users\username\source\repos\solution\project\`* (that is, the absolute path required to include *`headers\`*) to your `INCLUDE` paths. It would be easy to read this sentence to mean that you should add *`C:\Users\username\source\repos\solution\project\headers\`* to your `INCLUDE` path, even though that's not the intent. That wording can be cleared up, and some actual examples added. Would that address your objection?

**Comment by bradlitterell** [comment]
Created PR #4135

**Comment by corob-msft** [comment]
Closed as fixed; merged content is live.
