### ISSUE TITLE
Does not mention which library is needed

### ISSUE THREAD

**Issue by MikeUnverferth** [MicrosoftDocs/cpp-docs#4133]
Should note that need to link to legacy_stdio_definitions.lib as these functions are not in the usual msvc runtime library.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2bb364ee-46da-e132-0020-ce4e4e6c352a
* Version Independent ID: 59c4fd5a-bb2e-3f78-0bff-ba2ab94f5943
* Content: [vsnprintf_s, _vsnprintf_s, _vsnprintf_s_l, _vsnwprintf_s, _vsnwprintf_s_l](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/vsnprintf-s-vsnprintf-s-vsnprintf-s-l-vsnwprintf-s-vsnwprintf-s-l?view=msvc-170)
* Content Source: [docs/c-runtime-library/reference/vsnprintf-s-vsnprintf-s-vsnprintf-s-l-vsnwprintf-s-vsnwprintf-s-l.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/c-runtime-library/reference/vsnprintf-s-vsnprintf-s-vsnprintf-s-l-vsnwprintf-s-vsnwprintf-s-l.md)
* Product: **visual-cpp**
* Technology: **cpp-ucrt**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
@MikeUnverferth, I've added a note at the bottom of the article for this. It should be live early next week.
The issue is that prior to when the UCRT was built, there were many, many exports for all the variants of printf(), scanf(), etc. In attempt to reduce the number of exports in the new UCRT, the variants were grouped into families and a single function exported from the UCRT for each family that could handle all the variants. Then, in the header files, the various functions that were treated this way were inlined and they defer to the single function that handles all the cases. For example, _vsnprintf_s_l, _vsnprintf_s, _snprintf_s_l, and _snprintf_s all defer to __stdio_common_vsnprintf_s. Well, that cleans up the exports, but creates a problem when linking static libraries linked against an older version of the C runtime. legacy_stdio_definitions.lib was created as one way to deal with it if you can't recompile the older library.
