### ISSUE TITLE
Hard to Understand. Example would really help.

### ISSUE THREAD

**Issue by niupre** [MicrosoftDocs/cpp-docs#415]
An example would really help in this scenario. Hard to figure out the exact issue just from reading the description.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1618db17-1471-2891-a876-c3d8aaee28cb
* Version Independent ID: 740dc7c7-1dca-aa7f-c292-d48c87929193
* Content: [Compiler Warning (level 1) C4627](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-1-c4627?view=vs-2017)
* Content Source: [docs/error-messages/compiler-warnings/compiler-warning-level-1-c4627.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/error-messages/compiler-warnings/compiler-warning-level-1-c4627.md)
* Product: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@niupre I believe this warning was replaced in Visual Studio 2015 Update 1 and later by level 4 warning C4654. I need to check with the developers to be sure.

The most important thing to understand here is, never put anything ahead of the precompiled header in your source files except comments. 

The problem C4627 warns about indicates programmer confusion, because the compiler ignores anything found before the `#include "precompiled_header_name.h"` directive. (The most common name for a precompiled header is either "stdafx.h" or "pch.h", but it could be anything.) In VS2015 RTM and before, if the compiler finds a `#include` of a file that is *also* included by the precompiled header before it gets to the precompiled header, then since it would be included anyway, the compiler doesn't issue a warning. On the other hand, if an include file that is *not* in the precompiled header appears before the precompiled header, then it gives this warning. It's not a good explanation of the real problem, which is probably why it was changed.

What the compiler should really tell you is to move that header to somewhere after the precompiled header is included. Otherwise, it causes inexplicable errors later on: errors about undefined identifiers that appear to be perfectly well defined. That sort of thing.

I'll consider updating the text. Hopefully this explanation helps you in the interim.
