### ISSUE TITLE
x64 Calling Convention Return Values section is incorrect

### ISSUE THREAD

**Issue by CouleeApps** [MicrosoftDocs/cpp-docs#4152]
Specifically, in the part about User-defined types, the docs state: 
> To return a user-defined type by value in RAX, [...] it must also have no user-defined constructor, destructor, or copy assignment operator. It can have no private or protected non-static data members, and no non-static data members of reference type. It can't have base classes or virtual functions.

These cases are all correct and return as expected. However,

> And, it can only have data members that also meet these requirements.

This is not the case. For some types, they are returned by value even if they contain a data member that does not meet these requirements. Notably:
- Types with a user-defined constructors
- Types with private non-static data members
- Types with protected non-static data members
- Types with base classes

If a type has a data member that matches the earlier statement about things a type must not have, but it only has elements from this list, then types which have it as a member are still returned by value.

Here's a Godbolt link demonstrating this: https://godbolt.org/z/sKszd7G7e
Note:
- `foo_np1` through `foo_np8` take a pointer to the structure in rcx and take their argument in edx
- `maybe_np1` and `maybe_np7` return the structure directly in eax and take their argument in ecx
- `maybe_np4` and `maybe_np5` take a pointer to the structure in [rsp] and take their argument in ecx
- `maybe_np2`, `maybe_np3`, `maybe_np6`, and `maybe_np8` take a pointer to the structure in rcx and take their argument in edx (as expected)

So it seems to me like the docs attempted to explain consistently the strange rules of the x64 calling convention, but the compiler is somehow stranger yet. I'm not sure of a clean way to document this discrepancy in the calling convention, but I'm reporting this in case someone dares to try. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a87b11e0-0214-175b-0926-0f8a4653e444
* Version Independent ID: 43e8bf4a-9a0d-ea28-d432-ead828604d5e
* Content: [x64 calling convention](https://docs.microsoft.com/en-us/cpp/build/x64-calling-convention?view=msvc-170#return-values)
* Content Source: [docs/build/x64-calling-convention.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/build/x64-calling-convention.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@CouleeApps 
Thanks for the thorough investigation. The effective wording of the statement about data members predates the move to GitHub, so I can't see when it was made, or by whom, but IIRC it was originally from the C++03 POD definition. It got more complex as the actual language standard definition of POD was changed.

@xiangfan-ms Do you have any insights here, or know who else might have knowledge about this?

**Comment by xiangfan-ms** [comment]
The compiler doesn't check for the data member directly when it determines the calling convention. The property of the data member / base class can impact the property of the enclosing class (for example, whether the compiler generated special member function meets the requirement of certain type traits is often determined by the data member / base class), though.

I think there is no need to explicitly mention the data member in the document. You just need to treat both 'user-defined' and 'non-trivial compiler generated' as the criteria.
BTW, there are lots of special rules in addition to the ones mentioned in the document (you can check 'UDTReturnStyle' if you have access to the compiler code base) :-).

**Comment by CouleeApps** [comment]
Is it possible to document all the cases (or see the compiler code base ;-) ), or should I, as someone outside MS, just consider the rules "too complex to implement" and just make an educated guess?

**Comment by corob-msft** [comment]
Considering the complexity of the compiler code, reading it may not be as helpful as you might think. After scrolling through functions with names like `TagMustReturnByValue`, `TagNeedsUDTReturnTransform`, and the aforementioned `UDTReturnStyle`, I'm only slightly more enlightened than before. It's true that it doesn't appear that the checks for data members are recursive, so that statement should go. There also appear to be checks for managed/WinRT types that add some complexity to the return type behavior. And it looks like it may be possible for the compiler to decide to pass a type by reference when using C++ linkage if the complete type is unknown at the function declaration, even if the complete type could be passed by value. Since all callers have to agree on the return type for linking to work, this test must have consistent behavior across translation units. I'm having trouble wrapping my head around this particular test, so I could easily be wrong about its effects.

**Comment by xiangfan-ms** [comment]
These functions are often modified by backend people when they add support for new architecture or instruction set (like the logic related to intrinsic types for MMX/SSE), and we (frontend people) seldom change them except occasional bug fixes (which is rare because we have to keep ABI compatibility and these functions impact ABI).

I can share a human readable interpretation of the logic (many of which involve compiler specific criteria which isn't necessarily part of the C++ standard). But given that I don't work on the logic very often, I can't answer some of your questions (like the reason behind the logic for forward declared type). JonCaves probably has more context on those decisions made many (maybe 30+?) years ago.

**Comment by TylerMSFT** [comment]
Thank you for your patience as we work through our backlog. We have received more issues than we can manage at this time. We are closing issues based on their severity, how broadly applicable they are, and whether there is enough information provided to act on the issue. If you believe that this issue should not have been closed, please add a comment explaining why by 3/1/2024. We appreciate your contribution and encourage you to propose changes using public PRs or submit feedback through our updated control at the top of the page, as we phase out Git Issues for this repo. For more information on our feedback systems, see https://aka.ms/ContentUserFeedback.
