### ISSUE TITLE
No version shown for latest VC++ redistributable

### ISSUE THREAD

**Issue by jlpetz** [MicrosoftDocs/cpp-docs#4172]
All packages show the version number expected the latest "Visual Studio 2015, 2017, 2019, and 2022" redistirbutable. Can you please shown the version for these packages in the table of the page so then people know if there is a newer version without having to download the package and check manually.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 75e6432b-c6ec-e208-5f1c-bbc4fde9929b
* Version Independent ID: 9cbb940e-cddd-f82f-e8bb-ee62b17af794
* Content: [Latest supported Visual C++ Redistributable downloads](https://learn.microsoft.com/en-US/cpp/windows/latest-supported-vc-redist?view=msvc-170)
* Content Source: [docs/windows/latest-supported-vc-redist.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/windows/latest-supported-vc-redist.md)
* Product: **visual-cpp**
* Technology: **cpp-windows**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@jlpetz 
That would be useful, but we deliberately haven't published that information because the docs team isn't told when a Redistributables update ships.

@MahmoudGSaleh @TylerMSFT
Do we know who owns the Redistributables update process? Is there a way to get them to touch this document with version info when there's a new Redistributable version? This isn't the first or second time we've been asked for this info.

**Comment by corob-msft** [comment]
Another duplicate: MicrosoftDocs/cpp-docs/issues/4402

**Comment by stdin82** [comment]
A note was added to address that
https://github.com/MicrosoftDocs/cpp-docs/commit/70bdbf1e057b8af8ddc89f91681909cdfcbfb51f

**Comment by TylerMSFT** [comment]
Closing per the note we added about not updating the version number.
