### ISSUE TITLE
Information about dynamic link libraries mentioning .lib files. Should be dll?

### ISSUE THREAD

**Issue by MathiasDeWeerdt** [MicrosoftDocs/cpp-docs#4175]
Information about dynamic link libraries mentioning .lib files. Should be dll?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 08c574a2-cef0-ab13-7375-55851f966ef6
* Version Independent ID: fe3421c7-e9f4-4986-589f-fadaedce583e
* Content: [Walkthrough: Create and use your own Dynamic Link Library (C++)](https://learn.microsoft.com/en-us/cpp/build/walkthrough-creating-and-using-a-dynamic-link-library-cpp?view=msvc-170)
* Content Source: [docs/build/walkthrough-creating-and-using-a-dynamic-link-library-cpp.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/build/walkthrough-creating-and-using-a-dynamic-link-library-cpp.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@MathiasDeWeerdt 
Good question. This article is mainly about the mechanics of creating a DLL and calling it, so it doesn't do a lot of explaining about DLLs and how they work. To call functions in a DLL as if they were functions from a static library, you need to link your client by using an *import library*, a special kind of .lib file used for a DLL. Rather than containing the actual code like a static library does, a DLL import library just contains stub entries for the DLL's exported functions and data. You add the import library .lib file to the list of libraries and objects passed to the linker, so the linker can resolve those DLL exports when it builds your client executable. At load time, the loader finds the corresponding DLL and loads it into your process address space. Then the loader fixes up the stub entries in your executable to point to the actual DLL functions or data, so your code can call them directly at runtime just as if they were statically linked.

So, that's a long-winded way of saying that when we mention .lib files in this article, they are in fact .lib files, but they're import library files, not static library files. Hope this explains things.
