### ISSUE TITLE
Is there a way to mark our own functions that check an optional is not null so that we don't get this warning?

### ISSUE THREAD

**Issue by Dave-Lowndes** [MicrosoftDocs/cpp-docs#4208]
For example:

bool IsMyThingOK( const std::optional<CMyThing>& mt )
{
	return mt.has_value() && whatever_else_I_do;
}
...
if ( IsMyThingOK( mt ) )
{
  const auto& myThing = *mt; // Getting C26830, despite all being correct.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 58c75314-72f4-763d-9406-a0e55ece1129
* Version Independent ID: 58c75314-72f4-763d-9406-a0e55ece1129
* Content: [Warning C26830](https://learn.microsoft.com/en-us/cpp/code-quality/c26830?f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(C26830)%26rd%3Dtrue&view=msvc-170)
* Content Source: [docs/code-quality/c26830.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/code-quality/c26830.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@Dave-Lowndes 

> Is there a way to mark our own functions that check an optional is not null

Good question, but the answer is, not that I know of. I believe that only local analysis is done for this check, not whole-program analysis, so there's no way to propagate its state out of a function. You can ask the same question on [Developer Community](https://aka.ms/vsfeedback/browsecpp) for a possibly more definitive answer. Since there doesn't seem to be anything to change in the docs, I'm closing the issue.
