### ISSUE TITLE
Visual C++ Redistributable release notes

### ISSUE THREAD

**Issue by kipgawrych** [MicrosoftDocs/cpp-docs#4231]
Hi.  I'm having difficulty locating any release notes for the multiple versions of Visual C++ redistributable.  Specifically, I'm looking for release dates and if the patch is security related or not.  Can you please assist?

**Comment by corob-msft** [comment]
@kipgawrych 

Those are good questions. The [Visual C++ Redistributable](https://learn.microsoft.com/en-US/cpp/windows/latest-supported-vc-redist?view=msvc-170) doesn't have its own release notes. It's one of the [Distributable Code](https://learn.microsoft.com/en-us/visualstudio/releases/2022/redistribution) files available in Visual Studio. If there are security updates for Visual Studio or its Distributable Code files, they'll be mentioned in the [Visual Studio release notes](https://learn.microsoft.com/en-us/visualstudio/releases/2022/release-notes). You can scan the release notes by Visual Studio version in the Learn documentation for specific fixes in older releases. However, any code created with Visual Studio 2015 or later can use the latest Visual Studio 2022 version of the Redistributable, and that's what we recommend.

Older versions of the Redistributable were often accompanied by Knowledge Base articles with specifics on fixes, but as far as I can tell, there hasn't been anything similar written since the Visual Studio 2015 releases.

Since this question isn't one we cover in the C++ documentation, I'm closing it. Best of luck with your code.
