### ISSUE TITLE
#define RAND_MAX 

### ISSUE THREAD

**Issue by JamesBWhite** [MicrosoftDocs/cpp-docs#4240]
this should be a larger field than just 0x7fff  linux has 0x7fff ffff

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7475e01b-e06c-ec55-9ebe-c2e38d957288
* Version Independent ID: a7c918e5-3f03-cd05-b069-d2453d88cff8
* Content: [RAND_MAX](https://learn.microsoft.com/en-us/cpp/c-runtime-library/rand-max?view=msvc-170)
* Content Source: [docs/c-runtime-library/rand-max.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/c-runtime-library/rand-max.md)
* Product: **visual-cpp**
* Technology: **cpp-ucrt**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by corob-msft** [comment]
@JamesBWhite
 
Please, [don't use `rand`](https://learn.microsoft.com/en-us/events/goingnative-2013/rand-considered-harmful). Of all the functions in the C runtime library, [`rand`](https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/rand?view=msvc-170) may be the most [thoroughly deprecated](https://open-std.org/jtc1/sc22/wg21/docs/papers/2013/n3775.pdf). We don't recommend you use it for anything at all, unless you're writing code that has to be backward compatible with exactly the same calls to `rand`, on the same platform, using the same compiler and library. It's certainly not useful for anything remotely cryptographic. As the C++20 standard puts it,

>  [*Note: The other random number generation facilities in this document (26.6) are often preferable to `rand`, because
`rand`’s underlying algorithm is unspecified. Use of `rand` therefore continues to be non-portable, with
unpredictable and oft-questionable quality and performance. — end note*]

As the quote implies, the specific range of values or algorithm used by `rand` isn't specified by any C or C++ standard.  The Microsoft CRT library has used a value of 0x7FFF for `RAND_MAX` since the 1980s, so a breaking change isn't going to happen. It's more of a museum piece now, to be admired, but not touched.

**Comment by JamesBWhite** [comment]
@corob-msft  is there another new function that does this?  Give a number in the 9,999,999,999 to 0  range?

**Comment by corob-msft** [comment]
@JamesBWhite 

A function as easy to use as `rand`? Sadly, no. Even `rand` with a `RAND_MAX` of 0x7FFFFFFF doesn't do what you want, since 0x7FFFFFFF is only 2,147,483,647.

If what you're after is simple, say, a few runs of some Monte Carlo simulation, where you don't care much about cryptographic security, and just want to have a pseudo-random sequence generator with a uniform integer distribution in your specified range, then something like the Randomizer9000(tm) I just bodged up is probably sufficient.

This example uses a class template to create a pseudo-random number generator in a specified range. It's implemented using a Mersenne twister engine with 64 bits of seeded value to supply a uniform integer distribution PRNG of specified bounds, in this case, 0 to 9,999,999,999:

```
// Randomizer9000.cpp
// compile using: cl /EHsc /permissive- /W4 /nologo Randomizer9000.cpp

#include <iostream>
#include <random>

template<typename IntType = int, IntType lower_bound = 0, IntType upper_bound = std::numeric_limits<IntType>::max()>
class Randomizer9000
{
public:
    Randomizer9000()
    {
        std::random_device rd;
        generator.seed((static_cast<uint_fast64_t>(rd()) << 32) | rd());
    }
    IntType generate() { return distribution(generator); }
private:
    std::mt19937_64 generator;
    std::uniform_int_distribution<IntType> distribution {lower_bound, upper_bound};
};

int main()
{
    Randomizer9000<uint64_t, 0LL, 9'999'999'999LL> r10b;

    for (int i = 0; i < 10; ++i)
    {
        std::cout << r10b.generate() << "\n";
    }
}
```
 
The usual disclaimers apply: this isn't production-quality code with appropriate guards for exceptions, etc.; not warranted for merchantability or fitness for purpose; your mileage may vary; void where prohibited or taxed; *Non disponible au Québec*.
