### ISSUE TITLE
set_terminate doesn't work for write access violation

### ISSUE THREAD

**Issue by DCMinds** [MicrosoftDocs/cpp-docs#4249]
//For the below code myterminate function is not called
// I trying to perform write operation on un allocated memory p

#include <iostream>       // std::cerr
#include <exception>      // std::set_terminate
#include <cstdlib>        // std::abort

void myterminate() {
	std::cout << "terminate handler called\n";
	int n;
	std::cin >> n;
	abort();  // forces abnormal termination
}

int main(void) {
	std::set_terminate(myterminate);
	int* p=nullptr;
	//throw 0;  // unhandled exception: calls terminate handler
	std::cout << p;
	*p = 9;

	return 0;
}

**Comment by DCMinds** [comment]
> //For the below code myterminate function is not called // I trying to perform write operation on un allocated memory p
> 
> #include // std::cerr #include // std::set_terminate #include // std::abort
> 
> void myterminate() { std::cout << "terminate handler called\n"; int n; std::cin >> n; abort(); // forces abnormal termination }
> 
> int main(void) { std::set_terminate(myterminate); int* p=nullptr; //throw 0; // unhandled exception: calls terminate handler std::cout << p; *p = 9;
> 
> ```
> return 0;
> ```
> 
> }

**Comment by DCMinds** [comment]
Please help. i am stuck with this

[set_terminate doesn't work for write access violation](https://github.com/MicrosoftDocs/cpp-docs/issues/4249#top)
#4249
[DCMinds](https://github.com/DCMinds) opened this issue 2 minutes ago · 0 comments
Comments
@[DCMinds](https://github.com/DCMinds)
DCMinds commented [2 minutes ago](https://github.com/MicrosoftDocs/cpp-docs/issues/4249#issue-1426862373)
//For the below code myterminate function is not called
// I trying to perform write operation on un allocated memory p

#include // std::cerr
#include // std::set_terminate
#include // std::abort

void myterminate() {
std::cout << "terminate handler called\n";
int n;
std::cin >> n;
abort(); // forces abnormal termination
}

int main(void) {
std::set_terminate(myterminate);
int* p=nullptr;
//throw 0; // unhandled exception: calls terminate handler
std::cout << p;
*p = 9;

return 0;
}

**Comment by corob-msft** [comment]
@DCMinds 
I'm sorry you're having trouble, and also sorry to have to tell you that this isn't a help forum. For that sort of question, you can try [Microsoft Learn Q&A](https://learn.microsoft.com/en-us/answers/topics/c%2B%2B.html). My first guess is that your code can't possibly run with the commented `#include` targets. If you want to have someone help you, code that compiles, or if it doesn't compile, code that shows the exact source used and the exact errors reported by the compiler, is a necessary first step. Since this isn't a documentation issue, I'm closing it. Best of luck with your coding issue.
