### ISSUE TITLE
#pragma loop(no_vector) doesn’t work as advertised.

### ISSUE THREAD

**Issue by Const-me** [MicrosoftDocs/cpp-docs#4265]
[Here’s a repro](https://godbolt.org/z/8azvo9Mdv). As you see from disassembly, the compiler auto-vectorized the loop into 4-wide SIMD, despite the pragma.

To be fair, without the pragma it vectorizes into 8-wide AVX SIMD, and also unrolls the loop by 4 iterations, so the pragma has some effect.

But still, please fix the compiler, or at least document the current behavior. Because currently, it says “specify this pragma to disable the auto-vectorizer” which is not true.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 277c256f-f210-648c-76c1-f20a18a98f96
* Version Independent ID: ed4e9198-1f43-838c-6496-fe7294d49ecd
* Content: [loop pragma](https://learn.microsoft.com/en-us/cpp/preprocessor/loop?view=msvc-170#feedback)
* Content Source: [docs/preprocessor/loop.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/preprocessor/loop.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@Const-me 
Thanks for the report, and the repro. If you suspect a product issue, the place to raise it is on [Developer Community](https://aka.ms/vsfeedback/browsecpp), not in the documentation issues. We can't address product issues here. As such, I can't tell what the right thing to document is. If you'd be kind enough to create an issue there and link it here, we can follow along and document any resolution appropriately.

After some experimentation with your repro, I found that the vectorization is produced by the `/Og` option (enabled by `/O1` and `/O2`). It appears that if you want no vectorization at all, you need to leave `/O2` or `/O1` off of the compiler command line. Since `/Og` predates the auto-vectorizer by decades, I suspect that its loop vectorization optimizations are produced separately from anything produced by the auto-vectorizer. That is, the auto-vectorizer may run as a separate pass from the vectorizer built in to the `/Og` option. The implication is that `/Og` vectorization isn't affected by the `#pragma loop` directive. Without delving deeply into compiler innards that I barely understand, I can't say this for sure. However, I can tell the directive does apply as expected to the auto-vectorizations enabled by the `/Qpar` option. On one of the other `#pragma loop` options, we say, "The compiler ignores this option unless the **`/Qpar`** compiler switch is specified."  Perhaps this qualifier actually applies more broadly.

**Comment by Const-me** [comment]
> It appears that if you want no vectorization at all, you need to leave `/O2` or `/O1` off of the compiler command line.

Unfortunately, that workaround is not acceptable for my use cases. I want to disable vectorization of very specific loops. These loops handle remainder regions of the input buffers as the last step of manually-vectorized functions.

Without that pragma, the compiler typically auto-vectorizes that code. The compiler is not smart enough to conclude that final loop runs for just a few iterations after the majority of the input data is already consumed by another loop, which uses SIMD intrinsics.

Auto-vectorization of these remainder loops inflates code for no good reason, sometimes by an order of magnitude.

Reducing optimization level would be counter-productive. For my performance-critical C++, I want maximum level of optimizations, and normally I want automatic vectorization too. Just not for these remainder loops.

**Comment by TylerMSFT** [comment]
Thank you for your patience as we work through our backlog. We have received more issues than we can manage at this time. We are closing issues based on their severity, how broadly applicable they are, and whether there is enough information provided to act on the issue. If you believe that this issue should not have been closed, please add a comment explaining why by 2/23/2024. We appreciate your contribution and encourage you to propose changes using public PRs, or submit feedback through our updated control at the top of the page, as we phase out Git Issues for this repo. For more information on our feedback systems, see https://aka.ms/ContentUserFeedback.
