### ISSUE TITLE
need the dll name

### ISSUE THREAD

**Issue by ToddAndMargo** [MicrosoftDocs/cpp-docs#4314]
What is the name of the dll?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0b6b874d-c2c9-81d6-eaa3-eca9e43cf7ea
* Version Independent ID: f636c0be-83b2-0b26-a115-430b303e638d
* Content: [C runtime library reference](https://learn.microsoft.com/en-us/cpp/c-runtime-library/c-run-time-library-reference?view=msvc-170)
* Content Source: [docs/c-runtime-library/c-run-time-library-reference.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/c-runtime-library/c-run-time-library-reference.md)
* Product: **visual-cpp**
* Technology: **cpp-ucrt**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
It depends...
These topics may help:
https://learn.microsoft.com/en-us/cpp/windows/universal-crt-deployment?view=msvc-170
https://learn.microsoft.com/en-us/cpp/c-runtime-library/crt-library-features?view=msvc-170 
If you are asking so that you can redistribute it/them, see: https://learn.microsoft.com/en-us/cpp/windows/redistributing-visual-cpp-files?view=msvc-170
For an overview of the refactoring of the CRT, see https://devblogs.microsoft.com/cppblog/the-great-c-runtime-crt-refactoring/
