### ISSUE TITLE
Documentation too scarce

### ISSUE THREAD

**Issue by hfmanson** [MicrosoftDocs/cpp-docs#4316]
Is there documentation available which elaborates on the /SUBSYSTEM linker option? E.g. what does the POSIX subsystem mean?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: de5d3882-a68f-f94f-6096-428c444e6f8a
* Version Independent ID: d9e66b9c-a94f-69a9-fd9e-51a666dbf618
* Content: [/SUBSYSTEM (Specify Subsystem)](https://learn.microsoft.com/en-us/cpp/build/reference/subsystem-specify-subsystem?view=msvc-170)
* Content Source: [docs/build/reference/subsystem-specify-subsystem.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/build/reference/subsystem-specify-subsystem.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@hfmanson 

Thanks for asking. Is your request driven by a specific need, or idle curiosity?

Behind the scenes, the /SUBSYSTEM options control some flags set in the [PE header](https://learn.microsoft.com/en-us/windows/win32/debug/pe-format) for your binary. That document says what the flags are, but not what they're for. For that, most developers don't need any more detail than we provide here. Normally, one of these options is set for you by a template in the Visual Studio IDE based on the type of app you're writing, so you don't even have to think about it.

The people who use subsystem values other than WINDOWS or CONSOLE usually get their information from the documentation on the specific subsystem. For example, you'd learn more about the EFI subsystems in the [vendor documentation for programming UEFI drivers](https://www.intel.com/content/www/us/en/architecture-and-technology/unified-extensible-firmware-interface/uefi-driver-and-application-tool-resources.html). The NATIVE subsystem is used by some kernel drivers, described in the [Windows Hardware SDK](https://developer.microsoft.com/en-us/windows/hardware/) docs. If you're writing a BOOT_APPLICATION, [you know](https://learn.microsoft.com/en-us/windows-hardware/drivers/bringup/boot-and-uefi).

The POSIX option is for creating a binary that targets the now paleologically archaic [Microsoft POSIX subsystem](https://en.wikipedia.org/wiki/Microsoft_POSIX_subsystem). The POSIX subsystem has been obsolete for twenty years. It was dropped from Windows XP and Windows Server 2003. The linker switch still exists, so we include it in the documentation for historical reasons (that is, some people are still maintaining archaic software) and because no one asked us to remove it. 

I'm closing your issue as too general to address. If you have some articulable need for something specific, we can re-open it.
