### ISSUE TITLE
Conversions of unsigned long long to floating point look wrong

### ISSUE THREAD

**Issue by WilliamCushing** [MicrosoftDocs/cpp-docs#4320]
The table implies that after this:
```
    float f1 = 8.e12;
    unsigned long long ull = f1;  // 8 trillion is representable in both types 
    float f2 = ull;                         // so f1 == f2
```
f1 and f2 differ, because supposedly the last statement executes like:
```
    float f2 = (long)ull;
```
resulting in f2 == 0 (assuming long is 32 bits and ull is 64).

But I would like to believe in the following two points:
  1) Integral -> Floating point essentially only loses precision -- 'never' scale and unequivocally the sign bit is always correct. (Extreme conversions of int64_t or yet larger integrals to tiny floats like Float(5,11+1), can exhaust the mere 5 bits of exponent resulting in the loss of all bits, high and low, except one: the sign bit.  The result should be clamped to +-max (or +-inf, [impl. defined])
  2) In particular, `assert(0 <= Float(Unsigned(Mersenne()));` will never fail -- no conversion of an unsigned integral type to a floating point type will ever be negative.

**Comment by corob-msft** [comment]
@WilliamCushing 

Thanks for the report. I assume you're referring to the conversion table in [Conversions from unsigned integral types](https://learn.microsoft.com/cpp/c-language/conversions-from-unsigned-integral-types). A little experimentation with the 64-bit C compiler reveals that magnitude and sign are preserved for `unsigned long long` values implicitly converted to `float` by the usual arithmetic conversions, without a stop at conversion to `long` (or `long long`, for that matter).

@jpmorgan-atMS, do you have any insight to share here?

**Comment by jpmorgan-atMS** [comment]
Compliance with Standard C++-/C requires unsigned long and unsigned long long values to be converted to the correct floating-point values, and MSVC has been compliant for quite some time now. The last issue I know of with these conversions was an issue with rounding in the 64-bit compiler that was corrected years ago. I suspect that pre-standard versions of MSVC were doing an implicit conversion to long because the 8087 did not have an instruction for conversion from unsigned long or unsigned long long values. This is handled by adding a few additional instructions to compensate for incorrect conversion. The AVX-512 instruction set extension does have instructions to convert from these types, so no additional instructions are needed.

- John

**Comment by jpmorgan-atMS** [comment]
That last sentence should end "no additional instructions are needed when compiling with /arch:AVX512."

- John

From: John Morgan (Intel Corporation)
Sent: Monday, December 5, 2022 9:15 AM
To: MicrosoftDocs/cpp-docs ***@***.***>; MicrosoftDocs/cpp-docs ***@***.***>
Cc: Mention ***@***.***>
Subject: RE: [MicrosoftDocs/cpp-docs] Conversions of unsigned long long to floating point look wrong (Issue #4320)

Compliance with Standard C++-/C requires unsigned long and unsigned long long values to be converted to the correct floating-point values, and MSVC has been compliant for quite some time now. The last issue I know of with these conversions was an issue with rounding in the 64-bit compiler that was corrected years ago. I suspect that pre-standard versions of MSVC were doing an implicit conversion to long because the 8087 did not have an instruction for conversion from unsigned long or unsigned long long values. This is handled by adding a few additional instructions to compensate for incorrect conversion. The AVX-512 instruction set extension does have instructions to convert from these types, so no additional instructions are needed.

- John

**Comment by corob-msft** [comment]
Thanks, John. I'll update the documentation accordingly.

**Comment by corob-msft** [comment]
Updates to [Conversions from unsigned integral types](https://learn.microsoft.com/cpp/c-language/conversions-from-unsigned-integral-types) and [Conversions from signed integral types](https://learn.microsoft.com/cpp/c-language/conversions-from-signed-integral-types) are now live.

**Comment by WilliamCushing** [comment]
Thanks for fixing the docs! (and yes, indeed, I was referring to the conversion tables you linked)
