### ISSUE TITLE
When to call Close() on a CAsyncMonikerFile

### ISSUE THREAD

**Issue by richard-broadhurst** [MicrosoftDocs/cpp-docs#4323]
Really hard to find this class, but very useful.
Docs don't say when Close() should be called.
In OnDataAvailable at the end would be nice, but that doesn't fell right!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e87138fe-3f12-5d69-a590-b41f5d25a675
* Version Independent ID: 589c9cb0-f81a-995a-e53b-e0cfe9b6c28d
* Content: [CAsyncMonikerFile Class](https://learn.microsoft.com/en-us/cpp/mfc/reference/casyncmonikerfile-class?view=msvc-170#onprogress)
* Content Source: [docs/mfc/reference/casyncmonikerfile-class.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/mfc/reference/casyncmonikerfile-class.md)
* Product: **visual-cpp**
* Technology: **cpp-mfc**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
@richard-broadhurst, we can't really prescribe when to call Close() because it depends on your use case. I would say close it when you are done with it. I don't see a framework function that looks like a good place to call it from. I'd personally close it as soon as I was done with it so I'm not dragging an open file handle around longer than necessary. You can call Close() even if the file is already closed or unopened (see [ref](https://nam06.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.icodeguru.com%2FVC%2526MFC%2FMFCReference%2Fhtml%2F_mfc_casyncmonikerfile.3a3a.close.htm&data=05%7C01%7CTyler.Whitney%40microsoft.com%7Ccfa0c9ed5b464d7b26bb08dae38736d7%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638072467123858497%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=jqJ1kuPdyv7WE8NA2MIuC60bTJ92KpLxT4XpHo1BMqA%3D&reserved=0))
