### ISSUE TITLE
Example with /Fo and path incomplete

### ISSUE THREAD

**Issue by LurkingKiwi** [MicrosoftDocs/cpp-docs#4335]
Trying to use /Fo to specify a quoted path on the command line as per the example returned an error.
d:\LoRa>cl /Fo"Build\" datalog-lsn50.c spiflash.c crc16.c dlog_dummy.c dlog_test.c
Microsoft (R) C/C++ Optimizing Compiler Version 19.29.30147 for x86
Copyright (C) Microsoft Corporation.  All rights reserved.

cl : Command line error D8003 : missing source filename

I had to double the backslash when running the command in the Native Tools command prompt (or remove the quotes).
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2ca1e187-dfc2-3988-c184-845a66930ce1
* Version Independent ID: a4cdc0a2-9b78-9457-62ab-67ef1f135ab5
* Content: [/Fo (Object file name)](https://learn.microsoft.com/en-us/cpp/build/reference/fo-object-file-name?view=msvc-160)
* Content Source: [docs/build/reference/fo-object-file-name.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/build/reference/fo-object-file-name.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@LurkingKiwi 
Thanks for the report. I wondered why the compiler hadn't reported D8036 for your example instead of D8003. It took me a few moments to realize that the markdown renderer had eaten the trailing backslash in your example, which made all the difference. You're right, the example in the article is incorrect. The text is not quite as incorrect, as it describes using a slash, not a backslash, but it's not as helpful as it could be. A fix is in the works and should be available tomorrow.
