### ISSUE TITLE
Why there is a  character '\' followed some macro?

### ISSUE THREAD

**Issue by chucklu** [MicrosoftDocs/cpp-docs#434]
Most time I use these two marcos: $(TargetDir) and $(SolutionDir).
I pass them as parameters to a .bat in post build event of a project.

Then I will pass the parameter to Powershell(pwsh in Powershell 6.0).
However, when the folder name contains space in it, I will add double quotes to the parameter.
 
And the double quotes invoke in cmd, will cause some problems.
https://blogs.msdn.microsoft.com/twistylittlepassagesallalike/2011/04/23/everyone-quotes-command-line-arguments-the-wrong-way/

For me, the double quotes make the parameter parse not correctly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ba7e6dc-88bf-47ff-7bcf-467140bc92f1
* Version Independent ID: 5dfa8c91-eb92-8905-741e-15cd10d54baa
* Content: [Common macros for build commands and properties](https://docs.microsoft.com/en-us/cpp/ide/common-macros-for-build-commands-and-properties?view=vs-2017)
* Content Source: [docs/ide/common-macros-for-build-commands-and-properties.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/ide/common-macros-for-build-commands-and-properties.md)
* Product: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by chucklu** [comment]
- 1.

I have the following code in post build event 
.bat with six parameters
> "$(TargetDir)en-US\Resources.bat" "$(SolutionDir)" "$(TargetDir)" "$(TargetName)" "$(TargetExt)" en-US "$(ProjectDir)"

- 2.

the code in Resources.bat, this is usedto invoke pwsh(Powershell 6.0)
```bat
set solutionDir=%~1
set targetDir=%~2
set targetName=%~3
set targetExt=%~4
set languageCode=%~5
set projectDir=%~6
echo %solutionDir%
pwsh -file "%solutionDir%powershell\Resources.ps1" "%solutionDir%"
```
the echo result is 
`C:\Users\clu\source\repos\Core - Test\Solution\` ,there is not double quotes. Then I need pass it to pwsh with double quotes


- 3.

the code in Resources.ps1, used to import module
```Powershell
$moduleDir = $args[0]
$targetDir = $args[1]
$targetName = $args[2]
$targetExt = $args[3]
$languageCode = $args[4]

$modulePath = "{0}powershell\Resources.psm1" -f $moduleDir
echo $modulePath
```
the echo result is
 C:\Users\clu\source\repos\Core - Test\Solution"powershell\Resources.psm1
It means the parameter pass into Resources.ps1 with ", it make the file path not valid

**Comment by mikeblome** [comment]
investigating

**Comment by corob-msft** [comment]
@chucklu This seems more like a support question than a documentation question. I don't know how the document could be changed to answer your question; The values in some properties just end in a backslash. If your question is *why* some of the macro values in Visual Studio end with a backslash, then the answer is probably for convenience for someone. 

If your question is how to escape the trailing backslash when passing it out of a batch file to a command, then I recommend adding another backslash, so together the two backslashes are interpreted as one, rather than as an escape for the following double-quote. This answer may not work in other situations, so it's not something that the document should include.

**Comment by chucklu** [comment]
@corob-msft  thanks, I can use trimend to remove the backslash. 
But it's not convenient, I need to do the same thing again and again when I want to pass the dir as parameter.
