### ISSUE TITLE
Suggestion.:

### ISSUE THREAD

**Issue by mythrz** [MicrosoftDocs/cpp-docs#4341]
https://learn.microsoft.com/en-us/cpp/build/walkthrough-creating-and-using-a-dynamic-link-library-cpp?view=msvc-170

Don't Name everything with the same name. SolutionName=ProjectName=header/cppName= MathLibrary
Documentation is meant to be concise, and in this case, made it confusing to keep track of what I was referencing

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 08c574a2-cef0-ab13-7375-55851f966ef6
* Version Independent ID: fe3421c7-e9f4-4986-589f-fadaedce583e
* Content: [Walkthrough: Create and use your own Dynamic Link Library (C++)](https://learn.microsoft.com/en-us/cpp/build/walkthrough-creating-and-using-a-dynamic-link-library-cpp?view=msvc-170)
* Content Source: [docs/build/walkthrough-creating-and-using-a-dynamic-link-library-cpp.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/build/walkthrough-creating-and-using-a-dynamic-link-library-cpp.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@mythrz 

Thanks for taking the time to comment. I understand the common naming can be confusing. In this case, the common names are intentional. It's not unusual for real-world projects that have just one binary to share solution and project names, and often enough, to generate a binary with that same name. This is the default behavior of the IDE for most templates that generate solutions. In this case, our solution has two binaries, but they're relatively easy to distinguish. We name everything with the one common name by default, because using different names would add extra steps to the tutorial, and because the extra steps would introduce a source of potential mistakes in naming that would be difficult for beginners to diagnose. It's simpler this way on purpose, even if it comes at some cost. I appreciate your suggestion, but I'm leaving it as is for the other reasons given.
