### ISSUE TITLE
Why  #pragma warning( disable : 4003 ) not work

### ISSUE THREAD

**Issue by GameGameNoGG** [MicrosoftDocs/cpp-docs#4342]
I tested the snippet to only disable warning c4003 for test() but it did  not work.
```
#pragma warning( push )
#pragma warning( disable : 4003 )
#define test(A,B) A##B
#pragma warning( pop )

int main()
{
    test("1");
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9651a718-4fc5-35ea-f5d8-b3d4fc355639
* Version Independent ID: be36f8da-7c38-53c7-7d25-c9ea1f0f6755
* Content: [warning pragma](https://learn.microsoft.com/en-us/cpp/preprocessor/warning?view=msvc-170)
* Content Source: [docs/preprocessor/warning.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/preprocessor/warning.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@GameGameNoGG 

I think I see the source of your result. The `warning` pragma must be applied where the warning is generated. In this case, that would be around line 8, where the `test` macro is invoked. Since you've popped the `warning` pragma change before this line is encountered, it has no effect. Since it's behaving as expected and documented, I'm closing the issue.
