### ISSUE TITLE
Wrong language

### ISSUE THREAD

**Issue by ndearns** [MicrosoftDocs/cpp-docs#4349]
The code examples are labeled as C++ but they are some other language. 

C#?

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 97735f3b-8b07-d1a9-3456-72055a863ffd
* Version Independent ID: d51b0f2d-a9c7-58b1-e8c9-ae66f0a15dce
* Content: [typeid  (C++/CLI and C++/CX)](https://learn.microsoft.com/en-us/cpp/extensions/typeid-cpp-component-extensions?view=msvc-170)
* Content Source: [docs/extensions/typeid-cpp-component-extensions.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/extensions/typeid-cpp-component-extensions.md)
* Product: **visual-cpp**
* Technology: **cpp-cli**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@ndearns 

If there's actual C# code in our documentation, it's usually labelled as such, as for example in [How to: Expose an STL/CLR Container from an Assembly](https://learn.microsoft.com/en-us/cpp/dotnet/how-to-expose-an-stl-clr-container-from-an-assembly?view=msvc-170). The examples in this particular document are written in the C++/CX and C++/CLI extensions to standard C++. For technical reasons, the label is plain "C++" because the code colorizer doesn't recognize the more specific "C++/CX" and "C++/CLI" labels and does the wrong thing. Given the title of the article, we expect readers to realize that they're looking at the extensions documentation and to adjust their expectations accordingly. I don't have a better solution available, so I'm closing the issue.
