### ISSUE TITLE
The page misses info that Microsoft SDK is required to be installed.

### ISSUE THREAD

**Issue by msl1** [MicrosoftDocs/cpp-docs#4353]
[The page misses info that Microsoft SDK is required to be installed.]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c6b25c8d-63c4-e903-69cc-a90b88f7b13d
* Version Independent ID: 113c6b83-1457-d4ac-93d0-4177abb3b993
* Content: [Walkthrough: Compiling a Native C++ Program on the Command Line](https://learn.microsoft.com/en-us/cpp/build/walkthrough-compiling-a-native-cpp-program-on-the-command-line?view=msvc-170)
* Content Source: [docs/build/walkthrough-compiling-a-native-cpp-program-on-the-command-line.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/build/walkthrough-compiling-a-native-cpp-program-on-the-command-line.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@msl1 
All of the required parts of the SDK are installed by default when you install the C++ workload in the Visual Studio Installer for either the IDE or the command line tools. You'd have to go out of your way to remove them before this tutorial wouldn't work as written. Since that would be unexpected on the part of a reader, I'm not convinced that anything here needs to be changed.
