### ISSUE TITLE
Setup instructions feel incomplete for windows 10 uwp development

### ISSUE THREAD

**Issue by chrisfromwork** [MicrosoftDocs/cpp-docs#437]
Someone may want to rerun through these instructions using visual studio 2017/building against windows 10 sdks.

What I've noticed:
1) It's not immediately obvious how to get a generic dll to output a winmd with visual studio 2017. Compared to opting to create a new dll (Universal windows) project, I would suggest creating a windows runtime component (universal windows) project. Windows runtime components default to outputting winmds. Manually adding the idl and dllmain definitions as described to a windows runtime component should get things into a useable state.
2) MediaCapture::AddEffectAsync has been deprecated. In this instance adding a video effect works if you use a video effect definition where the name is the name of the activatable class defined in the dll
3) Calling into the mft dll required adding an additional stub to the media capture projects appxmanifest (replace dll name and mftclassname with whatever is appropriate):

  &lt;Extensions&gt;
    &lt;Extension Category="windows.activatableClass.inProcessServer"&gt;
      &lt;InProcessServer&gt;
        &lt;Path&gt;dllname.dll&lt;/Path&gt;
        &lt;ActivatableClass ActivatableClassId="mftclassname" ThreadingModel="both" /&gt;
      &lt;/InProcessServer&gt;
    &lt;/Extension&gt;
  &lt;/Extensions&gt; 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b95590c-f5e4-5a48-dc1e-c45033ac7c9e
* Version Independent ID: cbc07d96-b320-8e64-50b1-af3e483a4e31
* Content: [Walkthrough: Creating a UWP app using WRL and Media Foundation](https://docs.microsoft.com/en-us/cpp/windows/walkthrough-creating-a-windows-store-app-using-wrl-and-media-foundation?view=vs-2017)
* Content Source: [docs/windows/walkthrough-creating-a-windows-store-app-using-wrl-and-media-foundation.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/windows/walkthrough-creating-a-windows-store-app-using-wrl-and-media-foundation.md)
* Product: **visual-cpp**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by mikeblome** [comment]
investigating

**Comment by mikeblome** [comment]
@chrisfromwork thanks for the feedback. We updated the call to AddEffectAsync. with respect to generating metadata, did you you do this step under #11 Linker properties: Under Windows Metadata, set Generate Windows Metadata to Yes (/WINMD). ?

**Comment by mjmeans** [comment]
I followed the instructions on this walkthrough exactly. It works. Strange that it doesn't require the appxmanifest extension ActivatableClass entry in order to run.

**Comment by mjmeans** [comment]
The GitHub Windows-universal-samples\Samples\SimpleCommunication sample does not use dllmain, module.def or module.idl. But that sample uses an ActivatableClass entry.

**Comment by chrisfromwork** [comment]
I can't say with confidence that there isn't an issue with my local development environment. If others have been able to get through this tutorial completely and get things working, it seems reasonable to not want to change the documentation.

**Comment by mjmeans** [comment]
You can check your development environment using the attached project. It was built by following the walkthrough. It works fine on my PC using VS 2017 Community and building for DEBUG|x86. If this project works, then you perhaps missed a step or accidentally made some other change.
[MediaCapture.zip](https://github.com/MicrosoftDocs/cpp-docs/files/2416512/MediaCapture.zip)

Good luck. 

This sample only takes a single image photo and doesn't display continuous live video. I hope they soon update the full media foundation samples project on MSDN (built for Windows 8.1 and Windows Phone 8.1) that has several examples of processing audio and video, including several other MFT samples including AudioDelayTransform, GeometricSource, InvertTransform, Mpeg1Decoder, Mpeg1Source, and PolarTransform. my own attempts at converting those projects to UWP has failed, always getting a ClassFactory activation error.

**Comment by mjmeans** [comment]
FYI I've done a line by line comparison between the old GrayscaleTransform sample Windows Store 8.1 code [here](https://code.msdn.microsoft.com/windowsapps/Media-extensions-sample-7b466096) and this GrayscaleTransform. Besides being expanded with new settings, there are significant differences in the project design. The old one uses a Windows Runtime Component project type and the new one uses a DLL project type. I've tried opening the old sample in VS 2015 and creating a new Universal Windows Runtime Component C++ project using the same GrayscaleTransform.Shared project that the Windows 8.1 and WindowsPhone 8.1 projects use, and with the same project property settings. This build, but the resulting component will not load.

If you want to try it yourself, get the sample project from the link above and open it with VS 2015 (it cannot be opened in VS 2017 because the UI app targets Windows 8.1 and will not open in VS2017.. Create a new project using Visual C++ > Windows > Universal > Windows Runtime Component and name it "GrayscaleTransform.Universal". In the project properties set General > Target Name = GrayscaleTransform. Add to C/C++ > General > Additional Include Directories "..\..\Common". Add to Linker > Input >Additional Dependencies "mfplat.lib, mfuuid.lib, runtimeobject.lib". Delete the files Class1.cpp, Class1.h, pch.cpp, pch.h. Add a references to the shared project GrayscaleTransform.Shared. Then change the reference in the "MediaExtensions.Windows" project from "GrayscaleTransform.Windows" to "GrayscaleTransform.Universal". You can see that all other transforms (Windows 8.1 projects) work in UWP as is, but the GrayscaleTransform.Universal project doesn't. You get an unhandled win32 exception.

**Comment by mjmeans** [comment]
I've posted my attempt at creating a GrayscaleTransform from the old Windows 8.1 samples using a UWP Windows Runtime Component project instead of a DLL project. It is [here](https://github.com/mjmeans/Media-extensions-sample). I invite anyone to collaborate on why this doesn't work and how it can work. The goal is to update the entire Windows 8.1 MF sample to UWP.

**Comment by mikeblome** [comment]
@mjmeans thanks! I'll try to find someone who can take a look.

**Comment by mikeblome** [comment]
@mjmeans @chrisfromwork I'm obviously not getting any traction on this. You should much better luck posting this issue on Developer Community: https://developercommunity.visualstudio.com/spaces/8/index.html.
