### ISSUE TITLE
/CETCOMPAT documentation is not clear whether it should be applied to DLL's, EXE's or both

### ISSUE THREAD

**Issue by avivanoff** [MicrosoftDocs/cpp-docs#4382]
[Direct question to Microsoft](https://techcommunity.microsoft.com/t5/windows-os-platform-blog/developer-guidance-for-hardware-enforced-stack-protection/bc-p/3714569/highlight/true#M527) and [Stackoverflow](https://stackoverflow.com/questions/75099237/cetcompat-dlls-and-exes) are unanswered.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 20d8d73e-dcd5-67db-4050-54ec1c26463b
* Version Independent ID: ad26ab58-5b51-30ae-5201-46ab487484cb
* Content: [/CETCOMPAT (CET Shadow Stack compatible)](https://learn.microsoft.com/en-us/cpp/build/reference/cetcompat?view=msvc-170)
* Content Source: [docs/build/reference/cetcompat.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/build/reference/cetcompat.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@avivanoff 

I see no documentation that says the /CETCOMPAT flag applies to only one kind of executable image. As far as I'm aware, It's applicable to anything with a PE header as long as it contains x86 or x64 code. Have you seen any indication to the contrary? What prompted the question?

**Comment by avivanoff** [comment]
@corob-msft, about 9 paragraphs down in [Developer Guidance for Hardware-enforced Stack Protection](https://techcommunity.microsoft.com/t5/windows-os-platform-blog/developer-guidance-for-hardware-enforced-stack-protection/bc-p/3714569/highlight/true):

`Note that all native 64-bit Windows DLLs are compiled with /CETCOMPAT.`

Whay only DLL's?

**Comment by corob-msft** [comment]
@avivanoff 
When I saw that comment, "all native 64-bit Windows DLLs are compiled with /CETCOMPAT", I assumed it meant `/CETCOMPAT` was set for all the x64 DLLs shipped as part of the Windows OS. Windows consists primarily of DLLs, so that didn't seem unusual to me. Now I'm wondering if that interpretation is correct. @laxmansole, can you elaborate?

**Comment by avivanoff** [comment]
@corob-msft, @laxmansole, any updates?

**Comment by corob-msft** [comment]
@avivanoff 

I'm not sure what question you're asking. If the question is where to apply /CETCOMPAT, the flag can be applied to every kind of executable image. The hardware shadow stack doesn't know or care if the code it's executing is in an EXE or a DLL. The compiler doesn't know if an object file it generates will be linked into an EXE or DLL. That's why it's a linker option. If your target hardware supports it and it doesn't break your code, use /CETCOMPAT everywhere. It makes your apps and libraries harder to corrupt and turn into an attack vector for malware.

If the question is about why the article mentions that /CETCOMPAT is applied to all native x64 DLLs, it's because [that's what the developer wrote](https://techcommunity.microsoft.com/t5/windows-os-platform-blog/developer-guidance-for-hardware-enforced-stack-protection/bc-p/3714569/highlight/true#M527:~:text=Note%20that%20all%20native%2064%2Dbit%20Windows%20DLLs%20are%20compiled%20with%20/CETCOMPAT). In that article, the option is clearly also applied to various EXE files that ship with Windows (for example, svchost.exe is mentioned), so it's not meant to imply an exclusion.

**Comment by avivanoff** [comment]
@corob-msft,

Thank you for clarification. That article did confuse me, and the fact that some Microsoft-made executables were compiled with that switch, and some of them were not.

**Comment by TylerMSFT** [comment]
Thank you for your patience as we work through our backlog. We have received more issues than we can manage at this time. We are closing issues based on their severity, how broadly applicable they are, and whether there is enough information provided to act on the issue. If you believe that this issue should not have been closed, please add a comment explaining why by 2/23/2024. We appreciate your contribution and encourage you to propose changes using public PRs, or submit feedback through our updated control at the top of the page, as we phase out Git Issues for this repo. For more information on our feedback systems, see https://aka.ms/ContentUserFeedback.
