### ISSUE TITLE
Order of precedence?

### ISSUE THREAD

**Issue by ahtello** [MicrosoftDocs/cpp-docs#4435]
Code example: 
    'private int year = 2023;
    private static int ToDecadeBeginning(this int year) => year / 10 * 10;'
    
According to order of precedence-and-order-of-evaluation in this documentation,
I think this expression should evaluate to 2023 / (10 * 10) = 20.
Instead it evaluates to (2023 / 10) * 10 = 2020.

Can I get an explanation of why, or is it a bug in VS Studio (2022 and Code)?

![MicrosoftTeams-image (3)](https://user-images.githubusercontent.com/126264004/221206128-e76f8eec-ec7e-4150-a065-44487937d4db.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ddc4f59b-159f-5038-fc24-4e78c7dff783
* Version Independent ID: f0015080-14af-58f1-15bb-c2691ea4186f
* Content: [Precedence and order of evaluation](https://learn.microsoft.com/en-us/cpp/c-language/precedence-and-order-of-evaluation?view=msvc-170)
* Content Source: [docs/c-language/precedence-and-order-of-evaluation.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/c-language/precedence-and-order-of-evaluation.md)
* Product: **visual-cpp**
* Technology: **cpp-c-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@ahtello 
Sorry you're having trouble. Your example doesn't look very much like C, which as far as I know doesn't support `private` or `this` declarators, so I have to wonder if you're even looking at the right documentation. From your description, the expression ` year / 10 * 10;` is being evaluated correctly as `(year / 10) * 10;` since that's what left to right evaluation means. The `/` and `*` operators have equal precedence, so the leftmost operands are paired up by `/` first, and the temporary result is then paired up with the `*` operator and the next operand. Since this doesn't appear to be a documentation issue, I'm closing it. Best of luck with your code.

**Comment by ahtello** [comment]
Ok, sorry, my code is C#, my misstake.
