### ISSUE TITLE
Show code doing the same without [event_source(native)] attributes

### ISSUE THREAD

**Issue by troglobytor** [MicrosoftDocs/cpp-docs#4438]
It would be educational to show code doing the same thing without using attribute "[event_source(native)]"

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 31f09726-cc61-858c-3a0d-4fc80a0288b0
* Version Independent ID: d0ef017b-b938-4401-6c9a-1405bd60e096
* Content: [Event handling in native C++](https://learn.microsoft.com/en-us/cpp/cpp/event-handling-in-native-cpp?redirectedfrom=MSDN&view=msvc-170)
* Content Source: [docs/cpp/event-handling-in-native-cpp.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/cpp/event-handling-in-native-cpp.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@troglobytor 
Thanks for the suggestion. Adding documentation isn't planned, because [event handling support in native C++ is deprecated](https://learn.microsoft.com/en-us/cpp/cpp/event-handling?view=msvc-170). It's probably not worthwhile to replicate compiler intrinsic behavior without using the provided compiler attributes for events.
