### ISSUE TITLE
Confusing describtion of shadow space

### ISSUE THREAD

**Issue by Michal-Martinek** [MicrosoftDocs/cpp-docs#4439]
I found this sentence confusing:
"Any parameters beyond the first four must be stored on the stack after the shadow store before the call."
especially the word "after"
What does that mean?
Up or Down the stack?
On my machine the stack grows "down" (to lower addrs) so that would suggest that after means lower addr
But after could also mean after the addr of the shadow space, which means higher addr -> "up the stack"

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a87b11e0-0214-175b-0926-0f8a4653e444
* Version Independent ID: 43e8bf4a-9a0d-ea28-d432-ead828604d5e
* Content: [x64 calling convention](https://learn.microsoft.com/en-us/cpp/build/x64-calling-convention?view=msvc-170)
* Content Source: [docs/build/x64-calling-convention.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/build/x64-calling-convention.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@Michal-Martinek 
I'm sorry you found it confusing, and I appreciate that you shared your concern. "After" in the context of this article means "where things get pushed next," or in this particular case, where the subsequent parameters would be pushed on the stack in the absence of register calling conventions. The word "after" is used precisely because it doesn't require any knowledge or assumptions about the direction of stack growth, whereas a word like "lower" or "higher" does. Thus, I'm disinclined to add an explanation of those details here that's pedantic and disruptive to the flow of thought for most readers.
