### ISSUE TITLE
/Gs is not the same as /Gs0

### ISSUE THREAD

**Issue by zmodem** [MicrosoftDocs/cpp-docs#445]
/Gs is not the same as /Gs0; instead it seems to set the stack probe size to the default, i.e. /Gs4096.

See e.g. http://llvm.org/PR39074

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a7677050-221f-18a7-7f9f-0ce6c76fd878
* Version Independent ID: efdfd190-b9e8-d951-5256-41132bf4c743
* Content: [-Gs (Control Stack Checking Calls)](https://docs.microsoft.com/en-us/cpp/build/reference/gs-control-stack-checking-calls?view=vs-2017)
* Content Source: [docs/build/reference/gs-control-stack-checking-calls.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/reference/gs-control-stack-checking-calls.md)
* Product: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
The fixes are published. We now specifically note that /Gs is the same as /Gs0 only for x64 targets.

**Comment by zmodem** [comment]
Thanks for the update! Looking through the doc, it reads much clearer now.

```
For x64 targets, if the /Gs option is specified without a size argument, it is the same as /Gs0 [...]

For x86, ARM, and ARM64 targets, the /Gs option without a size argument is the same as /Gs4096 [...]
```

The /Gs without argument behaviour on x64 is surprising. Do you know why there's a difference depending on target and why this would be desired on x64?

**Comment by corob-msft** [comment]
I tried to find out, but didn't learn much, since it's a flag that's been around a lot longer than the version control systems we currently use. It may be a case of "mistakes were made" that live on because a change would break someone's code. It's hard to imagine how changing it wouldn't be an improvement in this case, though. This is one of the flags you should definitely not apply unless you know what you're doing, have profiled your code, and have set a non-default stack commit size.

**Comment by zmodem** [comment]
Thanks for looking into it. At least it's well documented now :-)
