### ISSUE TITLE
Cannot call an exe that is outside of the opened folder

### ISSUE THREAD

**Issue by chaosink** [MicrosoftDocs/cpp-docs#4451]
My attempts show that the properties "program" and "type=dll" are ignored.
It's the "project" that is called.

Actually what I want is to call an exe that is outside of the opened folder.
VSCode can do this.
VS seems not.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 43899bd1-664f-ee64-b56d-fc2b60464aed
* Version Independent ID: 7703eb41-41a8-6c69-5584-5df0f8962abf
* Content: [launch.vs.json schema reference (C++)](https://learn.microsoft.com/en-us/cpp/build/launch-vs-schema-reference-cpp?view=msvc-170&source=docs)
* Content Source: [docs/build/launch-vs-schema-reference-cpp.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/build/launch-vs-schema-reference-cpp.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
Hi, @Chosink. Do you have a doc request here? Otherwise, I recommend bringing this issue up on [Developer Community](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Faka.ms%2Fvsfeedback%2Fbrowsecpp&data=04%7C01%7CTyler.Whitney%40microsoft.com%7C5741446ac59c4b9db2fd08d9878e62a7%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637689867885607869%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=MF%2BRQ2YB96%2F8%2FGlewv2ttenU5mu%2FaAuBut8FcfVR12k%3D&reserved=0), where it can be seen by the product team. They'll take this under consideration. In the meantime, I'm closing this as not a documentation issue.
