### ISSUE TITLE
Warning does not appear - need /analyze?

### ISSUE THREAD

**Issue by jtooker** [MicrosoftDocs/cpp-docs#4467]
I'm trying to get a warning (if not an error) for my undeclared fall-throughs.  I want warning C26819.  I cannot seem to get it to be reported, but a comment here -  https://stackoverflow.com/questions/21909857/how-can-i-make-msvc-warn-or-fail-if-a-switch-case-falls-through/65925560#65925560 - implies I need to have /analyze flag on.  

If that is the case, please explicitly say so on this page.  (Even better, if that is the case, make C26819 a normal warning).

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: cd137f17-dac2-ead3-a451-4e7afcf95ed5
* Version Independent ID: 09b1e018-42eb-6e47-1ae6-f80e5278ec6c
* Content: [Warning C26819](https://learn.microsoft.com/en-us/cpp/code-quality/c26819?view=msvc-170)
* Content Source: [docs/code-quality/c26819.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/code-quality/c26819.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
Hello, sorry for the delay. There are a couple things to do to trigger this warning:
• It only applies to C++17 and up because [[fallthrough]] was added in C++17. So the user needs to add /std:c++17 or similar to the command line.
• This is implemented in a plugin. Add /analyze:plugin EspXEngine.dll to the command line
I've given myself a work item to update this topic.

**Comment by TylerMSFT** [comment]
Moved this issue to an internal work item tracking system because we are moving away from using GitHub issues to track C++ doc work.
