### ISSUE TITLE
IAsyncInfo::Start doesn't exist

### ISSUE THREAD

**Issue by bviglietta** [MicrosoftDocs/cpp-docs#450]
It says, "Start() is a default implementation of IAsyncInfo::Start," but there is no Start method in the IAsyncInfo interface.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 543fcfea-0fad-dbb0-d2b3-78f8b6a02ca3
* Version Independent ID: 1a6f9389-25ef-21dd-8107-2263c6675d9f
* Content: [AsyncBase Class](https://docs.microsoft.com/en-us/cpp/windows/asyncbase-class?view=vs-2017#inheritance-hierarchy)
* Content Source: [docs/windows/asyncbase-class.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/windows/asyncbase-class.md)
* Product: **visual-cpp**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by mikeblome** [comment]
@bviglietta Thanks for the feedback. Actually it does have a Start method but it's protected and won't always show up in Statement Completion. The method was incorrectly listed in the public method table, so I moved it to the correct table, but otherwise left the method itself untouched. Should be visible by tomorrow.

**Comment by mikeblome** [comment]
on re-reading the bug I see you are talking about IAsyncBase interface, not this class implementation. Yes you are correct and I have fixed the doc to remove that statement.
