### ISSUE TITLE
Can version numbers be added to the table in the Section, "Visual Studio 2015, 2017, 2019, and 2022"?

### ISSUE THREAD

**Issue by Uselessly7631** [MicrosoftDocs/cpp-docs#4515]
Can version numbers be added to the table in the Section, "Visual Studio 2015, 2017, 2019, and 2022"?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 75e6432b-c6ec-e208-5f1c-bbc4fde9929b
* Version Independent ID: 9cbb940e-cddd-f82f-e8bb-ee62b17af794
* Content: [Latest supported Visual C++ Redistributable downloads](https://learn.microsoft.com/en-US/cpp/windows/latest-supported-vc-redist?view=msvc-170)
* Content Source: [docs/windows/latest-supported-vc-redist.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/windows/latest-supported-vc-redist.md)
* Product: **visual-cpp**
* Technology: **cpp-windows**
* GitHub Login: @MahmoudGSaleh
* Microsoft Alias: **msaleh**

**Comment by TylerMSFT** [comment]
@Uselessly7631 , I'm not sure what you mean.

**Comment by TylerMSFT** [comment]
Closing as no response. Reopen if you can provide a little more detail about your ask.

**Comment by Uselessly7631** [comment]
Apologies for the delay.

On the page, "Microsoft Visual C++ Redistributable latest supported downloads" <https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170>, there are different sections for different versions of Visual Studio. Each section has a table Architectures, Versions, and Links. 

The *only* table on this page without a Versions column is the table under the "Visual Studio 2015, 2017, 2019, and 2022" section <https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170#visual-studio-2015-2017-2019-and-2022>. Can a Versions column be added to this table?

**Comment by TylerMSFT** [comment]
Hi @Uselessly7631 , I talked to the dev team about this and they left out the version numbers on purpose because, unlike the earlier versions of VS, the redist for VS 2015-2022 is updating frequently and they didn't want to put out a version number that would quickly become stale and be at risk of not getting updated. So, I added some instructions about how to find the version number for the latest redist that goes with VS 2015-2022.  That will be live tomorrow.  Take care.
