### ISSUE TITLE
Wrong long/ulong limits

### ISSUE THREAD

**Issue by bing007** [MicrosoftDocs/cpp-docs#4679]
The values for long/ulong are wrong.

<html>
<body>

INT_MAX | Maximum value for a variable of type int. | 2147483647
-- | -- | --
UINT_MAX | Maximum value for a variable of type unsigned int. | 4294967295 (0xffffffff)
LONG_MIN | Minimum value for a variable of type long. | -2147483647 - 1
LONG_MAX | Maximum value for a variable of type long. | 2147483647
ULONG_MAX | Maximum value for a variable of type unsigned long. | 4294967295 (0xffffffff)

</body>
</html>

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3172ab8c-37b9-1ce6-eeac-339ffed758b1
* Version Independent ID: b262c777-3978-8cd2-0173-b7f95b77ca1e
* Content: [C and C++ Integer Limits](https://learn.microsoft.com/en-us/cpp/c-language/cpp-integer-limits?view=msvc-170)
* Content Source: [docs/c-language/cpp-integer-limits.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/c-language/cpp-integer-limits.md)
* Product: **visual-cpp**
* Technology: **cpp-c-language**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
Hi, LONG_MIN is wrong (will fix) and maybe you meant that ULONG_MIN isn't listed (will add). I don't see anything wrong with the others. Compile with `/std:c++latest`

```cpp
#include <iostream>
#include <format>
#include <climits>

int main()
{
    std::cout << std::format("INT_MAX: {}, x{:X}\n", INT_MAX, INT_MAX);
    std::cout << std::format("UINT_MAX: {}, x{:X}\n", UINT_MAX, UINT_MAX);
    std::cout << std::format("LONG_MIN: {}, x{:X}\n", LONG_MIN, LONG_MIN);
    std::cout << std::format("LONG_MAX: {}, x{:X}\n", LONG_MAX, LONG_MAX);
    std::cout << std::format("ULONG_MAX: {}, x{:X}\n", ULONG_MAX, ULONG_MAX);

    return 0;
}
```

**Comment by orcmid** [comment]
I think it is understood that there are no UMIN cases because the value is always 0.  These are not defined in the C Standard library `<limits.h>` for that reason.

That `int` and `long` limits are the same is correct.  That's how it is in `<limits.h>` and how VC/C++ implementation handle those types.  

Not to worry.  The `long long` and `unsigned long long` types come to the rescue, all specified for C11.

Here's a demonstration of the `<limit.h>` values as of VS 17.6.5.

![F23xy100-2023-08-15-1438-VCshowInts](https://github.com/MicrosoftDocs/cpp-docs/assets/3372580/9ba0a7dd-ccba-4636-b9dc-fcc5af9e82a4)

The reason for -(2^n-1)-1 is likely related to the difficulty of expressing -2^n for the smallest n-bit 2's complement number.
