### ISSUE TITLE
About the "TempData td_noInit;" in the example

### ISSUE THREAD

**Issue by VictorQRS** [MicrosoftDocs/cpp-docs#471]
Wouldn't "TempData td_noInit;" in the example call the default constructor as well (although the values would not be initialized and therefore contain garbage)? Is the error "Error C4700 uninitialized local variable" something specific for the MS compilers? Could not reproduce "uninitialized local variable" (error code omitted because I believe this code to be MS specific) using GCC.

If it is an error of the example, than it only needs correction, but if it is MS-specific, it should say so.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 441b3ef5-7a22-0496-ddec-6baee7262991
* Version Independent ID: 711a8364-a43c-22fc-217a-30c95c5c946b
* Content: [Initializing classes and structs without constructors (C++)](https://docs.microsoft.com/en-us/cpp/cpp/initializing-classes-and-structs-without-constructors-cpp?view=vs-2017)
* Content Source: [docs/cpp/initializing-classes-and-structs-without-constructors-cpp.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/cpp/initializing-classes-and-structs-without-constructors-cpp.md)
* Product: **visual-cpp**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by corob-msft** [comment]
@VictorQRS It's hard to say what observable effect "calling the implicitly defined default constructor" to define `td_noInit` could possibly have, since it would be one that takes no parameters, has no body, and leaves all the member data built-in types uninitialized. It would be tantamount to a no-op for a POD structure such as this one. In fact, the compiler generates no such constructor, and merely puts a name on a suitably-sized portion of the stack to define `td_noInit`.

Because *every* error or warning mentioned in the documentation is Microsoft-specific, none are called out as such. You should not expect the diagnostics from different compilers to be the same; they are an implementation detail. In this case, the comment in the example above the definition of  `td_noInit` is not quite correct; you would instead see ` warning C4101: 'td_noInit': unreferenced local variable` if the compiler warning level is /W3 or higher. You would only see `warning C4700: uninitialized local variable 'td_noInit' used` if and when it was accessed, not on the definition. I've clarified the comment, and the fix should be published in a day or two.

As near as I can tell, gcc does not produce a diagnostic on the use of an uninitialized structure member when optimizations are turned off, which frankly seems odd. I used -Wc++14-compat -O0 -Wall -Wextra -Wpedantic without seeing anything. I did get a -Wuninitialized with -O1, but only on the first reference to an uninitialized member. YMMV.
