### ISSUE TITLE
c3.dll - ???

### ISSUE THREAD

**Issue by despair86** [MicrosoftDocs/cpp-docs#476]
Anyone know what the third-pass compiler would have done? Doesn't seem to exist anymore, was looking through old Visual C++ CDs....
```
c1.dll / c1[32[32|16]].exe - front end
c2.dll / c2[32[32|16]].exe - back end
c23pcd.exe - 16-bit p-code generator (no longer used)
c33216.exe - ??? (also appears to be 286-oriented)
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49c56566-26e0-88dc-3edf-6b4402cb5596
* Version Independent ID: e527d865-6794-9a4c-7856-697d58679b89
* Content: [Compiler Error C2364](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-errors-1/compiler-error-c2364?view=vs-2017)
* Content Source: [docs/error-messages/compiler-errors-1/compiler-error-c2364.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/error-messages/compiler-errors-1/compiler-error-c2364.md)
* Product: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@despair86 This seems like an odd question to ask on an apparently unrelated compiler error message. 

What I've heard is that the back end has a couple of optimization passes, one that works on the tuple output from c1, and one that's target-specific and works as part of the code generation, so my guess is, pass 3 in C33216.exe was probably the latter plus code generation for 16-bit target platforms on 32-bit hosts. They've been combined in c2 since VS 2.0 in the mid '90s. 

When you have a question about code dating back to the compilers that targeted Win32s and OS/2, I'd suggest [submitting a question](https://blogs.msdn.microsoft.com/oldnewthing/20100720-01/?p=13383/} to Raymond Chen's [The Old New Thing](https://blogs.msdn.microsoft.com/oldnewthing/) blog. He sometimes talks about tools from that era.
