### ISSUE TITLE
Incorrect documentation

### ISSUE THREAD

**Issue by Eljay-Adobe** [MicrosoftDocs/cpp-docs#4766]
The hexadecimal sentinel values for the `signed` numbers do not match the decimal number.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 474bd123-68fe-d111-182a-08f665929dda
* Version Independent ID: 474bd123-68fe-d111-182a-08f665929dda
* Content: [Sentinel conversion functions](https://learn.microsoft.com/en-us/cpp/intrinsics/sentinel-conversion-functions?view=msvc-170)
* Content Source: [docs/intrinsics/sentinel-conversion-functions.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/intrinsics/sentinel-conversion-functions.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by orcmid** [comment]
Nice catch.  Yes, those `0xFFF...F` values are all -1 as signed (2's complement) values. There also seem to be stray `'` characters in the `long long` hexadecimal values.

Based on the "farthest from 0" notion, I suspect the signed cases are hex 0x800...0 values.

Writing the decimal value is tricky because it likely does not convert properly.  The `<limits.h>` trick used for `INT_MIN` and `LLONG_MIN` might be better written here.

**Comment by TylerMSFT** [comment]
I think the values should be:

80000000
ffffffff
8000000000000000
ffffffffffffffff

I'll update the topic.
The ticks aren't strays - that's valid C++. They are like comma delimiters for thousands. Try this, for example:

```
int x = 0x80'000'000;
std::cout << std::hex << x;
```
The fix should go out by tomorrow afternoon.

**Comment by orcmid** [comment]
@TylerMSFT 
Yes, the tick notation is *not* used in `<limits.h>` and it does not appear to be supported in C Language.  So I would think it is to be avoided except where only C++ applies.  See (https://learn.microsoft.com/en-us/cpp/c-language/c-integer-constants?view=msvc-170)

There's another problem.  While it might be possible to output `INT_MIN` and `LL_MIN` correctly, I don't think writing those values directly in code will compile successfully.  See how `<limits.h>` gets around that at (https://learn.microsoft.com/en-us/cpp/c-language/cpp-integer-limits?view=msvc-170).

I gather `<intrin.h>` is a Microsoft-specific library, since it does not offer `long`, only `int` and `long long`, signed and `unsigned`.
