### ISSUE TITLE
Need documentation of available properties and macros in launch.vs.json for Linux configurations

### ISSUE THREAD

**Issue by margaretharp** [MicrosoftDocs/cpp-docs#477]
The documentation of properties in CMakeSettings.json is pretty good for Linux CMake projects, but not so for launch.vs.json.  This document contains no information about it, but a reference to the "Open Folder Projects" document, which does not discuss Linux-specific properties.  What little documentation I've been able to find anywhere refers to macros which either do not apply to Linux or are insufficiently documented.

How do I indicate that shared libraries and executable in my project must be moved from the directory where they are built to a different Linux directory and execute there?  For a Linux project, does "cwd" define the Linux directory which should be current when my executable runs?  Or is it "current_directory"?  Is "workspaceRoot" relevant in a Linux context?  How do I reference the remoteInstallRoot defined in CMakeSettings.json in launch.vs.json?  It does not seem that specifying this in CMakeSettings.json even causes my binaries to be copied there.  
The root of my Linux project is at /a.  The source for my executable is in /a/b/c/d (sources for shared libraries are in other subdirectories of /a).  The root for the build process is /a/b, and outputs my executable to /a/bin.  All of the shared libraries and my executable must be copied to /x/y/bin and the executable be run from that directory.  How do I specify all of this for a Visual Studio Linux CMake project?  The documentation is really lacking.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 296f6914-b366-1ab8-4c08-6d51fc7212fa
* Version Independent ID: 04aec2e0-f39a-2e52-6a09-354222d47146
* Content: [Configure a Linux CMake project in Visual Studio](https://docs.microsoft.com/en-us/cpp/linux/cmake-linux-project?view=vs-2017)
* Content Source: [docs/linux/cmake-linux-project.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/linux/cmake-linux-project.md)
* Product: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by mikeblome** [comment]
Investigating

**Comment by sfreed141** [comment]
Hi @margaretharp,
I think this problem is better solved by modifying the CMakeLists.txt. Take a look at [CMAKE_LIBRARY_OUTPUT_DIRECTORY](https://cmake.org/cmake/help/latest/variable/CMAKE_LIBRARY_OUTPUT_DIRECTORY.html) and [CMAKE_RUNTIME_OUTPUT_DIRECTORY](https://cmake.org/cmake/help/latest/variable/CMAKE_RUNTIME_OUTPUT_DIRECTORY.html), which specify where to place the LIBRARY and RUNTIME CMake targets after building, respectively. So your CMakeLists.txt might look like this (the variables must be set before adding the targets):
```
cmake_minimum_required (VERSION 3.8)

set(CMAKE_RUNTIME_OUTPUT_DIRECTORY <path to place executables>)
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY <path to place libraries>)

add_executable (foo "main.cpp")
```

Another option if you need more control is to use a post build command using [add_custom_command](https://cmake.org/cmake/help/latest/command/add_custom_command.html):
```
add_custom_command(TARGET foo POST_BUILD COMMAND ${CMAKE_COMMAND} -E copy <files to copy> <destination>)
```

**Comment by mikeblome** [comment]
@margaretharp If you still have a question feel free to reopen this issue or create a new one.
