### ISSUE TITLE
Thus is not good 

### ISSUE THREAD

**Issue by RaghavTheCoder2012** [MicrosoftDocs/cpp-docs#4771]
[Because the page doesn't give direct information]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 75e6432b-c6ec-e208-5f1c-bbc4fde9929b
* Version Independent ID: 9cbb940e-cddd-f82f-e8bb-ee62b17af794
* Content: [Latest supported Visual C++ Redistributable downloads](https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170)
* Content Source: [docs/windows/latest-supported-vc-redist.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/windows/latest-supported-vc-redist.md)
* Product: **visual-cpp**
* Technology: **cpp-windows**
* GitHub Login: @MahmoudGSaleh
* Microsoft Alias: **msaleh**

**Comment by orcmid** [comment]
I looked at the page (for en-US) and I don't see anything missing.  It seems to summarize all of the redistributable packages for the different versions of Visual Studio, and there are links as needed for the files and also for additional information on how to use them.

I did notice that I had to widen my browser window to see everything plainly.

What is expected as "direct information" that is not there?

**Comment by shawnkhall** [comment]
I suspect he's talking about this:

    "Unlike older versions of Visual Studio, which have infrequent redist updates, 
    the version number isn't listed in the following table for Visual Studio 2015-2022 
    because the redist is updated frequently. To find the version number of the latest 
    redist, download the redist you're interested in using one of the following links. 
    Then, look at its properties using Windows File Explorer. In the **Details** pane, 
    the **File version** contains the version of the redist.

Sure, eliminating the version numbers when it changes frequently can reduce documentation overload, but it hardly answers the question the page is literally designed to address, which is "Latest supported Visual C++ Redistributable downloads". 

Since instructions are given it's not like MS doesn't know what this number is at any given moment, and the GitHub include-fragment function could be used to inject this value from a document created during compilation of the redist.

**Comment by TylerMSFT** [comment]
Added the latest redist version number.
