### ISSUE TITLE
this keyword in C++ Reference

### ISSUE THREAD

**Issue by MurphyDublin** [MicrosoftDocs/cpp-docs#4816]
Below is what was written in the C++ Reference:
"The this keyword is a pointer to a class object. It's available within nonstatic member
functions. It points to the instance of the class for which the function was invoked."

The last sentence is confusing. I rewrote it like this: "It points to the instance of the class for the class-member function invoked in an expression".

Also in the example of the **this** pointer, does the pointer point to the instance of the class or to the class- member function? 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d494e44d-ff64-826f-f818-56c538a212fb
* Version Independent ID: 7c169725-4398-e432-e244-aa3a01db44df
* Content: [Primary expressions](https://learn.microsoft.com/en-us/cpp/cpp/primary-expressions?view=msvc-170)
* Content Source: [docs/cpp/primary-expressions.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/cpp/primary-expressions.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by frederick-vs-ja** [comment]
"Instance" seems confusing. Why don't we simply use "object"?

**Comment by orcmid** [comment]
@MurphyDublin @frederick-vs-ja
> "Instance" seems confusing. Why don't we simply use "object"?

It seems to me that a simplifying change is to change

"The **`this`** keyword is a pointer to a class object." to
"The **'this`** keyword is a pointer to an instance of a class object within a member of the instance.

With regard to the example, the comment suggests what the implicit declaration of **`this`** is within the different styles of `Func()` member declaration.  The value is always as a pointer to the instance of `class Example`.  That could be explained better.

@frederick-vs-ja Are you suggesting that the phrase "instance of the class" with regard to the **this** pointer is confusing.?

### Some TL;DR: 
In the context of C++, my impressions is that "object" is used informally, especially in code comments, but the official and standard observation is that "class instance" is the term of art here, despite (https://en.wikipedia.org/wiki/C%2B%2B_classes#The_this_keyword).  In particular, C++ has no Object from which all inheritance descends.  

In C++, **class** is a specialized term and it is rather implementation-oriented.  Early in my career I was confused by that and the use of the term "class" in regard to set theories.  But "instances of classes" is definitely the term of art for C++ despite the informal connections among Simula-inspired languages (https://en.wikipedia.org/wiki/This_(computer_programming)) and the informal use of "object-oriented."

The connection between **class** and **struct** is another reason that the notion of C++ class is spoken of in the way it is.  It may also be relevant that static methods have no **this** and are spoken of as class methods, not instance methods.  There is probably some connection of this nomenclature with the way C++ was initially developed as a preprocessor to a C Language compiler and how those innovators thought of it.  It may also be related to Simula nomenclature, but I've forgotten what little I knew about that ALGOL 60 compiler extension.

Is this helpful or have I simply added to the confusion?

In a past life, I tended to speak of interfaces as being objects because they walk and talk like (virtual) class instances.  The Microsoft experts were very firm in their objections.

**Comment by TylerMSFT** [comment]
Hey guys, I'm inclined to leave this as it is. To my ear, 'instance' is less ambiguous than 'object'.

Personally, I think the example should be deleted. It just raises questions and doesn't add value. Objections?

**Comment by TylerMSFT** [comment]
I made some changes in [PR 5136](https://github.com/MicrosoftDocs/cpp-docs-pr/pull/5136) if you want to take a look.

**Comment by orcmid** [comment]
@TylerMSFT 

> I made some changes in [PR 5136](https://github.com/MicrosoftDocs/cpp-docs-pr/pull/5136) if you want to take a look.

Mmmm, wrong repo.  Can't see over there :).

**Comment by TylerMSFT** [comment]
It's actually the 'right' repo. We prefer not to make changes in the public repo because not all of our validation tools run there. We work in the private mirror. Edits in the public repo aren't robustly supported. We make do for now, which sometimes means I pull it into the private repo, do the work, run our validation tools, and go through the normal publishing process from there.
Let's do this: I'll publish (should be live by Thursday) and we can iterate from there.

**Comment by TylerMSFT** [comment]
I'm getting ready to head out for the holidays. I'll close this, but of course feel free to reopen after my changes are live (by mid-day (US) Thurs 12/14) if there are still things you want to discuss.
- In [Primary expressions](https://learn.microsoft.com/cpp/cpp/primary-expressions), I removed the confusing code example. In my opinion, that topic wasn't the place to talk it about it, anyway.
- In [The `this` pointer](https://learn.microsoft.com/cpp/cpp/this-pointer) topic, I took the example from *Primary expressions* and repurposed it as a table. I put it here because this is the topic that endeavors to explain the vagaries of the type of the `this` pointer.
I hope you all enjoy the holidays.
