### ISSUE TITLE
/RTC1 seems to work with /fsanitize=address in at least VS2019 16.11.17

### ISSUE THREAD

**Issue by solstice333** [MicrosoftDocs/cpp-docs#4828]
I am able to get at least `/RTC1` working with `/fsanitize=address` in at least VS2019 16.11.17. Not sure which version this support was added, or if it was ever a real issue. Perhaps it would be good to mention this in documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6a6dd452-37f0-4bf1-b791-dfdaad2fcab7
* Version Independent ID: 7f114a50-c339-7527-c2fd-6bb73c599947
* Content: [AddressSanitizer](https://learn.microsoft.com/en-us/cpp/sanitizers/asan?view=msvc-160)
* Content Source: [docs/sanitizers/asan.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/sanitizers/asan.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
RTC1 and /fsanitize=address provide overlapping functionality and we have not yet defined the exact behavior they should have when combined. When you combine them it *might* work as you expect for your scenario, but because we don’t have any behavior or compatibility guarantees, it is an unsupported scenario.

**Comment by solstice333** [comment]
Thanks for the link! Apologies for going slightly off topic.
