### ISSUE TITLE
+/-1.7E308

### ISSUE THREAD

**Issue by skippernoodle** [MicrosoftDocs/cpp-docs#4935]
Hello, is it accurate to use +/-1.7E308  to describe 1.7+/-E308? Wouldn't people think it means negative number and positive number instead of 10 to the power of +/- number?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2cfa13c8-75c2-d2e2-c5ca-d10e89abe6f7
* Version Independent ID: 10518f64-2155-c2d1-75ca-ffe4f8ee0d95
* Content: [Type double](https://learn.microsoft.com/en-us/cpp/c-language/type-double?view=msvc-170)
* Content Source: [docs/c-language/type-double.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/c-language/type-double.md)
* Service: **visual-cpp**
* Sub-service: **c-language**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by orcmid** [comment]
The Microsoft-specific statement is correct.  It describes the extremes of the range, rather than the range of non-zero absolute values as given in the initial paragraph.

It is worth some wordsmithing to make that clear, since the "Microsoft specific" portion doesn't seem to specify any sort of exception.

In the first paragraph, perhaps one should say "**gives a magnitude** range ..."  It might be good to include `0.0` as well.

**Comment by skippernoodle** [comment]
Ohh that makes sense. Thank you for the reply! :)
