### ISSUE TITLE
VS2003-2015 history , missing rationale

### ISSUE THREAD

**Issue by tamlin-mike** [MicrosoftDocs/cpp-docs#50]
In the history for 2003-2015 there are multiple issues, but I'm just gonna touch the few issues I found while skimming:

- The document goes far beyond 2015 - it currently goes to (VS) 2017 - even that the document name clearly states it's only up to 2015.

- The change to <new> and <new.h>, where the operator new/delete functions are no longer exported from the runtime DLL, but now _always_ linked into your binary. This requires both rationale and elaboration.

- "_beginthread and _beginthreadex ... now hold a reference to the module in which the thread procedure is defined for the duration of the thread". Huh? If they now increment the load count of PE's, or do something completely different, spell it out. This is currently so vague it's practically useless, borderline disinformation.

**Comment by ghogen** [comment]
@mikeblome

**Comment by corob-msft** [comment]
These issues may be interesting for some, but we're not going to address them in the documentation. 

The article does mention VS 2017, but does not discuss changes made for VS2017, hence the name. 

The default operator new and operator delete functions were moved when the CRT was refactored into the UCRT and the vcruntime. C++-specific and particularly compiler-version-dependent runtime support was moved out of the UCRT. Functions that were required for startup moved into the static runtime. For elaboration, I suggest the blog posts [The Great C Runtime (CRT) Refactoring](http://blogs.msdn.com/b/vcblog/archive/2014/06/10/the-great-crt-refactoring.aspx), [C Runtime (CRT) Features, Fixes, and Breaking Changes in Visual Studio 14 CTP1](http://blogs.msdn.com/b/vcblog/archive/2014/06/18/crt-features-fixes-and-breaking-changes-in-visual-studio-14-ctp1.aspx), and  [Introducing the Universal CRT](https://blogs.msdn.microsoft.com/vcblog/2015/03/03/introducing-the-universal-crt/) by James McNellis.

As for the _beginthread and _beginthreadex calls, we say they "hold a reference to the module in which the thread procedure is defined for the duration of the thread" as a short way of saying they "increment the module reference count of the module in which the thread procedure is defined, and store the module handle for the duration of the thread, which is used to decrement the module reference count when the thread exits." It's a useful shorthand, and it's what we assume developers understand by the phrase. You can look up the functions in the UCRT source code to see they call GetModuleHandleExW and FreeLibrary if you're curious.

**Comment by tamlin-mike** [comment]
@corob-msft 
While this is so long ago I can't even remember what I opened this issue about, subject seems to suggest it's about the _history_ of VS. The issue I opened referred to only the C++ part of this history, and how it was lacking vital information.

Instead of pointing only me to these blog posts, I suggest they are added to the document in question (provided it stil exist) as a "further reading" footnote. That way the people that _are_ interested in this actually stand a chance finding the information. There's rougly 0% chance they'd find it here, in a closed github issue, making it practically impossible for future generations to track change history.

**Comment by corob-msft** [comment]
I see where you're coming from, and how some confusion might arise. This article is actually a collection of all the old "breaking changes" articles for each version of the compiler from MSDN in one convenient place, with a few updates to call out earlier changes that because obsolete or deprecated by subsequent changes. There's a separate roll-up of all the historical "what's new" articles with feature changes.

The reason to leave the rationale out of the article, other than a mention of conformance, or a bug fix, etc., is that it's largely distracting clutter for people just looking for info on how to change their code to satisfy the new compiler, the real point of the article. That's not to suggest readers don't wonder why some change was made - they almost always do, just like you did, often while muttering imprecations - but that's secondary to getting their code to work again as quickly as possible.

We assume curious people will use a search engine to find more detailed rationale info, and our experience bears it out. It's what I did to find the blog posts; anyone else could do it just as well. And for a long while, our article policy was not to link to the blog, both because it was considered ephemeral, and because its link schema has changed from time to time, so link rot was a real issue. We've loosened up a bit on that.

**Comment by tamlin-mike** [comment]
@corob-msft Thanks for the reply. Now it makes more sense.

Still, "We assume curious people will use a search engine to find more detailed rationale info" is something I find questionable at best, unacceptable at worst.

Scenario 1: Someone is in ten years from now tasked to fix some software written in C++ using VC98's version of C++99. The build system is a mess of makefiles, DSW's and maybe even some `sed` and `awk` scripts thrown in for good measure (you know, the normal MO when software _design_ is at #99 of 100 and #1 is "Get it done NOW!").

Scenario 2: Google and Bing are shut down.


Windows(R) has already become a hell of DLL-hell (again). Currently a simple console application can load 50+ (and growing) DLL's before it's even started - and this will only become worse.

I know, it's a longshot, maybe even a strawman argument, but it still displays the importance of having history documented. From your explanation I agree this is not the document to host this info, but as I think this info is (or will become) vital in the future - if for nothing else, archeology - could there be made a case for creating a new (plain-text) document including the vital info, including text from blogs?

**Comment by corob-msft** [comment]
Hah! If Bing and Google and the Wayback Machine or their successors have gone away for good, I think we'll all have bigger problems to worry about than old Windows code with bit rot. If you're concerned about the preservation of vital knowledge, [you can always print out Wikipedia for a little light reading in your fallout shelter](https://www.npr.org/sections/alltechconsidered/2014/03/27/295262783/printing-wikipedia-would-take-1-million-pages-but-thats-sort-of-the-point).  Or maybe just for the extra shielding. Or, you know, for less apocalyptic off-line scenarios, grab the PDF files from the links on practically every page, and stick them on a thumb drive.
