### ISSUE TITLE
Instructions for Walkthrough: Create a traditional Windows Desktop appliction (C++) incomplete

### ISSUE THREAD

**Issue by alleryn** [MicrosoftDocs/cpp-docs#519]
This is regarding the section [Prerequisites](https://docs.microsoft.com/en-us/cpp/windows/walkthrough-creating-windows-desktop-applications-cpp?view=vs-2017#prerequisites) on the page [Walkthrough: Create a traditional Windows Desktop application (C++)](https://docs.microsoft.com/en-us/cpp/windows/walkthrough-creating-windows-desktop-applications-cpp?view=vs-2017)

"When you run the installer, make sure that the Desktop development with C++ workload is checked."

This is insufficient.  In the Installation Details sidepanel, one must also have checked VC++ 2017 Version [_Version number_] latest [_version number_] tools. (Currently VC++ 2017 version 15.8 v14.15 latest v141 tools).

For example, a user may have an old installation of Visual Studio 2017 which was used only for VC 2015 stuff and didn't have the tools for VC 2017 installed.  The Desktop development with C++ workload will still be checked, but following the guide's instructions will result in an error message in Visual Studio, directing the user to install the VC 2017 tools.

I suggest amending the above-quoted line to "When you run the installer, make sure that the Desktop development with C++ workload is checked, and that the 'VC++ 2017 [_version number_] latest [_version number_] tools' Component is checked in the sidebar".

Hope that helps!
--Tim

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eda99bc7-483b-e53c-1035-886f4d0955f4
* Version Independent ID: a6fdba4d-53e4-9f1a-2352-bc68ef491069
* Content: [Walkthrough: Create a traditional Windows Desktop application (C++)](https://docs.microsoft.com/en-us/cpp/windows/walkthrough-creating-windows-desktop-applications-cpp?view=vs-2017)
* Content Source: [docs/windows/walkthrough-creating-windows-desktop-applications-cpp.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/windows/walkthrough-creating-windows-desktop-applications-cpp.md)
* Product: **visual-cpp**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by corob-msft** [comment]
@alleryn I'm pretty sure you would have to have specifically removed the VC++ 2017 toolset option in the installer at some point after installing the Desktop development with C++ workload to get into the situation you describe. In that case, the error message does its job and tells you what to do. The extra verbiage isn't needed for the main target audience of this document, which is people who have just downloaded VS 2017 for the first time, or are using it for C++ development for the first time. For them, it would be a slightly confusing distraction, since the option is selected by default when the workload is selected for the first time. I appreciate you thinking through the cases, though.

**Comment by corob-msft** [comment]
I think I meant to qualify that as "or people who are using it for C++ Windows Desktop development for the first time." I'm not sure there are many people new to C++ who decide to get their feet wet by making a desktop app.
