### ISSUE TITLE
The passage, "Convert a UTF-16 or UTF-32 wide character into a multibyte character in the current locale," seems to have a vague meaning.

### ISSUE THREAD

**Issue by tommai78101** [MicrosoftDocs/cpp-docs#524]
In C++11, there exists a standard header file, &lt;clocale&gt;. On Linux, we need to use &lt;clocale&gt; and then we need to invoke the function, `setlocale()`, with the corresponding parameters, in order to set the current locale for the following codes.

However, what is vague about that passage in the title is:

* Does it imply that we are *required* to invoke the call to `setlocale()`, with relevant parameters, whenever we need to call on the functions from &lt;cuchar&gt; standard header?
* Does it mean, if we don't set any locales, the code is converting to ANSI code page by default implicitly?
* Is there an option of converting the locale to ANSI code page?
* What does the "current locale" mean? Is it based on a clean Windows 10 operating system's default locale, ANSI? UTF-16LE? Or UTF-8?

Article in question:
https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/c16rtomb-c32rtomb1?view=vs-2017

Thanks. Hopefully any answers will be put in as updates to the passage, as clarifications, as remarks, or as notes.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: af5bbc86-8179-ff08-a602-8dcd81036601
* Version Independent ID: d7b1527c-2b17-e5a1-45e4-bd98ed5a6dfb
* Content: [c16rtomb, c32rtomb1](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/c16rtomb-c32rtomb1?view=vs-2017)
* Content Source: [docs/c-runtime-library/reference/c16rtomb-c32rtomb1.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/c-runtime-library/reference/c16rtomb-c32rtomb1.md)
* Product: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by mikeblome** [comment]
investigating

**Comment by MSDN-WhiteKnight** [comment]
In my tests, `c16rtomb` always returns UTF8, no matter the current locale. I tried setting locale to `.ACP`, `.OCP`, `ru_RU.1251` and others - it had no effect, still the result is UTF8. This behaviour is different from `wcrtomb`, which respects current locale. I used Windows 10 and Visual Studio 2017.

**Comment by tommai78101** [comment]
Uh, it's supposed to be about clarifying the vague sentences and phrasing in the docs, and has no relations with the C++ bug filed in the Developer Community. :(

**Comment by corob-msft** [comment]
@tommai78101 

The document has been updated to reflect what the functions actually do. The only supported multibyte conversions are from UTF-16(LE) to UTF-8 by using `c16rtomb`, or UTF-32 to UTF-8 by using `c32rtomb`.  These functions have no dependency on the current locale settings for either the C runtime or the C++ Standard library, so any wording that implied otherwise has been removed. No call to `setlocale` is required; the normal vcruntime initialization before `main` is called is sufficient.

There's currently no plan to support any other multibyte character set conversions with these functions. The document now mentions which functions do support other MBCS locales and code pages, if that's your intent.

Please feel free to reopen the issue with your specific questions about the current text, if anything remains unclear.

**Comment by tommai78101** [comment]
@corob-msft 

Thank you , this is all I wanted to know and see the documentation mentioning this:

>  No call to setlocale is required; the normal vcruntime initialization before main is called is sufficient.
