### ISSUE TITLE
Microsoft Code open duplicate files because of /FC option stripping mixed case

### ISSUE THREAD

**Issue by sholmes74** [MicrosoftDocs/cpp-docs#543]
I'm compiling with Microsft Code and in order for our build system to be able to find the file with ctrl+click, the FC option is required, but as you can see in your documentation, it strips out the mixed case of the filename!  So Code will open a second copy of the file, all lowercase!  Why would you strip casing from the path?!?!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 20abc1bd-f716-106b-f43b-45798c500742
* Version Independent ID: e114ee63-9ee2-0d01-e242-59ab428b85dd
* Content: [/FC (Full Path of Source Code File in Diagnostics)](https://docs.microsoft.com/en-us/cpp/build/reference/fc-full-path-of-source-code-file-in-diagnostics?view=vs-2017)
* Content Source: [docs/build/reference/fc-full-path-of-source-code-file-in-diagnostics.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/reference/fc-full-path-of-source-code-file-in-diagnostics.md)
* Product: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@sholmes74 I'm sorry you're having trouble, but I'm not sure what Microsoft Code means in this context. Are you talking about [Visual Studio Code](https://code.visualstudio.com), the editor? 

The behavior of CL and LINK that folds paths to lower-case is a legacy of running on case-insensitive file systems. Neither FAT nor NTFS normally distinguish files by case, though they do preserve case. However, the case-folding behavior is obviously an issue for other file systems, cross-platform builds, and some third-party tooling. 

Since you can't change the **/FC** option behavior in the near term, I'd suggest you look for a work-around. For the longer term, I'd suggest you send a product suggestion to the development teams involved:

- To suggest that VS Code should look in a case-insensitive manner for files to open by using Ctrl+Click, you can raise an issue by using **Help** > **Report issue** and then fill in the Issue Reporter dialog. This might be the most productive path to follow. It's possible that work-arounds for the issue already exist.

- To propose a behavior change for the **/FC** compiler option to preserve case, you can use the [C++ Developer Community](https://developercommunity.visualstudio.com/spaces/62/index.html) web site. You can also use the Visual Studio IDE to do this, by using the  **Help** > **Send Feedback** > **Report a Problem** or ** Provide a Suggestion** options to fill out a report form. This could result in a change a few minor versions of the compiler down the road, if they decide it wouldn't break too much legacy code. It's not a short-term fix.

Since the behavior is as described in the documentation, this doesn't seem like it's a documentation issue, so I'm closing this report. Feel free to reopen it if you think there's something specific that needs to change in the documentation. And good luck.
