### ISSUE TITLE
Unlisted Way to Get Linker Error LNK2019/LNK2001

### ISSUE THREAD

**Issue by hak33m16** [MicrosoftDocs/cpp-docs#553]
Turns out that if you right click in Visual Studio 2017 solution explorer -&gt; Add New Item -&gt; (accidentally click Header File) and then rename the file to a .cpp that does NOT register with Visual Studio that the file is no longer a header. You must right click the file -&gt; Properties -&gt; Item Type -&gt; and select "C/C++ compiler" or recreate it altogether. There go a few hours of my life! :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab7d8d70-709a-67c8-799f-399ba8a6c38c
* Version Independent ID: ba5ba087-422c-4974-db42-4ae343defb3f
* Content: [Linker Tools Error LNK2019](https://docs.microsoft.com/en-us/cpp/error-messages/tool-errors/linker-tools-error-lnk2019?view=vs-2017)
* Content Source: [docs/error-messages/tool-errors/linker-tools-error-lnk2019.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/error-messages/tool-errors/linker-tools-error-lnk2019.md)
* Product: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by hak33m16** [comment]
I'd like to add that the error was happening when I would add the function definitions for my class from the header into the supposed .cpp file, and I accidentally stumbled on this property

**Comment by corob-msft** [comment]
@hak33m16 I'm sorry you had that experience; it's a way to cause these errors that I'd never heard of before - and I've heard of a lot of ways to get this error.

So, if I understand the problem correctly, the new .cpp file you created was not actually being compiled, because its property settings were not set correctly by the New Item dialog for a .cpp file. You got the LNK2019 error as soon as you built other code that referred to symbols you defined in that .cpp file, because the missing .obj file couldn't be included in the link. And this was not immediately obvious, because you expect your .cpp files to be compiled, as they are clearly source files, and why wouldn't they be?

In addition to the method you found, I can imagine this happening as a result of adding an existing file, maybe some source code from a third party, to your project. Say, for example, if you had a .txt file with the source, you added it to your project, and then changed the extension to .cpp.

The way to solve this seems to belong under a general category of "Check if the file where the symbol is defined is really being compiled," perhaps by way of "Verify that the object file that defines the symbol is both generated by the compiler and included by the linker." And if it's not being compiled, then check the file's properties to make sure the compiler picks it up. 

I'll see about adding some relevant prose to the error topics.

**Comment by hak33m16** [comment]
@corob-msft That's exactly the problem I had. In all my years of using Visual Studio, I've never done this, but I did it hazily last night, and never got around to compiling the code until the morning. By then, I'd completely forgotten I had re-named the file, and started running into these seemingly unrelated linker issues for something as simple as defining the constructor.

I agree that it could fall under that general category, but it wasn't obvious to me that the file was not being compiled as I have ~50 of my own .cpp files in the project. The prose in there could hopefully prevent somebody from making the same mistake I did.

Also, I appreciate the swift response.
