### ISSUE TITLE
Demotion in Ellipses conversions?

### ISSUE THREAD

**Issue by Ma-XX-oN** [MicrosoftDocs/cpp-docs#570]
> The size field is optional for some argument types. When no size prefix is specified, the formatter consumes integer arguments—for example, signed or unsigned `char`, `short`, `int`, `long`, and enumeration types—as 32-bit `int` types, and `float`, `double`, and `long double` floating-point arguments are consumed as 64-bit `double` types. 

Um, why is a `long double` getting demoted to a `double`?  That makes no sense.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 78bd3fde-7eae-a126-f330-563d912a1fab
* Version Independent ID: b6f2df29-3154-05ec-4c9b-9dbd8c316dd3
* Content: [Format Specification Syntax: printf and wprintf Functions](https://docs.microsoft.com/en-us/cpp/c-runtime-library/format-specification-syntax-printf-and-wprintf-functions?view=vs-2017#size)
* Content Source: [docs/c-runtime-library/format-specification-syntax-printf-and-wprintf-functions.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/c-runtime-library/format-specification-syntax-printf-and-wprintf-functions.md)
* Product: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@Ma-XX-oN In the Microsoft compilers, __double__ and __long double__ have identical representations even though they are treated as distinct types. Both are already 64-bit types, so no demotion that loses information is taking place here.

**Comment by corob-msft** [comment]
Just here, or every place where we mention the **long double** type? There are a few hundred of those, so rather than mention it in all of them, we rely on readers to be familiar with the [fundamental types](https://docs.microsoft.com/en-us/cpp/cpp/fundamental-types-cpp?view=vs-2017) and their Microsoft-specific implementation details. This is one of the first things to learn when you want to write portable code; compilers differ in their implementations of these types, and that's perfectly valid according to the standard.
