### ISSUE TITLE
Question.

### ISSUE THREAD

**Issue by TrojAnTriangle** [MicrosoftDocs/cpp-docs#571]
Remarks section elaborates the behavior of _localtime32_s, does the _localtime64_s have same behavior?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 684adba0-62cb-59d7-d58c-69c7181b9903
* Version Independent ID: ef0c00f2-d75b-42f2-7918-208dd9c96560
* Content: [localtime_s, _localtime32_s, _localtime64_s](https://docs.microsoft.com/en-gb/cpp/c-runtime-library/reference/localtime-s-localtime32-s-localtime64-s?view=vs-2017)
* Content Source: [docs/c-runtime-library/reference/localtime-s-localtime32-s-localtime64-s.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/c-runtime-library/reference/localtime-s-localtime32-s-localtime64-s.md)
* Product: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@TrojAnTriangle I can see how this is confusing. In the first two paragraphs of the remarks, it should say **localtime_s** instead of **_localtime32_s** and **time_t** instead of **long**. The only difference in behavior between **_localtime32_s** and **_localtime64_s** is in the size of the *sourceTime* parameter and the range of supported dates in the output *tmDest* `tm` struct.

**Comment by mikeblome** [comment]
fixed
