### ISSUE TITLE
According to the universal standard does it mean that I have to use /MT in my program?

### ISSUE THREAD

**Issue by baizebing** [MicrosoftDocs/cpp-docs#582]
I have use Apivalidator to scan my dll file and the result is apis in msvcp140.dll and vcruntime140.dll are illegal. So I have to compile my program with the flag "/MT" which will call libvcruntime140.lib and libucrt.lib. And here is the problem, when I use libucrt.lib to link, there are many error "unresolved symbol". So I have to use /NODEFAULTLIB:libucrt.lib /DEFAULTLIB:ucrt.lib to solve the case. Are there any conflicts and what libs on earth should I use?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4f9074f9-b954-c810-e449-f2663c1546ce
* Version Independent ID: 4b3b0d42-eae9-d7bb-4b5f-e505595204bc
* Content: [CRT Library Features](https://docs.microsoft.com/en-us/cpp/c-runtime-library/crt-library-features?view=vs-2017#feedback)
* Content Source: [docs/c-runtime-library/crt-library-features.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/c-runtime-library/crt-library-features.md)
* Product: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@baizebing I'm sorry you're having trouble with your project. Statically linking the VC runtime and UCRT libraries is not a fix for ApiValidator errors. Some APIs can't be called by Universal Windows code, no matter how they are linked into your code. You do not have to use /MT, although you can if you want to. When you changed your project to link the libraries statically, you may have created a build configuration error. It sounds like you have a support issue rather than a documentation issue, and the documentation team is not really equipped to handle support questions. I recommend you ask your questions in the [Developer Community](https://developercommunity.visualstudio.com/spaces/62/index.html) forums instead, where others may have the same problem and where you may get more knowledgeable support.
