### ISSUE TITLE
Function Pointers needs more meat

### ISSUE THREAD

**Issue by mfstanton** [MicrosoftDocs/cpp-docs#617]
Function Pointers section needs more meat, inclucing examples  Lately it seems I am better off digging up my K&R or Sjorstrup refererence.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e504bf89-cc53-16bb-0c28-a6464888a890
* Version Independent ID: 76d0abe5-46ea-0b48-ed24-ea4b8e113cf7
* Content: [Function Pointers](https://docs.microsoft.com/en-us/cpp/build/function-pointers?view=vs-2017)
* Content Source: [docs/build/function-pointers.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/function-pointers.md)
* Product: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@mfstanton Perhaps it isn't clear what this topic is about. Otherwise, I'm curious what more you'd like to know about how a function pointer is passed as a parameter in the x64 ABI. It's basically just the label for the function entry point address. You can see an example by generating an assembly listing for a call that takes a function pointer parameter using the x64 compiler. I'm not sure it would be very valuable to add that to the topic.

Since the topic title may be misleading to people who arrive here based on search terms, I'm consolidating this and other related topics under the [x64 calling conventions](https://docs.microsoft.com/en-us/cpp/build/calling-convention) heading. This update should go live today sometime around noon Pacific time, and will hopefully clear up confusion about the context.

**Comment by corob-msft** [comment]
As a follow-up, if it is a matter of confusion, and you're actually looking for information about function pointers as a C++ language feature, then you really are better off looking at a textbook. The .Net language docs have extensive language tutorials, but the C++ docs have never gotten past "Hello world". We have compiler and tools reference info, as well as extensive library documentation, but in general, we expect the people who come here to already know the language.

**Comment by mfstanton** [comment]
The documentation in the sample needs more than what is there. How the function pointer is used, what fields can be valid, how it relates to things like declspec and stdcall parameters. I have some code from an Army Corps of Engineers that was originally compiled under Borland products that was turned into a DLL and the compiler is saying I have illegal parameters. The Function Pointer spec tells very little about what syncactical combinations are legal.  Thank you for your time.

 

 

Michael Stanton

GEOSPAN Corporation

6901 E. Fish Lake Road

Suite 156

Maple Grove, MN  55369

763-493-9320 X5003

651-270-3191 (mobile)

www.geospan.com

**Comment by mfstanton** [comment]
I have been working with c language for many years. What I was trying to do works with GCC and GCC+ because I was taking it out of a device driver I wrote for Linux. I was looking for any caveats WRT the Microsoft compiler which seems to be quite bug ridden and inconsistent in the 2015 version of VS.

**Comment by mfstanton** [comment]
What I am fighting with is the fact that the following is a legal construct in C  

 

#ifndef CCGEOID_H

#define CCGEOID_H

 

#ifndef DLLEXPORT

#define DLLEXPORT __declspec(dllexport)

#endif

 

#define MAXGEOIDAREAS 50

 

DLLEXPORT int _stdcall geoid(double x, double y, double *ght);

 

DLLEXPORT int _stdcall describe_geoid_areas(char *desc);

 

DLLEXPORT int _stdcall initialize_geoid90(char *geoid_file_path);

DLLEXPORT int _stdcall initialize_geoid93(char *geoid_file_path);

DLLEXPORT int _stdcall initialize_geoid96(char *geoid_file_path);

DLLEXPORT int _stdcall clean_up_geoid90();

DLLEXPORT int _stdcall clean_up_geoid93();

DLLEXPORT int _stdcall  clean_up_geoid96();

DLLEXPORT int _stdcall initialize_geoid_from_file(char *geoid_file_path, char *area_filename);

 

DLLEXPORT int _stdcall clean_up_geoid(void);

 

 

 

However, the following construct in “C” gets a fatal diagnostic as being illegal but other compliant C compilers allow it, giving the following diagnostic:

 


Severity

Code

Description

Project

File

Line

Suppression State


Error (active)

 

a calling convention may not be followed by a nested declarator

UTM_Transform

w:\GIS_Topics\UTM\CORPSCON\224\I\cc_convert.h

68

 

 

 

 

 

 

DLLEXPORT int _stdcall ( *g_usng2geo_function )();

DLLEXPORT int _stdcall ( *g_grid2geo_function )();

DLLEXPORT int _stdcall ( *g_togeo83_function )();

DLLEXPORT int _stdcall ( *g_fromgeo83_function )();

DLLEXPORT int _stdcall ( *g_geo2grid_function )();

DLLEXPORT int _stdcall ( *g_geo2usng_function )();

DLLEXPORT int _stdcall ( *g_geoid_function )();

DLLEXPORT int _stdcall ( *g_vertcon_function )();

DLLEXPORT int _stdcall ( *g_z_function1 )();

DLLEXPORT int _stdcall ( *g_z_function2 )();

DLLEXPORT int _stdcall ( *g_cf_function_in )();

DLLEXPORT int _stdcall ( *g_cf_function_out )();

 

My purpose in looking through your documentation since there are many “Microsoft specific Extensions” is to find where in the document incorrectly says that such a construct that is legal in other compiler products should be diagnosed by Microsoft’s product as an error.  You will note in the two examples that the only difference between the function declarations is that one of them uses a pointer to get to the target and the other uses a specific function name. Yes I checked it in my first edition copy of Kernigan & Ritchie that was given to me by a colleague at Bell Labs. I also referenced a few other sources (e.g., Bjarne Soustrup)  to verify that it is legal and wondered why such poor documentation was available at the Microsoft Web site which is a pale replacement for a real paper reference manual like the ones I have at my ready disposal.  

 

 

 

 

 

From: mfstanton@comcast.net <mfstanton@comcast.net> 
Sent: Wednesday, December 19, 2018 10:36 AM
To: 'MicrosoftDocs/cpp-docs' <reply@reply.github.com>; 'MicrosoftDocs/cpp-docs' <cpp-docs@noreply.github.com>
Cc: 'Mention' <mention@noreply.github.com>
Subject: RE: [MicrosoftDocs/cpp-docs] Function Pointers needs more meat (#617)

 

I have been working with c language for many years. What I was trying to do works with GCC and GCC+ because I was taking it out of a device driver I wrote for Linux. I was looking for any caveats WRT the Microsoft compiler which seems to be quite bug ridden and inconsistent in the 2015 version of VS.

**Comment by corob-msft** [comment]
I suspect the documentation you're looking for is in [__stdcall](https://docs.microsoft.com/en-us/cpp/cpp/stdcall), part of the [Argument Passing and Naming Conventions](https://docs.microsoft.com/en-us/cpp/cpp/argument-passing-and-naming-conventions) section. Pay particular attention to the example at the end. The quick solution is to move the `__stdcall` modifier inside the parentheses that contain the function name pointer. This documentation doesn't say so, but it's generally x86-specific, since modifiers such as `__stdcall` are basically no-ops on x64, which just supports the native fast call convention and `__vectorcall`. And that's okay, because the corresponding functions are also compiled the same way.
