### ISSUE TITLE
Need an example for a multibyte character

### ISSUE THREAD

**Issue by b1nch3f** [MicrosoftDocs/cpp-docs#661]
Each byte sequence represents a single character. By sequence i presume it's an Array. Then how does an Array would represent a single character. Please provide an example for clarity.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f41bbbc-0ae7-8a8a-0998-eb413a5dc002
* Version Independent ID: 1f5430a7-9d5e-f73b-21b3-3d33f1f496da
* Content: [Multibyte and Wide Characters](https://docs.microsoft.com/en-us/cpp/c-language/multibyte-and-wide-characters?view=vs-2017)
* Content Source: [docs/c-language/multibyte-and-wide-characters.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/c-language/multibyte-and-wide-characters.md)
* Product: **visual-cpp**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by mikeblome** [comment]
@b1nch3f Yes the multibyte "sequence" can be accessed as a C-style array of bytes. However, multibyte characters are a very old technology at this point, and there's not much point to adding an example for how to use them.  In fact, this entire topic is outdated because it doesn't talk about UTF-8 or other modern Unicode encodings. Always use some kind of Unicode encoding in new applications.
