### ISSUE TITLE
Is it the default or not?

### ISSUE THREAD

**Issue by ScotBren** [MicrosoftDocs/cpp-docs#674]
The article states that /Ob2 is the default.  But then it says that other optimizations switches are required, if you use /Ob2.   So, which is it?  Is it the default or not?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b8753fc2-5ab9-47ad-f52b-ae878986bc0f
* Version Independent ID: 47c6098b-17b4-a22d-b21a-8d8032b0df78
* Content: [/Ob (Inline Function Expansion)](https://docs.microsoft.com/en-us/cpp/build/reference/ob-inline-function-expansion?view=vs-2017)
* Content Source: [docs/build/reference/ob-inline-function-expansion.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/reference/ob-inline-function-expansion.md)
* Product: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@ScotBren The document is confusing, and at least partly incorrect. The default behavior (that is, when **/Ob**_N_ is unspecified) depends on which other switches are set. It would be safe to call **/Ob0** the default for debug builds. **/Ob2** is set automatically as a side-effect of options **/O1**, **/O2**, and **/Ox**, but otherwise, **/Ob0** is in effect for **/Ot** (the default if no optimization switch is specified), **/Os**, **/Og**, or (no surprise) **/Od**. You can set **/Ob0**, **/Ob1**, or **/Ob2** explicitly without regard to other optimization switch settings, and the more restrictive settings (**/Ob0**, **/Ob1**) are honored when the compiler would otherwise inline a function. However, inlining remains at the discretion of the compiler, and I wouldn't expect much effect if you added **/Ob1** or **/Ob2** to **/Os** or **/Od**.

**Comment by corob-msft** [comment]
Resolved in an update on 08/07/2019.
