### ISSUE TITLE
Sequences of quotation marks

### ISSUE THREAD

**Issue by mgkuhn** [MicrosoftDocs/cpp-docs#700]
What processing does the Microsoft C startup code apply to sequences of quotation marks? There seems to be more going on than what is documented on this page. For example, I get

 input -&gt; argv[1]
 "a""b" -&gt; a"b
 "a"""b" -&gt; a"b
 "a""""b" -&gt; a"b
 "a"""""b" -&gt; a""b

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 767a133c-6b2a-d353-f39a-9ced2772a1ff
* Version Independent ID: 03b704f2-39fc-f68a-f649-0ed46eb9282f
* Content: [Parsing C Command-Line Arguments](https://docs.microsoft.com/en-us/cpp/c-language/parsing-c-command-line-arguments?view=vs-2017)
* Content Source: [docs/c-language/parsing-c-command-line-arguments.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/c-language/parsing-c-command-line-arguments.md)
* Product: **visual-cpp**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by mgkuhn** [comment]
How does this all interact with the command-line processing applied by cmd.exe (where quotation marks toggle a quote flag that controls the interpretation of metacharacters, independent of whether there is a backslash in front of the metacharacter or not)?

What escaping algorithm is recommended to robustly get arbitrary strings past both the cmd.exe command-line parser and the C run-time parser described here?

**Comment by corob-msft** [comment]
@mgkuhn It can be hard to tell which effects are due to the command interpreter, and which are part of the runtime startup processing done by the default `_setargv` routine. I believe you can read the source code for the latter in the UCRT source that ships as part of the Windows SDK. On my machine, I found it in `C:\Program Files (x86)\Windows Kits\10\Source\10.0.17763.0\ucrt\startup\argv_parsing.cpp`. You can substitute your own `_setargv` routine if you'd like to experiment, and it's probably the best way to see what your program gets from the command processor before it's interpreted into the runtime environment. I strongly suspect both are involved in what you're seeing with double-quote sequences.

This doesn't seem like an actionable request for documentation changes - or at least, not yet. I'm closing it for now, but if you find that something needs to be mentioned specifically, feel free to re-open this issue.

**Comment by redmcg** [comment]
I'm using CreateProcessA to eliminate the command interpreter. I'm sending the following string:
`"""" "\\\"""`

The result is a single argument with the following value:
`" \"`

Can you explain this? I would have expected two arguments with the values of: `"` and `\""`.

Here's the CreateProcessA call:
```
CreateProcessA(
            NULL,
            "printArgs.exe \"\"\"\" \"\\\\\\\"\"\"",
            ...)
```
And printArgs.exe is simply:
```
   for (int i = 0; i < argc; i++)
      printf("%s\r\n", argv[i]);
```
Note I don't have access to `argv_parsing.cpp` so would really appreciate an explaination.
