### ISSUE TITLE
Args to compare

### ISSUE THREAD

**Issue by amp64** [MicrosoftDocs/cpp-docs#703]
The second argument to the compare function appears to be the key passed to bsearch_s, not the address of the key as claimed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a50973f7-0c09-d7c9-e698-cd0afa23f204
* Version Independent ID: 462ee04a-79ed-d425-87e5-809410aeef42
* Content: [bsearch_s](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/bsearch-s?view=vs-2017)
* Content Source: [docs/c-runtime-library/reference/bsearch-s.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/c-runtime-library/reference/bsearch-s.md)
* Product: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@amp64 Yes, the issue is that the *key* parameter should be described as a pointer to the thing to search for, and then this apparent conflict goes away. The *key* parameter that's passed to the callback is exactly the same *key* parameter passed to the `bsearch` or `bsearch_s` function, not its dereferenced value, and not its address.
