### ISSUE TITLE
What would a concurrent Process do here --quoted text below?

### ISSUE THREAD

**Issue by b1nch3f** [MicrosoftDocs/cpp-docs#720]
"The declaration of w specifies that the program cannot change the value pointed to and that the program cannot modify the pointer."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e5a55527-20e0-3841-e3e3-e7250af5f088
* Version Independent ID: dde4872e-68b2-7959-9041-3cef6066bad6
* Content: [Pointer Declarations](https://docs.microsoft.com/en-us/cpp/c-language/pointer-declarations?view=vs-2017)
* Content Source: [docs/c-language/pointer-declarations.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/c-language/pointer-declarations.md)
* Product: **visual-cpp**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by mikeblome** [comment]
@b1nch3f The wording here is accurate but not super clear. Think of a memory location that one process or thread can write to and another can only read from.  The first process might have access to that address by a non-const variable or pointer declaration. The second process has a variable that points to the same location, but cannot modify it due to "const" and also cannot assume the value is unchanged; "volatile" is used to tell the compiler that it read the value at that location every time it is used.
