### ISSUE TITLE
GetLine documentation is wrong

### ISSUE THREAD

**Issue by LordLiverpool2** [MicrosoftDocs/cpp-docs#725]
I'm sure this has been covered by the comments you decided to throw away from the old documentation. The documentation of the "nMaxLength" parameter of GetLine is wrong. It states:

"nMaxLength
Specifies the maximum number of bytes that can be copied to the buffer. GetLine places this value in the first word of lpszBuffer before making the call to Windows"

But as the previous parameter makes clear, it's the number of *characters*, not bytes. See also EM_GETLINE for confirmation. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f86b1a15-2ebf-6f85-4dad-06687c22be5c
* Version Independent ID: 4794949e-d6a0-4d30-747a-2fc47199aad4
* Content: [CEdit Class](https://docs.microsoft.com/en-us/cpp/mfc/reference/cedit-class?view=vs-2017)
* Content Source: [docs/mfc/reference/cedit-class.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/mfc/reference/cedit-class.md)
* Product: **visual-cpp**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by mikeblome** [comment]
@LordLiverpool2 thanks for the feedback. You are correct although the number of bytes = number of characters for ANSI strings. I updated the topic to say TCHARs instead of bytes. 
Also, if you can point me to an example where we removed remarks from older topics, I would like to see it. If any such text was removed from MFC documentation it was almost certainly inadvertent.
