### ISSUE TITLE
Deprecation of redist MSMs?

### ISSUE THREAD

**Issue by mikekaganski** [MicrosoftDocs/cpp-docs#746]
https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes-preview#VS2019_Preview2 tells:

&gt; Our documentation actively discourages usage of Merge Modules for Visual C++ Runtime deployment. We are taking the extra step this release of marking our MSMs as deprecated. Consider migrating your VCRuntime central deployment from MSMs to the redistributable package.

However, this page does not have any traces of deprecation for the MSM usage. And my issue is not that this page doesn't have that; my issue is that clearly there is a move to actually deprecate MSMs *without providing an alternative* which is compatible with MSI.

The other way to deploy redist centrally is using vcredist.exe, which is a WIX Burn project that contains MSIs (for Visual C++ libraries) and MSUs (for UCRT). And having MSIs in the EXE prevents from using the EXE in MSI's deferred actions. Not to mention the EXE's flawed logic detecting if MSUs are applicable to the system, which aviods installing UCRT on systems with improperly installed UCRT (see https://developercommunity.visualstudio.com/idea/412198/detect-a-windows-version-from-msi.html).

Now deprecation the MSMs takes away the option to use MSMs + MSUs + own detection and application logic to finally install all the redist stuff properly in an MSI. Unless there is a *proper* solution from MS, redist MSMs *must not* be deprecated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c45f6269-45a0-436f-33f9-19d3815351ec
* Version Independent ID: 8851dcef-4f42-1864-d899-2c01c4d9d008
* Content: [Deployment in Visual C++](https://docs.microsoft.com/en-us/cpp/ide/deployment-in-visual-cpp?view=vs-2019)
* Content Source: [docs/ide/deployment-in-visual-cpp.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/ide/deployment-in-visual-cpp.md)
* Product: **visual-cpp**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by PhilHannent** [comment]
I have to second this problem. By depreciating VCRuntime MSNs you effectively make it so that Visual C++ programs MUST be installed via an EXE installer, because a bootstrapper is required. 

A community of network administrators at large organisations will only accept MSI installers, probably because for decades Microsoft has been promoting MSI as a be all and end all. These network administrators are using tools to transform the MSI to their requirements and deploying it to 1,000s of computers at once.

Telling them to deploy the runtime and an application separately doesn't work as ultimately someone doesn't read the documentation and fails to deploy the runtime and it's "our app" which is broken. Customers want one MSI to run and everything just work.

The depreciation is given without justification or advice on how to solve this deployment problem. Either VCRuntime MSNs have to stay or Microsoft has to tell network administrators to stop asking for MSI installers.

Please consider the end user experience and how we as software developers are perceived. Your current planned approach looks set to create customer frustration and support calls.

**Comment by corob-msft** [comment]
@mikekaganski @PhilHannent You both make good points, but you're not making them in the right place. The cpp-docs Issues board is for bringing up problems, inaccuracies, or omissions in the documentation, not problems in the product itself. For those, you'll need to use the other button at the bottom of the topic. It will take you to the [Developer Community C++ forum](https://developercommunity.visualstudio.com/spaces/62/index.html).

Issues raised on Developer Community go to the product team directly, whereas doc issues only go to the doc writers. And when we see product issues, as we often do since we might be the first people to try new features out, we go to the exact same place on Developer Community to report them that you can. I haven't looked, but I bet you're not alone in your take on this particular change, so someone else may have created an issue for it already. It pays to search first. If there is one already, you can upvote it. If you don't see it, you can create a new issue.  

I'm closing this issue, because the docs appear to be accurate at this time. We'll be revisiting the preview topics as we get closer to shipping, so they should reflect what's actually in the product.

**Comment by mikekaganski** [comment]
FYI: https://developercommunity.visualstudio.com/content/problem/439217/deprecation-of-crt-redist-msms.html is closed NOTABUG :-)

**Comment by corob-msft** [comment]
Figures. If there's a post on the Visual C++ Team Blog that talks about it, you can leave feedback there, too.
