### ISSUE TITLE
Document how to find some of the defailt libs and code to replicate them if desired.

### ISSUE THREAD

**Issue by AraHaan** [MicrosoftDocs/cpp-docs#75]
I would like if the possible locations for some of the default libs used in linking things as simple as this code for example to be documented:

```c
int main() {
    return 0;
}
```

That with certain compile settings on VS2015 on the latest update for that and the compiler with no target for the ``ucrt`` (statically linked library):

Some people might want to override the imports from the above code from 65 imports to this:

kernel32.dll:
    LoadLibrary(A or W)
    GetProcAddress
    FreeLibrary

Or maybe an update to MSVC to configure an version of the statical runtime that uses GetProcAddress on all the other functions it calls? Either way I would like as little Imports as possible coming from the static runtimes. At same time I want the programs I make to work on Windows Vista or newer. Hence why I link with static runtimes.

**Comment by corob-msft** [comment]
There's a surprising amount of machinery in the libcmt.lib and libvcruntime.lib libraries that are required in order for your C++ code's process to be initialized and terminate normally, for thread-local storage, the heap, and the stack to work correctly, and for just about any C++ facility to work at all. However, you don't have to link in the UCRT or other default libraries if you don't want to. The linker [/NODEFAULTLIB](https://docs.microsoft.com/en-us/cpp/build/reference/nodefaultlib-ignore-libraries) option turns them off. The default libraries and their contents are documented in the [CRT Library Features](https://docs.microsoft.com/en-us/cpp/c-runtime-library/crt-library-features) topic, in general terms. You can find all the relevant libraries mentioned by searching your Visual Studio installation directories. For a specialized use case like yours, we're very unlikely to provide much assistance. People use C++ instead of assembler language for a reason, and that reason usually has to do with the language facilities and libraries that come at some cost in terms of executable size. If you want to build a specialized C++ runtime that dynamically invokes every OS call, that's fine, but as for how to do it, you're on your own.

**Comment by AraHaan** [comment]
So, in this case I would have to customize my own CRT startup stuff, thanks.

**Comment by corob-msft** [comment]
The relevant sources are available in your Visual Studio installation in the VC\Tools\MSVC\*version*\crt\src directory. They're a mixture of C, C++, and assembler files. Not all of the files are used in the CRT libraries at the same time. Some are alternative versions for specialized situations like yours, that build separate object files that you link in to do specific things, such as the linkopts files for things like removing the environment variables from your memory image or skipping floating point support. You have to read the sources to determine which you need. I've built a simplified version of the runtime startup before, for exceptionally simple C code that didn't need the heap, console IO or math support, just file system and serial IO. I used the /FAs compiler option to reverse engineer what the compiler required during startup, and supplied the bare minimum from the startup sources -- and it still required a lot of initialization to get the file IO and serial IO functions supported. I think I managed a complete Windows console executable in C with statically linked library functions in about 4K. This is a non-trivial exercise, but it can be done.

**Comment by AraHaan** [comment]
hmm, seems like I cant figure out manually implementing these symbols.
```
unresolved external symbol ___acrt_iob_func
unresolved external symbol ___stdio_common_vfprintf
```

**Comment by corob-msft** [comment]
I can guess what these functions are for based on the names; they're probably for returning file handles and for implementing the core of vfprintf. Three leading underscores means an internal implementation detail. You could search the source and see if you can deduce their return types and create your own empty stub definitions, if you don't use file handles or vfprintf. As I recall, the IOB is deliberately obfuscated in recent versions of the CRT for some reason, probably security related.

**Comment by AraHaan** [comment]
I am using printf to test if it would work and it pulls those errors.
