### ISSUE TITLE
Setting Option Gm to Off

### ISSUE THREAD

**Issue by IndigoOlive** [MicrosoftDocs/cpp-docs#752]
The documentation is not clear on exactly how to set Gm to the off position.  To set Gm to off go to Project Property pages, select C/C++, select Code Generation and then set Enable Minimal Build to No (-Gm).

This will assign -Gm which means Gm is not defined and is off.

**Comment by corob-msft** [comment]
@IndigoOlive This action doesn't need to be taken for most projects, since /Gm is deprecated and off by default. You can follow the instructions in [/Gm (Enable Minimal Rebuild)](https://docs.microsoft.com/en-us/cpp/build/reference/gm-enable-minimal-rebuild) to turn the option off in existing projects.
