### ISSUE TITLE
The "T" length modifier for printf format specifiers is undocumented

### ISSUE THREAD

**Issue by MicheleCicciottiWork** [MicrosoftDocs/cpp-docs#761]
[I already reported this as a Visual Studio issue](https://developercommunity.visualstudio.com/content/problem/425337/the-t-length-modifier-for-printf-format-specifiers.html) but it may get more attention here

The `T` length modifier is undocumented. I would document it myself, but short of reverse-engineering the UCRT, I have no idea what it does. I _believe_ it's used to specify `_TCHAR` characters and strings, i.e. a character or string with the same width as the function that was called (`char` for `sprintf`, `wchar_t` for `swprintf`, etc.) but it would be nice to know for sure

**Comment by corob-msft** [comment]
@MicheleCicciottiWork Based on my look at the sources available in the SDK, I think your hypothesis is correct. I've put in a question to the library maintainers to see what they say.

**Comment by corob-msft** [comment]
@MicheleCicciottiWork I've gotten word back that, while the `T` modifier has been present in the code since VS2015, it is an unsupported extension, it may go away without announcement, and hence should remain undocumented. We don't recommend its use in any case. I'm closing this issue as won't fix.

A bit of history for the curious: `T` was added when a preview of the library for VS2015 briefly flirted with supporting the standard meanings of `%s` and `%S` (and `%c` and `%C`) to strictly specify narrow and wide strings (and characters), respectively. `%Ts` would be a way of maintaining the context-specific width. [Since that library change basically broke much if not most existing formatting code, it was reverted](https://blogs.msdn.microsoft.com/vcblog/2014/06/18/c-runtime-crt-features-fixes-and-breaking-changes-in-visual-studio-14-ctp1/), so that `%s` is interpreted as whatever the width of the function is, and `%S` means the opposite, as before. That made `%Ts` redundant. The supporting code hasn't been removed, but it isn't advertised, either.

**Comment by MicheleCicciottiWork** [comment]
Do you have any contact with whoever is handling the [Visual Studio Community bug report](https://developercommunity.visualstudio.com/content/problem/425337/the-t-length-modifier-for-printf-format-specifiers.html)? So that the issue can be closed there, too
