### ISSUE TITLE
web course presentation

### ISSUE THREAD

**Issue by Jaschus** [MicrosoftDocs/cpp-docs#765]
Your examples, gifs?, run too fast to be followed.  Can they be slowed or stopped so the screen can be read?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d597b582-59ec-2014-699b-6aac8db69cf6
* Version Independent ID: 81941537-4446-9c5a-6af3-25318396420d
* Content: [Build and run a C++ console app project](https://docs.microsoft.com/en-us/cpp/build/vscpp-step-2-build?view=vs-2017#build-and-run-your-code-in-visual-studio-issues)
* Content Source: [docs/build/vscpp-step-2-build.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/vscpp-step-2-build.md)
* Product: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@Jaschus Since the animation only shows you what you'd see on your own computer if you followed the steps above, the easiest way to see what happens slowly is to follow those steps in Visual Studio yourself. This animation is going to be removed when the content is updated for the next version of Visual Studio, and that's why we think it's not worth investing time to change the current one. Sorry.

**Comment by Jaschus** [comment]
Thanks for the answer.
Jim Schuster,
Certified Elder Law Attorney
Southfield, Mich.
(248) 356-3500
www.JimSchuster.com
