### ISSUE TITLE
What are "frame pointers"? The documentation needs to explain what they are, and how they can be used

### ISSUE THREAD

**Issue by tommai78101** [MicrosoftDocs/cpp-docs#791]
It is not clear what "Frame pointers" are, especially when they are briefly mentioned here in the "Symbols and Symbol Files" article here:

https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/symbols-and-symbol-files

and here:

https://docs.microsoft.com/en-us/cpp/build/reference/oy-frame-pointer-omission?view=vs-2017

Does it mean anything related to how Windows handle the memory allocation, which also mentioned frame pointers here.

https://docs.microsoft.com/en-us/cpp/build/stack-usage?view=vs-2017#alloca

In that instance, it is said `_alloca()` requires the use of frame pointers, which is still vague for us to understand what they are, and how it can be used with `_alloca()`. Are there any "gotchas" we need to be aware of when working with "frame pointers"?

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bbd14f34-9a79-51c8-5691-0af44764db45
* Version Independent ID: fc84eed6-cfc6-aa7d-1ac7-f3cb8278572d
* Content: [/Oy (Frame-Pointer Omission)](https://docs.microsoft.com/en-us/cpp/build/reference/oy-frame-pointer-omission?view=vs-2017)
* Content Source: [docs/build/reference/oy-frame-pointer-omission.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/reference/oy-frame-pointer-omission.md)
* Product: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@tommai78101 Most of the time, you don't need to worry about frame pointers. You probably only need to know what they are and how and whether they are used if you write assembly code, because it affects how you write your function prologs and epilogs. You need to enable frame pointers if you use `alloca`, `setjmp`/`longjmp`, or structured exception handling. And if your code will be debugged by other people, then frame pointers will make their lives easier.

What's a frame pointer? Every time you call a non-trivial function (that is, one that might call another function, or cause an exception), the compiler generates a *stack frame*, an area allocated on the stack to be used by the called function. Depending on the architecture, it may have space set aside to store non-volatile register contents, local variables, and space allocated by `alloca()`, as well as space for the parameters of functions it calls. A special-purpose, architecture-specific register is used as the *stack pointer*, and it always points at the top of the stack. A *frame pointer* is another register-based pointer that's used to figure out where the start of the stack frame is. It's not strictly necessary, since the compiler generates code to remove the stack frame when the call returns, or when a `longjmp` or an exception occurs, and it creates function prolog and epilog code that does the right thing needed to unwind the stack at each point in the function. When a frame pointer is used, it points to either the beginning of or a specified offset into the stack frame, depending on architecture and calling convention. Like the stack pointer, the frame pointer also uses an architecture-specific register (EBP on x86, RBP on x64, r29 on ARM or ARM64). Having the frame pointer in the register and stored at fixed locations in the stack frame allows for rapid traversal of the stack, whether for debugging or exception unwinding, as each frame pointer stored in the stack frame either points to the previous frame, or to a spot that's at a fixed offset from the previous frame. When there are no frame pointers, it's a little more work for a debugger, but it may save a small bit of time and space in the code by not having to save and restore the frame register, and lets functions use that register for something else. That's why it's an optimization option. By default, the x64 ABI doesn't use frame pointers, but the other architectures do.

**Comment by tommai78101** [comment]
I see. Thanks for the long explanation.

But, if possible, can that description be added somewhere in the article? It helps to explain why it's an optimization option, and that is something I was looking for more information on when I had been curious about the inclusions in some projects.
