### ISSUE TITLE
Please explain why we "should" rewrite old-style declarators in prototype form

### ISSUE THREAD

**Issue by ScotBren** [MicrosoftDocs/cpp-docs#800]
I came looking for an explanation of the disadvantages of the obsolete old-style declaration, and why it is better to write prototypes.  I was disappointed that this article simply "should"s on us without an explanation.  It reminds me of the parent who simply says "because I said so".
The reason I came looking for this is that some open-source libraries have the old-style declarators, and the compiler warns about it without explanation of why that's a problem. This code has hundreds of such functions, and before I go to the tedious trouble of converting them, I want to understand what the benefit will be (other than the warnings going away).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab57611a-0be3-5d11-eb3f-740383c4dd73
* Version Independent ID: 3cd8cf16-355f-f5e0-0973-f20577441f5f
* Content: [Obsolete Forms of Function Declarations and Definitions](https://docs.microsoft.com/en-us/cpp/c-language/obsolete-forms-of-function-declarations-and-definitions?view=vs-2017)
* Content Source: [docs/c-language/obsolete-forms-of-function-declarations-and-definitions.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/c-language/obsolete-forms-of-function-declarations-and-definitions.md)
* Product: **visual-cpp**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by corob-msft** [comment]
@ScotBren While I appreciate that you expect the compiler documentation to repeat the thirty-year-old justifications of the ANSI C89 standardization committee for this change, it might not be realistic. The reason we say "should" isn't "because we say so", it's "because the standard says so." Quoting from the ANSI C89 draft:

- **3.9.4 Function declarators**

  The use of function declarators with empty parentheses (not prototype-format parameter type declarators) is an obsolescent feature.

- **3.9.5 Function definitions**

  The use of function definitions with separate parameter identifier and declaration lists (not prototype-format parameter type and identifier declarators) is an obsolescent feature.

The standard itself doesn't say as much (which is why we don't explain the "should") but the old style is based on very immature linker technology. It makes it all too easy to call functions in another compilation unit that have a different signature than you declared locally, which makes things go boom. The reason for unified parameter lists for function definitions is basically DRY. These old styles collectively constitute Bad Engineering Practice, hence the recommended new styles. It's also why C++ went even further and created mangled names, for the linker to participate in enforcing type safety.

And I'm impressed that you're still using code so ancient as to retain this declaration style, which went out of fashion even before the 1989 ANSI standard came out and called it "obsolescent." I'm not sure I'd let it anywhere near a project I maintained. One of the ways you can tell that old code is still useful and not a bugfest is that it's been maintained to get rid of archaisms like this.

**Comment by ScotBren** [comment]
Thanks for your reply, Colin. I really dislike the ancient old-style declarators, and I really don’t understand why the open-source ZLib library continues to use them. I’ve gone through in the past and converted them all to proper function prototype declarators.  But then when I download a new version of the open source code, I have to go through it again.  Extremely tedious.  And if I don’t, I am swamped with hundreds of warnings (unless I disable it, which I also hate to do). I was hoping that the article would explain the good reasons for why we “should” convert to the newer style. I’d love to point the authors of that open source code to the explanation for why they should stop using that archaic style, but all we have there is “you should”.

**Comment by corob-msft** [comment]
@ScotBren The ZLib project maintainers may have another reason for using the old style. Namely, they're trying to remain compatible with the broadest possible range of C compilers. I suppose it's possible, but it's hard to imagine a platform so old that it still uses a pre-C89 compiler that also has enough memory to run ZLib - we're talking the 640K era and earlier. Also, some projects have a policy of not touching code unless it's got a demonstrable bug. I think that's mostly just a way of slacking off on technical debt, but it also keeps you from adding new bugs. I feel for you.

**Comment by ScotBren** [comment]
Yep, it’s a pain. I guess I’ll just live with it. But in general, I have had a similar complain about lots of Microsoft documents that tell you “what”, and sometimes “how”, but very rarely “why”.  So many times, I’ve seen documentation about an API that doesn’t give a good explanation for why someone would use it, or maybe the various parameter options don’t explain why to choose one over the other.  Some docs are better than others in this regard.
This particular warning triggered my pet peeve about not telling me “why” we “should” change it.
