### ISSUE TITLE
Status of /Za flag

### ISSUE THREAD

**Issue by nickaein** [MicrosoftDocs/cpp-docs#801]
[This official blog post](https://blogs.msdn.microsoft.com/vcblog/2016/11/16/permissive-switch/) states that `/Za` is not maintained anymore and users should use `/permissive` flag instead (look for *Is there any relation to /Za?* title).

The [current documentation of `/Za`](https://docs.microsoft.com/en-us/cpp/build/reference/za-ze-disable-language-extensions?view=vs-2017) doesn't say that though. What is the recommendation on the usage of `/Za`? Is it officially deprecated?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29f36976-a408-0624-f60e-c913ba77d7bb
* Version Independent ID: b81a6cdf-8026-1458-77e7-f53b997363a1
* Content: [/Za, /Ze (Disable Language Extensions)](https://docs.microsoft.com/en-us/cpp/build/reference/za-ze-disable-language-extensions?view=vs-2017)
* Content Source: [docs/build/reference/za-ze-disable-language-extensions.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/reference/za-ze-disable-language-extensions.md)
* Product: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@nickaein The `/Za` documentation could use some clarification. I haven't heard anything about official deprecation, though the related `/Ze` flag is deprecated.

When `/Za` is specified to the C compiler, it specifies that Microsoft extensions to ANSI C89/ISO C90 are disabled, including changes that happen to support any later standards. (There's only compiler support for the parts of the later C standards that have also been incorporated into C++ standards, and only when the code is compiled as C++). C89/C90 is a pretty archaic standard these days, but it's also a good baseline for portable C that works on just about every device everywhere, no matter how basic their compiler is. This is the main use case for `/Za`.

In C++ compilation units, my understanding is that `/Za` disables most but not all of the extensions to Microsoft's implementation of ISO C++98. That includes some features Microsoft implemented as extensions that became part of later C++ standards from ISO C++ 2003 onwards. So, if you're trying to be portable to other platforms that only support C++98, `/Za` is still useful.

There is no combination of switches that guarantees standards conformance for either C++03 or C++11. I would personally consider `Za` deprecated for code that requires C++03 and later standards, because `/Za` doesn't support all code constructs that the standard allows. I believe it also doesn't disable all Microsoft-specific extensions to these standards. To maximize portability of code that supports C++03 and C++11 standards, a combination of the more finely grained `/Zc` options is your best choice. For portable code that supports C++14 and later, use the `/permissive-` option in combination with `/std`. `/Zc` options can be used after these options to re-enable non-standards-compliant Microsoft extensions that may have been relied on in your existing code, and for some features, to disable compliance with C++11 and later standards.

**Comment by nickaein** [comment]
Thank you for thorough explanation!

> `/Za` disables most but not all of the extensions to Microsoft's implementation of ISO C++98. That includes some features Microsoft implemented as extensions that became part of later C++ standards from ISO C++ 2003 onwards.

That's what I thought too in this case https://github.com/nlohmann/json/issues/1481 which the `/Za` gives compile error while the same code compiles with `/permissive-` and also on GCC/Clang without error.

If that's the case, a note in `/Za` documentation would be helpful to let the user know `/Za` is for older standards (e.g. `C++98`) as you mentioned and it should not be used for checking C++1x adherence.

**Comment by corob-msft** [comment]
The updated documentation should be live now, so I'm closing this issue. This change should make clear that `/Za` is not recommended for use in C++ code at all, and its use in C code is only to support the archaic C89/C90 standard, which didn't even have `//` comments. (The Microsoft extensions to C do support `//` comments, among other things, if `/Za` isn't specified.)

After some discussion with the engineering team, they're considering whether to deprecate `/Za` when compiling C++ code, since it doesn't fully enforce any official C++ standard, not even C++98. Apparently    there was briefly an effort by multiple compiler vendors to create a common C++ standards mode in the C++98 era, but it petered out. The code hasn't seen active development for the last couple of decades; it's only had enough maintenance to keep some tests passing. If the deprecation happens, it will probably be in an update to the VS 2019 toolset, sometime after the initial release, and will be mentioned in the "What's new" and "breaking changes" documentation.
