### ISSUE TITLE
${name} expansion does not work in VS2017 in all documented contexts.

### ISSUE THREAD

**Issue by gmcode** [MicrosoftDocs/cpp-docs#826]
The documentation here:
https://docs.microsoft.com/en-us/cpp/ide/cmake-tools-for-visual-cpp?view=vs-2017
says that the expansion of ${name} should work in the environments section of CMakeSettings.json VS2017. See below.

  "environments": [
    {
      // Does not work on VS2017 but does on VS2019.
      "SOME_VARIABLE": "SOME_VALUE\\${name}\\lib"
    }
  ],
  "configurations": [
// etc.
  ]

It does indeed works on VS 2019, but not on VS2017, at least in VS2017 15.9.7
The documentation should be updated to reflect that fact, or if it's a bug it should be fixed.

I'd appreciate knowing if it is expected to work in VS2017?

**Comment by sfreed141** [comment]
Hi gmcode,

It works for me in VS2017 15.9.8.

Here's my CMakeSettings.json:
```
{
  "environments": [ { "TEST": "${name}" } ],
  "configurations": [
    {
      "name": "x64-Debug",
      "generator": "Ninja",
      "configurationType": "Debug",
      "inheritEnvironments": [
        "msvc_x64_x64"
      ],
      "buildRoot": "${env.USERPROFILE}\\CMakeBuilds\\${workspaceHash}\\build\\${name}",
      "installRoot": "${env.USERPROFILE}\\CMakeBuilds\\${workspaceHash}\\install\\${name}",
      "cmakeCommandArgs": "",
      "buildCommandArgs": "-v",
      "ctestCommandArgs": ""
    }
  ]
}
```

In my CMakeLists.txt: `message(STATUS "var is $ENV{TEST}")`

And output from generation:
![image](https://user-images.githubusercontent.com/6880264/54701602-90007180-4af2-11e9-8207-04a54a345a5b.png)
("var is x64-Debug" is printed on line 3)

Can you try updating VS? Otherwise, where are you attempting to use the environment variable? The variables should be available during generation and build, but not runtime. Let me know if it still doesn't work.

Thanks,
Sam

**Comment by gmcode** [comment]
Hi Sam
I can confirm you are correct that VS2017 does work correctly.
I can't see why I thought it was wrong now. My best guess is I made a mistake in trying to print out the value and used ${x} syntax instead of the  $ENV{x} syntax.

Thank you for looking into this and sorry for wasting your time on this occasion.
