### ISSUE TITLE
Topic is unclear and is missing its sample code

### ISSUE THREAD

**Issue by TheJCAB** [MicrosoftDocs/cpp-docs#828]
The old MSDN version of this topic contained a code sample, showing the correct placement of __unaligned, but that sample is missing here.

The document doesn't explain clearly where this goes. The code sample helps a lot in that regard.

I'd suggest bringing back the sample, as well as fixing the topic to explain the correct placement clearly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e27cfc35-f8c1-9179-26f9-440dd8e5877f
* Version Independent ID: d278ce44-4815-838b-d47c-9784641b1be3
* Content: [__unaligned](https://docs.microsoft.com/en-us/cpp/cpp/unaligned?view=vs-2017)
* Content Source: [docs/cpp/unaligned.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/cpp/unaligned.md)
* Product: **visual-cpp**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by corob-msft** [comment]
@TheJCAB The example was removed because it was specific to Itanium (IA-64), which hasn't been supported by the compiler for some time. I believe Windows XP-64/Server 2008 was the last OS to support Itanium, and it hasn't been supported by the compiler since Visual Studio 2010. On later Windows platforms, the operating system uses either processor settings or traps to handle exceptions on unaligned data accesses.

The `__unaligned` keyword exists to tell the compiler to generate extra code to bring in data on aligned boundaries before performing the actual reads/writes. Since this step is now handled either by processor microcode or the trap handlers in Windows, the extra code isn't needed. The keyword is essentially obsolete on platforms other than legacy and unsupported MIPS or Itanium, that is, in all the currently-supported x64, ARM, and ARM64 compilers. Don't use it unless you have to; and you probably don't have to.
