### ISSUE TITLE
Standard breaking Math Constants Definitiion

### ISSUE THREAD

**Issue by DavidChipman** [MicrosoftDocs/cpp-docs#849]
Why do you require _USE_MATH_DEFINES, along with the inclusion of math.h or cmath? Who do you think you are, requiring that, when no other C/C++ compiler works that way?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9bc6b17-58bd-4505-5abf-dbe93fda1560
* Version Independent ID: 5417cb08-4448-9d2c-d457-ad77ac8b2700
* Content: [Math Constants](https://docs.microsoft.com/en-us/cpp/c-runtime-library/math-constants?view=vs-2017#feedback)
* Content Source: [docs/c-runtime-library/math-constants.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/c-runtime-library/math-constants.md)
* Product: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@DavidChipman This is a compromise between support for the POSIX/XOPEN standard and the C standard for \<math.h>. The C standards (incorporated by reference in the C++ standards) do not define these constants, which means they'd be polluting the global namespace if they were available by default. Way back something like 20 years ago, someone decided that the Microsoft CRT should only expose the POSIX/XOPEN extensions under various guard macros, so the default was strictly conforming to the C standard. Some other runtime libraries were not as careful. Rather than cruft up your code with VC-specific defines, use the /D_USE_MATH_DEFINES command line option to enable the constants.
