### ISSUE TITLE
Supported in VS 15.9.9?

### ISSUE THREAD

**Issue by inthemedium** [MicrosoftDocs/cpp-docs#870]
After upgrading to VS 15.9.9 I am seeing this warning: 
  cl : Command line warning D9002: ignoring unknown option '/JMC'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c0a18808-d7a4-58d9-02ec-801e5a37f714
* Version Independent ID: bbd8c856-7fa8-efce-3d1b-cc6c9d8169e7
* Content: [/JMC (Just My Code debugging)](https://docs.microsoft.com/en-us/cpp/build/reference/jmc?view=vs-2017#feedback)
* Content Source: [docs/build/reference/jmc.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/reference/jmc.md)
* Product: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@inthemedium I don't recall any recent changes here; the option should be on by default. I'm not seeing any indication of others running into this problem on the [C++ Developer Community](https://developercommunity.visualstudio.com/spaces/62/index.html) web site or on StackOverflow, either.  I'd suggest opening an issue on Developer Community if you can't find a local configuration error. You can use the Visual Studio IDE to do this, by using the  **Help** > **Send Feedback** > **Report a Problem** or **Provide a Suggestion** options to fill out a report form. I'm closing this issue, since as far as I can tell, it's not a documentation problem. Yet.
