### ISSUE TITLE
Document the changes in the COFF object files produced when built with /bigobj

### ISSUE THREAD

**Issue by Ybalrid** [MicrosoftDocs/cpp-docs#873]
Hi,

I'm currently trying to solve an issue in a project that manipulate object files directly. The program worked fine until I tried to use it on files built with /bigobj.

I'm currently trying to peice together the differences between normal COFF files and the "extened" ones produced when /bigobj is used.

I worked out the fact that the header structure is changed from respecting the layout of the `IMAGE_FILE_HEADER` struct to the layout of `ANON_OBJECT_HEADER_BIGOBJ` and the different sets of values that permit to detect that. But right now, I'm trying to correctly read the symbol tables out of one of those files, and I feel like I'm only reading garbage beyound the first one when I try to map the data to an array of `IMAGE_SYMBOL`.

I am currently trying to find the correct way to read the symbol table out of a object file built with /bigobj, but the documentation doesn't point to the details of the changes produced by the usagle of /bigobj.

The documentation about PE/COFF doesn't seem to point to these differences too. This problem has already been pointed out in your forums by another user (https://developercommunity.visualstudio.com/idea/408610/pecoff-format-specification-issues.html) 

Where should I look for when searching for documentation about extended COFF files produced by the `/bigobj` option of cl.exe?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b57d68ce-ca50-af15-98b6-4aef2c5c1212
* Version Independent ID: ceaad016-32ea-d1c6-c2a3-cdc6cc926b2f
* Content: [/bigobj (Increase Number of Sections in .Obj file)](https://docs.microsoft.com/en-us/cpp/build/reference/bigobj-increase-number-of-sections-in-dot-obj-file?view=vs-2017#feedback)
* Content Source: [docs/build/reference/bigobj-increase-number-of-sections-in-dot-obj-file.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/build/reference/bigobj-increase-number-of-sections-in-dot-obj-file.md)
* Product: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by mikeblome** [comment]
investigating

**Comment by Ybalrid** [comment]
Thinking about this, I think a better place to document what's actually going on is there:  https://docs.microsoft.com/en-us/windows/desktop/debug/pe-format

But the mentioned documentation page should probably mention, or point to this.

I finally figured out that the symbols in that case corespond to the `IMAGE_SYMBOL_EX` structure instead of `IMAGE_SYMBOL`.

**Comment by corob-msft** [comment]
@Ybalrid We've got someone looking into it, but it may take a while to turn into updated documentation in the PE Format docs in Windows. As a quick heuristic, the /bigobj switch writes info by using a few similarly-named structures/defines as the regular format, but with _EX appended, as you've already discovered. Structures `IMAGE_SYMBOL_EX`, `IMAGE_AUX_SYMBOL_EX`, and the size `IMAGE_SYM_SECTION_MAX_EX` come to mind. 

I've added a reference link to the [PE-COFF format](https://docs.microsoft.com/en-us/windows/desktop/debug/pe-format) docs in Windows to the /bigobj topic; it should appear tomorrow. Since this is the only change I expect in the compiler documentation, I'm closing this issue.

**Comment by bbqsrc** [comment]
The documentation still doesn't seem to discuss these changes?

**Comment by corob-msft** [comment]
@bbqsrc 
The PE Format documentation is supplied by the dev team. The Docs team just edits and hosts it.  I'd recommend a comment and upvote on [])https://developercommunity.visualstudio.com/idea/408610/pecoff-format-specification-issues.html) in hopes of attracting their attention. 
@VCZYK FYI.

**Comment by SamB** [comment]
@corob-msft *WHICH* dev team? The thing you linked to never seems to have been routed to any dev team ...

**Comment by corob-msft** [comment]
@SamB 
That would be the linker team, part of the C++ dev team. I know they've seen it, but that doesn't mean they've done anything about it. One problem with getting something documented that hasn't been documented for years is, it's assumed to be low-priority precisely *because* no one's gotten around to it for years.
