### ISSUE TITLE
The backslash escape rules as stated above are confusing and conflict with the behaviour of existing Microsoft executables 

### ISSUE THREAD

**Issue by mdell-seradex** [MicrosoftDocs/cpp-docs#884]
1. It is very confusing for a backslash to sometimes be used as an escape behaviour and can easily lead to inconsistent results.
2. Existing executable, such as the dir command, do not follow these rules.
Example: If the following command is executed, according to these rules, it should fail.
    dir "C:\Windows\Downloaded Installations\" /s
These rules mean that the dir command should try to find the 'C:\Windows\Downloaded Installations\" /s' path which does not exist instead of recursing all sub-folders under C:\Windows\Downloaded Installations\.
I think that it would make sense that all executables created by Microsoft should follow the rules set forth by Microsoft.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 78e8ccf8-b903-0543-e1df-e4a3d1dd6483
* Version Independent ID: 2a44fb40-4e63-380f-8598-e553ec072712
* Content: [Parsing C++ Command-Line Arguments](https://docs.microsoft.com/en-us/cpp/cpp/parsing-cpp-command-line-arguments?view=vs-2017#feedback)
* Content Source: [docs/cpp/parsing-cpp-command-line-arguments.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/cpp/parsing-cpp-command-line-arguments.md)
* Product: **visual-cpp**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by corob-msft** [comment]
@mdell-seradex The confusing parsing behavior is a product of combining the escaping rules for C-string literals with the escaping rules for command-line processing. If you create your command-line strings in your source code, this interaction is unavoidable. You can skip the C-string escaping part by loading strings as resources, which means you only need to deal with the rules for command-line escaping, which are implemented in Windows. I think that's outside the scope of this document, so I'm closing this issue as not a documentation error. However, if you consider this a product issue worthy of making a suggestion about, I recommend raising it on the [C++ Developer Communication site](https://developercommunity.visualstudio.com/spaces/62/index.html).

**Comment by mdell-seradex** [comment]
I would disagree that the escaping rules for C-string literals has anything to do with this for two reasons.
1.  I don't use C, C++ or C#.  I use VB which does not use a backslash for escaping characters.
2.  Strings sent to a C, C++ or C# application always have all of their backslashes doubled up.  It has nothing to do with whether they follow a double quote or not.

As you suggest, I will raise the concern on the C++ Developer Communication site.

Note that I was directed here by Jeff Schwartz due to his comment at the following posting even though my issue was not with C++, but instead with .NET.  He informed me that they follow the rules stated here.
https://developercommunity.visualstudio.com/content/problem/473717/environmentgetcommandlineargs-and-myapplicationcom.html?childToView=506512#comment-506512

**Comment by corob-msft** [comment]
@mdell-seradex Apologies, I see that I was answering a different question than the one you actually asked, based on a question I'd gotten before.

There are still different layers in play, and they play by different rules. I'll warn you up front that these sets of rules are decades old, and will not be changed. The best you can hope for is that some new API gets created with rules that are more consistent. However, even that won't help in every case.

The first set of rules is for escaping in the [command processor](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/cmd). These rules are complex, especially when interpreting command or batch files, and understandable documentation is hard to find. 

Then there's the command line processing done by Windows when the command processor actually kicks off your process, usually by calling [CreateProcessW](https://docs.microsoft.com/en-us/windows/desktop/api/processthreadsapi/nf-processthreadsapi-createprocessw) or a related function. This is where the process environment is created that contains the command line passed to the app. It does some minimal processing, and loads the resulting command line in your process space, where you can read it with [GetCommandLine](https://msdn.microsoft.com/en-us/08dfcab2-eb6e-49a4-80eb-87d4076c98c6?).

At this point, every app, no matter what language it's written in, should see the same string for the command line. However, what any particular programming language does with this command line is entirely at the discretion of the language, and the apps written in it. Whether they have some consistency with other languages' behaviors or not is completely arbitrary. 

All I can tell you is what the C and C++ runtimes do, which is something like this. The first function called is usually `mainCRTStartup` or `wmainCRTStartup` for a console app, or `WinMainCRTStartup` or `wWinMainCRTStartup` for a desktop app. This is the code that sets up the C runtime environment, the stack, the CRT heap, the locale info, any thread-local variables, read-only constants, etc., and creates the `argc`, `argv`, and `envp` parameters that are then passed when the runtime invokes [main](https://docs.microsoft.com/en-us/cpp/cpp/main-program-startup) or its equivalent. There's some command-line interpretation that happens to create the `argv` and `envp` parameters, and they're invoked through function pointers you can access and modify, [_setargv and _setenvp](https://docs.microsoft.com/en-us/cpp/cpp/customizing-cpp-command-line-processing). The default processing is done by a CRT internal function.

The final result of these processes, combining both the command processor and the language runtime, is what's described by this document. The result will be slightly different if you bypass the command line and create a process directly, since you're stripping off a layer of escapes. It will also be different in any C/C++ app that skips the internal runtime routine that processes `argv` and substitutes it's own. What you see described here is the default behavior. You can also see the result of each layer of processing, if you're running the app from the command line and in a debugger. 

What I can't tell you is if any given app will behave this way. That's up to the app and its language runtime. And nothing added in Windows or our implementation of C++ will change that.

**Comment by mdell-seradex** [comment]
I understand what you are saying. It just seems odd and wrong that Microsoft does not appear to follow its own rules as evidenced by the behaviour of the dir command and many other command prompt commands.
I would think that many of those commands are actually older than the establishment of these rules, but I cannot say for certain.

**Comment by mdell-seradex** [comment]
I find it disappointing that Microsoft essentially abandoned their even older, original, more intuitive behaviour in favour of something that is partially identical to C rules for character escaping which is not more human readable.
