### ISSUE TITLE
Clarify lifetime of copy on unmanaged heap

### ISSUE THREAD

**Issue by b8adamson** [MicrosoftDocs/cpp-docs#903]
The article above says:

"This technique causes a copy of the string to be constructed on the unmanaged heap, so changes made to the string by the native function will not be reflected in the managed copy of the string."

It would be helpful to explicitly state how/when this copy gets cleaned up (and who is responsible).  Because it's not stated I'm assuming the compiler handles this when it returns from the unmanaged function. 

I'm also wondering what happens if the CLR is sitting on top of a different version of the C++ runtime than the unmanaged DLL that's having the string marshalled into it.  Is there any chance the program might get confused about _which_ unmanaged heap it's marshalling the string to/from?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 80f540b4-6c02-6a10-1501-f6cfbcf999ff
* Version Independent ID: 96b961fd-260e-3fdf-b376-a169ead7821e
* Content: [How to: Marshal Strings Using PInvoke](https://docs.microsoft.com/en-us/cpp/dotnet/how-to-marshal-strings-using-pinvoke?view=vs-2017#feedback)
* Content Source: [docs/dotnet/how-to-marshal-strings-using-pinvoke.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/dotnet/how-to-marshal-strings-using-pinvoke.md)
* Product: **visual-cpp**
* Technology: **cpp-cli**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by corob-msft** [comment]
@b8adamson The best introduction to P/invoke and marshaling is over in the .NET documentation. Check out [Default Marshaling Behavior](https://docs.microsoft.com/en-us/dotnet/framework/interop/default-marshaling-behavior) and the topics linked to it for details. The way to think about it is that the marshaler wraps the call to the unmanaged function in a hidden wrapper routine that pins and copies the managed string into a locally allocated one in the unmanaged context, which then is passed to the unmanaged function. When the unmanaged function returns, the wrapper either deletes the resource, or if it was on the stack, it gets reclaimed when the wrapper goes out of scope. The unmanaged function is not responsible for this memory.

The marshalling wrapper also does some work for you if your unmanaged routine returns a string, either as a return value or an out parameter. That memory is copied into a new managed string, [then released](https://docs.microsoft.com/en-us/dotnet/framework/interop/default-marshaling-behavior#memory-management-with-the-interop-marshaler). The marshaller can handle these simple scenarios, but if you want to pass around user-defined types, you have to do more work to describe how to marshall them, and that's beyond the scope of this document. Instead, check out [Marshaling Data with Platform Invoke](https://docs.microsoft.com/en-us/dotnet/framework/interop/marshaling-data-with-platform-invoke).

It's a virtual certainty that the CLR CRT and the DLL CRT are different, if the DLL is strictly unmanaged and not, say, a C++/CLI component. That's not an issue, since the unmanaged DLL code only accesses memory in the heap set up by its own CRT. It's the marshaling layer that deals with the different contexts.

**Comment by mikeblome** [comment]
answer here was copied into the topic for Sept 11 publishing.
