### ISSUE TITLE
If your code needs to be safe or verifiable, then we recommend that you port it to C#.

### ISSUE THREAD

**Issue by shinjitekun** [MicrosoftDocs/cpp-docs#925]
I recommend Microsoft fires/terminates/ousts the whole staff that thought this was a great idea:
If your code needs to be safe or verifiable, then we recommend that you port it to C#. 

I have a code base who wants to SQL functions of a .net DLL. The .dot net DLL has to use a library thats been around longer than your life on this planet. That library is written in C. If I rewrite the library in C# it won't work at all and just run slow.

C# is not safe or pure code and you know it.

Make coding great again.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 507ca2e9-12ec-4e54-0223-661ac264aad6
* Version Independent ID: 849a4b4f-f6ee-62f6-3b13-b25e87e10a5f
* Content: [Pure and Verifiable Code (C++/CLI)](https://docs.microsoft.com/en-us/cpp/dotnet/pure-and-verifiable-code-cpp-cli?view=vs-2019#feedback)
* Content Source: [docs/dotnet/pure-and-verifiable-code-cpp-cli.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/dotnet/pure-and-verifiable-code-cpp-cli.md)
* Product: **visual-cpp**
* Technology: **cpp-cli**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by corob-msft** [comment]
@shinjitekun

*Pure*, *safe*, and *verifiable* all have specific meanings in this context that may not have a lot to do with their common meanings in everyday usage. *Pure* means the code can contain both native and managed data types, but only managed functions. Both *safe* and *verifiable* mean the same thing: the managed language runtime can verify the security model and type safety of the code at runtime. Verifiable assemblies can't contain any unmanaged functions or data types. None of the terms has anything to do with whether the code is buggy or can be formally analyzed for correctness. 

The C++ compiler since VS2017 only supports mixed mode assemblies. If you're trying to create extended stored procedures, and you don't want to fiddle with the TRUSTWORTHY setting in SQL, then you're out of luck. If that's not a worry, then you can just P/Invoke your C library right from your C# stored procedure code. You only need a C++/CLI interop layer if you're doing some fancy manipulation of managed objects. Read the other topics in the table of contents near this one for more info, or go straight to the source in [the .NET documentation](https://docs.microsoft.com/en-us/dotnet/standard/native-interop/).

**Comment by shinjitekun** [comment]
Would you say that is no different from the unsafe keyword. I think I'm ok
with that.

**Comment by corob-msft** [comment]
Yes, *mixed mode* and *unsafe* are probably close to synonymous here. Any code that calls outside the managed universe is considered "unsafe". There might be other kinds of unsafe managed code, but I'm only familiar with the kind that does P/Invoke and works with native data types.
