### ISSUE TITLE
__FUNCDNAME__ and /clr switch

### ISSUE THREAD

**Issue by tibx** [MicrosoftDocs/cpp-docs#929]
If the / clr switch is used (Project &gt; Properties &gt; General &gt; Common Language Runtime Support &gt; /clr), the __FUNCDNAME__ macro does not return real decorated function name exported from the image (e.g. DLL). When function signature is void __stdcall Test(char *,int) real decorated name is ?Test@@YGXPADH@Z but __FUNCDNAME__ returns ?Test@@$$FYGXPADH@Z. This makes it impossible to use the #pragma comment directive to export function from DLL directly from the code without name decoration.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 302c807b-34ed-c367-be11-c1528666cb75
* Version Independent ID: acf8ddce-337a-1a41-d39e-b7d2b52360cf
* Content: [Predefined Macros](https://docs.microsoft.com/en-us/cpp/preprocessor/predefined-macros?view=vs-2019#feedback)
* Content Source: [docs/preprocessor/predefined-macros.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/preprocessor/predefined-macros.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by corob-msft** [comment]
@tibx This sounds like a possible product bug. I recommend you bring it up on the [Visual Studio Developer Community C++](https://developercommunity.visualstudio.com/spaces/62/index.html) forum. More information on submitting product issues can be found in [How to report a problem with the Visual C++ toolset](https://docs.microsoft.com/cpp/overview/how-to-report-a-problem-with-the-visual-cpp-toolset). If it turns out something in the documentation needs to be updated, please reopen this issue.
