### ISSUE TITLE
Basic property initialization

### ISSUE THREAD

**Issue by Stannieman** [MicrosoftDocs/cpp-docs#932]
When I use a basic properties (like "property int Size;") I get warning CS26495: Variable 'XXX' is uninitialized. Always initialize a member variable (type.6).
However I can't find the syntax to do so. Neither assignment (property int Size = 0;) nor constructor (property int Size{}; or property int Size();) work.

Is there a way to initialize them without using a backing field? Is it perhaps not needed because they are a member of a managed type?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45fe3dc6-7a36-54e9-9c57-2854b246e71d
* Version Independent ID: e14c986b-2286-074b-87ee-ebd19d7ae3d9
* Content: [How to: Use Properties in C++/CLI](https://docs.microsoft.com/en-us/cpp/dotnet/how-to-use-properties-in-cpp-cli?view=vs-2019)
* Content Source: [docs/dotnet/how-to-use-properties-in-cpp-cli.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/dotnet/how-to-use-properties-in-cpp-cli.md)
* Product: **visual-cpp**
* Technology: **cpp-cli**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by MSDN-WhiteKnight** [comment]
I suppose, CS26495 is a typo, and the real warning code is [C26495](https://docs.microsoft.com/en-us/visualstudio/code-quality/c26495?view=vs-2017) from C++ Core Guidelines ruleset? 

I'm not aware of any syntax to initialize auto-properties in C++/CLI. And in fact omitting their initialization for managed types is not critical, since CLR inititizlize everything to default value automatically. However, C++ Core Guidelines ruleset seems to be applicable only to unmanaged C++ projects, at least i receive warning when i'm trying to select it for C++/CLI project, and no analysis is performed at all. 

This issue is not reproduced for me in VS2017, but VS2019 has a bug related to background analysis that may cause this issue: https://developercommunity.visualstudio.com/content/problem/514960/c26495-warning-for-vc-clr-project-is-annoying-and.html The recommended workaround is to turn off background analysis.

**Comment by Stannieman** [comment]
@MSDN-WhiteKnight Sorry it was indeed C26495.
The background analysis of VS2019 is indeed causing the problem. This also explains why the warnings are only there when the relevant files were open in the editor and again go away after closing the files and rebuilding.
Thanks!
