### ISSUE TITLE
Cannot save default palette in VS 2017

### ISSUE THREAD

**Issue by bailie** [MicrosoftDocs/cpp-docs#979]
There is no way to make the default palette, or to display correctly when another palette was used. This feature is broken. You have to draw within the editor or else you will not display correctly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a9fbc94f-02e2-07c7-2bc4-9416677a0d3c
* Version Independent ID: 55dbce74-daeb-5b60-a9e1-f984d4cf8395
* Content: [How to: Work with Color](https://docs.microsoft.com/en-us/cpp/windows/working-with-color-image-editor-for-icons?view=vs-2019#feedback)
* Content Source: [docs/windows/working-with-color-image-editor-for-icons.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/windows/working-with-color-image-editor-for-icons.md)
* Product: **visual-cpp**
* Technology: **cpp-windows**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by corob-msft** [comment]
@bailie 
I'm sorry you're having trouble with the image editor. You should be able to save the default palette if you create a new icon resource, and then choose the **Image** > **Save Palette** menu item. If you've saved a custom palette, you should be able to load it again by choosing the **Image** > **Load Palette** menu item. If the feature doesn't work correctly, you should enter an issue for the product team. There's an easy way to do that, built right into Visual Studio. Go to the **Help** menu, select **Send Feedback** > **Report a Problem**, and fill out a new problem report. Your report will be seen by the product developers who can do something about it. Make sure you include a description of what you're trying to do, all the steps you took, and what didn't work the way you expected. I think it will even let you include screen shots. You can expect follow-up on the [Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html) web site.

Since this doesn't seem like a documentation issue, I'm closing it here.
